begin;
select pg_advisory_xact_lock(hashtext('cramapple-apcalcab-unit1-owner-approval-20260930'));
create temporary table t (content_key text primary key, difficulty text) on commit drop;
insert into t values
('apcalcab-frq-u1n-001','Medium'),
('apcalcab-frq-u1n-002','Medium'),
('apcalcab-frq-u1n-003','Hard'),
('apcalcab-frq-u1n-004','Medium'),
('apcalcab-frq-u1n-005','Medium'),
('apcalcab-mcq-u1n-001','Easy'),
('apcalcab-mcq-u1n-002','Easy'),
('apcalcab-mcq-u1n-003','Easy'),
('apcalcab-mcq-u1n-004','Medium'),
('apcalcab-mcq-u1n-005','Easy'),
('apcalcab-mcq-u1n-006','Medium'),
('apcalcab-mcq-u1n-007','Easy'),
('apcalcab-mcq-u1n-008','Easy'),
('apcalcab-mcq-u1n-009','Medium'),
('apcalcab-mcq-u1n-010','Easy'),
('apcalcab-mcq-u1n-011','Easy'),
('apcalcab-mcq-u1n-012','Medium'),
('apcalcab-mcq-u1n-013','Medium'),
('apcalcab-mcq-u1n-014','Medium'),
('apcalcab-mcq-u1n-015','Medium'),
('apcalcab-mcq-u1n-016','Medium'),
('apcalcab-mcq-u1n-017','Medium'),
('apcalcab-mcq-u1n-018','Medium'),
('apcalcab-mcq-u1n-019','Medium'),
('apcalcab-mcq-u1n-020','Medium'),
('apcalcab-mcq-u1n-021','Medium'),
('apcalcab-mcq-u1n-022','Medium'),
('apcalcab-mcq-u1n-023','Medium'),
('apcalcab-mcq-u1n-024','Easy'),
('apcalcab-mcq-u1n-025','Medium'),
('apcalcab-mcq-u1n-026','Easy'),
('apcalcab-mcq-u1n-027','Medium'),
('apcalcab-mcq-u1n-028','Easy'),
('apcalcab-mcq-u1n-029','Medium'),
('apcalcab-frq-u1v-001-v1','Medium'),
('apcalcab-frq-u1v-001-v2',''),
('apcalcab-frq-u1v-001-v3','Medium'),
('apcalcab-frq-u1v-002-v1','Medium'),
('apcalcab-frq-u1v-002-v2','Medium'),
('apcalcab-frq-u1v-002-v3','Medium'),
('apcalcab-frq-u1v-003-v1','Hard'),
('apcalcab-frq-u1v-003-v2','Hard'),
('apcalcab-frq-u1v-003-v3','Hard'),
('apcalcab-frq-u1v-004-v1','Medium'),
('apcalcab-frq-u1v-004-v2','Medium'),
('apcalcab-frq-u1v-004-v3','Medium'),
('apcalcab-frq-u1v-005-v1','Medium'),
('apcalcab-frq-u1v-005-v2','Medium'),
('apcalcab-frq-u1v-005-v3','Medium'),
('apcalcab-mcq-u1v-001-v1','Easy'),
('apcalcab-mcq-u1v-001-v2',''),
('apcalcab-mcq-u1v-001-v3','Easy'),
('apcalcab-mcq-u1v-002-v1','Easy'),
('apcalcab-mcq-u1v-002-v2','Easy'),
('apcalcab-mcq-u1v-002-v3','Easy'),
('apcalcab-mcq-u1v-003-v1','Easy'),
('apcalcab-mcq-u1v-003-v2','Easy'),
('apcalcab-mcq-u1v-003-v3','Easy'),
('apcalcab-mcq-u1v-004-v1','Medium'),
('apcalcab-mcq-u1v-004-v2','Medium'),
('apcalcab-mcq-u1v-004-v3','Medium'),
('apcalcab-mcq-u1v-005-v1','Easy'),
('apcalcab-mcq-u1v-005-v2','Easy'),
('apcalcab-mcq-u1v-005-v3','Easy'),
('apcalcab-mcq-u1v-006-v1','Medium'),
('apcalcab-mcq-u1v-006-v2','Medium'),
('apcalcab-mcq-u1v-006-v3','Medium'),
('apcalcab-mcq-u1v-007-v1','Easy'),
('apcalcab-mcq-u1v-007-v2',''),
('apcalcab-mcq-u1v-007-v3',''),
('apcalcab-mcq-u1v-008-v1','Easy'),
('apcalcab-mcq-u1v-008-v2','Easy'),
('apcalcab-mcq-u1v-008-v3','Easy'),
('apcalcab-mcq-u1v-009-v1','Medium'),
('apcalcab-mcq-u1v-009-v2','Medium'),
('apcalcab-mcq-u1v-009-v3','Medium'),
('apcalcab-mcq-u1v-010-v1','Easy'),
('apcalcab-mcq-u1v-010-v2',''),
('apcalcab-mcq-u1v-010-v3',''),
('apcalcab-mcq-u1v-011-v1',''),
('apcalcab-mcq-u1v-011-v2',''),
('apcalcab-mcq-u1v-011-v3',''),
('apcalcab-mcq-u1v-012-v1','Medium'),
('apcalcab-mcq-u1v-012-v2','Medium'),
('apcalcab-mcq-u1v-012-v3','Medium'),
('apcalcab-mcq-u1v-013-v1','Medium'),
('apcalcab-mcq-u1v-013-v2','Medium'),
('apcalcab-mcq-u1v-013-v3',''),
('apcalcab-mcq-u1v-014-v1','Medium'),
('apcalcab-mcq-u1v-014-v2','Medium'),
('apcalcab-mcq-u1v-014-v3','Medium'),
('apcalcab-mcq-u1v-015-v1','Medium'),
('apcalcab-mcq-u1v-015-v2','Medium'),
('apcalcab-mcq-u1v-015-v3','Medium'),
('apcalcab-mcq-u1v-016-v1','Medium'),
('apcalcab-mcq-u1v-016-v2','Medium'),
('apcalcab-mcq-u1v-016-v3','Medium'),
('apcalcab-mcq-u1v-017-v1','Medium'),
('apcalcab-mcq-u1v-017-v2','Medium'),
('apcalcab-mcq-u1v-017-v3','Medium'),
('apcalcab-mcq-u1v-018-v1','Medium'),
('apcalcab-mcq-u1v-018-v2','Medium'),
('apcalcab-mcq-u1v-018-v3','Medium'),
('apcalcab-mcq-u1v-019-v1','Medium'),
('apcalcab-mcq-u1v-019-v2','Medium'),
('apcalcab-mcq-u1v-019-v3','Medium'),
('apcalcab-mcq-u1v-020-v1','Medium'),
('apcalcab-mcq-u1v-020-v2','Medium'),
('apcalcab-mcq-u1v-020-v3','Medium'),
('apcalcab-mcq-u1v-021-v1','Medium'),
('apcalcab-mcq-u1v-021-v2','Medium'),
('apcalcab-mcq-u1v-021-v3','Medium'),
('apcalcab-mcq-u1v-022-v1','Medium'),
('apcalcab-mcq-u1v-022-v2','Medium'),
('apcalcab-mcq-u1v-022-v3','Medium'),
('apcalcab-mcq-u1v-023-v1','Medium'),
('apcalcab-mcq-u1v-023-v2','Medium'),
('apcalcab-mcq-u1v-023-v3','Medium'),
('apcalcab-mcq-u1v-024-v1',''),
('apcalcab-mcq-u1v-024-v2','Easy'),
('apcalcab-mcq-u1v-024-v3',''),
('apcalcab-mcq-u1v-025-v1','Medium'),
('apcalcab-mcq-u1v-025-v2','Medium'),
('apcalcab-mcq-u1v-025-v3',''),
('apcalcab-mcq-u1v-026-v1',''),
('apcalcab-mcq-u1v-026-v2',''),
('apcalcab-mcq-u1v-026-v3','Easy'),
('apcalcab-mcq-u1v-027-v1','Medium'),
('apcalcab-mcq-u1v-027-v2','Medium'),
('apcalcab-mcq-u1v-027-v3',''),
('apcalcab-mcq-u1v-028-v1','Easy'),
('apcalcab-mcq-u1v-028-v2','Easy'),
('apcalcab-mcq-u1v-028-v3',''),
('apcalcab-mcq-u1v-029-v1','Medium'),
('apcalcab-mcq-u1v-029-v2','Medium'),
('apcalcab-mcq-u1v-029-v3','Medium');
create temporary table tgt on commit drop as
select t.content_key, ci.id item_id, civ.id version_id, ci.item_type, nullif(t.difficulty,'') difficulty, gen_random_uuid() assignment_id
from t join app.content_items ci on ci.content_key=t.content_key and ci.exam_pack_version_id='826c8cf1-bc1b-4f2a-bd33-61a758e1487d'
join app.content_item_versions civ on civ.content_item_id=ci.id and civ.version_num=1
where ci.status='draft' and civ.status='draft';
do $$ begin if (select count(*) from tgt)<>136 then raise exception 'expected 136 draft targets, got %', (select count(*) from tgt); end if; end $$;
insert into app.content_review_assignments (content_review_assignment_id, content_item_version_id, reviewer_id, review_stage, review_kind, status, assignment_purpose, created_by)
select assignment_id, version_id, 'f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid, 'tutor_question', item_type, 'pending', 'owner_remediation_approval', 'f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid from tgt;
insert into app.content_review_decisions (content_review_assignment_id, content_item_version_id, reviewer_id, review_stage, tutor_score, difficulty_label, diagnostic_flag, concern_codes, note, tutor_decision, decision_payload, decision_hash, created_by)
select assignment_id, version_id, 'f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid, 'tutor_question', 1, difficulty, false, array[]::text[],
 'AP Calc AB Unit 1 original/variant batch: human review waived by Product Owner (David Bloom, 2026-09-30). Math verified by Qwen+DeepSeek+sympy; CED scope verified by two independent model families.',
 'approve',
 jsonb_build_object('review_stage','tutor_question','tutor_score',1,'tutor_decision','approve','approval_basis','apcalcab_unit1_batch_po_waiver','qa_date','2026-09-30','content_key',content_key),
 encode(extensions.digest(jsonb_build_object('review_stage','tutor_question','tutor_score',1,'tutor_decision','approve','approval_basis','apcalcab_unit1_batch_po_waiver','qa_date','2026-09-30','content_key',content_key)::text,'sha256'),'hex'),
 'f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid
from tgt;
create temporary table qa_blocked on commit drop as
select g.content_key, case
 when nullif(trim(civ.stem),'') is null then 'blank stem'
 when g.item_type='mcq' and (select count(*) from app.mcq_choices m where m.content_item_version_id=civ.id)<>4 then 'choice count'
 when g.item_type='mcq' and (select count(distinct lower(trim(m.choice_text))) from app.mcq_choices m where m.content_item_version_id=civ.id)<>4 then 'duplicate choice text'
 when g.item_type='mcq' and (select count(*) from app.mcq_choices m where m.content_item_version_id=civ.id and m.is_correct)<>1 then 'correct key count'
 when g.item_type='mcq' and exists (select 1 from app.mcq_choices m where m.content_item_version_id=civ.id and nullif(trim(coalesce(m.rationale,'')),'') is null) then 'blank rationale'
 when g.item_type='frq' and not exists (select 1 from app.frq_criteria c where c.content_item_version_id=civ.id) then 'no criteria'
 end reason
from tgt g join app.content_item_versions civ on civ.id=g.version_id;
delete from qa_blocked where reason is null;
do $$ begin if exists (select 1 from qa_blocked) then raise exception 'structural QA blocked: %', (select string_agg(content_key||':'||reason, ', ') from qa_blocked); end if; end $$;
update app.content_item_versions civ set status='reviewed_approved', review_status='question_review_approved', approved_by='f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid, approved_at=coalesce(civ.approved_at,now()), updated_at=now() from tgt where civ.id=tgt.version_id;
update app.content_items ci set status='reviewed_approved', updated_at=now() from tgt where ci.id=tgt.item_id;
select count(*) approved from tgt;
commit;