#!/usr/bin/env python3
"""Build the variants batch: verify, check near-duplicates, draw random answer positions, write SQL + manifest.

Run:  python3 build_variants.py
Reads variants_mcq_a/b/c.py and variants_frq.py. Writes:
  20260929_apcalcab_unit1_variants_batch.sql   (NOT applied to any database)
  variants_manifest.json                        (variant -> original, topic, what changed)
  variants_ced_items.json                       (input for the CED-conformance script)
"""
import difflib
import importlib
import json
import secrets
import sys
from pathlib import Path

from items import FRQS, MCQS
from vlib import check_variants
from verify_and_build import sq

HERE = Path(__file__).parent
MODULES = ["variants_mcq_a", "variants_mcq_b", "variants_mcq_c", "variants_frq"]
LETTERS = ["A", "B", "C", "D"]

orig_mcq = {m["id"]: m for m in MCQS}
orig_frq = {f["id"]: f for f in FRQS}


def load():
    out = []
    for name in MODULES:
        out += importlib.import_module(name).VARIANTS
    return out


def _tokens(v):
    """Word-level tokens of the whole item as a student sees it: stem, stimulus, and choices/parts."""
    import re
    if v["kind"] == "mcq":
        text = v["stem"] + " " + v["correct"][0] + " " + " ".join(w[0] for w in v["wrong"])
    else:
        text = v["stem"] + " " + v["stimulus"]
    return set(re.findall(r"[A-Za-z]+|\d+(?:\.\d+)?|[^\sA-Za-z\d]", text.lower()))


def _orig_tokens(v):
    import re
    if v["kind"] == "mcq":
        o = orig_mcq[v["of"]]
        text = o["stem"] + " " + o["correct"][0] + " " + " ".join(w[0] for w in o["wrong"])
    else:
        o = orig_frq[v["of"]]
        text = o["stem"] + " " + o["stimulus"]
    return set(re.findall(r"[A-Za-z]+|\d+(?:\.\d+)?|[^\sA-Za-z\d]", text.lower()))


def near_duplicates(variants, threshold=0.6):
    """Flag items whose word sets (stem + choices) overlap too much with the original or a sibling (Jaccard)."""
    def jac(a, b):
        return len(a & b) / len(a | b)
    warns = []
    for v in variants:
        j = jac(_tokens(v), _orig_tokens(v))
        if j > threshold:
            warns.append(f"{v['kind']} {v['id']}: {j:.2f} word overlap with its original")
    by = {}
    for v in variants:
        by.setdefault((v["kind"], v["of"]), []).append(v)
    for (kind, of), vs in by.items():
        for i in range(len(vs)):
            for k in range(i + 1, len(vs)):
                j = jac(_tokens(vs[i]), _tokens(vs[k]))
                if j > threshold:
                    warns.append(f"{kind} {vs[i]['id']} vs {vs[k]['id']}: {j:.2f} word overlap")
    return warns


def draw_letters(mcqs, rng):
    """Random position per item, resampled until the spread is sane and no triple shares one letter."""
    n = len(mcqs)
    lo, hi = int(n / 4 * 0.7), int(n / 4 * 1.35) + 1
    for _ in range(2000):
        draw = {v["id"]: rng.randrange(4) for v in mcqs}
        counts = [0] * 4
        for x in draw.values():
            counts[x] += 1
        if min(counts) < lo or max(counts) > hi:
            continue
        triples = {}
        for v in mcqs:
            triples.setdefault(v["of"], []).append(draw[v["id"]])
        if any(len(set(t)) == 1 for t in triples.values()):
            continue
        return draw, counts
    raise RuntimeError("could not draw a balanced letter assignment")


def build_sql(variants):
    rng = secrets.SystemRandom()
    mcqs = [v for v in variants if v["kind"] == "mcq"]
    frqs = [v for v in variants if v["kind"] == "frq"]
    draw, counts = draw_letters(mcqs, rng)
    out = [f"""-- AP Calculus AB, Unit 1: VARIANTS of the 34 original items (3 each), DRAFT.
-- Generated by build_variants.py. NOT APPLIED to any database.
--
-- Each variant is a separate content_item (its own content_key, prefix u1v) that teaches the same skill
-- as its original with different numbers AND a different context. variants_manifest.json maps every variant to
-- its original and records what changed. Provenance and originality: see README.md (same author, same batch family).
--
-- Content keys: apcalcab-mcq-u1v-NNN-vK ({len(mcqs)} MCQ), apcalcab-frq-u1v-NNN-vK ({len(frqs)} FRQ).
-- All rows status='draft', review_status='tutor_review_pending'. Correct MCQ letters drawn at random (spread {counts}).
--
-- Publication is NOT authorised by this file. Preconditions: phase 3 human review (originals first, variants
-- sampled), phase 4 CED check on a sample of variants, and independent section-9 re-derivation by someone other
-- than the author.

begin;
select pg_advisory_xact_lock(hashtext('cramapple-apcalcab-unit1-variants-20260929'));

do $$
declare
  v_epv_id uuid;
begin
  select epv.id into v_epv_id
  from app.exam_pack_versions epv
  join app.exam_packs e on e.id = epv.exam_pack_id
  where e.exam_name = 'AP Calculus AB';
  if v_epv_id is null then
    raise exception 'no_exam_pack_version_found:AP Calculus AB';
  end if;
  if exists (select 1 from app.content_items
             where content_key like 'apcalcab-mcq-u1v-%' or content_key like 'apcalcab-frq-u1v-%') then
    raise exception 'batch_already_seeded:apcalcab-u1v';
  end if;
  create temporary table u1v_epv (epv_id uuid) on commit drop;
  insert into u1v_epv values (v_epv_id);
end $$;
"""]
    for v in mcqs:
        key = f"apcalcab-mcq-u1v-{v['id']}"
        order = [("correct", v["correct"])] + [("wrong", w) for w in v["wrong"]]
        rng.shuffle(order)
        # force the drawn position for the correct answer
        pos = next(i for i, (k, _) in enumerate(order) if k == "correct")
        want = draw[v["id"]]
        order[pos], order[want] = order[want], order[pos]
        rows = []
        for i, (kind, (txt, rat)) in enumerate(order):
            rows.append(f"select gen_random_uuid(), id, {sq(LETTERS[i])}, {sq(txt)}, {'true' if kind == 'correct' else 'false'}, {sq(rat)} from version_ins")
        v["_letter"] = LETTERS[want]
        out.append(f"""
-- MCQ variant {v['id']} of {v['of']} | {v['diff']} | {v['title']}
with item_ins as (
  insert into app.content_items (id, exam_pack_version_id, content_key, item_type, title, status)
  select gen_random_uuid(), epv_id, {sq(key)}, 'mcq', {sq(v['title'])}, 'draft' from u1v_epv returning id
), version_ins as (
  insert into app.content_item_versions (id, content_item_id, version_num, stem, content_hash, status, review_status, canonical_answer_1)
  select gen_random_uuid(), id, 1, {sq(v['stem'])}, md5({sq(key)}), 'draft', 'tutor_review_pending', {sq(LETTERS[want])}
  from item_ins returning id
)
insert into app.mcq_choices (id, content_item_version_id, choice_key, choice_text, is_correct, rationale)
{rows[0]}
""" + "".join(f"union all {r}\n" for r in rows[1:]) + ";\n")
    for v in frqs:
        key = f"apcalcab-frq-u1v-{v['id']}"
        crit = []
        for (ck, text_, pts, ev, fix, var) in v["criteria"]:
            vj = "'[" + ",".join('"' + s.replace('"', '\\"').replace("'", "''") + '"' for s in var) + "]'::jsonb"
            crit.append(f"select gen_random_uuid(), id, {sq(ck)}, {sq(text_)}, {pts}, {sq(ev)}, {sq(fix)}, {vj} from version_ins")
        out.append(f"""
-- FRQ variant {v['id']} of {v['of']} | {v['diff']} | {v['title']}
with item_ins as (
  insert into app.content_items (id, exam_pack_version_id, content_key, item_type, title, status, frq_form, practice_format, frq_archetype)
  select gen_random_uuid(), epv_id, {sq(key)}, 'frq', {sq(v['title'])}, 'draft', 'short', 'targeted_drill', {sq(v['archetype'])}
  from u1v_epv returning id
), version_ins as (
  insert into app.content_item_versions (id, content_item_id, version_num, stem, stimulus, content_hash, status, review_status, rubric_type, evaluator_strategy)
  select gen_random_uuid(), id, 1, {sq(v['stem'])}, {sq(v['stimulus'])}, md5({sq(key)}), 'draft', 'tutor_review_pending', 'discrete_text', 'llm_discrete_text'
  from item_ins returning id
)
insert into app.frq_criteria (id, content_item_version_id, criterion_key, learner_facing_text, points_possible, evidence_requirements, minimum_fix, accepted_variants)
{crit[0]}
""" + "".join(f"union all {c}\n" for c in crit[1:]) + ";\n")
    out.append("\ncommit;\n")
    return "".join(out), counts


def main():
    variants = load()
    fails, per = check_variants(variants, MCQS, FRQS)
    for (kind, of), ids in sorted(per.items()):
        if len(ids) != 3:
            fails.append(f"{kind} original {of}: {len(ids)} variants, need 3")
    have = {(k, o) for (k, o) in per}
    for m in MCQS:
        if ("mcq", m["id"]) not in have:
            fails.append(f"missing variants for MCQ {m['id']}")
    for f in FRQS:
        if ("frq", f["id"]) not in have:
            fails.append(f"missing variants for FRQ {f['id']}")
    warns = near_duplicates(variants)
    if fails:
        print("FAILED:")
        for f in fails:
            print("  -", f)
        sys.exit(1)
    sql, counts = build_sql(variants)
    (HERE / "20260929_apcalcab_unit1_variants_batch.sql").write_text(sql)
    topic = {m["id"]: m["topic"] for m in MCQS}
    topic.update({("F" + f["id"]): f["topic"] for f in FRQS})
    manifest = []
    ced = []
    for v in variants:
        okey = f"apcalcab-{'mcq' if v['kind']=='mcq' else 'frq'}-u1n-{v['of']}"
        vkey = f"apcalcab-{'mcq' if v['kind']=='mcq' else 'frq'}-u1v-{v['id']}"
        manifest.append(dict(variant_key=vkey, original_key=okey, kind=v["kind"],
                             topic=(topic[v["of"]] if v["kind"] == "mcq" else topic["F" + v["of"]]),
                             difficulty=v["diff"], change=v["change"]))
        if v["kind"] == "mcq":
            ch = [(v["correct"][0], True)] + [(w[0], False) for w in v["wrong"]]
            ced.append(dict(content_key=vkey, item_type="mcq", stem=v["stem"], stimulus=None,
                            criteria=[f"{LETTERS[i]}. {'(correct) ' if c else ''}{t}" for i, (t, c) in enumerate(ch)]))
        else:
            ced.append(dict(content_key=vkey, item_type="frq", stem=v["stem"], stimulus=v["stimulus"],
                            criteria=[f"{c[0]} ({c[2]}pt): {c[1]} Evidence: {c[3]}" for c in v["criteria"]]))
    (HERE / "variants_manifest.json").write_text(json.dumps(manifest, indent=1))
    (HERE / "variants_ced_items.json").write_text(json.dumps(ced, indent=1))
    nm = sum(1 for v in variants if v["kind"] == "mcq")
    print(f"verified {len(variants)} variants ({nm} MCQ, {len(variants) - nm} FRQ); all calc()/checks agree.")
    print("MCQ correct-letter spread A/B/C/D:", counts)
    if warns:
        print("NEAR-DUPLICATE WARNINGS (review before accepting):")
        for w in warns:
            print("  -", w)
    else:
        print("no near-duplicate stems (all under 0.60 word overlap with the original and with siblings)")


if __name__ == "__main__":
    main()
