# AP Calculus AB, Unit 1 (Limits and Continuity): original item drafts.
#
# Every problem here was designed from the CED topic list and the fact pack
# (docs/product/AP_CALCULUS_AB_BC_CED_FACT_PACK.md), NOT from any third-party
# packet. See README.md for the originality statement.
#
# Each MCQ is (topic, difficulty, title, stem, correct, [distractors], check_id).
# `correct` and each distractor are (choice_text, rationale).
# `check_id` names an independent derivation in verify_and_build.py that
# recomputes the answer from the problem's own expression, without reading
# the keyed text first.

MCQS = [
    # ---------------------------------------------------------------- 1.1
    dict(id="001", topic="1.1", diff="easy", check="m01",
         title="Instantaneous Velocity From Average Velocity",
         stem="A particle moves along a line with position s(t) = t^2 feet at time t seconds. The average velocity of the particle over the interval [2, 2 + h] is 4 + h feet per second. What is the instantaneous velocity of the particle at t = 2?",
         correct=("4 feet per second",
                  "The instantaneous velocity is the limit of the average velocity as h approaches 0. As h approaches 0, 4 + h approaches 4."),
         wrong=[("4 + h feet per second",
                 "This is the average velocity over an interval of length h, so it depends on h. The instantaneous velocity is the limit of that expression as h approaches 0."),
                ("0 feet per second",
                 "Letting h approach 0 shrinks the interval, but it does not make the velocity 0. The expression 4 + h approaches 4."),
                ("2 feet per second",
                 "This uses the time t = 2 as if it were the velocity. The velocity is found from the limit of the average velocity, not read off the time.")]),
    dict(id="002", topic="1.1", diff="medium", check="m02",
         title="Estimating an Instantaneous Rate From Shrinking Intervals",
         stem="The table gives the average rate of change of a function f over the interval [1, 1 + h] for three values of h.\n\nh = 0.1: 6.3\nh = 0.01: 6.03\nh = 0.001: 6.003\n\nWhich of the following is the best estimate of the instantaneous rate of change of f at x = 1?",
         correct=("6",
                  "As the interval shrinks, the average rates are 6.3, 6.03, 6.003, moving toward 6. The instantaneous rate is the value these averages approach."),
         wrong=[("6.3",
                 "This is only the average rate over the widest interval. It is the least accurate of the three values, not the value being approached."),
                ("6.003",
                 "This is the average rate over the smallest interval in the table. It is close to the target but is still an average over an interval of length 0.001, not the value the averages approach."),
                ("0",
                 "Shrinking the interval toward length 0 does not make the rate 0. The averages in the table are getting closer to 6.")]),
    # ---------------------------------------------------------------- 1.2
    dict(id="003", topic="1.2", diff="easy", check="m03",
         title="What a Limit Statement Guarantees",
         stem="If lim(x->4) f(x) = 7, which of the following must be true?",
         correct=("The values of f(x) get arbitrarily close to 7 as x gets arbitrarily close to 4 from both sides of 4.",
                  "This is the meaning of a two-sided limit: the outputs approach 7 as the inputs approach 4 from the left and from the right."),
         wrong=[("f(4) = 7",
                 "A limit describes what f does near x = 4, not at x = 4. The value f(4) may be a different number, or f(4) may be undefined."),
                ("f is continuous at x = 4",
                 "Continuity requires f(4) to exist and equal the limit. The limit statement alone does not tell us anything about f(4)."),
                ("f is defined at x = 4",
                 "The limit as x approaches 4 does not depend on whether f is defined at x = 4, so the statement does not guarantee this.")]),
    dict(id="004", topic="1.2", diff="medium", check="m04",
         title="Limit Versus Function Value",
         stem="Let f be the function defined by\n\nf(x) = 2x - 1 for x < 3\nf(3) = 9\nf(x) = x^2 - 4 for x > 3\n\nWhat is lim(x->3) f(x)?",
         correct=("5",
                  "From the left, 2(3) - 1 = 5. From the right, 3^2 - 4 = 5. The one-sided limits agree, so the limit is 5, regardless of f(3)."),
         wrong=[("9",
                 "This is the value of f(3). The limit depends only on the values of f near 3, not on the value at 3."),
                ("6",
                 "This evaluates 2x at x = 3 and drops the -1 from the left-hand piece. The left piece is 2x - 1, which equals 5 at x = 3."),
                ("The limit does not exist.",
                 "The limit would fail to exist if the one-sided limits differed. Here both equal 5. The fact that f(3) = 9 does not affect the limit.")]),
    # ---------------------------------------------------------------- 1.4
    dict(id="005", topic="1.4", diff="medium", check="m05",
         title="Estimating a Limit From a Table With an Undefined Point",
         stem="The table shows values of a function f near x = 2. The value f(2) is undefined.\n\nx = 1.9: f(x) = 2.9\nx = 1.99: f(x) = 2.99\nx = 1.999: f(x) = 2.999\nx = 2.001: f(x) = 3.001\nx = 2.01: f(x) = 3.01\nx = 2.1: f(x) = 3.1\n\nWhich of the following is the best estimate of lim(x->2) f(x)?",
         correct=("3",
                  "From both sides the values of f(x) get closer to 3 as x gets closer to 2. The undefined value f(2) does not affect the limit."),
         wrong=[("2.999",
                 "This is the value at x = 1.999, one of the sampled points. The limit is the number the values approach, not one of the sampled outputs."),
                ("3.1",
                 "This is the output at the sampled point x = 2.1, which is the farthest from 2 on the right. The values keep decreasing toward 3."),
                ("The limit does not exist because f(2) is undefined.",
                 "A limit can exist even if the function is not defined at that point. What matters is the behavior of f on both sides of 2.")]),
    # ---------------------------------------------------------------- 1.5
    dict(id="006", topic="1.5", diff="medium", check="m06",
         title="Combining Limits With Algebraic Properties",
         stem="Suppose lim(x->4) f(x) = 3 and lim(x->4) g(x) = -2. What is lim(x->4) [3f(x) + (g(x))^2] / [f(x) + g(x)]?",
         correct=("13",
                  "The numerator approaches 3(3) + (-2)^2 = 9 + 4 = 13 and the denominator approaches 3 + (-2) = 1. The denominator's limit is not 0, so the quotient approaches 13/1 = 13."),
         wrong=[("5",
                 "This treats (-2)^2 as -4. Squaring -2 gives 4, so the numerator's limit is 9 + 4 = 13, not 9 - 4."),
                ("13/5",
                 "This uses 3 + 2 for the denominator, ignoring the sign of g. The denominator's limit is 3 + (-2) = 1."),
                ("7",
                 "This forgets to multiply f by 3 in the numerator, using 3 + 4 = 7 instead of 9 + 4 = 13.")]),
    dict(id="007", topic="1.5", diff="medium", check="m07",
         title="Quotient of Two Limits That Are Both Zero",
         stem="Suppose lim(x->1) f(x) = 0 and lim(x->1) g(x) = 0. Which of the following is true about lim(x->1) f(x)/g(x)?",
         correct=("It cannot be determined from this information alone.",
                  "The quotient law for limits requires the denominator's limit to be nonzero. When both limits are 0, the quotient can approach different values depending on the functions. For example, f(x) = 2(x - 1) and g(x) = x - 1 give 2, while f(x) = (x - 1)^2 and g(x) = x - 1 give 0."),
         wrong=[("It equals 0.",
                 "The form 0/0 is indeterminate. It is not automatically 0, as the example f(x) = 2(x - 1) and g(x) = x - 1 shows, where the quotient approaches 2."),
                ("It equals 1.",
                 "The form 0/0 is not automatically 1. The quotient's limit depends on how quickly f and g each approach 0."),
                ("It does not exist.",
                 "The quotient's limit sometimes exists, as with f(x) = 2(x - 1) and g(x) = x - 1, where it equals 2. So it is not guaranteed not to exist.")]),
    # ---------------------------------------------------------------- 1.7
    dict(id="008", topic="1.7", diff="easy", check="m08",
         title="Choosing a Method: When Direct Substitution Works",
         stem="For which of the following limits can the value be found by direct substitution?",
         correct=("lim(x->2) (x^2 + 3x)/(x - 1)",
                  "Substituting x = 2 gives (4 + 6)/(2 - 1) = 10. The denominator is nonzero at x = 2, so direct substitution gives the limit."),
         wrong=[("lim(x->1) (x^3 - 1)/(x - 1)",
                 "Substituting x = 1 gives 0/0. The expression must be simplified first by factoring x^3 - 1 = (x - 1)(x^2 + x + 1)."),
                ("lim(x->0) |x|/x",
                 "Substituting x = 0 gives 0/0, and the one-sided limits are 1 from the right and -1 from the left, so the limit does not exist."),
                ("lim(x->3) (x - 3)/(x^2 - 9)",
                 "Substituting x = 3 gives 0/0. The expression must be simplified first by factoring x^2 - 9 = (x - 3)(x + 3).")]),
    dict(id="009", topic="1.7", diff="medium", check="m09",
         title="Using the Sine Limit After Adjusting the Argument",
         stem="What is lim(x->0) sin(3x)/x?",
         correct=("3",
                  "Write sin(3x)/x as 3 * sin(3x)/(3x). As x approaches 0, sin(3x)/(3x) approaches 1, so the limit is 3(1) = 3."),
         wrong=[("1",
                 "The special limit sin(u)/u = 1 needs the same expression in the numerator's argument and in the denominator. Here the argument is 3x but the denominator is x, so a factor of 3 remains."),
                ("0",
                 "The numerator approaches 0, but so does the denominator. The form is 0/0, which is not automatically 0."),
                ("1/3",
                 "This inverts the factor. Since sin(3x) behaves like 3x near 0, the ratio sin(3x)/x behaves like 3x/x = 3, not 1/3.")]),
    # ---------------------------------------------------------------- 1.8
    dict(id="010", topic="1.8", diff="easy", check="m10",
         title="Applying the Squeeze Theorem",
         stem="A function f satisfies 4 - 3x^2 <= f(x) <= 4 + x^2 for all x. What is lim(x->0) f(x)?",
         correct=("4",
                  "Both bounding functions approach 4 as x approaches 0. Since f is between them, the Squeeze Theorem gives lim f(x) = 4."),
         wrong=[("0",
                 "The terms 3x^2 and x^2 approach 0, but the bounds are 4 - 3x^2 and 4 + x^2, and those approach 4."),
                ("8",
                 "This adds the two bounding limits, 4 + 4. The Squeeze Theorem says f has the same limit as the bounds, not their sum."),
                ("It cannot be determined.",
                 "The Squeeze Theorem applies here because the upper and lower bounds have the same limit, 4, as x approaches 0.")]),
    # ---------------------------------------------------------------- 1.9
    dict(id="011", topic="1.9", diff="medium", check="m11",
         title="Limit, Continuity and Discontinuity Type Together",
         stem="A function f has lim(x->2-) f(x) = 5, lim(x->2+) f(x) = 5, and f(2) = 1. Consider the following statements.\n\nI. lim(x->2) f(x) exists.\nII. f is continuous at x = 2.\nIII. f has a removable discontinuity at x = 2.\n\nWhich of the statements are true?",
         correct=("I and III only",
                  "The one-sided limits are equal, so the limit exists (I). Because f(2) = 1 is not equal to the limit 5, f is not continuous at 2 (II is false). A discontinuity where the limit exists is removable (III)."),
         wrong=[("I only",
                 "Statement I is true, but so is III. A discontinuity where the limit exists but differs from the function value is removable."),
                ("I and II only",
                 "Continuity requires f(2) to equal the limit. Here f(2) = 1 and the limit is 5, so f is not continuous at x = 2."),
                ("II and III only",
                 "Statement II is false because f(2) does not equal the limit, and statement I is true because the one-sided limits agree.")]),
    dict(id="012", topic="1.9", diff="medium", check="m12",
         title="A Quotient With an Absolute Value",
         stem="Let f(x) = |x - 3|/(x - 3) for x != 3. Which of the following is true about lim(x->3) f(x)?",
         correct=("The limit does not exist because the one-sided limits are -1 and 1.",
                  "For x > 3, |x - 3| = x - 3, so f(x) = 1. For x < 3, |x - 3| = -(x - 3), so f(x) = -1. The one-sided limits differ, so the two-sided limit does not exist."),
         wrong=[("The limit is 1.",
                 "This is the right-hand limit only. From the left, f(x) = -1, so the two-sided limit does not exist."),
                ("The limit is -1.",
                 "This is the left-hand limit only. From the right, f(x) = 1, so the two-sided limit does not exist."),
                ("The limit is 0.",
                 "The values of f are -1 to the left and 1 to the right of x = 3. They are never 0 near x = 3, and neither one-sided limit is 0.")]),
    # ---------------------------------------------------------------- 1.10
    dict(id="013", topic="1.10", diff="easy", check="m13",
         title="Identifying a Jump Discontinuity",
         stem="Let f be the function defined by\n\nf(x) = x + 2 for x < 1\nf(x) = 5 - x for x >= 1\n\nWhich of the following describes f at x = 1?",
         correct=("f has a jump discontinuity at x = 1.",
                  "From the left, the limit is 1 + 2 = 3. From the right, the limit is 5 - 1 = 4. Both one-sided limits exist but are unequal, which is a jump discontinuity."),
         wrong=[("f has a removable discontinuity at x = 1.",
                 "A removable discontinuity has equal one-sided limits. Here the one-sided limits are 3 and 4."),
                ("f has an infinite discontinuity at x = 1.",
                 "An infinite discontinuity involves unbounded behavior. Both one-sided limits here are finite numbers."),
                ("f is continuous at x = 1.",
                 "Continuity requires the limit to exist. The left-hand limit is 3 and the right-hand limit is 4, so the limit does not exist.")]),
    dict(id="014", topic="1.10", diff="medium", check="m14",
         title="Recognizing an Infinite Discontinuity",
         stem="Which of the following functions has an infinite discontinuity at x = 3?",
         correct=("f(x) = (x + 1)/(x - 3)^2",
                  "At x = 3 the denominator is 0 and the numerator is 4, which is nonzero. The function is unbounded near 3, so there is an infinite discontinuity."),
         wrong=[("f(x) = (x^2 - x - 6)/(x - 3)",
                 "Factoring gives (x - 3)(x + 2)/(x - 3), which equals x + 2 for x != 3. The limit at 3 is 5, so this is a removable discontinuity."),
                ("f(x) = |x - 3|/(x - 3)",
                 "The one-sided limits are -1 and 1, both finite. This is a jump discontinuity."),
                ("f(x) = (x - 3)/(x + 3)",
                 "This function is continuous at x = 3, where it equals 0. Its discontinuity is at x = -3.")]),
    # ---------------------------------------------------------------- 1.11
    dict(id="015", topic="1.11", diff="medium", check="m15",
         title="Choosing a Parameter for Continuity at a Boundary",
         stem="Let f be the function defined by\n\nf(x) = ax + 1 for x < 2\nf(x) = x^2 - a for x >= 2\n\nFor what value of a is f continuous at x = 2?",
         correct=("1",
                  "Continuity requires the left-hand limit 2a + 1 to equal f(2) = 4 - a. Solving 2a + 1 = 4 - a gives 3a = 3, so a = 1."),
         wrong=[("5/3",
                 "This solves 2a + 1 = 4 - a as 3a = 5, adding 1 instead of subtracting it. The correct step is 3a = 4 - 1 = 3."),
                ("3/2",
                 "This sets 2a + 1 = 4 and forgets that the right-hand piece, x^2 - a, also contains a."),
                ("-5",
                 "This sets up 2a + 1 = a - 4, changing the sign of the right-hand piece. The right-hand value at x = 2 is 4 - a.")]),
    # ---------------------------------------------------------------- 1.12
    dict(id="016", topic="1.12", diff="medium", check="m16",
         title="Where Is a Radical Quotient Continuous?",
         stem="What is the largest set on which f(x) = sqrt(x - 1)/(x - 4) is continuous?",
         correct=("The union of [1, 4) and (4, infinity)",
                  "The square root requires x >= 1, and the denominator is 0 at x = 4. The function is continuous at every point in its domain, and continuity at x = 1 is from the right, so 1 is included."),
         wrong=[("[1, infinity)",
                 "This includes x = 4, where the denominator is 0 and f is undefined."),
                ("The union of (1, 4) and (4, infinity)",
                 "The function is continuous on this set, but it is not the largest such set. f is also continuous at x = 1 from the right, because f(1) is defined and equals the right-hand limit."),
                ("The union of (-infinity, 4) and (4, infinity)",
                 "The square root is undefined for x < 1, so f is not defined on much of this set.")]),
    dict(id="017", topic="1.12", diff="hard", check="m17",
         title="Continuity on a Closed Interval",
         stem="Which of the following functions is continuous on the closed interval [0, 5]?",
         correct=("f(x) = tan(pi x/12)",
                  "The tangent function is undefined only where its argument is pi/2 plus a multiple of pi. Here that happens at x = 6 + 12k for every integer k, and the nearest such x-values are x = 6 and x = -6, both outside [0, 5], so f is continuous on the whole interval."),
         wrong=[("f(x) = 1/(x - 3)",
                 "The function is undefined at x = 3, which lies in [0, 5]."),
                ("f(x) = ln(x - 1)",
                 "The logarithm is undefined for x <= 1, so f is not defined on [0, 1]."),
                ("f(x) = |x - 2|/(x - 2)",
                 "The function is undefined at x = 2, which lies in [0, 5].")]),
    # ---------------------------------------------------------------- 1.13
    dict(id="018", topic="1.13", diff="easy", check="m18",
         title="Filling a Hole Left by a Cube Difference",
         stem="The function g is defined by g(x) = (x^3 - 8)/(x - 2) for x != 2, and g(2) = k. For what value of k is g continuous at x = 2?",
         correct=("12",
                  "Since x^3 - 8 = (x - 2)(x^2 + 2x + 4), g(x) = x^2 + 2x + 4 for x != 2. The limit as x approaches 2 is 4 + 4 + 4 = 12, and continuity requires k to equal that limit."),
         wrong=[("8",
                 "This factors x^3 - 8 as (x - 2)(x^2 + 4), dropping the middle term. Expanding (x - 2)(x^2 + 4) gives x^3 - 2x^2 + 4x - 8, not x^3 - 8."),
                ("0",
                 "Substituting x = 2 gives 0 in the numerator, but the denominator is also 0. The form 0/0 is indeterminate, so the limit must be found by simplifying first."),
                ("No such value of k exists.",
                 "The denominator is 0 at x = 2, but the factor x - 2 cancels. The limit exists, so a value of k that matches it does exist.")]),
    dict(id="019", topic="1.13", diff="medium", check="m19",
         title="Removing a Discontinuity With a Radical",
         stem="The function h is defined by h(x) = (sqrt(x + 9) - 3)/x for x != 0, and h(0) = c. For what value of c is h continuous at x = 0?",
         correct=("1/6",
                  "Multiplying the numerator and denominator by the conjugate sqrt(x + 9) + 3 gives x/(x(sqrt(x + 9) + 3)) = 1/(sqrt(x + 9) + 3) for x != 0. As x approaches 0 this approaches 1/(3 + 3) = 1/6."),
         wrong=[("1/3",
                 "This uses 3 instead of 6 for the denominator. After multiplying by the conjugate, the denominator becomes sqrt(x + 9) + 3, which equals 3 + 3 = 6 at x = 0, not 3."),
                ("0",
                 "The numerator sqrt(0 + 9) - 3 equals 0, but the denominator is also 0. The quotient is 0/0, which is indeterminate, so the limit has to be found by simplifying first, for example by rationalizing with the conjugate."),
                ("6",
                 "This inverts the result. After multiplying by the conjugate, the expression is 1/(sqrt(x + 9) + 3), which approaches 1/6.")]),
    dict(id="020", topic="1.13", diff="medium", check="m20",
         title="Choosing a Parameter So the Numerator Cancels",
         stem="Let f be the function defined by f(x) = (x^2 + ax - 10)/(x - 2) for x != 2, and f(2) = 7. For what value of a is f continuous at x = 2?",
         correct=("3",
                  "For the limit to exist, the numerator must be 0 at x = 2: 4 + 2a - 10 = 0, so a = 3. Then x^2 + 3x - 10 = (x - 2)(x + 5), and the limit is 2 + 5 = 7, which matches f(2)."),
         wrong=[("5",
                 "This assumes the numerator factors as (x - 2)(x + a) and sets 2 + a = 7. But (x - 2)(x + 5) = x^2 + 3x - 10, so the coefficient of x would have to be 3, not 5."),
                ("7",
                 "This confuses the required limit value with the parameter. The number 7 is the value f(2) that the limit must match, not the value of a."),
                ("-3",
                 "This makes a sign error in solving 4 + 2a - 10 = 0. Adding 6 to both sides gives 2a = 6, so a = 3.")]),
    dict(id="021", topic="1.13", diff="hard", check="m21",
         title="Removable Versus Infinite Discontinuities in One Function",
         stem="Let f(x) = (x^2 - 9)/(x^2 - 5x + 6). Which of the following describes the discontinuities of f?",
         correct=("Removable at x = 3 and infinite at x = 2",
                  "Factoring gives f(x) = (x - 3)(x + 3)/((x - 2)(x - 3)). The factor x - 3 cancels, so the limit at x = 3 is 6 and the discontinuity there is removable. The factor x - 2 remains in the denominator while the numerator is -5 at x = 2, so f is unbounded near 2."),
         wrong=[("Infinite at both x = 2 and x = 3",
                 "Both are zeros of the denominator, but at x = 3 the factor x - 3 also appears in the numerator and cancels, so the limit there is finite."),
                ("Removable at both x = 2 and x = 3",
                 "At x = 2 the numerator is 4 - 9 = -5, not 0, so nothing cancels and f is unbounded near 2."),
                ("Removable at x = 2 and infinite at x = 3",
                 "This reverses the roles. It is at x = 3 that a common factor cancels, and at x = 2 that the denominator stays zero.")]),
    # ---------------------------------------------------------------- 1.14
    dict(id="022", topic="1.14", diff="easy", check="m22",
         title="One-Sided Infinite Limit From the Right",
         stem="What is lim(x->3+) 2x/(x^2 - 9)?",
         correct=("infinity",
                  "As x approaches 3 from the right, the numerator approaches 6, which is positive. The denominator (x - 3)(x + 3) is a small positive number times a number near 6, so it is small and positive. A positive number divided by a small positive number grows without bound."),
         wrong=[("-infinity",
                 "This uses the wrong sign. For x slightly greater than 3, x - 3 is positive, so the denominator is positive."),
                ("0",
                 "The denominator approaches 0 while the numerator approaches 6. A small denominator makes the quotient large, not small."),
                ("6",
                 "This uses the numerator's value alone. The denominator approaches 0, so the quotient is unbounded.")]),
    dict(id="023", topic="1.14", diff="medium", check="m23",
         title="Holes Versus Vertical Asymptotes",
         stem="Let f(x) = (x^2 - 4x)/(x^2 - 16). Which of the following gives all vertical asymptotes of the graph of f?",
         correct=("x = -4 only",
                  "Factoring gives f(x) = x(x - 4)/((x - 4)(x + 4)). The factor x - 4 cancels, leaving a hole at x = 4. At x = -4 the denominator of the simplified expression x/(x + 4) is 0 while the numerator is -4, which is nonzero, so there is a vertical asymptote."),
        wrong=[("x = 4 and x = -4",
                 "Both are zeros of the denominator, but at x = 4 the factor x - 4 cancels with the numerator, leaving a hole rather than an asymptote."),
                ("x = 0 and x = -4",
                 "x = 0 is a zero of the numerator, so f(0) = 0. It is not a zero of the denominator, so there is no asymptote there."),
                ("x = 4 only",
                 "At x = 4 the factor cancels, leaving a hole. The asymptote is at x = -4, where the zero of the denominator remains after simplifying.")]),
    dict(id="024", topic="1.14", diff="medium", check="m24",
         title="An Infinite Limit With a Squared Denominator",
         stem="What is lim(x->-2-) (x + 5)/(x + 2)^2?",
         correct=("infinity",
                  "The numerator approaches 3, which is positive. The denominator (x + 2)^2 is positive for every x != -2 and approaches 0, so the quotient is positive and unbounded."),
         wrong=[("-infinity",
                 "It is tempting to say x + 2 is negative when x < -2. But the factor is squared, so the denominator is positive on both sides of -2."),
                ("0",
                 "The numerator approaches 3, a nonzero number. When the numerator approaches a nonzero number, a denominator approaching 0 makes the quotient large in magnitude, not small."),
                ("The limit does not exist because the one-sided limits are different.",
                 "The one-sided limits are equal here: (x + 2)^2 is positive on both sides of -2, so the quotient grows without bound in the same direction from both sides.")]),
    dict(id="025", topic="1.14", diff="hard", check="m25",
         title="A Vertical Asymptote of a Trigonometric Function",
         stem="On the interval 0 <= x <= pi, the graph of f(x) = 1/(2cos x - 1) has a vertical asymptote at x =",
         correct=("pi/3",
                  "A vertical asymptote occurs where the denominator is 0 and the numerator is not. Setting 2cos x - 1 = 0 gives cos x = 1/2, and the only solution in [0, pi] is x = pi/3."),
         wrong=[("pi/6",
                 "sin(pi/6) equals 1/2, but the denominator involves cosine. The equation is cos x = 1/2."),
                ("pi/2",
                 "cos(pi/2) = 0, which makes 2cos x - 1 equal -1. The function is defined there, so there is no asymptote."),
                ("0",
                 "At x = 0, 2cos 0 - 1 = 1, so f(0) = 1 and there is no asymptote.")]),
    # ---------------------------------------------------------------- 1.15
    dict(id="026", topic="1.15", diff="easy", check="m26",
         title="Limit at Infinity of a Rational Function",
         stem="What is lim(x->infinity) (5x^3 - 2x)/(2x^3 + 7x^2)?",
         correct=("5/2",
                  "The numerator and denominator both have degree 3. Dividing each term by x^3 leaves (5 - 2/x^2)/(2 + 7/x), which approaches 5/2."),
         wrong=[("2/5",
                 "This inverts the ratio of leading coefficients. The numerator's leading coefficient is 5 and the denominator's is 2."),
                ("0",
                 "A limit of 0 would require the denominator's degree to exceed the numerator's. Here the degrees are equal."),
                ("infinity",
                 "A limit of infinity would require the numerator's degree to exceed the denominator's. Here the degrees are equal.")]),
    dict(id="027", topic="1.15", diff="hard", check="m27",
         title="Two Horizontal Asymptotes From a Radical",
         stem="Let f(x) = 3x/sqrt(4x^2 + 1). Which of the following gives all horizontal asymptotes of the graph of f?",
         correct=("y = 3/2 and y = -3/2",
                  "For large positive x, sqrt(4x^2 + 1) behaves like 2x, so f approaches 3/2. For large negative x, sqrt(4x^2 + 1) behaves like 2|x| = -2x, so f approaches -3/2."),
         wrong=[("y = 3/2 only",
                 "This considers only x approaching positive infinity. As x approaches negative infinity, the radical is positive while x is negative, giving the limit -3/2."),
                ("y = 0 only",
                 "The numerator grows like x and sqrt(4x^2 + 1) grows like 2|x|. They grow at the same rate, so the limit is not 0."),
                ("y = 3 and y = -3",
                 "This treats sqrt(4x^2 + 1) as behaving like |x|. It behaves like 2|x|, because sqrt(4x^2) = 2|x|.")]),
    dict(id="028", topic="1.15", diff="medium", check="m28",
         title="Interpreting a Limit at Infinity in Context",
         stem="The temperature of a cup of tea is modeled by T(t) = 20 + 60e^(-t/4) degrees Celsius, where t >= 0 is the time in minutes. What is lim(t->infinity) T(t), and what does it mean in this context?",
         correct=("20; the tea's temperature levels off near 20 degrees Celsius.",
                  "As t increases, e^(-t/4) approaches 0, so T(t) approaches 20 + 60(0) = 20. The model predicts the temperature settles near 20 degrees."),
         wrong=[("80; the tea's temperature levels off near 80 degrees Celsius.",
                 "The value 80 is T(0), the starting temperature. The question is about what happens as t grows large, not at t = 0."),
                ("0; the tea eventually cools to 0 degrees Celsius.",
                 "The exponential term approaches 0, but the constant 20 remains, so T(t) approaches 20."),
                ("infinity; the tea's temperature grows without bound.",
                 "The exponent -t/4 is negative, so e^(-t/4) decays toward 0. The temperature does not grow.")]),
    dict(id="029", topic="1.15", diff="hard", check="m29",
         title="Comparing Growth Rates at Infinity",
         stem="What is lim(x->infinity) (x^5 + 3^x)/(2 * 4^x)?",
         correct=("0",
                  "Exponential 4^x grows faster than both the exponential 3^x and the polynomial x^5. Dividing the numerator and denominator by 4^x gives (x^5/4^x + (3/4)^x)/2, and both terms in the numerator approach 0."),
         wrong=[("1/2",
                 "This compares only the coefficients 1 and 2, ignoring that the denominator's 4^x outgrows both terms in the numerator."),
                ("infinity",
                 "This assumes the numerator outgrows the denominator. But 4^x grows faster than 3^x and faster than any power of x."),
                ("2",
                 "This inverts the coefficient comparison, and it also ignores the difference in growth rates.")]),
]

# ---------------------------------------------------------------- FRQs
# Each criterion: (key, learner_facing_text, points, evidence_requirements, minimum_fix, accepted_variants)
FRQS = [
    dict(id="001", topic="1.13", diff="medium", archetype="mathematical_routines",
         title="A Hole and an Asymptote in One Rational Function",
         stimulus="Let g be the function defined by g(x) = (2x^2 - x - 15)/(x^2 - 9) for x != 3 and x != -3.",
         stem="Answer all parts of the following question.\n\n(a) Find lim(x->3) g(x). Show the algebra that leads to your answer.\n\n(b) The graph of g has a removable discontinuity at x = 3. Justify this, and state the value that would have to be assigned to g(3) to make the function continuous at x = 3.\n\n(c) Find lim(x->-3-) g(x) and lim(x->-3+) g(x). Give a reason for the sign of each.",
         criteria=[
             ("part-a-criterion-01", "Factors and cancels x - 3, then evaluates to obtain the limit 11/6.", 1,
              "Response factors the numerator as (2x + 5)(x - 3) and the denominator as (x - 3)(x + 3), cancels x - 3, and evaluates (2x + 5)/(x + 3) at x = 3 to get 11/6.",
              "Show the factoring and cancellation step before evaluating. A correct value with no algebra does not earn the point.",
              ["11/6"]),
             ("part-b-criterion-01", "Justifies a removable discontinuity: the limit at x = 3 exists but g(3) is not defined.", 1,
              "Response states that the limit exists as a finite number while g(3) is undefined (or does not equal the limit), so the discontinuity is removable.",
              "State that the limit exists and that g(3) is undefined. Saying only 'the factors cancel' is not sufficient.",
              []),
             ("part-b-criterion-02", "States that g(3) would have to equal 11/6 for continuity.", 1,
              "Response states that assigning g(3) = 11/6 (the limit found in part (a)) makes g continuous at x = 3.",
              "Give the value 11/6 and connect it to the limit.",
              ["11/6"]),
             ("part-c-criterion-01", "Finds the one-sided limits at x = -3 as infinity from the left and -infinity from the right, with sign reasoning.", 1,
              "Response gives lim(x->-3-) g(x) = infinity and lim(x->-3+) g(x) = -infinity, using the simplified form (2x + 5)/(x + 3): the numerator is -1 near x = -3 and x + 3 is negative on the left and positive on the right.",
              "Give both one-sided limits and explain the sign of x + 3 on each side. Both must be correct.",
              ["+infinity", "positive infinity", "negative infinity"]),
         ]),
    dict(id="002", topic="1.14", diff="medium", archetype="mathematical_routines",
         title="Vertical and Horizontal Asymptotes of a Rational Function",
         stimulus="Let f be the function defined by f(x) = 3x/(x^2 - 4x - 5).",
         stem="Answer all parts of the following question.\n\n(a) Find all vertical asymptotes of the graph of f. Justify your answer.\n\n(b) Find lim(x->5+) f(x). Give a reason for the sign of your answer.\n\n(c) Find lim(x->-1-) f(x). Give a reason for the sign of your answer.\n\n(d) Write an equation for the horizontal asymptote of the graph of f, or explain why there is none.",
         criteria=[
             ("part-a-criterion-01", "Identifies x = 5 and x = -1 and justifies each with a zero denominator and a nonzero numerator.", 1,
              "Response factors the denominator as (x - 5)(x + 1) and identifies x = 5 and x = -1, noting that the numerator 3x is nonzero (15 and -3) at each.",
              "Name both asymptotes and state that the numerator is nonzero at each. Listing the zeros of the denominator alone is not enough.",
              []),
             ("part-b-criterion-01", "Finds lim(x->5+) f(x) = infinity, with sign reasoning.", 1,
              "Response gives infinity and explains that near 5 from the right the numerator is positive (about 15), x - 5 is small and positive, and x + 1 is positive.",
              "Give infinity and justify the sign of each factor.",
              ["+infinity", "positive infinity"]),
             ("part-c-criterion-01", "Finds lim(x->-1-) f(x) = -infinity, with sign reasoning.", 1,
              "Response gives -infinity and explains that near -1 from the left the numerator is negative (about -3), and both x + 1 and x - 5 are negative, so the denominator is small and positive.",
              "Give -infinity and justify the sign of the numerator and denominator.",
              ["negative infinity"]),
             ("part-d-criterion-01", "States the horizontal asymptote y = 0 with a valid reason based on degrees or a limit at infinity.", 1,
              "Response gives y = 0 and justifies it with the degree of the denominator exceeding the degree of the numerator, or by evaluating lim(x->infinity) f(x) = 0.",
              "State y = 0 and give a reason based on degrees or the limit at infinity.",
              ["y = 0"]),
         ]),
    dict(id="003", topic="1.15", diff="hard", archetype="mathematical_routines",
         title="Long-Run Behavior in Context and Growth-Rate Comparison",
         stimulus="The amount of salt, in grams, dissolved in a tank at time t minutes is modeled by A(t) = (80t + 100)/(2t + 5) for t >= 0.",
         stem="Answer all parts of the following question.\n\n(a) Find lim(t->infinity) A(t). Include units and interpret the meaning of your answer in context.\n\n(b) Let q(x) = (4x + 1)/sqrt(9x^2 + 2). Find all horizontal asymptotes of the graph of q. Show the work that leads to each.\n\n(c) Evaluate lim(x->infinity) (2x^4 + 5^x)/(3^x + x^7). Justify your answer using the relative growth rates of the functions involved.",
         criteria=[
             ("part-a-criterion-01", "Finds lim(t->infinity) A(t) = 40 using the leading terms or dividing by t.", 1,
              "Response evaluates the limit as 40, for example by dividing by t or comparing leading coefficients 80 and 2.",
              "Show the method (dividing by t or comparing leading terms) along with the value 40.",
              ["40"]),
             ("part-a-criterion-02", "Interprets the limit with units: the amount of salt approaches 40 grams in the long run.", 1,
              "Response states that as time increases without bound, the amount of salt in the tank approaches (levels off near) 40 grams.",
              "Include the units (grams) and say what quantity approaches 40 as time grows.",
              ["40 grams"]),
             ("part-b-criterion-01", "Finds both horizontal asymptotes y = 4/3 and y = -4/3, using sqrt(9x^2) = 3|x|.", 1,
              "Response gives y = 4/3 (as x approaches infinity) and y = -4/3 (as x approaches negative infinity), showing that the radical behaves like 3|x|.",
              "Give both asymptotes and show that the denominator behaves like 3|x|, so its sign flips for negative x.",
              ["y = 4/3 and y = -4/3"]),
             ("part-c-criterion-01", "Finds the limit is infinity and justifies with 5^x growing faster than 3^x and any polynomial.", 1,
              "Response gives infinity and justifies that 5^x outgrows 3^x and powers of x (for example by dividing by 5^x to obtain a numerator approaching 1 and a denominator approaching 0 from above).",
              "State infinity and compare growth rates of 5^x, 3^x, x^4 and x^7.",
              ["infinity", "positive infinity"]),
         ]),
    dict(id="004", topic="1.12", diff="medium", archetype="mathematical_routines",
         title="Continuity of a Piecewise Function With Two Parameters",
         stimulus="Let f be the function defined by\n\nf(x) = kx + 2 for x < 1\nf(1) = m\nf(x) = (x^2 + 2x - 3)/(x - 1) for x > 1\n\nwhere k and m are constants.",
         stem="Answer all parts of the following question.\n\n(a) Find lim(x->1+) f(x). Show the work that leads to your answer.\n\n(b) Find the values of k and m for which f is continuous at x = 1. Justify your answer using the definition of continuity.\n\n(c) Suppose k = 3 and m = 4. Is f continuous at x = 1? If not, classify the discontinuity and justify your answer.",
         criteria=[
             ("part-a-criterion-01", "Factors and cancels to find lim(x->1+) f(x) = 4.", 1,
              "Response factors x^2 + 2x - 3 = (x + 3)(x - 1), cancels x - 1, and evaluates x + 3 at x = 1 to get 4.",
              "Show the factoring and cancellation, not just the value 4.",
              ["4"]),
             ("part-b-criterion-01", "Sets the left-hand limit equal to the right-hand limit and finds k = 2.", 1,
              "Response sets k(1) + 2 = 4 (the left-hand limit equals the right-hand limit) and finds k = 2.",
              "Set the one-sided limits equal and solve for k.",
              ["k = 2"]),
             ("part-b-criterion-02", "Sets m equal to the limit and finds m = 4, citing the three conditions of continuity.", 1,
              "Response states that f(1) must equal the limit as x approaches 1, so m = 4, referencing that f(1) is defined, the limit exists, and the two are equal.",
              "State that f(1) must equal the limit and give m = 4.",
              ["m = 4"]),
             ("part-c-criterion-01", "Finds the one-sided limits 5 and 4, concludes f is not continuous, and classifies it as a jump discontinuity.", 1,
              "Response gives lim(x->1-) f(x) = 3(1) + 2 = 5 and lim(x->1+) f(x) = 4, concludes that the limit does not exist so f is not continuous, and names the discontinuity a jump discontinuity.",
              "Give both one-sided limits (5 and 4), conclude f is not continuous, and name the discontinuity type.",
              ["jump"]),
         ]),
    dict(id="005", topic="1.9", diff="medium", archetype="translation_between_representations",
         title="Table Estimate and Algebraic Confirmation of a Limit",
         stimulus="Let h be the function defined by h(x) = (sqrt(x + 4) - 3)/(x - 5) for x != 5. Selected values of h(x) are given in the table.\n\nx = 4.9: h(x) = TABLE_H1\nx = 4.99: h(x) = TABLE_H2\nx = 4.999: h(x) = TABLE_H3\nx = 5.001: h(x) = TABLE_H4\nx = 5.01: h(x) = TABLE_H5\nx = 5.1: h(x) = TABLE_H6",
         stem="Answer all parts of the following question.\n\n(a) Use the table to estimate lim(x->5) h(x). Explain how the table supports your estimate.\n\n(b) Use algebra to find the exact value of lim(x->5) h(x). Show your work.\n\n(c) The function h is extended by defining h(5) = 0.2. Is the extended function continuous at x = 5? If not, classify the discontinuity and justify your answer.",
         criteria=[
             ("part-a-criterion-01", "Estimates the limit near 0.1667 and supports it with values from both sides of 5.", 1,
              "Response gives an estimate of about 0.167 (or 1/6) and notes that the values from both the left and the right of x = 5 approach that number.",
              "Cite values from both sides of 5, not just one side, when supporting the estimate.",
              ["0.167", "0.1667", "1/6"]),
             ("part-b-criterion-01", "Multiplies by the conjugate sqrt(x + 4) + 3 and simplifies.", 1,
              "Response multiplies numerator and denominator by sqrt(x + 4) + 3 and simplifies the numerator to (x + 4) - 9 = x - 5, then cancels x - 5.",
              "Show the multiplication by the conjugate and the cancellation of x - 5.",
              []),
             ("part-b-criterion-02", "Evaluates to the exact limit 1/6.", 1,
              "Response evaluates 1/(sqrt(x + 4) + 3) at x = 5 to obtain 1/(3 + 3) = 1/6.",
              "State the exact value 1/6.",
              ["1/6"]),
             ("part-c-criterion-01", "Concludes the extended function is not continuous because 0.2 does not equal 1/6, and calls the discontinuity removable.", 1,
              "Response states that the limit 1/6 exists but does not equal h(5) = 0.2 (which is 1/5), so h is not continuous at x = 5, and that the discontinuity is removable.",
              "Compare the limit 1/6 with the value 0.2, state that they differ, and name the discontinuity removable.",
              ["removable"]),
         ]),
]
