# Variants (3 each) of MCQ originals 001-010, AP Calculus AB Unit 1.
from sympy import symbols, limit, sqrt, sin, cos, tan, log, Rational, oo, S, Abs, nan, zoo
from vlib import M, fmt

x, h, t, q, a, b = symbols("x h t q a b", real=True)


def direct_ok(expr, at):
    """True if plain substitution gives a finite number (not 0/0, not k/0)."""
    v = expr.subs(x, at)
    return v not in (nan, zoo, oo, -oo) and v.is_finite is not False


VARIANTS = [
    # ---------------- 001: instantaneous velocity from an average-rate expression ----------------
    M("001-v1", "001", "easy", "Cyclist Speed From Average Speeds",
      "A cyclist's position is s(t) meters at time t seconds. The average velocity of the cyclist over the interval [5, 5 + h] is 12 - 3h + h^2 meters per second. What is the cyclist's instantaneous velocity at t = 5?",
      ("12 meters per second",
       "The instantaneous velocity is the limit of the average velocity as h approaches 0. As h approaches 0, 12 - 3h + h^2 approaches 12."),
      [("12 - 3h + h^2 meters per second",
        "This is the average velocity over an interval of length h, so it still depends on h. The instantaneous velocity is the limit of that expression as h approaches 0."),
       ("0 meters per second",
        "Letting h approach 0 shrinks the interval but does not make the velocity 0. The expression 12 - 3h + h^2 approaches 12."),
       ("5 meters per second",
        "This uses the time t = 5 as if it were the velocity. The velocity comes from the limit of the average velocity, not from the time value.")],
      calc=lambda: fmt(limit(12 - 3 * h + h**2, h, 0)) + " meters per second",
      change="numbers: 4 + h -> 12 - 3h + h^2; context: particle on a line -> cyclist"),
    M("001-v2", "001", "easy", "Draining Tank Rate From a Volume Change",
      "Water drains from a tank. Let V(t) be the volume in liters at time t minutes. Over the interval [4, 4 + h], the volume changes by V(4 + h) - V(4) = -5h - 2h^2 liters. What is the instantaneous rate of change of the volume at t = 4?",
      ("-5 liters per minute",
       "The average rate over [4, 4 + h] is (-5h - 2h^2)/h = -5 - 2h for h != 0. As h approaches 0 this approaches -5, which is the instantaneous rate."),
      [("0 liters per minute",
        "This lets h approach 0 in the numerator only, where -5h - 2h^2 goes to 0, but the denominator h also goes to 0. The quotient must be simplified first; it approaches -5."),
       ("-5 - 2h liters per minute",
        "This is the average rate over an interval of length h, so it still depends on h. The instantaneous rate is the limit of this expression as h approaches 0."),
       ("4 liters per minute",
        "This uses the time t = 4 as if it were the rate. The rate is found from the limit of the average rate, not read from the time value.")],
      calc=lambda: fmt(limit((-5 * h - 2 * h**2) / h, h, 0)) + " liters per minute",
      wrong_calcs=[lambda: fmt(limit(-5 * h - 2 * h**2, h, 0)) + " liters per minute", None, None],
      change="numbers: 4 + h -> change -5h - 2h^2 over h; context: particle -> draining tank, given as a volume change"),
    M("001-v3", "001", "easy", "Revenue Growth From a Fractional Average Rate",
      "A shop's cumulative revenue is R(t) thousand dollars after t weeks. The average rate of change of R over the interval [10, 10 + h] is 18/(6 + h) thousand dollars per week. What is the instantaneous rate of change of R at t = 10?",
      ("3 thousand dollars per week",
       "The instantaneous rate is the limit of the average rate as h approaches 0. As h approaches 0, 18/(6 + h) approaches 18/6 = 3."),
      [("18/(6 + h) thousand dollars per week",
        "This is the average rate over an interval of length h, so it depends on h. The instantaneous rate is the limit of that expression as h approaches 0."),
       ("0 thousand dollars per week",
        "Shrinking the interval does not make the rate 0. The expression 18/(6 + h) approaches 18/6 = 3."),
       ("18/7 thousand dollars per week",
        "This substitutes h = 1 instead of letting h approach 0. The limit lets h shrink to 0, giving 18/6 = 3.")],
      calc=lambda: fmt(limit(18 / (6 + h), h, 0)) + " thousand dollars per week",
      wrong_calcs=[None, None, lambda: fmt((18 / (6 + h)).subs(h, 1)) + " thousand dollars per week"],
      change="numbers: 4 + h -> 18/(6 + h); context: particle -> shop revenue, rational average rate"),

    # ---------------- 002: estimating an instantaneous rate from a table ----------------
    M("002-v1", "002", "medium", "Cooling Rate From Shrinking Intervals",
      "The temperature of a cooling liquid is T(t) degrees Celsius at time t minutes. The table gives the average rate of change of T over [2, 2 + h], in degrees per minute.\n\nh = 0.1: -4.2\nh = 0.01: -4.02\nh = 0.001: -4.002\n\nWhich of the following is the best estimate of the instantaneous rate of change of T at t = 2?",
      ("-4",
       "As the interval shrinks, the average rates -4.2, -4.02, -4.002 move toward -4. The instantaneous rate is the value these averages approach."),
      [("-4.2",
        "This is the average rate over the widest interval in the table. It is the least accurate of the three values, not the value the averages approach."),
       ("-4.002",
        "This is the average rate over the smallest interval listed. It is close but is still an average over an interval of length 0.001, not the value being approached."),
       ("0",
        "Shrinking the interval toward length 0 does not make the rate 0. The averages in the table are getting closer to -4.")],
      calc=lambda: fmt(limit(-4 - 2 * h, h, 0)),
      change="numbers: 6.3, 6.03, 6.003 -> -4.2, -4.02, -4.002; context: abstract f -> cooling liquid"),
    M("002-v2", "002", "medium", "Plant Growth Rate From Two-Sided Intervals",
      "The height of a plant is H(t) centimeters at day t. The table gives the average rate of change of H, in cm per day, between day 3 and day 3 + h, where h can be negative.\n\nh = -0.1: 9.7\nh = -0.01: 9.97\nh = 0.01: 10.03\nh = 0.1: 10.3\n\nWhich of the following is the best estimate of the instantaneous rate of change of H at day 3?",
      ("10",
       "From both sides, the average rates move toward 10 as |h| shrinks (9.7, 9.97 from below and 10.3, 10.03 from above). The instantaneous rate is the value they approach."),
      [("10.03",
        "This is the average rate over the closest interval on the right only. It is still an average over an interval of length 0.01, not the value both sides approach."),
       ("10.3",
        "This is the average rate over the widest interval on the right. It is the least accurate entry on that side, not the value being approached."),
       ("The instantaneous rate does not exist because the table has no entry for h = 0.",
        "A table only samples the averages; it need not include h = 0, and the rate is defined as the limit of the averages. Both sides approach 10, so the rate exists.")],
      calc=lambda: fmt(limit(10 + 3 * h, h, 0)),
      change="numbers: one-sided 6.x -> two-sided values around 10; context: abstract f -> plant height"),
    M("002-v3", "002", "medium", "Reaction Rate Approached From Below",
      "The amount of a product is P(t) moles at time t seconds. The table gives the average rate of change of P over [1, 1 + h], in moles per second.\n\nh = 0.1: 0.48\nh = 0.01: 0.498\nh = 0.001: 0.4998\n\nWhich of the following is the best estimate of the instantaneous rate of change of P at t = 1?",
      ("1/2",
       "As the interval shrinks, the average rates 0.48, 0.498, 0.4998 increase toward 0.5 = 1/2. The instantaneous rate is the value these averages approach."),
      [("0.48",
        "This is the average rate over the widest interval. It is the least accurate value in the table, not the value the averages approach."),
       ("0.4998",
        "This is the average rate over the smallest interval listed. It is close to the target but is still an average over an interval of length 0.001."),
       ("0",
        "Shrinking the interval toward length 0 does not make the rate 0. The averages in the table are getting closer to 1/2.")],
      calc=lambda: fmt(limit(Rational(1, 2) - Rational(1, 5) * h, h, 0)),
      change="numbers: 6.3.. -> 0.48, 0.498, 0.4998 (approach from below); context: abstract f -> reaction product"),

    # ---------------- 003: what a limit statement guarantees ----------------
    M("003-v1", "003", "easy", "Sensor Reading Near a Time",
      "A sensor reports a reading R(t) in degrees at time t hours, and lim(t->12) R(t) = 30. Which of the following must be true?",
      (f"The readings R(t) get arbitrarily close to {fmt(limit(30 + (t - 12) * (t + 2), t, 12))} as t gets arbitrarily close to 12 from either side of 12.",
       "This is the meaning of a two-sided limit: the outputs approach 30 as the inputs approach 12 from the left and from the right."),
      [("R(12) = 30",
        "A limit describes what R does near t = 12, not at t = 12. The reading R(12) may be a different number, or may not exist."),
       ("R(t) < 30 for every t less than 12",
        "A limit does not force the outputs to stay on one side of the limit value or to approach it monotonically. The readings could be above 30 on either side of 12."),
       ("R(t) = 30 for some t other than 12 that is near 12",
        "The outputs only need to get close to 30, not to reach it. A function can approach 30 without ever equaling 30 for t != 12.")],
      calc=lambda: f"The readings R(t) get arbitrarily close to {fmt(limit(30 + (t - 12) * (t + 2), t, 12))} as t gets arbitrarily close to 12 from either side of 12.",
      change="numbers: 4, 7 -> 12, 30; context: f(x) -> sensor reading; distractors reworked (monotone approach, attaining the value)"),
    M("003-v2", "003", "easy", "Limit and Value Disagree",
      "For a function p, lim(x->1) p(x) = -3 and p(1) = 2. Which of the following must be true?",
      (f"As x gets arbitrarily close to 1 from either side, p(x) gets arbitrarily close to {fmt(limit((x - 1) * (x + 4) - 3, x, 1))}, even though p(1) is different.",
       "The limit describes the behavior of p near x = 1, so the outputs approach -3. The value p(1) = 2 is a separate fact and does not change the limit."),
      [("As x approaches 1, p(x) gets arbitrarily close to 2.",
        "This uses the value p(1) as if it were the limit. The limit depends only on the outputs near x = 1, which approach -3."),
       ("The limit does not exist because p(1) is not equal to the limit.",
        "The limit exists and equals -3. It does not have to equal p(1); a mismatch only means p is not continuous at 1."),
       ("The limit equals -1/2, the average of -3 and 2.",
        "A limit is not an average of nearby values and the function value. It is the single number the outputs approach, and here it is given as -3.")],
      calc=lambda: f"As x gets arbitrarily close to 1 from either side, p(x) gets arbitrarily close to {fmt(limit((x - 1) * (x + 4) - 3, x, 1))}, even though p(1) is different.",
      wrong_calcs=[None, None, lambda: "The limit equals " + fmt(Rational(-3 + 2, 2)) + ", the average of -3 and 2."],
      change="numbers: 4, 7 -> 1, -3 with p(1) = 2 given; context/form: statement about limit and value disagreeing"),
    M("003-v3", "003", "easy", "Cost at an Undefined Production Level",
      "A cost function C(q) satisfies lim(q->3) C(q) = 12, and C(3) is not defined. Which of the following must be true?",
      (f"C(q) gets arbitrarily close to {fmt(limit(12 + (q - 3) * (q + 1), q, 3))} as q gets arbitrarily close to 3 from either side, even though C(3) does not exist.",
       "A limit depends only on the values of C near q = 3, not at q = 3. The outputs approach 12 from both sides, so the limit statement is consistent with C(3) being undefined."),
      [("The limit cannot be 12, because C(3) is not defined.",
        "A limit can exist at a point where the function is undefined. Only the behavior of C near q = 3 matters."),
       ("Any value later assigned to C(3) must be 12.",
        "The limit says nothing about what value may be assigned at q = 3. C(3) can be defined as any number without changing the limit; only a value chosen to make C continuous at q = 3 would have to be 12."),
       ("C(q) = 12 for every q near 3 other than q = 3.",
        "Approaching 12 does not mean being equal to 12. C(q) could be 12.1 at one point and 11.98 at another and still have limit 12.")],
      calc=lambda: f"C(q) gets arbitrarily close to {fmt(limit(12 + (q - 3) * (q + 1), q, 3))} as q gets arbitrarily close to 3 from either side, even though C(3) does not exist.",
      change="numbers: 4, 7 -> 3, 12; context: abstract f -> cost function undefined at a point"),

    # ---------------- 004: limit versus function value (piecewise) ----------------
    M("004-v1", "004", "medium", "Cost Function With a Shutdown Value",
      "A plant's cost function is defined by\n\nC(q) = 3q + 1 for q < 2\nC(2) = 0\nC(q) = q^2 + 3 for q > 2\n\nWhat is lim(q->2) C(q)?",
      (fmt(limit(3 * q + 1, q, 2, "-")) if limit(3 * q + 1, q, 2, "-") == limit(q**2 + 3, q, 2, "+") else "X",
       "From the left, 3(2) + 1 = 7. From the right, 2^2 + 3 = 7. The one-sided limits agree, so the limit is 7, regardless of C(2)."),
      [("0",
        "This is the value C(2). The limit depends only on the values of C near 2, not on the value at 2."),
       ("6",
        "This evaluates 3q at q = 2 and drops the +1 from the left-hand piece. The left piece is 3q + 1, which equals 7 at q = 2."),
       ("The limit does not exist.",
        "The limit would fail to exist if the one-sided limits differed. Here both equal 7, and the odd value C(2) = 0 does not affect the limit.")],
      calc=lambda: (lambda L, R: fmt(L) if L == R else "The limit does not exist.")(limit(3 * q + 1, q, 2, "-"), limit(q**2 + 3, q, 2, "+")),
      wrong_calcs=[None, lambda: fmt(limit(3 * q, q, 2)), None],
      change="numbers: 2x-1, x^2-4, f(3)=9 -> 3q+1, q^2+3, C(2)=0; context: abstract f -> plant cost"),
    M("004-v2", "004", "medium", "Piecewise Temperature With Mismatched Sides",
      "The temperature of a metal part is defined by\n\nT(t) = 2t + 1 for t < 1\nT(1) = 5\nT(t) = t^2 + 4 for t > 1\n\nWhat is lim(t->1) T(t)?",
      ((lambda L, R: fmt(L) if L == R else "The limit does not exist.")(limit(2 * t + 1, t, 1, "-"), limit(t**2 + 4, t, 1, "+")),
       "From the left, 2(1) + 1 = 3. From the right, 1^2 + 4 = 5. The one-sided limits differ, so the two-sided limit does not exist, even though T(1) = 5."),
      [("5",
        "This is T(1), and it also equals the right-hand limit. The two-sided limit requires the left-hand limit to match, and the left-hand limit is 3."),
       ("3",
        "This uses only the left-hand piece. A two-sided limit must also agree with the right-hand piece, which approaches 5."),
       ("4",
        "This averages the one-sided limits 3 and 5. A limit is a single value approached from both sides; when the sides disagree, there is no such value.")],
      calc=lambda: (lambda L, R: fmt(L) if L == R else "The limit does not exist.")(limit(2 * t + 1, t, 1, "-"), limit(t**2 + 4, t, 1, "+")),
      wrong_calcs=[lambda: fmt(limit(t**2 + 4, t, 1, "+")), lambda: fmt(limit(2 * t + 1, t, 1, "-")),
                   lambda: fmt((limit(2 * t + 1, t, 1, "-") + limit(t**2 + 4, t, 1, "+")) / 2)],
      change="numbers: pieces now disagree (3 vs 5) so the limit does not exist; context: abstract f -> temperature"),
    M("004-v3", "004", "medium", "Piecewise With a Radical and a Fraction",
      "A signal is defined by\n\ng(x) = sqrt(x + 13) - 1 for x < 3\ng(3) = -4\ng(x) = (x^2 - 3)/2 for x > 3\n\nWhat is lim(x->3) g(x)?",
      ((lambda L, R: fmt(L) if L == R else "The limit does not exist.")(limit(sqrt(x + 13) - 1, x, 3, "-"), limit((x**2 - 3) / 2, x, 3, "+")),
       "From the left, sqrt(3 + 13) - 1 = 4 - 1 = 3. From the right, (9 - 3)/2 = 3. The one-sided limits agree, so the limit is 3, regardless of g(3)."),
      [("-4",
        "This is the value g(3). The limit depends only on the values of g near 3, not on the value at 3."),
       ("4",
        "This evaluates the radical sqrt(16) = 4 on the left piece but drops the -1. The left piece is sqrt(x + 13) - 1, which equals 3 at x = 3."),
       ("The limit does not exist.",
        "The limit would fail to exist if the one-sided limits differed. Here both equal 3, and g(3) = -4 does not affect the limit.")],
      calc=lambda: (lambda L, R: fmt(L) if L == R else "The limit does not exist.")(limit(sqrt(x + 13) - 1, x, 3, "-"), limit((x**2 - 3) / 2, x, 3, "+")),
      wrong_calcs=[None, lambda: fmt(limit(sqrt(x + 13), x, 3, "-")), None],
      change="numbers: 2x-1, x^2-4 -> sqrt(x+13)-1, (x^2-3)/2, g(3)=-4; context: abstract f -> signal, radical and fraction pieces"),

    # ---------------- 005: estimating a limit from a table with an undefined point ----------------
    M("005-v1", "005", "medium", "Voltage Table Approaching From Above",
      "The table shows values of a function V near t = 5. The value V(5) is undefined.\n\nt = 4.9: V(t) = -1.8\nt = 4.99: V(t) = -1.98\nt = 4.999: V(t) = -1.998\nt = 5.001: V(t) = -2.002\nt = 5.01: V(t) = -2.02\nt = 5.1: V(t) = -2.2\n\nWhich of the following is the best estimate of lim(t->5) V(t)?",
      (fmt(limit(-2 - 2 * (t - 5), t, 5)),
       "From both sides the values of V(t) get closer to -2 as t gets closer to 5. The undefined value V(5) does not affect the limit."),
      [("-1.998",
        "This is the value at t = 4.999, one of the sampled points. The limit is the number the values approach, not one of the sampled outputs."),
       ("-2.2",
        "This is the output at the sampled point t = 5.1, the farthest from 5 on the right. The values keep moving toward -2 as t gets closer to 5."),
       ("The limit does not exist because V(5) is undefined.",
        "A limit can exist even if the function is not defined at that point. What matters is the behavior of V on both sides of 5.")],
      calc=lambda: fmt(limit(-2 - 2 * (t - 5), t, 5)),
      change="numbers: increasing values near 2 -> decreasing values near 5 (-2); context: abstract f -> voltage"),
    M("005-v2", "005", "medium", "Table Where the Function Value Differs",
      "The table shows values of a function f near x = 1. The function is defined at x = 1 with f(1) = 8.\n\nx = 0.9: f(x) = 2.5\nx = 0.99: f(x) = 2.95\nx = 0.999: f(x) = 2.995\nx = 1.001: f(x) = 3.005\nx = 1.01: f(x) = 3.05\nx = 1.1: f(x) = 3.5\n\nWhich of the following is the best estimate of lim(x->1) f(x)?",
      (fmt(limit(3 + 5 * (x - 1), x, 1)),
       "From both sides the values of f(x) get closer to 3 as x gets closer to 1. The value f(1) = 8 does not affect the limit."),
      [("8",
        "This is the value f(1). The limit depends on the values of f near x = 1, which approach 3, not on the value at x = 1."),
       ("5.5",
        "This averages the limit-like value 3 with f(1) = 8. A limit is not a blend of the nearby values and the value at the point; it is the number the nearby values approach."),
       ("2.995",
        "This is the value at x = 0.999, one of the sampled points. The limit is the number the values approach, not one of the sampled outputs.")],
      calc=lambda: fmt(limit(3 + 5 * (x - 1), x, 1)),
      wrong_calcs=[None, lambda: str(float((limit(3 + 5 * (x - 1), x, 1) + 8) / 2)), None],
      change="numbers: near 2 -> near 1 with slope 5, f(1) = 8 defined; context: hole -> value defined but different"),
    M("005-v3", "005", "medium", "Table With Values Changing Sign",
      "The table shows the displacement d(x) of a spring, in millimeters, near x = 1.5. The value d(1.5) is undefined.\n\nx = 1.4: d = -0.4\nx = 1.49: d = -0.04\nx = 1.499: d = -0.004\nx = 1.501: d = 0.004\nx = 1.51: d = 0.04\nx = 1.6: d = 0.4\n\nWhich of the following is the best estimate of lim(x->1.5) d(x)?",
      (fmt(limit(4 * (x - Rational(3, 2)), x, Rational(3, 2))),
       "From both sides the values of d(x) get closer to 0 as x gets closer to 1.5. Passing from negative to positive values is fine because both sides approach the same number, 0."),
      [("-0.004",
        "This is the value at x = 1.499, one of the sampled points. The limit is the number the values approach, not one of the sampled outputs."),
       ("0.4",
        "This is the output at x = 1.6, the farthest sampled point on the right. The values shrink toward 0 as x gets closer to 1.5."),
       ("The limit does not exist because the values change sign.",
        "Values on the two sides having opposite signs does not prevent a limit. What matters is whether both sides approach the same number, and both approach 0.")],
      calc=lambda: fmt(limit(4 * (x - Rational(3, 2)), x, Rational(3, 2))),
      change="numbers: values near 3 -> values near 0 crossing sign; context: abstract f -> spring displacement"),

    # ---------------- 006: combining limits with algebraic properties ----------------
    M("006-v1", "006", "medium", "Combining Two Sensor Limits",
      "Suppose lim(t->6) u(t) = -5 and lim(t->6) v(t) = 2. What is lim(t->6) [(u(t))^2 - 3v(t)] / [u(t) + 2v(t)]?",
      (fmt(((a**2 - 3 * b) / (a + 2 * b)).subs({a: -5, b: 2})),
       "The numerator approaches (-5)^2 - 3(2) = 25 - 6 = 19 and the denominator approaches -5 + 2(2) = -1. The denominator's limit is not 0, so the quotient approaches 19/(-1) = -19."),
      [("31",
        "This treats (-5)^2 as -25, giving numerator -25 - 6 = -31 over -1. Squaring -5 gives +25, so the numerator's limit is 25 - 6 = 19."),
       ("-19/3",
        "This uses u + 2v with v counted once, giving -5 + 2 = -3 in the denominator. The denominator's limit is -5 + 2(2) = -1."),
       ("-31",
        "This changes the sign of the 3v term, computing 25 + 6 = 31 in the numerator. The numerator's limit is 25 - 3(2) = 19.")],
      calc=lambda: fmt(((a**2 - 3 * b) / (a + 2 * b)).subs({a: -5, b: 2})),
      wrong_calcs=[lambda: fmt(((-a**2 - 3 * b) / (a + 2 * b)).subs({a: -5, b: 2})),
                   lambda: fmt(((a**2 - 3 * b) / (a + b)).subs({a: -5, b: 2})),
                   lambda: fmt(((a**2 + 3 * b) / (a + 2 * b)).subs({a: -5, b: 2}))],
      change="numbers: 3, -2 -> -5, 2, new expression; context: abstract f, g -> sensor signals"),
    M("006-v2", "006", "medium", "Cubes and Products of Limits",
      "Two competing rates F(x) and G(x) satisfy lim(x->9) F(x) = -2 and lim(x->9) G(x) = 4. What is lim(x->9) [(F(x))^3 + 2F(x)G(x)] / [G(x) - F(x)]?",
      (fmt(((a**3 + 2 * a * b) / (b - a)).subs({a: -2, b: 4})),
       "The numerator approaches (-2)^3 + 2(-2)(4) = -8 - 16 = -24 and the denominator approaches 4 - (-2) = 6. The denominator's limit is not 0, so the quotient approaches -24/6 = -4."),
      [("-4/3",
        "This treats (-2)^3 as 8, giving numerator 8 - 16 = -8 over 6. Cubing -2 gives -8, so the numerator's limit is -8 - 16 = -24."),
       ("-12",
        "This adds instead of subtracting in the denominator, using 4 + (-2) = 2. The denominator's limit is G - F = 4 - (-2) = 6."),
       ("-11/3",
        "This replaces F cubed with 3F, computing -6 - 16 = -22 in the numerator. F cubed approaches (-2)^3 = -8, not 3(-2).")],
      calc=lambda: fmt(((a**3 + 2 * a * b) / (b - a)).subs({a: -2, b: 4})),
      wrong_calcs=[lambda: fmt(((-a**3 + 2 * a * b) / (b - a)).subs({a: -2, b: 4})),
                   lambda: fmt(((a**3 + 2 * a * b) / (b + a)).subs({a: -2, b: 4})),
                   lambda: fmt(((3 * a + 2 * a * b) / (b - a)).subs({a: -2, b: 4}))],
      change="numbers: new limits -2, 4 and an expression with a cube and a product; context: abstract f, g -> competing rates"),
    M("006-v3", "006", "medium", "Supply and Demand Limits in a Quotient",
      "Suppose lim(p->10) S(p) = 3 and lim(p->10) D(p) = -5 for a supply function S and a demand function D. What is lim(p->10) (S(p) - D(p))^2 / (D(p) + 2S(p))?",
      (fmt(((a - b)**2 / (b + 2 * a)).subs({a: 3, b: -5})),
       "The numerator approaches (3 - (-5))^2 = 8^2 = 64 and the denominator approaches -5 + 2(3) = 1. The denominator's limit is not 0, so the quotient approaches 64/1 = 64."),
      [("-16",
        "This treats (S - D)^2 as S^2 - D^2 = 9 - 25 = -16. Squaring a difference does not distribute; (3 + 5)^2 = 64."),
       ("-32",
        "This uses D + S in the denominator, leaving out the factor 2 and giving -5 + 3 = -2. The denominator's limit is -5 + 2(3) = 1."),
       ("4/11",
        "This treats D as 5, ignoring its sign: (3 - 5)^2 = 4 over 5 + 6 = 11. The limit of D is -5, so S - D approaches 3 + 5 = 8.")],
      calc=lambda: fmt(((a - b)**2 / (b + 2 * a)).subs({a: 3, b: -5})),
      wrong_calcs=[lambda: fmt(((a**2 - b**2) / (b + 2 * a)).subs({a: 3, b: -5})),
                   lambda: fmt(((a - b)**2 / (b + a)).subs({a: 3, b: -5})),
                   lambda: fmt(((a - Abs(b))**2 / (Abs(b) + 2 * a)).subs({a: 3, b: -5}))],
      change="numbers: 3, -2 -> 3, -5 with a squared difference; context: abstract f, g -> supply and demand"),

    # ---------------- 007: quotient of two limits that are both zero ----------------
    M("007-v1", "007", "medium", "Two Quantities Both Shrinking to Zero",
      "Two chemical amounts A(t) and B(t) both approach 0 as t approaches 7, so lim(t->7) A(t) = 0 and lim(t->7) B(t) = 0. Which of the following is true about lim(t->7) A(t)/B(t)?",
      ("It cannot be determined from this information alone.",
       "The quotient law for limits requires the denominator's limit to be nonzero. With both limits 0, the ratio depends on the functions: A(t) = 3(t - 7) and B(t) = t - 7 give 3, while A(t) = (t - 7)^3 and B(t) = t - 7 give 0."),
      [("It equals 0, because the numerator approaches 0.",
        "The numerator approaching 0 does not force the quotient to 0, since the denominator also approaches 0. For A(t) = 3(t - 7) and B(t) = t - 7, the quotient approaches 3."),
       ("It is infinity, because the denominator approaches 0.",
        "A denominator approaching 0 does not by itself make the quotient unbounded, because here the numerator also approaches 0. For A(t) = (t - 7)^3 and B(t) = t - 7, the quotient approaches 0, not infinity."),
       ("It does not exist, because B(t) approaches 0.",
        "The quotient often has a limit even when the denominator approaches 0. For A(t) = 3(t - 7) and B(t) = t - 7, the quotient equals 3 for t != 7.")],
      calc=lambda: "It cannot be determined from this information alone." if len({limit(3 * (x - 7) / (x - 7), x, 7), limit((x - 7)**3 / (x - 7), x, 7)}) > 1 else "X",
      change="numbers: x -> 1 becomes t -> 7; context: abstract f, g -> chemical amounts; distractors reworded around unbounded/DNE claims"),
    M("007-v2", "007", "medium", "Evaluating a Classmate's Claim About 0/0",
      "Suppose lim(x->-3) f(x) = 0 and lim(x->-3) g(x) = 0. A classmate says that lim(x->-3) f(x)/g(x) must not exist because 0/0 is undefined. Which of the following best evaluates the claim?",
      (f"The claim is incorrect: the limit may exist (for example, f(x) = 5(x + 3) and g(x) = x + 3 give {fmt(limit(5 * (x + 3) / (x + 3), x, -3))}), so it cannot be determined without more information.",
       "The quotient law for limits does not apply when the denominator's limit is 0, so nothing is settled by the given limits alone. Some pairs give a finite limit, such as 5, and others do not."),
      [("The claim is correct: dividing by a quantity that approaches 0 means the limit can never exist.",
        "The limit of a quotient can exist even when the denominator approaches 0. For f(x) = 5(x + 3) and g(x) = x + 3, the quotient equals 5 for x != -3."),
       ("The claim is incorrect: the limit must equal 0, because the numerator approaches 0.",
        "The numerator approaching 0 does not force the ratio to 0. With f(x) = 5(x + 3) and g(x) = x + 3, the ratio approaches 5."),
       ("The claim is incorrect: the limit must equal 1, because both functions approach the same number.",
        "Both approaching 0 does not make their ratio approach 1. With f(x) = 5(x + 3) and g(x) = x + 3, the ratio approaches 5, and other pairs give other values.")],
      calc=lambda: f"The claim is incorrect: the limit may exist (for example, f(x) = 5(x + 3) and g(x) = x + 3 give {fmt(limit(5 * (x + 3) / (x + 3), x, -3))}), so it cannot be determined without more information.",
      change="numbers: x -> 1 becomes x -> -3; form: direct question -> evaluate a classmate's claim"),
    M("007-v3", "007", "medium", "Choosing Functions With a Given Ratio Limit",
      "In each option, both f and g approach 0 as x approaches 2. For which pair does lim(x->2) f(x)/g(x) equal 3?",
      (next(tx for tx, fx, gx in [
          ("f(x) = 6(x - 2)^2 and g(x) = 2(x - 2)^2", 6 * (x - 2)**2, 2 * (x - 2)**2),
          ("f(x) = 3(x - 2) and g(x) = (x - 2)^2", 3 * (x - 2), (x - 2)**2),
          ("f(x) = (x - 2)^3 and g(x) = 3(x - 2)^2", (x - 2)**3, 3 * (x - 2)**2),
          ("f(x) = x - 2 and g(x) = 3(x - 2)", x - 2, 3 * (x - 2))] if limit(fx / gx, x, 2) == 3),
       "The factors of (x - 2)^2 cancel for x != 2, leaving 6/2 = 3. Both functions approach 0, but their ratio approaches 3."),
      [("f(x) = 3(x - 2) and g(x) = (x - 2)^2",
        "The quotient simplifies to 3/(x - 2), which grows without bound in magnitude near 2 and has different signs on the two sides, so the limit does not exist. The coefficient 3 is not the limit."),
       ("f(x) = (x - 2)^3 and g(x) = 3(x - 2)^2",
        "The quotient simplifies to (x - 2)/3, which approaches 0. Having a 3 in the expression does not make the ratio's limit 3."),
       ("f(x) = x - 2 and g(x) = 3(x - 2)",
        "The quotient simplifies to 1/3, which is the inverse of the intended ratio. The limit is 1/3, not 3.")],
      calc=lambda: next(tx for tx, fx, gx in [
          ("f(x) = 6(x - 2)^2 and g(x) = 2(x - 2)^2", 6 * (x - 2)**2, 2 * (x - 2)**2),
          ("f(x) = 3(x - 2) and g(x) = (x - 2)^2", 3 * (x - 2), (x - 2)**2),
          ("f(x) = (x - 2)^3 and g(x) = 3(x - 2)^2", (x - 2)**3, 3 * (x - 2)**2),
          ("f(x) = x - 2 and g(x) = 3(x - 2)", x - 2, 3 * (x - 2))] if limit(fx / gx, x, 2) == 3),
      change="form: conceptual statement -> choose which concrete pair gives ratio limit 3; numbers x -> 2"),

    # ---------------- 008: when direct substitution works ----------------
    M("008-v1", "008", "easy", "Which Plug-In Gives the Real Limit",
      "A lab technician tries to evaluate four limits by simply plugging in the target input. For which one does plugging in actually give the value of the limit?",
      ("lim(t->1) (ln(t) + 5)/(t^2 + 1)",
       "Substituting t = 1 gives (0 + 5)/(1 + 1) = 5/2. Every piece is defined at t = 1 and the denominator is nonzero, so direct substitution gives the limit."),
      [("lim(t->-2) (t^2 - 4)/(t + 2)^2",
        "Substituting t = -2 gives 0/0. Cancelling one factor of t + 2 leaves (t - 2)/(t + 2), which is unbounded near -2, so substitution does not give the limit."),
       ("lim(t->5) (sqrt(t + 4) - 3)/(t - 5)",
        "Substituting t = 5 gives 0/0. The expression is most directly handled by rationalizing with the conjugate sqrt(t + 4) + 3, since substitution alone does not give the limit."),
       ("lim(t->0) 4t/sin(t)",
        "Substituting t = 0 gives 0/0. The value 4 comes from the special limit sin(t)/t = 1, not from plugging in.")],
      calc=lambda: next(tx for tx, ex, at in [
          ("lim(t->1) (ln(t) + 5)/(t^2 + 1)", (log(t) + 5) / (t**2 + 1), 1),
          ("lim(t->-2) (t^2 - 4)/(t + 2)^2", (t**2 - 4) / (t + 2)**2, -2),
          ("lim(t->5) (sqrt(t + 4) - 3)/(t - 5)", (sqrt(t + 4) - 3) / (t - 5), 5),
          ("lim(t->0) 4t/sin(t)", 4 * t / sin(t), 0)]
          if ex.subs(t, at) not in (nan, zoo, oo, -oo) and ex.subs(t, at).is_finite is not False),
      change="functions: radical/sine/reciprocal-square -> logarithm quotient with rational, conjugate and sine-reciprocal traps; context: pure question -> lab technician plugging in values"),
    M("008-v2", "008", "easy", "Spotting the Substitution-Friendly Limit",
      "A student wants to evaluate each limit below. For which one does plugging in the x-value directly give the limit?",
      ("lim(x->-1) (x^3 + 2x)/(x^2 + 4)",
       "Substituting x = -1 gives (-1 - 2)/(1 + 4) = -3/5. The denominator is nonzero at x = -1, so direct substitution gives the limit."),
      [("lim(x->2) |x - 2|/(x - 2)",
        "Substituting x = 2 gives 0/0, and the one-sided limits are 1 from the right and -1 from the left, so the limit does not exist."),
       ("lim(x->-3) (x^2 + 2x - 3)/(x + 3)",
        "Substituting x = -3 gives 0/0. The numerator must be factored as (x + 3)(x - 1) and the common factor cancelled first."),
       ("lim(x->1) (1/x - 1)/(x - 1)",
        "Substituting x = 1 gives 0/0. The complex fraction must be simplified first, for example 1/x - 1 = (1 - x)/x.")],
      calc=lambda: next(tx for tx, ex, at in [
          ("lim(x->-1) (x^3 + 2x)/(x^2 + 4)", (x**3 + 2 * x) / (x**2 + 4), -1),
          ("lim(x->2) |x - 2|/(x - 2)", Abs(x - 2) / (x - 2), 2),
          ("lim(x->-3) (x^2 + 2x - 3)/(x + 3)", (x**2 + 2 * x - 3) / (x + 3), -3),
          ("lim(x->1) (1/x - 1)/(x - 1)", (1 / x - 1) / (x - 1), 1)] if direct_ok(ex, at)),
      change="functions: polynomial ratio at -1; distractors use absolute value, factoring and complex fraction"),
    M("008-v3", "008", "easy", "Substitution Versus Simplifying First",
      "Which of the following limits equals the value obtained by substituting the x-value into the expression?",
      ("lim(x->5) (x^2 - 3x)/(2x - 9)",
       "Substituting x = 5 gives (25 - 15)/(10 - 9) = 10. The denominator is nonzero at x = 5, so direct substitution gives the limit."),
      [("lim(x->1/2) (2x - 1)/(4x^2 - 1)",
        "Substituting x = 1/2 gives 0/0. The denominator must be factored as (2x - 1)(2x + 1) and the common factor cancelled first."),
       ("lim(x->0) (1 - cos(x))/x",
        "Substituting x = 0 gives 0/0. This requires the special limit of (1 - cos x)/x, not substitution."),
       ("lim(x->-2) (x^4 - 16)/(x + 2)",
        "Substituting x = -2 gives 0/0. The numerator must be factored, for example x^4 - 16 = (x + 2)(x - 2)(x^2 + 4), before cancelling.")],
      calc=lambda: next(tx for tx, ex, at in [
          ("lim(x->5) (x^2 - 3x)/(2x - 9)", (x**2 - 3 * x) / (2 * x - 9), 5),
          ("lim(x->1/2) (2x - 1)/(4x^2 - 1)", (2 * x - 1) / (4 * x**2 - 1), Rational(1, 2)),
          ("lim(x->0) (1 - cos(x))/x", (1 - cos(x)) / x, 0),
          ("lim(x->-2) (x^4 - 16)/(x + 2)", (x**4 - 16) / (x + 2), -2)] if direct_ok(ex, at)),
      change="functions: rational at 5; distractors use rational factoring, cosine special limit, quartic difference"),

    # ---------------- 009: sine limit after adjusting the argument ----------------
    M("009-v1", "009", "medium", "Low-Frequency Filter Response Near Zero",
      "A filter's normalized response to a small input of size x is modeled by G(x) = sin(8x)/(6x). What value does G(x) approach as x approaches 0?",
      (fmt(limit(sin(8 * x) / (6 * x), x, 0)),
       "Write sin(8x)/(6x) as (8/6) * sin(8x)/(8x) = (4/3) * sin(8x)/(8x). As x approaches 0, sin(8x)/(8x) approaches 1, so G approaches 4/3."),
      [("8",
        "This treats sin(8x)/(6x) as if the denominator were just x, dropping the factor 6. That gives sin(8x)/x, whose limit is 8, but the actual denominator is 6x."),
       ("1",
        "The special limit sin(u)/u = 1 needs the same expression in the argument and the denominator. Here they are 8x and 6x, so constants remain."),
       ("3/4",
        "This inverts the factor. Since sin(8x) behaves like 8x near 0, the ratio behaves like 8x/(6x) = 4/3, not 3/4.")],
      calc=lambda: fmt(limit(sin(8 * x) / (6 * x), x, 0)),
      wrong_calcs=[lambda: fmt(limit(sin(8 * x) / x, x, 0)), None, lambda: fmt(limit(6 * x / sin(8 * x), x, 0))],
      change="numbers: sin(3x)/x -> sin(8x)/(6x); context: bare limit -> normalized filter response to a small input"),
    M("009-v2", "009", "medium", "Small-Angle Ratio With a Tangent",
      "In a small-angle model of a swinging arm, the ratio R(x) = 5x/tan(2x) compares a scaled angle to the tangent of twice the angle, where x is measured in radians. What is lim(x->0) R(x)?",
      (fmt(limit(5 * x / tan(2 * x), x, 0)),
       "Write 5x/tan(2x) as 5x cos(2x)/sin(2x) = (5/2) * cos(2x) * (2x)/sin(2x). As x approaches 0, cos(2x) approaches 1 and (2x)/sin(2x) approaches 1, so the limit is 5/2."),
      [("2/5",
        "This inverts the factor. Since tan(2x) behaves like 2x near 0, the ratio behaves like 5x/(2x) = 5/2, not 2/5."),
       ("5",
        "This treats tan(2x) as if it behaved like x, ignoring the 2 in the argument. It behaves like 2x, so the ratio behaves like 5x/(2x) = 5/2."),
       ("0",
        "Both 5x and tan(2x) approach 0, giving 0/0, which is not automatically 0. The ratio behaves like 5x/(2x) = 5/2.")],
      calc=lambda: fmt(limit(5 * x / tan(2 * x), x, 0)),
      wrong_calcs=[lambda: fmt(limit(tan(2 * x) / (5 * x), x, 0)), lambda: fmt(limit(5 * x / x, x, 0)), None],
      change="numbers: sin(3x)/x -> 5x/tan(2x); function shape: sine quotient -> tangent in the denominator; context: bare limit -> small-angle swing model"),
    M("009-v3", "009", "medium", "Ratio of Two Sines Near Zero",
      "Two waves have amplitudes proportional to sin(2x) and sin(7x). What is lim(x->0) sin(2x)/sin(7x)?",
      (fmt(limit(sin(2 * x) / sin(7 * x), x, 0)),
       "Write sin(2x)/sin(7x) as (2x/7x) * [sin(2x)/(2x)] / [sin(7x)/(7x)]. Both bracketed ratios approach 1, so the limit is 2/7."),
      [("7/2",
        "This inverts the ratio. Since sin(2x) behaves like 2x and sin(7x) like 7x, the quotient behaves like 2x/(7x) = 2/7."),
       ("1",
        "The special limit sin(u)/u = 1 needs the same expression in the numerator's argument and the denominator. Here the arguments 2x and 7x differ, so factors remain."),
       ("0",
        "Both sines approach 0, giving 0/0, which is not automatically 0. The ratio behaves like 2x/(7x) = 2/7.")],
      calc=lambda: fmt(limit(sin(2 * x) / sin(7 * x), x, 0)),
      wrong_calcs=[lambda: fmt(limit(sin(7 * x) / sin(2 * x), x, 0)), None, None],
      change="numbers: sin(3x)/x -> sin(2x)/sin(7x); context: symbolic -> ratio of wave amplitudes"),

    # ---------------- 010: squeeze theorem ----------------
    M("010-v1", "010", "easy", "Squeezing a Measurement Between Bounds",
      "A quantity f satisfies 9 - 5(x - 2)^2 <= f(x) <= 9 + 4|x - 2| for all x. What is lim(x->2) f(x)?",
      ((lambda lo, hi: fmt(lo) if lo == hi else "X")(limit(9 - 5 * (x - 2)**2, x, 2), limit(9 + 4 * Abs(x - 2), x, 2)),
       "Both bounding functions approach 9 as x approaches 2. Since f is between them, the Squeeze Theorem gives lim f(x) = 9."),
      [("0",
        "The terms 5(x - 2)^2 and 4|x - 2| approach 0, but the bounds are 9 - 5(x - 2)^2 and 9 + 4|x - 2|, and those approach 9."),
       ("18",
        "This adds the two bounding limits, 9 + 9. The Squeeze Theorem says f has the same limit as the bounds, not their sum."),
       ("It cannot be determined because the two bounds are different functions.",
        "The bounds do not need to be the same function. The Squeeze Theorem applies because both bounds have the same limit, 9, as x approaches 2.")],
      calc=lambda: (lambda lo, hi: fmt(lo) if lo == hi else "X")(limit(9 - 5 * (x - 2)**2, x, 2), limit(9 + 4 * Abs(x - 2), x, 2)),
      wrong_calcs=[None, lambda: fmt(limit(9 - 5 * (x - 2)**2, x, 2) + limit(9 + 4 * Abs(x - 2), x, 2)), None],
      change="numbers: at 0 -> at 2 with an absolute-value upper bound; context: abstract f -> measured quantity"),
    M("010-v2", "010", "easy", "Squeeze From an Absolute-Value Inequality",
      "A function g satisfies |g(x) - 5| <= 4(x - 1)^2 for all x. What is lim(x->1) g(x)?",
      ((lambda lo, hi: fmt(lo) if lo == hi else "X")(limit(5 - 4 * (x - 1)**2, x, 1), limit(5 + 4 * (x - 1)**2, x, 1)),
       "The inequality means 5 - 4(x - 1)^2 <= g(x) <= 5 + 4(x - 1)^2. Both bounds approach 5 as x approaches 1, so the Squeeze Theorem gives lim g(x) = 5."),
      [("0",
        "The bound 4(x - 1)^2 approaches 0, but it is only an upper bound on how far g is from 5 (on |g(x) - 5|), not the value of g. The bounds on g itself are 5 - 4(x - 1)^2 and 5 + 4(x - 1)^2."),
       ("4",
        "This reads the coefficient 4 in the bound as the limit. The bound controls the distance |g(x) - 5|, which shrinks to 0, so g approaches 5."),
       ("It cannot be determined because g is not given by a formula.",
        "A formula for g is not needed. Its bounds 5 - 4(x - 1)^2 and 5 + 4(x - 1)^2 have the same limit, 5, so the Squeeze Theorem applies.")],
      calc=lambda: (lambda lo, hi: fmt(lo) if lo == hi else "X")(limit(5 - 4 * (x - 1)**2, x, 1), limit(5 + 4 * (x - 1)**2, x, 1)),
      wrong_calcs=[lambda: fmt(limit(4 * (x - 1)**2, x, 1)), None, None],
      change="numbers: explicit bounds -> |g(x) - 5| <= 4(x - 1)^2; form: absolute-value inequality, limit at 1"),
    M("010-v3", "010", "easy", "Bounded Oscillation Times a Vanishing Factor",
      "For x != 0, -1 <= sin(1/x) <= 1. What is lim(x->0) x^2 sin(1/x)?",
      ((lambda lo, hi: fmt(lo) if lo == hi else "X")(limit(-x**2, x, 0), limit(x**2, x, 0)),
       "Multiplying by x^2 >= 0 gives -x^2 <= x^2 sin(1/x) <= x^2. Both bounds approach 0 as x approaches 0, so the Squeeze Theorem gives a limit of 0."),
      [("1",
        "This takes the bound 1 on sin(1/x) as if it were the limit of the whole product and ignores the factor x^2. The bound that matters is x^2: the product lies between -x^2 and x^2, and x^2 shrinks to 0, which forces the product to 0."),
       ("The limit does not exist because sin(1/x) oscillates.",
        "sin(1/x) alone has no limit at 0, but the product does. The bounds -x^2 and x^2 both approach 0, and the product is squeezed between them."),
       ("infinity",
        "This lets 1/x grow without bound and assumes the product does too. The sine keeps the second factor between -1 and 1, while x^2 approaches 0, so the product approaches 0.")],
      calc=lambda: (lambda lo, hi: fmt(lo) if lo == hi else "X")(limit(-x**2, x, 0), limit(x**2, x, 0)),
      change="numbers: quadratic bounds -> bounds from -1 <= sin(1/x) <= 1 times x^2; context: symbolic -> oscillating factor"),
]
