# Variants of original MCQs 011-020 (AP Calculus AB, Unit 1). Three per original, new numbers AND new context/form.
from sympy import (symbols, limit, sqrt, exp, Rational, oo, S, Abs, log, sin, tan, pi, Eq, solve, solveset,
                   Interval, Union, Integer)
from sympy.calculus.util import continuous_domain
from vlib import M, fmt

x, t, a = symbols("x t a", real=True)


# ----------------------------------------------------------------------------- helpers
def sides(e, v, p):
    return limit(e, v, p, "-"), limit(e, v, p, "+")


def statements_text(flags):
    names = [n for n, f in zip(["I", "II", "III"], flags) if f]
    if len(names) == 3:
        return "I, II and III"
    if len(names) == 1:
        return names[0] + " only"
    return " and ".join(names) + " only"


def disc_type(lexpr, rexpr, v, p, fval):
    L, R = sides(lexpr, v, p)[0], sides(rexpr, v, p)[1]
    if L in (oo, -oo) or R in (oo, -oo):
        return "infinite"
    if L != R:
        return "jump"
    return "continuous" if fval == L else "removable"


def ivl(I):
    lo = "-infinity" if I.start == -oo else fmt(I.start)
    hi = "infinity" if I.end == oo else fmt(I.end)
    return ("(" if I.left_open else "[") + lo + ", " + hi + (")" if I.right_open else "]")


def set_text(Sx):
    parts = list(Sx.args) if isinstance(Sx, Union) else [Sx]
    parts = sorted(parts, key=lambda I: (I.start != -oo, I.start if I.start != -oo else 0))
    strs = [ivl(p) for p in parts]
    if len(strs) == 1:
        return "The interval " + strs[0]
    return "The union of " + ", ".join(strs[:-1]) + " and " + strs[-1]


def solve_param(eq_lhs, eq_rhs):
    return fmt(solve(Eq(eq_lhs, eq_rhs), a)[0])


VARIANTS = [
    # ======================================================================== 011
    # Original: one-sided limits equal, f(2) differs; three statements (limit exists / continuous / removable).
    M("011-v1", "011", "medium", "Enzyme Rate Model at a Reference Time",
      "The reaction rate r(t), in millimoles per second, of an enzyme at time t minutes is modeled by r(t) = (2t^2 - 7t - 4)/(t - 4) for t != 4, and a lab instrument records r(4) = 3. Consider the following statements.\n\nI. lim(t->4) r(t) exists.\nII. r is continuous at t = 4.\nIII. r has a removable discontinuity at t = 4.\n\nWhich of the statements are true?",
      ("I and III only",
       "Since 2t^2 - 7t - 4 = (2t + 1)(t - 4), r(t) = 2t + 1 for t != 4, so the limit at 4 exists and equals 9 (I). The recorded value r(4) = 3 differs from 9, so r is not continuous (II is false). A discontinuity where the limit exists is removable (III)."),
      [("I only",
        "Statement I is true, but III is also true. A discontinuity at which the limit exists but differs from the function value is removable."),
       ("I and II only",
        "Continuity requires r(4) to equal the limit. Here r(4) = 3 but the limit is 9, so r is not continuous at t = 4."),
       ("II and III only",
        "Statement II is false because r(4) = 3 does not equal the limit 9, and statement I is true because the one-sided limits are both 9.")],
      calc=lambda: statements_text([
          limit((2*t**2 - 7*t - 4)/(t - 4), t, 4, "-") == limit((2*t**2 - 7*t - 4)/(t - 4), t, 4, "+"),
          limit((2*t**2 - 7*t - 4)/(t - 4), t, 4) == 3,
          (limit((2*t**2 - 7*t - 4)/(t - 4), t, 4) != 3)]),
      wrong_calcs=[lambda: statements_text([True, False, False]),
                   lambda: statements_text([True, True, False]),
                   lambda: statements_text([False, True, True])],
      change="numbers: limit 5 and f(2)=1 -> limit 9 and r(4)=3, formula-defined; context: bare limits -> enzyme reaction rate"),
    M("011-v2", "011", "medium", "Shipping Fee at a Weight Threshold",
      "A carrier charges F(w) dollars to ship a package of w pounds, where F(w) = 3w + 2 for w < 5 and F(w) = 30 - 2w for w >= 5 (heavy-package rebate schedule). Consider the following statements.\n\nI. lim(w->5) F(w) exists.\nII. F is continuous at w = 5.\nIII. F has a jump discontinuity at w = 5.\n\nWhich of the statements are true?",
      ("III only",
       "From the left the fee approaches 3(5) + 2 = 17, and from the right it approaches 30 - 10 = 20. The one-sided limits are unequal, so the limit does not exist (I is false), F is not continuous (II is false), and the finite unequal one-sided limits make a jump discontinuity (III)."),
      [("II only",
        "F(5) = 20 does match the right-hand limit, but continuity needs the limit from both sides to equal F(5). The left-hand limit is 17."),
       ("I and III only",
        "A jump discontinuity means the one-sided limits exist but are unequal, so the two-sided limit does not exist. Statement I is false."),
       ("I and II only",
        "The one-sided limits are 17 and 20, so the two-sided limit does not exist, and continuity (which requires the limit to exist) fails as well.")],
      calc=lambda: statements_text(
          [sides(3*t + 2, t, 5)[0] == sides(30 - 2*t, t, 5)[1],
           sides(3*t + 2, t, 5)[0] == sides(30 - 2*t, t, 5)[1] == (30 - 2*t).subs(t, 5),
           disc_type(3*t + 2, 30 - 2*t, t, 5, (30 - 2*t).subs(t, 5)) == "jump"]),
      wrong_calcs=[lambda: statements_text([False, sides(30 - 2*t, t, 5)[1] == (30 - 2*t).subs(t, 5), False]),
                   None, None],
      change="numbers: equal limits 5 -> unequal limits 17 and 20; context: bare limits -> shipping fee schedule; statements changed to test jump"),
    M("011-v3", "011", "medium", "Sensor Gain With a Stored Calibration Value",
      "A sensor's gain is modeled by g(x) = (sqrt(x + 7) - 3)/(x - 2) for x != 2, and the stored calibration value is g(2) = 1/6. Consider the following statements.\n\nI. lim(x->2) g(x) exists.\nII. g is continuous at x = 2.\nIII. g has a removable discontinuity at x = 2.\n\nWhich of the statements are true?",
      ("I and II only",
       "Multiplying by the conjugate gives g(x) = 1/(sqrt(x + 7) + 3) for x != 2, so the limit at 2 is 1/(3 + 3) = 1/6 (I). Since g(2) = 1/6 equals this limit, g is continuous at 2 (II), and therefore there is no discontinuity to remove (III is false)."),
      [("I only",
        "Statement I is true, but the limit 1/6 equals g(2) = 1/6, so all three conditions for continuity hold and II is also true."),
       ("I and III only",
        "A removable discontinuity needs the limit to differ from the function value or the value to be missing. Here g(2) = 1/6 equals the limit, so g is continuous, not discontinuous."),
       ("II and III only",
        "A function cannot be both continuous and discontinuous at the same point. In fact g is continuous at 2, so III is false.")],
      calc=lambda: statements_text([
          sides((sqrt(x + 7) - 3)/(x - 2), x, 2)[0] == sides((sqrt(x + 7) - 3)/(x - 2), x, 2)[1],
          limit((sqrt(x + 7) - 3)/(x - 2), x, 2) == Rational(1, 6),
          limit((sqrt(x + 7) - 3)/(x - 2), x, 2) != Rational(1, 6)]),
      wrong_calcs=[lambda: statements_text([True, False, False]), None, None],
      change="numbers: limit 5 vs f(2)=1 -> limit 1/6 equal to stored value 1/6; context: bare limits -> sensor calibration; outcome changes to continuous"),

    # ======================================================================== 012
    # Original: |x-3|/(x-3), one-sided limits -1 and 1, limit DNE.
    M("012-v1", "012", "medium", "Signed Correction From a Motor Controller",
      "A motor controller outputs the signed correction c(x) = (x^2 - 4x)/|x - 4| for x != 4, where x is the commanded position in centimeters. Which of the following is true about lim(x->4) c(x)?",
      ("The limit does not exist because the one-sided limits are -4 and 4.",
       "Since x^2 - 4x = x(x - 4), for x > 4 we have |x - 4| = x - 4, so c(x) = x, which approaches 4. For x < 4, |x - 4| = -(x - 4), so c(x) = -x, which approaches -4. The one-sided limits differ, so the two-sided limit does not exist."),
      [("The limit is 4.",
        "This is the right-hand limit only. From the left, c(x) = -x approaches -4, so the two-sided limit does not exist."),
       ("The limit is -4.",
        "This is the left-hand limit only. From the right, c(x) = x approaches 4, so the two-sided limit does not exist."),
       ("The limit is 0.",
        "Substituting x = 4 makes the numerator 0, but the denominator |x - 4| is also 0, so the value is undefined, not 0. Near 4 the outputs are close to -4 on the left and close to 4 on the right.")],
      calc=lambda: ("The limit does not exist because the one-sided limits are "
                    + fmt(sides((x**2 - 4*x)/Abs(x - 4), x, 4)[0]) + " and "
                    + fmt(sides((x**2 - 4*x)/Abs(x - 4), x, 4)[1]) + "."),
      wrong_calcs=[lambda: "The limit is " + fmt(sides((x**2 - 4*x)/Abs(x - 4), x, 4)[1]) + ".",
                   lambda: "The limit is " + fmt(sides((x**2 - 4*x)/Abs(x - 4), x, 4)[0]) + ".",
                   lambda: "The limit is " + fmt((x**2 - 4*x).subs(x, 4)) + "."],
      change="numbers: |x-3|/(x-3) -> (x^2-4x)/|x-4| with one-sided values -4 and 4; context: bare function -> motor controller correction"),
    M("012-v2", "012", "medium", "Polarity Flag in a Circuit Model",
      "In a circuit model, a polarity readout is p(v) = |2v + 6|/(v + 3) for v != -3, where v is a voltage in volts. Which of the following is true about lim(v->-3) p(v)?",
      ("The limit does not exist because the one-sided limits are -2 and 2.",
       "Since |2v + 6| = 2|v + 3|, p(v) = 2|v + 3|/(v + 3). For v > -3 this is 2, and for v < -3 it is -2. The one-sided limits are 2 and -2, which differ, so the two-sided limit does not exist."),
      [("The limit is 2.",
        "This is the right-hand limit only. For v < -3 the absolute value flips the sign and p(v) = -2."),
       ("The limit is -2.",
        "This is the left-hand limit only. For v > -3, |2v + 6| = 2v + 6 and p(v) = 2."),
       ("The limit does not exist because p is unbounded near v = -3.",
        "The denominator does approach 0, but so does the numerator, and the ratio stays at the finite values -2 and 2. The limit fails to exist because the one-sided limits differ, not because p is unbounded.")],
      calc=lambda: ("The limit does not exist because the one-sided limits are "
                    + fmt(sides(Abs(2*x + 6)/(x + 3), x, -3)[0]) + " and "
                    + fmt(sides(Abs(2*x + 6)/(x + 3), x, -3)[1]) + "."),
      wrong_calcs=[lambda: "The limit is " + fmt(sides(Abs(2*x + 6)/(x + 3), x, -3)[1]) + ".",
                   lambda: "The limit is " + fmt(sides(Abs(2*x + 6)/(x + 3), x, -3)[0]) + ".",
                   None],
      change="numbers: point 3 -> -3, values +-1 -> +-2 via factor 2 inside |.|; context: bare function -> circuit polarity readout; third distractor now the 'unbounded' misconception"),
    M("012-v3", "012", "medium", "Profit Swing Around a Break-Even Output",
      "A firm's profit swing at output level q (in thousands of units) is modeled by s(q) = |q^2 - 25|/(q - 5) for q != 5. Which of the following is true about lim(q->5) s(q)?",
      ("The limit does not exist because the one-sided limits are -10 and 10.",
       "Write q^2 - 25 = (q - 5)(q + 5). Near q = 5, for q > 5 the expression q^2 - 25 is positive, so s(q) = q + 5, which approaches 10. For q < 5 (with q > -5) it is negative, so s(q) = -(q + 5), which approaches -10. The one-sided limits differ."),
      [("The limit is 10.",
        "This is the right-hand limit only. For q slightly below 5, q^2 - 25 is negative, the absolute value reverses its sign, and s(q) approaches -10."),
       ("The limit is -10.",
        "This is the left-hand limit only. For q slightly above 5, q^2 - 25 is positive and s(q) = q + 5 approaches 10."),
       ("The limit is 0.",
        "Substituting q = 5 makes the numerator 0, but the denominator is also 0, so no value is defined there. The 0/0 form must be resolved by cases, and it gives -10 from the left and 10 from the right.")],
      calc=lambda: ("The limit does not exist because the one-sided limits are "
                    + fmt(sides(Abs(x**2 - 25)/(x - 5), x, 5)[0]) + " and "
                    + fmt(sides(Abs(x**2 - 25)/(x - 5), x, 5)[1]) + "."),
      wrong_calcs=[lambda: "The limit is " + fmt(sides(Abs(x**2 - 25)/(x - 5), x, 5)[1]) + ".",
                   lambda: "The limit is " + fmt(sides(Abs(x**2 - 25)/(x - 5), x, 5)[0]) + ".",
                   lambda: "The limit is " + fmt((x**2 - 25).subs(x, 5)) + "."],
      change="numbers: |x-3|/(x-3) -> |q^2-25|/(q-5) with one-sided values -10 and 10 (quadratic inside |.|); context: bare function -> profit swing"),

    # ======================================================================== 013
    # Original: piecewise, jump discontinuity at x = 1 (finite unequal one-sided limits).
    M("013-v1", "013", "easy", "Identifying a Jump in a Taxi Fare",
      "A taxi fare F(d), in dollars for a ride of d miles, is defined by\n\nF(d) = 3d + 2 for d < 4\nF(d) = 5d - 1 for d >= 4\n\nWhich of the following describes F at d = 4?",
      ("F has a jump discontinuity at d = 4.",
       "From below, the fare approaches 3(4) + 2 = 14. From above (and at d = 4), it is 5(4) - 1 = 19. Both one-sided limits exist but are unequal, which is a jump discontinuity."),
      [("F has a removable discontinuity at d = 4.",
        "A removable discontinuity requires equal one-sided limits. Here they are 14 and 19."),
       ("F has an infinite discontinuity at d = 4.",
        "An infinite discontinuity involves unbounded behavior. Both one-sided limits here are finite numbers."),
       ("F is continuous at d = 4.",
        "F(4) = 19 matches the right-hand piece, but continuity also needs the left-hand limit 14 to equal it. The limit does not exist.")],
      calc=lambda: {"jump": "F has a jump discontinuity at d = 4.",
                    "removable": "F has a removable discontinuity at d = 4.",
                    "infinite": "F has an infinite discontinuity at d = 4.",
                    "continuous": "F is continuous at d = 4."}[
          disc_type(3*t + 2, 5*t - 1, t, 4, (5*t - 1).subs(t, 4))],
      wrong_calcs=[None, None, None],
      change="numbers: pieces x+2 / 5-x at 1 -> 3d+2 / 5d-1 at 4 (limits 14, 19); context: bare function -> taxi fare"),
    M("013-v2", "013", "easy", "Classifying a Gap in a Growth Model",
      "A colony-size model is defined by\n\nP(x) = (3x^2 - 12x)/(x - 4) for x != 4\nP(4) = 5\n\nWhich of the following describes P at x = 4?",
      ("P has a removable discontinuity at x = 4.",
       "Since 3x^2 - 12x = 3x(x - 4), P(x) = 3x for x != 4, so the limit at 4 is 12. P(4) = 5 does not equal 12, but the limit exists, which is a removable discontinuity."),
      [("P has a jump discontinuity at x = 4.",
        "A jump discontinuity needs unequal one-sided limits. Both one-sided limits are 12, because P(x) = 3x on both sides of 4."),
       ("P has an infinite discontinuity at x = 4.",
        "The denominator is 0 at x = 4, but the factor x - 4 cancels with the numerator, so the values stay near 12 and are not unbounded."),
       ("P is continuous at x = 4.",
        "P(4) is defined, but P(4) = 5 while the limit is 12. Continuity requires the value and the limit to be equal.")],
      calc=lambda: {"jump": "P has a jump discontinuity at x = 4.",
                    "removable": "P has a removable discontinuity at x = 4.",
                    "infinite": "P has an infinite discontinuity at x = 4.",
                    "continuous": "P is continuous at x = 4."}[
          disc_type((3*x**2 - 12*x)/(x - 4), (3*x**2 - 12*x)/(x - 4), x, 4, 5)],
      wrong_calcs=[None, None, None],
      change="numbers: piecewise linear pieces -> quotient with cancelling factor, limit 12 vs value 5; context: bare function -> colony size; outcome: removable"),
    M("013-v3", "013", "easy", "Doubling Then Linear Decline in a Culture",
      "The population index of a culture is defined by\n\nB(t) = 2^t for t < 3\nB(t) = 12 - t for t >= 3\n\nWhich of the following describes B at t = 3?",
      ("B has a jump discontinuity at t = 3.",
       "From the left, B approaches 2^3 = 8. From the right, B approaches 12 - 3 = 9. Both one-sided limits exist but are unequal, so the limit does not exist and the discontinuity is a jump."),
      [("B has a removable discontinuity at t = 3.",
        "A removable discontinuity requires the one-sided limits to be equal. Here they are 8 and 9, which are close but not equal."),
       ("B has an infinite discontinuity at t = 3.",
        "An infinite discontinuity involves unbounded behavior. Both one-sided limits here are finite numbers."),
       ("B is continuous at t = 3.",
        "B(3) = 9 equals the right-hand limit, but the left-hand limit is 8. Continuity requires the limit from both sides to equal B(3).")],
      calc=lambda: {"jump": "B has a jump discontinuity at t = 3.",
                    "removable": "B has a removable discontinuity at t = 3.",
                    "infinite": "B has an infinite discontinuity at t = 3.",
                    "continuous": "B is continuous at t = 3."}[
          disc_type(2**t, 12 - t, t, 3, (12 - t).subs(t, 3))],
      wrong_calcs=[None, None, None],
      change="numbers: linear pieces -> exponential 2^t and 12-t at 3 (limits 8, 9, close together); context: bare function -> culture population"),

    # ======================================================================== 014
    # Original: which function has an infinite discontinuity at x = 3 (choices are formulas).
    M("014-v1", "014", "medium", "Which Model Blows Up at t = 4?",
      "Four models of a quantity Q(t) are shown, where t is time in seconds. Which of them has an infinite discontinuity at t = 4?",
      ("Q(t) = (t^2 + 1)/(16 - t^2)",
       "At t = 4 the denominator is 16 - 16 = 0 while the numerator is 17, which is nonzero. Q is unbounded near t = 4, so there is an infinite discontinuity."),
      [("Q(t) = (t^2 - 3t - 4)/(t - 4)",
        "Factoring gives (t - 4)(t + 1)/(t - 4), which equals t + 1 for t != 4. The limit at 4 is 5, so this is a removable discontinuity."),
       ("Q(t) = 2 for t < 4 and Q(t) = 7 for t >= 4",
        "Both one-sided limits (2 and 7) are finite and unequal. This is a jump discontinuity."),
       ("Q(t) = (t - 4)^2/(t + 4)",
        "This function is continuous at t = 4, where it equals 0. Its trouble spot is t = -4, not t = 4.")],
      calc=lambda: [c[0] for c in [
          ("Q(t) = (t^2 + 1)/(16 - t^2)", (t**2 + 1)/(16 - t**2), (t**2 + 1)/(16 - t**2)),
          ("Q(t) = (t^2 - 3t - 4)/(t - 4)", (t**2 - 3*t - 4)/(t - 4), (t**2 - 3*t - 4)/(t - 4)),
          ("Q(t) = 2 for t < 4 and Q(t) = 7 for t >= 4", S(2), S(7)),
          ("Q(t) = (t - 4)^2/(t + 4)", (t - 4)**2/(t + 4), (t - 4)**2/(t + 4))]
          if oo in (abs(sides(c[1], t, 4)[0]), abs(sides(c[2], t, 4)[1]))][0],
      wrong_calcs=[None, None, None],
      change="numbers: point 3 -> 4, new formulas; context: symbolic -> time-dependent physical quantity, denominator 16 - t^2 (difference of squares) instead of a squared factor"),
    M("014-v2", "014", "medium", "Which Intensity Formula Becomes Unbounded at d = 2?",
      "An acoustics student proposes four formulas for the intensity I(d) of a sound source at distance d meters. Which formula becomes unbounded, that is, has an infinite discontinuity, at d = 2?",
      ("I(d) = 3/(e^(d - 2) - 1)",
       "At d = 2 the denominator is e^0 - 1 = 0 while the numerator is 3, which is nonzero. The values grow without bound in size near d = 2 (negative from the left, positive from the right), so the discontinuity is infinite."),
      [("I(d) = (d^3 - 8)/(d - 2)",
        "Factoring d^3 - 8 = (d - 2)(d^2 + 2d + 4) shows the factor d - 2 cancels, so I equals d^2 + 2d + 4 for d != 2. The limit at 2 is 12, a finite number, so this is removable."),
       ("I(d) = 4 for d < 2 and I(d) = 9 - d for d >= 2",
        "The left-hand limit is 4 and the right-hand limit is 9 - 2 = 7. Both are finite but unequal, so this is a jump discontinuity."),
       ("I(d) = (d - 2)/(d^2 + 1)",
        "The denominator d^2 + 1 is never 0, so I is continuous everywhere. At d = 2 the zero numerator only makes I(2) = 0; it does not make I unbounded.")],
      calc=lambda: (lambda d: [c[0] for c in [
          ("I(d) = 3/(e^(d - 2) - 1)", 3 / (exp(d - 2) - 1), 3 / (exp(d - 2) - 1)),
          ("I(d) = (d^3 - 8)/(d - 2)", (d**3 - 8) / (d - 2), (d**3 - 8) / (d - 2)),
          ("I(d) = 4 for d < 2 and I(d) = 9 - d for d >= 2", S(4), 9 - d),
          ("I(d) = (d - 2)/(d^2 + 1)", (d - 2) / (d**2 + 1), (d - 2) / (d**2 + 1))]
          if oo in (abs(sides(c[1], d, 2)[0]), abs(sides(c[2], d, 2)[1]))][0])(symbols("d", real=True)),
      wrong_calcs=[None, None, None],
      change="numbers: point 3 -> 2; function family: rational with squared factor -> exponential denominator; context: bare formulas -> candidate models of sound intensity, with a never-zero denominator as the continuous case"),
    M("014-v3", "014", "medium", "Unbounded Plant Density Along a River Bank",
      "A biologist tests four formulas for the density D(s) of a plant species at position s kilometers along a river bank. Which formula has an infinite discontinuity at s = -1?",
      ("D(s) = 6/|s + 1|",
       "At s = -1 the denominator |s + 1| is 0 while the numerator is 6, which is nonzero. The values grow without bound on both sides of -1, so there is an infinite discontinuity."),
      [("D(s) = (s^2 - 1)/(s + 1)",
        "Factoring gives (s - 1)(s + 1)/(s + 1), which equals s - 1 for s != -1. The limit at -1 is -2, a finite number, so this is a removable discontinuity."),
       ("D(s) = (|s + 1| + s + 1)/(s + 1)",
        "For s < -1 this equals 0 and for s > -1 it equals 2. The one-sided limits are 0 and 2, both finite but unequal, so this is a jump discontinuity."),
       ("D(s) = sqrt(s^2 + 3)/(s + 4)",
        "At s = -1 this equals 2/3, and the function is continuous there. Its only trouble spot is s = -4, where the denominator is 0.")],
      calc=lambda: (lambda d: [c[0] for c in [
          ("D(s) = 6/|s + 1|", 6 / Abs(d + 1)),
          ("D(s) = (s^2 - 1)/(s + 1)", (d**2 - 1) / (d + 1)),
          ("D(s) = (|s + 1| + s + 1)/(s + 1)", (Abs(d + 1) + d + 1) / (d + 1)),
          ("D(s) = sqrt(s^2 + 3)/(s + 4)", sqrt(d**2 + 3) / (d + 4))]
          if oo in (abs(sides(c[1], d, -1)[0]), abs(sides(c[1], d, -1)[1]))][0])(symbols("d", real=True)),
      wrong_calcs=[None, None, None],
      change="numbers: point 0 -> -1; function family: sin(x) denominator -> absolute-value denominator; context: bare formulas -> plant density along a river bank"),

    # ======================================================================== 015
    # Original: choose a so a two-piece function is continuous; distractors are algebra-step errors.
    M("015-v1", "015", "medium", "Tiered Energy Charge Continuous at 3 Units",
      "A utility's charge C(x), in dollars for x units of energy, is defined by\n\nC(x) = ax - 5 for x < 3\nC(x) = x^2 - 2a for x >= 3\n\nFor what value of a is the charge C continuous at x = 3?",
      ("14/5",
       "Continuity requires the left-hand limit 3a - 5 to equal C(3) = 9 - 2a. Solving 3a - 5 = 9 - 2a gives 5a = 14, so a = 14/5."),
      [("4/5",
        "This solves 3a + 5 = 9 - 2a, treating the -5 as +5. The left-hand value at x = 3 is 3a - 5."),
       ("14/3",
        "This sets 3a - 5 = 9 and forgets that the right-hand piece, x^2 - 2a, also contains a."),
       ("14",
        "This combines 3a and -2a on opposite sides as 3a - 2a = 14 instead of adding 2a to both sides to get 3a + 2a = 14.")],
      calc=lambda: solve_param(a*3 - 5, 3**2 - 2*a),
      wrong_calcs=[lambda: solve_param(3*a + 5, 9 - 2*a),
                   lambda: solve_param(3*a - 5, 9),
                   lambda: solve_param(3*a - 2*a, 14)],
      change="numbers: ax+1 / x^2-a at 2 -> ax-5 / x^2-2a at 3, answer 14/5; context: bare function -> tiered energy charge"),
    M("015-v2", "015", "medium", "Heat Model With a Radical Branch",
      "The temperature T(x), in degrees, at position x along a metal rod is modeled by\n\nT(x) = 3x - a for x < 4\nT(x) = a*sqrt(x) + 1 for x >= 4\n\nFor what value of a is T continuous at x = 4?",
      ("11/3",
       "Continuity requires the left-hand limit 3(4) - a = 12 - a to equal T(4) = a*sqrt(4) + 1 = 2a + 1. Solving 12 - a = 2a + 1 gives 3a = 11, so a = 11/3."),
      [("11/5",
        "This evaluates sqrt(4) as 4, giving 12 - a = 4a + 1. The square root of 4 is 2."),
       ("11",
        "This gives 12 + a = 2a + 1, changing the sign of a in the left-hand piece. The left-hand value at x = 4 is 12 - a."),
       ("13/3",
        "This moves the +1 across the equal sign without changing its sign, writing 3a = 12 + 1 instead of 3a = 12 - 1.")],
      calc=lambda: solve_param(3*4 - a, a*sqrt(4) + 1),
      wrong_calcs=[lambda: solve_param(12 - a, 4*a + 1),
                   lambda: solve_param(12 + a, 2*a + 1),
                   lambda: solve_param(3*a, 12 + 1)],
      change="numbers: quadratic right branch -> a*sqrt(x)+1 at 4, answer 11/3; context: bare function -> temperature along a rod"),
    M("015-v3", "015", "medium", "Signal Shaper Continuous at -2",
      "A signal-shaping function is defined by\n\nS(x) = x^3 + ax for x <= -2\nS(x) = x^2 - a for x > -2\n\nFor what value of a is S continuous at x = -2?",
      ("-12",
       "S(-2) = (-2)^3 + a(-2) = -8 - 2a, and the right-hand limit is (-2)^2 - a = 4 - a. Continuity requires -8 - 2a = 4 - a, which gives -a = 12, so a = -12."),
      [("4",
        "This evaluates (-2)^3 as +8, giving 8 - 2a = 4 - a. A negative number cubed is negative, so (-2)^3 = -8."),
       ("-4",
        "This evaluates (-2)^2 as -4, giving -8 - 2a = -4 - a. A negative number squared is positive, so (-2)^2 = 4."),
       ("12",
        "This solves -8 - 2a = 4 - a correctly down to -a = 12 but then drops the negative sign, reporting 12 instead of -12.")],
      calc=lambda: solve_param((-2)**3 + a*(-2), (-2)**2 - a),
      wrong_calcs=[lambda: solve_param(8 - 2*a, 4 - a),
                   lambda: solve_param(-8 - 2*a, -4 - a),
                   lambda: fmt(-solve(Eq((-2)**3 + a*(-2), (-2)**2 - a), a)[0])],
      change="numbers: linear/quadratic at 2 -> cubic/quadratic at -2, answer -12; context: bare function -> signal shaper; boundary is negative so sign errors are the trap"),

    # ======================================================================== 016
    # Original: largest set of continuity for sqrt(x-1)/(x-4). Variants use open domains (no endpoint disputes).
    M("016-v1", "016", "medium", "Continuity Set of a Logarithmic Quotient",
      "Consider the function f(x) = ln(6 - 2x)/(x + 1). What is the set of all x at which f is continuous?",
      ("The union of (-infinity, -1) and (-1, 3)",
       "The logarithm requires 6 - 2x > 0, which means x < 3. The denominator is 0 at x = -1, which lies in that range and must be removed. f is continuous at every point of its domain, which is (-infinity, -1) and (-1, 3)."),
      [("The interval (-infinity, 3)",
        "This satisfies the logarithm's requirement but includes x = -1, where the denominator is 0 and f is undefined."),
       ("The union of (-infinity, -1) and (-1, infinity)",
        "This removes only x = -1 and ignores the logarithm. ln(6 - 2x) is undefined for x >= 3."),
       ("The interval (3, infinity)",
        "This solves 6 - 2x > 0 as x > 3, failing to reverse the inequality when dividing by -2. The correct condition is x < 3.")],
      calc=lambda: set_text(continuous_domain(log(6 - 2*x)/(x + 1), x, S.Reals)),
      wrong_calcs=[lambda: set_text(continuous_domain(log(6 - 2*x), x, S.Reals)),
                   lambda: set_text(continuous_domain(1/(x + 1), x, S.Reals)),
                   lambda: set_text(solveset(6 - 2*x > 0, x, S.Reals).complement(S.Reals) - {3})],
      change="numbers/family: sqrt(x-1)/(x-4) -> ln(6-2x)/(x+1), open domain with a reversed inequality; context: symbolic, different function family"),
    M("016-v2", "016", "medium", "Continuity Set With a Radical in the Denominator",
      "Consider the function f(x) = 1/sqrt(x^2 - 4x - 5). What is the set of all x at which f is continuous?",
      ("The union of (-infinity, -1) and (5, infinity)",
       "Since x^2 - 4x - 5 = (x - 5)(x + 1), the radical is defined and nonzero only where (x - 5)(x + 1) > 0, which is x < -1 or x > 5. On that set f is continuous."),
      [("The interval (-1, 5)",
        "This is where (x - 5)(x + 1) is negative, so the radicand is negative and the square root is undefined there."),
       ("The union of (-infinity, -1] and [5, infinity)",
        "At x = -1 and x = 5 the radicand is 0, so the denominator sqrt(0) is 0 and f is undefined. Those endpoints must be excluded."),
       ("The union of (-infinity, -1), (-1, 5) and (5, infinity)",
        "This removes only the points where the radicand is 0 and ignores the square root's requirement. For -1 < x < 5 the radicand is negative.")],
      calc=lambda: set_text(continuous_domain(1/sqrt(x**2 - 4*x - 5), x, S.Reals)),
      wrong_calcs=[lambda: set_text(solveset(x**2 - 4*x - 5 < 0, x, S.Reals)),
                   lambda: set_text(solveset(x**2 - 4*x - 5 >= 0, x, S.Reals)),
                   lambda: set_text(S.Reals - solveset(x**2 - 4*x - 5, x, S.Reals))],
      change="numbers/family: sqrt(x-1)/(x-4) -> reciprocal of a square root of a quadratic; context: symbolic, different function family (inequality with two boundary points)"),
    M("016-v3", "016", "medium", "Continuity Set of a Reciprocal With Absolute Value",
      "Consider the function f(x) = 1/(|x - 1| - 3). What is the set of all x at which f is continuous?",
      ("The union of (-infinity, -2), (-2, 4) and (4, infinity)",
       "The denominator is 0 when |x - 1| = 3, which means x - 1 = 3 or x - 1 = -3, so x = 4 or x = -2. The absolute value function is continuous everywhere, so f is continuous at every other real number."),
      [("The union of (-infinity, 4) and (4, infinity)",
        "This solves |x - 1| = 3 with only the positive case x - 1 = 3, missing the negative case x - 1 = -3, which gives x = -2."),
       ("The union of (-infinity, -4), (-4, 2) and (2, infinity)",
        "This solves x - 1 = 3 and x - 1 = -3 as x + 1 = 3 and x + 1 = -3, changing the sign of the 1. The correct solutions are x = 4 and x = -2."),
       ("The union of (-infinity, -2), (-2, 1), (1, 4) and (4, infinity)",
        "This treats the corner of |x - 1| at x = 1 as a discontinuity. The graph has a sharp corner there, but f is defined and continuous at x = 1, where it equals 1/(0 - 3) = -1/3.")],
      calc=lambda: set_text(continuous_domain(1/(Abs(x - 1) - 3), x, S.Reals)),
      wrong_calcs=[lambda: set_text(S.Reals - {4}),
                   lambda: set_text(S.Reals - {2, -4}),
                   lambda: set_text(S.Reals - {-2, 1, 4})],
      change="numbers/family: sqrt quotient -> reciprocal of |x-1|-3, two removed points and a corner trap; context: symbolic, different function family"),

    # ======================================================================== 017
    # Original: which function is continuous on [0, 5] (choices are formulas).
    M("017-v1", "017", "hard", "Continuous Calibration Curve on [-3, 4]",
      "A sensor is calibrated for input settings from -3 to 4 inclusive. Only one of four candidate response curves is defined and continuous at every setting in that range. Which curve is it?",
      ("R(x) = sqrt(x + 5)/(x^2 + 1)",
       "The radical is defined for x >= -5, which includes all of [-3, 4], and the denominator x^2 + 1 is never 0. The quotient of continuous functions with a nonzero denominator is continuous on the whole interval."),
      [("R(x) = 1/(x^2 - 4)",
        "Since x^2 - 4 = (x - 2)(x + 2), the denominator is 0 at x = 2 and x = -2, both in [-3, 4]."),
       ("R(x) = ln(x + 2)",
        "The logarithm is undefined for x <= -2, so R is not defined on [-3, -2]."),
       ("R(x) = sqrt(1 - x)",
        "The square root is undefined for x > 1, so R is not defined on (1, 4].")],
      calc=lambda: [c[0] for c in [
          ("R(x) = sqrt(x + 5)/(x^2 + 1)", sqrt(x + 5)/(x**2 + 1)),
          ("R(x) = 1/(x^2 - 4)", 1/(x**2 - 4)),
          ("R(x) = ln(x + 2)", log(x + 2)),
          ("R(x) = sqrt(1 - x)", sqrt(1 - x))]
          if continuous_domain(c[1], x, Interval(-3, 4)) == Interval(-3, 4)][0],
      wrong_calcs=[None, None, None],
      change="numbers: interval [-2,3] -> [-3,4]; family: quadratic denominator -> radical over a never-zero quadratic; context: bare functions -> sensor calibration curves with a differently phrased stem"),
    M("017-v2", "017", "hard", "Continuity on [1, 6] for a Logarithm of a Quadratic",
      "A technician needs a model that is continuous at every input from 1 to 6, inclusive. Which of the following functions is continuous on the closed interval [1, 6]?",
      ("f(x) = ln(x^2 - 4x + 5)",
       "The argument x^2 - 4x + 5 = (x - 2)^2 + 1 is at least 1 for every real x, so it is always positive. The logarithm of a positive continuous function is continuous, so f is continuous on [1, 6]."),
      [("f(x) = |x - 4|/(x - 4)",
        "The function is undefined at x = 4, which lies in [1, 6]."),
       ("f(x) = sqrt(5 - x)",
        "The square root is undefined for x > 5, so f is not defined on (5, 6]."),
       ("f(x) = 1/(x^2 - 7x + 10)",
        "Since x^2 - 7x + 10 = (x - 2)(x - 5), the denominator is 0 at x = 2 and x = 5, both in [1, 6].")],
      calc=lambda: [c[0] for c in [
          ("f(x) = ln(x^2 - 4x + 5)", log(x**2 - 4*x + 5)),
          ("f(x) = |x - 4|/(x - 4)", Abs(x - 4)/(x - 4)),
          ("f(x) = sqrt(5 - x)", sqrt(5 - x)),
          ("f(x) = 1/(x^2 - 7x + 10)", 1/(x**2 - 7*x + 10))]
          if continuous_domain(c[1], x, Interval(1, 6)) == Interval(1, 6)][0],
      wrong_calcs=[None, None, None],
      change="numbers: interval [0,5] -> [1,6]; family: tangent correct -> logarithm of an always-positive quadratic correct; context: technician model"),
    M("017-v3", "017", "hard", "Continuity on [0, 4] of a Tangent Model",
      "An oscillating gauge reading must be defined and continuous at every time from 0 to 4 seconds, inclusive. Which of the following functions is continuous on the closed interval [0, 4]?",
      ("f(x) = tan(pi x/10)",
       "The tangent function is undefined only where its argument is pi/2 plus a multiple of pi. Here that happens at x = 5 + 10k for every integer k, and the nearest such x-values are x = 5 and x = -5, both outside [0, 4], so f is continuous on the whole interval."),
      [("f(x) = tan(pi x/6)",
        "The argument pi x/6 equals pi/2 at x = 3, which lies in [0, 4], so f is undefined there."),
       ("f(x) = ln(2x - 3)",
        "The logarithm requires 2x - 3 > 0, so x > 3/2. f is not defined on [0, 3/2]."),
       ("f(x) = (x^2 - 3x)/(x - 3)",
        "This simplifies to x for x != 3, but the original expression is undefined at x = 3, which lies in [0, 4]. Simplifying does not make f defined there.")],
      calc=lambda: [c[0] for c in [
          ("f(x) = tan(pi x/10)", tan(pi*x/10)),
          ("f(x) = tan(pi x/6)", tan(pi*x/6)),
          ("f(x) = ln(2x - 3)", log(2*x - 3)),
          ("f(x) = (x^2 - 3x)/(x - 3)", (x**2 - 3*x)/(x - 3))]
          if continuous_domain(c[1], x, Interval(0, 4)) == Interval(0, 4)][0],
      wrong_calcs=[None, None, None],
      change="numbers: tan(pi x/12) on [0,5] -> tan(pi x/10) on [0,4] with a nearby tan(pi x/6) trap; context: gauge reading; distractors include a simplifiable quotient"),

    # ======================================================================== 018
    # Original: fill a hole, (x^3 - 8)/(x - 2), k = 12.
    M("018-v1", "018", "easy", "Filling a Gap in a Cost Ratio With a Sum of Cubes",
      "An engineer models a cost ratio by g(x) = (x^3 + 125)/(x + 5) for x != -5, and sets g(-5) = k. For what value of k is g continuous at x = -5?",
      ("75",
       "The sum of cubes factors as x^3 + 125 = (x + 5)(x^2 - 5x + 25), so g(x) = x^2 - 5x + 25 for x != -5. The limit as x approaches -5 is 25 + 25 + 25 = 75, and continuity requires k to equal it."),
      [("25",
        "This factors the sum of cubes with the wrong sign, as (x + 5)(x^2 + 5x + 25). At x = -5 that gives 25 - 25 + 25 = 25, but the correct middle term is -5x."),
       ("0",
        "Substituting x = -5 gives 0 in the numerator, but the denominator is also 0. The form 0/0 is indeterminate, so the limit must be found by simplifying first."),
       ("No such value of k exists.",
        "The denominator is 0 at x = -5, but the factor x + 5 cancels. The limit exists, so a value of k that matches it does exist.")],
      calc=lambda: fmt(limit((x**3 + 125)/(x + 5), x, -5)),
      wrong_calcs=[lambda: fmt(limit((x + 5)*(x**2 + 5*x + 25)/(x + 5), x, -5)), None, None],
      change="numbers: x^3-8 over x-2 -> x^3+125 over x+5 (sum of cubes, sign trap), k = 75; context: bare function -> engineering cost ratio"),
    M("018-v2", "018", "easy", "Filling a Gap in a Scaled Volume Ratio",
      "A scaling model for a cube of side s uses the ratio V(s) = (8s^3 - 1)/(2s - 1) for s != 1/2, and defines V(1/2) = m. For what value of m is V continuous at s = 1/2?",
      ("3",
       "The difference of cubes 8s^3 - 1 = (2s)^3 - 1 factors as (2s - 1)(4s^2 + 2s + 1), so V(s) = 4s^2 + 2s + 1 for s != 1/2. The limit at s = 1/2 is 1 + 1 + 1 = 3, and continuity requires m to equal it."),
      [("2",
        "This factors 8s^3 - 1 as (2s - 1)(4s^2 + 1), dropping the middle term. Expanding that product gives 8s^3 - 4s^2 + 2s - 1, not 8s^3 - 1."),
       ("0",
        "Substituting s = 1/2 gives 0 in the numerator, but the denominator is also 0. The form 0/0 is indeterminate, so the limit must be found by simplifying first."),
       ("6",
        "This rewrites the denominator as 2(s - 1/2) and cancels only the factor s - 1/2, forgetting that the leftover 2 divides the result. The quotient is exactly 4s^2 + 2s + 1, which approaches 3.")],
      calc=lambda: fmt(limit((8*x**3 - 1)/(2*x - 1), x, Rational(1, 2))),
      wrong_calcs=[lambda: fmt(limit(4*x**2 + 1, x, Rational(1, 2))), None,
                   lambda: fmt(2*limit((8*x**3 - 1)/(2*x - 1), x, Rational(1, 2)))],
      change="numbers: x^3-8 over x-2 -> 8s^3-1 over 2s-1 at s=1/2 (non-integer point, leading coefficient), m = 3; context: bare function -> scaling model for a cube"),
    M("018-v3", "018", "easy", "Filling a Gap in a Reversed-Order Difference Quotient",
      "The rate constant of a reaction is modeled by k(y) = (64 - y^3)/(4 - y) for y != 4, and k(4) = r. For what value of r is k continuous at y = 4?",
      ("48",
       "The difference of cubes factors as 64 - y^3 = (4 - y)(16 + 4y + y^2), so k(y) = y^2 + 4y + 16 for y != 4. The limit at y = 4 is 16 + 16 + 16 = 48, and continuity requires r to equal it."),
      [("32",
        "This factors 64 - y^3 as (4 - y)(16 + y^2), dropping the middle term 4y. Expanding that product gives 64 - 16y + 4y^2 - y^3, not 64 - y^3."),
       ("0",
        "Substituting y = 4 gives 0 in the numerator, but the denominator is also 0. The form 0/0 is indeterminate, so the limit must be found by simplifying first."),
       ("-48",
        "This flips the sign, as if the denominator were y - 4 instead of 4 - y. The factor 4 - y appears in both the numerator's factorization and the denominator, so it cancels with no sign change and the limit is +48.")],
      calc=lambda: fmt(limit((64 - x**3)/(4 - x), x, 4)),
      wrong_calcs=[lambda: fmt(limit((4 - x)*(16 + x**2)/(4 - x), x, 4)), None,
                   lambda: fmt(-limit((64 - x**3)/(4 - x), x, 4))],
      change="numbers: x^3-8 over x-2 -> 64-y^3 over 4-y (reversed order of terms), r = 48; context: bare function -> reaction rate constant"),

    # ======================================================================== 019
    # Original: (sqrt(x+9)-3)/x, conjugate, c = 1/6.
    M("019-v1", "019", "medium", "Removing a Gap With a Radical in the Denominator",
      "A power-output model is p(x) = (x - 4)/(sqrt(x) - 2) for x != 4, and p(4) = m. For what value of m is p continuous at x = 4?",
      ("4",
       "Multiplying the numerator and denominator by the conjugate sqrt(x) + 2 gives (x - 4)(sqrt(x) + 2)/(x - 4) = sqrt(x) + 2 for x != 4. As x approaches 4 this approaches 2 + 2 = 4."),
      [("0",
        "The numerator 4 - 4 equals 0, but the denominator sqrt(4) - 2 is also 0. The quotient is 0/0, which is indeterminate, so the limit has to be found by simplifying first, for example by rationalizing with the conjugate."),
       ("1/4",
        "This inverts the result. After multiplying by the conjugate the expression is sqrt(x) + 2, not 1/(sqrt(x) + 2), and it approaches 4."),
       ("2",
        "This reduces the expression to sqrt(x) by dropping the +2 from sqrt(x) + 2, giving sqrt(4) = 2. Since the conjugate factor is sqrt(x) + 2, its value at 4 is 4.")],
      calc=lambda: fmt(limit((x - 4)/(sqrt(x) - 2), x, 4)),
      wrong_calcs=[None, lambda: fmt(1/limit(sqrt(x) + 2, x, 4)), lambda: fmt(limit(sqrt(x), x, 4))],
      change="numbers: sqrt(x+9)-3 over x -> (x-4)/(sqrt(x)-2), m = 4; form: radical in numerator -> radical in denominator; context: bare function -> power output"),
    M("019-v2", "019", "medium", "Rationalizing a Reaction-Rate Model With a Reversed Difference",
      "A chemist models the rate of a reaction by k(x) = (5 - sqrt(25 - 3x))/x for x < 25/3, x != 0, and k(0) = m. For what value of m is k continuous at x = 0?",
      ("3/10",
       "Multiplying by the conjugate 5 + sqrt(25 - 3x) gives (25 - (25 - 3x))/(x(5 + sqrt(25 - 3x))) = 3x/(x(5 + sqrt(25 - 3x))) = 3/(5 + sqrt(25 - 3x)) for x != 0. As x approaches 0 this approaches 3/(5 + 5) = 3/10."),
      [("3/5",
        "This treats the conjugate sum as 5 instead of 10. At x = 0 the factor 5 + sqrt(25 - 3x) equals 5 + 5 = 10, so the limit is 3/10."),
       ("0",
        "The numerator 5 - sqrt(25) equals 0, but the denominator is also 0. The quotient is 0/0, which is indeterminate, so the limit has to be found by simplifying first, for example by rationalizing, and it should not be assumed to be 0."),
       ("10/3",
        "This inverts the result. After rationalizing, the expression is 3/(5 + sqrt(25 - 3x)), which approaches 3/10, not 10/3.")],
      calc=lambda: fmt(limit((5 - sqrt(25 - 3*x))/x, x, 0)),
      wrong_calcs=[lambda: fmt(limit(Rational(3, 5) + 0*x, x, 0)), None,
                   lambda: fmt(1/limit((5 - sqrt(25 - 3*x))/x, x, 0))],
      change="numbers: sqrt(2x+1)-3 over x-4 -> 5-sqrt(25-3x) over x, m = 3/10; form: constant minus radical (negated conjugate order); context: valve efficiency -> chemical reaction rate"),
    M("019-v3", "019", "medium", "Rationalizing a Difference of Two Radicals",
      "A signal ratio is modeled by r(x) = (sqrt(x + 3) - sqrt(5x - 1))/(x - 1) for x > 1/5, x != 1, and r(1) = d. For what value of d is r continuous at x = 1?",
      ("-1",
       "Multiplying by the conjugate sqrt(x + 3) + sqrt(5x - 1) gives ((x + 3) - (5x - 1))/((x - 1)(sqrt(x + 3) + sqrt(5x - 1))) = -4(x - 1)/((x - 1)(...)) = -4/(sqrt(x + 3) + sqrt(5x - 1)). As x approaches 1 this approaches -4/(2 + 2) = -1."),
      [("1",
        "This subtracts the radicands in the wrong order, getting (5x - 1) - (x + 3) = 4x - 4 = 4(x - 1) in the numerator. The numerator is (x + 3) - (5x - 1) = -4x + 4 = -4(x - 1)."),
       ("-4",
        "This cancels x - 1 to get -4 but forgets to divide by the conjugate sum sqrt(x + 3) + sqrt(5x - 1), which equals 4 at x = 1."),
       ("0",
        "At x = 1 the numerator is sqrt(4) - sqrt(4) = 0 and the denominator is also 0. The quotient is 0/0, which is indeterminate, so the limit has to be found by simplifying first, for example by rationalizing with the conjugate.")],
      calc=lambda: fmt(limit((sqrt(x + 3) - sqrt(5*x - 1))/(x - 1), x, 1)),
      wrong_calcs=[lambda: fmt(limit(((5*x - 1) - (x + 3))/((x - 1)*(sqrt(x + 3) + sqrt(5*x - 1))), x, 1)),
                   lambda: fmt(limit(((x + 3) - (5*x - 1))/(x - 1), x, 1)),
                   None],
      change="numbers: one radical minus constant -> difference of two radicals, d = -1; context: bare function -> signal ratio"),

    # ======================================================================== 020
    # Original: choose a so the numerator cancels (x^2 + ax - 10)/(x - 2), f(2) = 7, a = 3.
    M("020-v1", "020", "medium", "Choosing a Coefficient So a Wind-Speed Model Has No Gap",
      "A wind-speed model is defined by w(x) = (x^2 + ax + 6)/(x - 1) for x != 1, and w(1) = -5. For what value of a is w continuous at x = 1?",
      ("-7",
       "For the limit to exist, the numerator must be 0 at x = 1: 1 + a + 6 = 0, so a = -7. Then x^2 - 7x + 6 = (x - 1)(x - 6), and the limit is 1 - 6 = -5, which matches w(1)."),
      [("-6",
        "This assumes the numerator factors as (x - 1)(x + a) and sets 1 + a = -5. But (x - 1)(x - 6) = x^2 - 7x + 6, so the coefficient of x is -7, not -6."),
       ("-5",
        "This confuses the required limit value with the parameter. The number -5 is the value w(1) that the limit must match, not the value of a."),
       ("7",
        "This makes a sign error in solving 1 + a + 6 = 0. Subtracting 7 from both sides gives a = -7.")],
      calc=lambda: fmt(solve((x**2 + a*x + 6).subs(x, 1), a)[0]) if limit((x**2 - 7*x + 6)/(x - 1), x, 1) == -5 else "invalid",
      wrong_calcs=[lambda: solve_param(1 + a, -5),
                   None,
                   lambda: fmt(-solve((x**2 + a*x + 6).subs(x, 1), a)[0])],
      change="numbers: a = 3, f(2) = 7 -> a = -7, w(1) = -5; context: bare function -> wind-speed model with negative parameter"),
    M("020-v2", "020", "medium", "Choosing a Constant So a Profit Model Has No Gap",
      "The profit per unit, in dollars, when q hundred units are sold is modeled by P(q) = (q^2 - 2q + a)/(q - 5) for q != 5, and P(5) = 8. For what value of a is P continuous at q = 5?",
      ("-15",
       "For the limit to exist, the numerator must be 0 at q = 5: 25 - 10 + a = 0, so a = -15. Then q^2 - 2q - 15 = (q - 5)(q + 3), and the limit is 5 + 3 = 8, which matches P(5)."),
      [("8",
        "This confuses the required limit value with the parameter. The number 8 is the value P(5) that the limit must match, not the value of a."),
       ("15",
        "This makes a sign error in solving 25 - 10 + a = 0. Since 25 - 10 = 15, moving it across gives a = -15, not 15."),
       ("3",
        "This treats a as the constant in the second factor, setting 5 + a = 8. But a is the constant term of the numerator, which equals -5 times 3, that is -15.")],
      calc=lambda: fmt(solve((x**2 - 2*x + a).subs(x, 5), a)[0]) if limit((x**2 - 2*x - 15)/(x - 5), x, 5) == 8 else "invalid",
      wrong_calcs=[None,
                   lambda: fmt(-solve((x**2 - 2*x + a).subs(x, 5), a)[0]),
                   lambda: solve_param(5 + a, 8)],
      change="numbers: a on the leading term, zero at -3 -> a as the constant term, zero at 5, a = -15; context: reaction rate -> profit per unit"),
    M("020-v3", "020", "medium", "Choosing a Linear Coefficient in a Cubic Numerator",
      "A stress model is defined by s(x) = (x^3 + ax - 6)/(x - 2) for x != 2, and s(2) = 11. For what value of a is s continuous at x = 2?",
      ("-1",
       "For the limit to exist, the numerator must be 0 at x = 2: 8 + 2a - 6 = 0, so a = -1. Then x^3 - x - 6 = (x - 2)(x^2 + 2x + 3), and the limit is 4 + 4 + 3 = 11, which matches s(2)."),
      [("11",
        "This confuses the required limit value with the parameter. The number 11 is the value s(2) that the limit must match, not the value of a."),
       ("-7",
        "This makes a sign error on the constant term, using 8 + 2a + 6 = 0. The numerator's constant is -6, so the equation is 8 + 2a - 6 = 0."),
       ("0",
        "This evaluates 2^3 as 6 (2 times 3), giving 6 + 2a - 6 = 0. The cube 2^3 equals 8.")],
      calc=lambda: fmt(solve((x**3 + a*x - 6).subs(x, 2), a)[0]) if limit((x**3 - x - 6)/(x - 2), x, 2) == 11 else "invalid",
      wrong_calcs=[None,
                   lambda: fmt(solve(8 + 2*a + 6, a)[0]),
                   lambda: fmt(solve(6 + 2*a - 6, a)[0])],
      change="numbers: quadratic numerator -> cubic numerator, a = -1, s(2) = 11; context: bare function -> stress model"),
]
