const subjectKeys = ["ap-calculus-ab", "ap-calculus-bc", "ap-precalculus"];
const subjectPackages = [];
const itemPackages = [];

for (const subjectKey of subjectKeys) {
  subjectPackages.push(JSON.parse(await Deno.readTextFile(`content/subject-packages/${subjectKey}.subject-package.json`)));
  for await (const entry of Deno.readDir(`content/item-packages/${subjectKey}`)) {
    if (entry.isFile && entry.name.endsWith(".json")) {
      itemPackages.push(JSON.parse(await Deno.readTextFile(`content/item-packages/${subjectKey}/${entry.name}`)));
    }
  }
}
itemPackages.sort((a, b) => a.content_key.localeCompare(b.content_key));

const literal = (value: unknown) => `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`;
const subjectValues = subjectPackages.map((value) => `(${literal(value)})`).join(",\n");
const itemValues = itemPackages.map((value) => `(${literal(value)})`).join(",\n");

const sql = `-- Generated by scripts/calculus-content/build-production-seed.ts.
-- Production-native draft content load. No publication and no Tutor assignment.
begin;

create temp table calculus_subject_seed(payload jsonb not null) on commit drop;
insert into calculus_subject_seed(payload) values
${subjectValues};

create temp table calculus_item_seed(payload jsonb not null) on commit drop;
insert into calculus_item_seed(payload) values
${itemValues};

do $$
begin
  if (select count(*) from calculus_subject_seed) <> 3 then
    raise exception 'calculus_seed:expected_3_subjects';
  end if;
  if (select count(*) from calculus_item_seed) <> 108 then
    raise exception 'calculus_seed:expected_108_items';
  end if;
  if exists (
    select 1
    from calculus_item_seed seed
    join app.content_items ci on ci.content_key=seed.payload->>'content_key'
    join app.content_item_versions civ on civ.content_item_id=ci.id and civ.version_num=1
    where ci.status<>'draft' or civ.status<>'draft'
  ) then
    raise exception 'calculus_seed:refuse_to_replace_non_draft_content';
  end if;
end
$$;

insert into app.subjects(subject_key,display_name,status)
select payload#>>'{subject,subject_key}',payload#>>'{subject,display_name}','active'
from calculus_subject_seed
on conflict(subject_key) do update
set display_name=excluded.display_name,updated_at=now();

insert into app.exam_packs(exam_code,exam_name,subject_id)
select seed.payload#>>'{exam_pack,exam_code}',seed.payload#>>'{exam_pack,exam_name}',s.id
from calculus_subject_seed seed
join app.subjects s on s.subject_key=seed.payload#>>'{subject,subject_key}'
on conflict(exam_code) do update
set exam_name=excluded.exam_name,subject_id=excluded.subject_id,updated_at=now();

insert into app.exam_pack_versions(exam_pack_id,school_year,official_exam_date,status,source_uri,source_published_at)
select ep.id,seed.payload#>>'{exam_pack,school_year}',(seed.payload#>>'{exam_pack,official_exam_date}')::date,'draft',
       seed.payload#>>'{sources,0,uri}','2026-07-17'::date
from calculus_subject_seed seed
join app.exam_packs ep on ep.exam_code=seed.payload#>>'{exam_pack,exam_code}'
on conflict(exam_pack_id,school_year) do update
set official_exam_date=excluded.official_exam_date,status='draft',source_uri=excluded.source_uri,
    source_published_at=excluded.source_published_at,updated_at=now();

insert into app.content_labels(exam_pack_id,label_key,label_name,label_type,status)
select ep.id,node->>'node_key',node->>'label','unit','draft'
from calculus_subject_seed seed
join app.exam_packs ep on ep.exam_code=seed.payload#>>'{exam_pack,exam_code}'
cross join lateral jsonb_array_elements(seed.payload#>'{taxonomy,nodes}') node
where node->>'node_type'='unit'
on conflict(exam_pack_id,label_key) do update
set label_name=excluded.label_name,label_type=excluded.label_type,status='draft',updated_at=now();

insert into app.content_labels(exam_pack_id,label_key,label_name,label_type,status)
select ep.id,'difficulty-'||lower(replace(level,' ','-')),level,'difficulty','draft'
from calculus_subject_seed seed
join app.exam_packs ep on ep.exam_code=seed.payload#>>'{exam_pack,exam_code}'
cross join (values('Easy'),('Medium'),('Hard'),('Very Hard')) levels(level)
on conflict(exam_pack_id,label_key) do update
set label_name=excluded.label_name,label_type=excluded.label_type,status='draft',updated_at=now();

insert into app.content_labels(exam_pack_id,label_key,label_name,label_type,status)
select ep.id,'tutor-review-seed-2026-07-17','Tutor review seed 2026-07-17','workflow','draft'
from calculus_subject_seed seed
join app.exam_packs ep on ep.exam_code=seed.payload#>>'{exam_pack,exam_code}'
on conflict(exam_pack_id,label_key) do update
set label_name=excluded.label_name,label_type=excluded.label_type,status='draft',updated_at=now();

insert into app.content_items(exam_pack_version_id,content_key,item_type,title,status,frq_form)
select epv.id,item.payload->>'content_key',item.payload->>'item_type',upper(item.payload->>'content_key'),'draft',
       case when item.payload->>'item_type'='frq' then item.payload->>'frq_form' else null end
from calculus_item_seed item
join app.exam_packs ep on ep.exam_code=item.payload#>>'{exam_pack_ref,exam_code}'
join app.exam_pack_versions epv on epv.exam_pack_id=ep.id and epv.school_year=item.payload#>>'{exam_pack_ref,school_year}'
on conflict(exam_pack_version_id,content_key) do update
set item_type=excluded.item_type,title=excluded.title,status='draft',frq_form=excluded.frq_form,updated_at=now();

insert into app.content_item_versions(
  content_item_id,version_num,stem,stimulus,prompt_json,explanation,help_text,content_hash,status,
  canonical_answer_1,canonical_answer_2,review_status,rubric_type,evaluator_strategy
)
select ci.id,1,
       case when item.payload->>'item_type'='mcq'
         then split_part(item.payload#>>'{parts,0,prompt}',E'\n\nA. ',1)
         else (select string_agg(coalesce(part->>'label','')||' '||(part->>'prompt'),E'\n\n' order by (part->>'ordinal')::int)
               from jsonb_array_elements(item.payload->'parts') part)
       end,
       item.payload#>>'{stimuli,0,payload,text}',item.payload,item.payload#>>'{review_notes,expected_reasoning}',null,
       item.payload#>>'{provenance,content_sha256}','draft',item.payload#>>'{canonical_answers,0}',
       item.payload#>>'{canonical_answers,1}',null,
       case when item.payload->>'item_type'='mcq' then 'mcq' else 'discrete_text' end,
       case when item.payload->>'item_type'='mcq' then 'rule_based_mcq' else 'llm_discrete_text' end
from calculus_item_seed item
join app.content_items ci on ci.content_key=item.payload->>'content_key'
join app.exam_pack_versions epv on epv.id=ci.exam_pack_version_id
join app.exam_packs ep on ep.id=epv.exam_pack_id and ep.exam_code=item.payload#>>'{exam_pack_ref,exam_code}'
on conflict(content_item_id,version_num) do update
set stem=excluded.stem,stimulus=excluded.stimulus,prompt_json=excluded.prompt_json,
    explanation=excluded.explanation,help_text=excluded.help_text,content_hash=excluded.content_hash,status='draft',
    canonical_answer_1=excluded.canonical_answer_1,canonical_answer_2=excluded.canonical_answer_2,
    review_status=null,rubric_type=excluded.rubric_type,evaluator_strategy=excluded.evaluator_strategy,updated_at=now();

delete from app.mcq_choices choice
using app.content_item_versions civ,app.content_items ci,calculus_item_seed seed
where choice.content_item_version_id=civ.id and civ.content_item_id=ci.id
  and ci.content_key=seed.payload->>'content_key';

delete from app.frq_criteria criterion
using app.content_item_versions civ,app.content_items ci,calculus_item_seed seed
where criterion.content_item_version_id=civ.id and civ.content_item_id=ci.id
  and ci.content_key=seed.payload->>'content_key';

insert into app.mcq_choices(content_item_version_id,choice_key,choice_text,is_correct,rationale)
select civ.id,choice->>'choice_key',choice->>'choice_text',(choice->>'is_correct')::boolean,choice->>'rationale'
from calculus_item_seed seed
join app.content_items ci on ci.content_key=seed.payload->>'content_key'
join app.content_item_versions civ on civ.content_item_id=ci.id and civ.version_num=1
cross join lateral jsonb_array_elements(seed.payload->'mcq_choices') choice
where seed.payload->>'item_type'='mcq';

insert into app.frq_criteria(
  content_item_version_id,criterion_key,learner_facing_text,points_possible,
  evidence_requirements,minimum_fix,accepted_variants
)
select civ.id,criterion->>'criterion_key',criterion->>'description',(criterion->>'points')::int,
       array_to_string(array(select jsonb_array_elements_text(criterion->'required_evidence')),'; '),
       'Provide the missing mathematical evidence: '||array_to_string(array(select jsonb_array_elements_text(criterion->'required_evidence')),', '),
       coalesce(criterion->'accepted_variants','[]'::jsonb)
from calculus_item_seed seed
join app.content_items ci on ci.content_key=seed.payload->>'content_key'
join app.content_item_versions civ on civ.content_item_id=ci.id and civ.version_num=1
cross join lateral jsonb_array_elements(seed.payload->'parts') part
cross join lateral jsonb_array_elements(part->'criteria') criterion
where seed.payload->>'item_type'='frq';

insert into app.content_item_labels(content_item_id,content_label_id)
select ci.id,label.id
from calculus_item_seed seed
join app.content_items ci on ci.content_key=seed.payload->>'content_key'
join app.exam_pack_versions epv on epv.id=ci.exam_pack_version_id
join app.content_labels label on label.exam_pack_id=epv.exam_pack_id
  and label.label_key=(select ref->>'node_key' from jsonb_array_elements(seed.payload->'taxonomy_refs') ref where ref->>'node_key' like 'unit-%' limit 1)
on conflict do nothing;

insert into app.content_item_labels(content_item_id,content_label_id)
select ci.id,label.id
from calculus_item_seed seed
join app.content_items ci on ci.content_key=seed.payload->>'content_key'
join app.exam_pack_versions epv on epv.id=ci.exam_pack_version_id
join app.content_labels label on label.exam_pack_id=epv.exam_pack_id
  and label.label_key='difficulty-'||lower(replace(seed.payload->>'difficulty',' ','-'))
on conflict do nothing;

insert into app.content_item_labels(content_item_id,content_label_id)
select ci.id,label.id
from calculus_item_seed seed
join app.content_items ci on ci.content_key=seed.payload->>'content_key'
join app.exam_pack_versions epv on epv.id=ci.exam_pack_version_id
join app.content_labels label on label.exam_pack_id=epv.exam_pack_id
  and label.label_key='tutor-review-seed-2026-07-17'
on conflict do nothing;

do $$
declare
  v_subject record;
begin
  for v_subject in
    select seed.payload#>>'{exam_pack,exam_code}' exam_code
    from calculus_subject_seed seed
  loop
    if (select count(*) from app.content_items ci join app.exam_pack_versions epv on epv.id=ci.exam_pack_version_id join app.exam_packs ep on ep.id=epv.exam_pack_id where ep.exam_code=v_subject.exam_code and ci.status='draft' and ci.item_type='mcq') <> 20 then
      raise exception 'calculus_seed:% expected 20 draft MCQ',v_subject.exam_code;
    end if;
    if (select count(*) from app.content_items ci join app.exam_pack_versions epv on epv.id=ci.exam_pack_version_id join app.exam_packs ep on ep.id=epv.exam_pack_id where ep.exam_code=v_subject.exam_code and ci.status='draft' and ci.item_type='frq') <> 16 then
      raise exception 'calculus_seed:% expected 16 draft FRQ',v_subject.exam_code;
    end if;
  end loop;
  if (select count(*) from app.mcq_choices choice join app.content_item_versions civ on civ.id=choice.content_item_version_id join app.content_items ci on ci.id=civ.content_item_id where ci.content_key in (select payload->>'content_key' from calculus_item_seed)) <> 240 then
    raise exception 'calculus_seed:expected_240_mcq_choices';
  end if;
  if (select count(*) from app.frq_criteria criterion join app.content_item_versions civ on civ.id=criterion.content_item_version_id join app.content_items ci on ci.id=civ.content_item_id where ci.content_key in (select payload->>'content_key' from calculus_item_seed)) <> 192 then
    raise exception 'calculus_seed:expected_192_frq_criteria';
  end if;
  if exists (
    select 1 from app.content_review_assignments assignment
    join app.content_item_versions civ on civ.id=assignment.content_item_version_id
    join app.content_items ci on ci.id=civ.content_item_id
    where ci.content_key in (select payload->>'content_key' from calculus_item_seed)
  ) then
    raise exception 'calculus_seed:unexpected_reviewer_assignment';
  end if;
end
$$;

commit;
`;

await Deno.writeTextFile("/private/tmp/cramapple-calculus-seed-production.sql", sql);
await Deno.writeTextFile("/private/tmp/cramapple-calculus-seed-production-dry-run.sql", sql.replace(/\ncommit;\n$/, "\nrollback;\n"));
console.log(JSON.stringify({ output: "/private/tmp/cramapple-calculus-seed-production.sql", dryRun: "/private/tmp/cramapple-calculus-seed-production-dry-run.sql", subjects: subjectPackages.length, items: itemPackages.length, bytes: new TextEncoder().encode(sql).length }));
