// Turns generate_gold_set.mjs's output JSONL into a ready-to-run migration:
// inserts each provisional_accept answer into app.gold_set_answers, then
// creates a gold_set_verification_assignments row for each of two named
// reviewers against every inserted answer (blind double-coverage, same
// pattern the existing AP Statistics Set A pool already uses -- see
// docs/Q&A/SESSION_2026_08_13_GOLD_SET_REVIEWER_ASSIGNMENT_AND_CALC_SETA.md).
//
// discard / reader_queue rows are reported but NOT loaded -- discard means
// the writer didn't follow its own script (regenerate, don't load); reader_
// queue means the two verifiers split (genuine ambiguity, needs a human
// call before it's usable, not silently forced into the reviewer queue).
//
// Usage: node build_setA_load_sql.mjs <answers.jsonl> <reviewer1_uuid> <reviewer2_uuid> <out.sql>

import fs from 'node:fs';

const [, , JSONL_PATH, REVIEWER1, REVIEWER2, OUT_PATH] = process.argv;
if (!JSONL_PATH || !REVIEWER1 || !REVIEWER2 || !OUT_PATH) {
  console.error('Usage: node build_setA_load_sql.mjs <answers.jsonl> <reviewer1_uuid> <reviewer2_uuid> <out.sql>');
  process.exit(1);
}

const lines = fs.readFileSync(JSONL_PATH, 'utf8').split('\n').filter(Boolean);
const records = lines.map((l) => JSON.parse(l));

const accepted = records.filter((r) => r.route === 'provisional_accept');
const discarded = records.filter((r) => r.route === 'discard');
const queued = records.filter((r) => r.route === 'reader_queue');

console.log(`${records.length} records: ${accepted.length} provisional_accept (will load), ` +
  `${discarded.length} discard (skipped), ${queued.length} reader_queue (skipped -- needs a human call)`);
if (discarded.length) console.log('  discarded:', discarded.map((r) => `${r.content_key}/${r.answer_type}`).join(', '));
if (queued.length) console.log('  reader_queue:', queued.map((r) => `${r.content_key}/${r.answer_type}`).join(', '));

if (!accepted.length) {
  console.error('Nothing to load -- 0 provisional_accept records.');
  process.exit(1);
}

const esc = (s) => `$q$${s}$q$`; // dollar-quote; answer text/scripts never contain "$q$"

const insertValues = accepted.map((r) => {
  const scriptJson = JSON.stringify(r.script).replace(/\$q\$/g, '');
  return `('A', '${r.content_item_version_id}', '${r.answer_type}', ${esc(r.answer_text)}, ` +
    `'${r.writer_family}', ${esc(scriptJson)}::jsonb, '${r.script_hash}', '${r.route}', '${r.item_content_hash}')`;
}).join(',\n  ');

const sql = `-- Set A answer load + reviewer assignment, generated by build_setA_load_sql.mjs
-- from ${JSONL_PATH} on ${new Date().toISOString().slice(0, 10)}.
-- ${accepted.length} provisional_accept answers across ${new Set(accepted.map((r) => r.content_key)).size} items.
-- ${discarded.length} discarded, ${queued.length} reader_queue -- both excluded, see script header.

begin;
select pg_advisory_xact_lock(hashtext('cramapple-calc-setA-answer-load'));

create temporary table new_answers (
  gold_set_answer_id uuid primary key default gen_random_uuid(),
  content_key text not null
) on commit drop;

with inserted as (
  insert into app.gold_set_answers (set_key, content_item_version_id, answer_type, answer_text, writer_family, script, script_hash, route, item_content_hash)
  values
  ${insertValues}
  returning gold_set_answer_id, content_item_version_id
)
insert into new_answers (gold_set_answer_id, content_key)
select i.gold_set_answer_id, ci.content_key
from inserted i
join app.content_item_versions v on v.id = i.content_item_version_id
join app.content_items ci on ci.id = v.content_item_id;

insert into app.gold_set_verification_assignments (gold_set_verification_assignment_id, gold_set_answer_id, reviewer_id, seq, status, assigned_at)
select gen_random_uuid(), na.gold_set_answer_id, r.reviewer_id, 1, 'pending', now()
from new_answers na
cross join (values ('${REVIEWER1}'::uuid), ('${REVIEWER2}'::uuid)) as r(reviewer_id);

select 'answers_loaded' metric, count(*)::text value from new_answers
union all select 'assignments_created', count(*)::text from app.gold_set_verification_assignments where gold_set_answer_id in (select gold_set_answer_id from new_answers)
union all select 'items_covered', string_agg(distinct content_key, ', ' order by content_key) from new_answers;

commit;
`;

fs.writeFileSync(OUT_PATH, sql);
console.log(`\nWrote ${OUT_PATH}`);
