"""Format pass: write checked symbol definitions onto existing AP Chemistry formula entries.

Updates body/items/caution of an existing published row matched on (subject_key, owner_topic_code,
kind='formula', title), so reference_entry_id (and any hook pointing at it) is kept and topic tags are
unchanged. A re-extracted row is written only when both checkers accepted it and the veto did not
reject it (check.py's `accepted`), its title and owner match the current row exactly, and it defines at
least one symbol in items. Everything else keeps its current version and is listed in the report.
Output: out/update_formulas.sql + out/update_report.json. No hand edits."""
import json, pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "out"
BATCH = "task0067-chem-formula-symbols-2026-10-10"


def q(s):
    return "NULL" if s is None else "'" + str(s).replace("'", "''") + "'"


def j(v):
    return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def main():
    current = json.loads((OUT / "current_formulas_dev.json").read_text())
    by_key = {(r["owner_topic_code"], r["title"]): r for r in current}
    lines = [f"-- generated by upsert.py; do not hand-edit. Batch: {BATCH}", "begin;"]
    report = {"updated": [], "kept_current": []}
    for u in range(1, 10):
        cp, vp = OUT / f"candidates_ap_chemistry_u{u}_r9.json", OUT / f"verdicts_ap_chemistry_u{u}_r9.json"
        if not cp.exists() or not vp.exists():
            report["kept_current"] += [{"unit": u, "title": r["title"], "why": "no format-pass output"} for r in current if r["unit_number"] == u]
            continue
        cands = {c["candidate_id"]: c for c in json.loads(cp.read_text())}
        verdicts = {v["candidate_id"]: v for v in json.loads(vp.read_text()) if not v.get("control")}
        done = set()
        for cid, c in cands.items():
            key = (c.get("owner_topic_code"), c.get("title"))
            v = verdicts.get(cid)
            row = by_key.get(key)
            why = None
            if row is None or row["unit_number"] != u:
                why = f"title/owner changed by extractor: {key}"
            elif c.get("kind") != "formula":
                why = "kind changed"
            elif not v or not v.get("accepted"):
                why = "not accepted by checkers/veto"
            elif not [i for i in (c.get("items") or []) if i.get("label") and i.get("meaning")]:
                why = "no symbol definitions"
            if why:
                report["kept_current"].append({"unit": u, "candidate_id": cid, "title": c.get("title"), "why": why})
                continue
            done.add(key)
            note = f"; fmt={BATCH}:{cid}"
            lines.append(
                "update app.unit_reference_entries set "
                f"body = {q(c['body'])}, items = {j(c['items'])}, caution = {q(c.get('caution'))}, "
                f"source_note = source_note || {q(note)}\n"
                # Match on the table's unique key, not reference_entry_id: Development and Production
                # generated their own ids, so the same SQL must resolve the row in both.
                f"where subject_key = 'ap_chemistry' and owner_topic_code = {q(row['owner_topic_code'])} "
                f"and kind = 'formula' and title = {q(row['title'])} and status = 'published';")
            report["updated"].append({"unit": u, "title": row["title"], "symbols": len(c["items"]), "caution": bool(c.get("caution"))})
        for r in current:
            if r["unit_number"] == u and (r["owner_topic_code"], r["title"]) not in done and not any(
                    k.get("title") == r["title"] for k in report["kept_current"] if k.get("unit") == u):
                report["kept_current"].append({"unit": u, "title": r["title"], "why": "not re-extracted"})
    lines.append("commit;")
    (OUT / "update_formulas.sql").write_text("\n".join(lines) + "\n")
    (OUT / "update_report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False))
    print(f"updated {len(report['updated'])}, kept current {len(report['kept_current'])}")


if __name__ == "__main__":
    main()
