import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";

const ROOT = new URL("../../", import.meta.url).pathname;
const OUT = `${ROOT}content/item-packages/ap-precalculus`;
const PACKET = `${ROOT}docs/teaching/AP_PRECALCULUS_PRACTICE_PACKET_2026_07_27.md`;
const GENERATED_AT = "2026-07-28T00:00:00Z";
const SOURCE_REF = "ap-precalculus-ced-effective-fall-2026";
const ORIGINALITY = "Independently authored Cramapple practice item from a blank scope brief; no released, secure, or third-party question or scoring language was used.";

const mcq = [
  ["1.2","1","Medium","no-calculator","For f(x)=x³−4x, what is the average rate of change on [−1,2]?",["−2","−1","+1","+2"],"B","[f(2)−f(−1)]/3=(0−3)/3=−1.","Divides the output change by an incorrect interval length.","Correctly computes the secant slope as −1.","Reverses the subtraction of the function values.","Uses only the input change."],
  ["1.5","1","Medium","no-calculator","The polynomial p(x)=x⁴−5x²+4 has which complete set of real zeros?",["{−2,−1,1,2}","{−4,−1,1,4}","{−2,−1,1}","{−2,1,2}"],"A","Let u=x². Then u²−5u+4=(u−1)(u−4), so x=±1,±2.","Correctly treats the expression as quadratic in x².","Confuses the values of x² with values of x.","Omits the positive root from x²=4.","Omits the negative root from x²=1."],
  ["1.6","3","Easy","no-calculator","Which statement describes the end behavior of q(x)=−3x⁵+2x²−7?",["q(x)→∞ at both ends","q(x)→−∞ at both ends","q(x)→−∞ as x→∞ and q(x)→∞ as x→−∞","q(x)→∞ as x→∞ and q(x)→−∞ as x→−∞"],"C","The odd-degree leading term −3x⁵ controls the ends.","Treats the polynomial as even degree with positive leading coefficient.","Treats the polynomial as even degree with negative leading coefficient.","Uses the odd degree and negative leading coefficient correctly.","Ignores the negative leading coefficient."],
  ["1.9","2","Medium","no-calculator","For r(x)=(x+1)/(x²−5x+6), which values are vertical asymptotes?",["x=−1 only","x=2 only","x=3 only","x=2 and x=3"],"D","The denominator factors as (x−2)(x−3), and neither factor cancels.","Uses the numerator zero rather than denominator zeros.","Finds only one denominator zero.","Finds only the other denominator zero.","Finds both noncanceled denominator zeros."],
  ["1.10","3","Medium","no-calculator","Let h(x)=(x²−9)/(x−3) for x≠3. Which statement is true?",["The graph has a hole at (3,6).","The graph has a vertical asymptote at x=3.","The graph has a hole at (−3,0).","The graph is the entire line y=x+3."],"A","For x≠3, h(x)=x+3; the excluded input produces a hole at (3,6).","Correctly cancels and evaluates the missing point.","Fails to recognize the removable discontinuity.","Uses a zero of the numerator as the hole.","Ignores the original domain restriction."],
  ["1.12","1","Easy","no-calculator","If g(x)=−2f(x−3)+5, which transformation takes the graph of f to the graph of g?",["Left 3, vertical stretch 2, reflect across x-axis, up 5","Right 3, vertical stretch 2, reflect across x-axis, up 5","Right 5, vertical shrink 1/2, down 3","Left 5, vertical stretch 2, reflect across y-axis, up 3"],"B","The input shift is right 3; the output is multiplied by −2 and then increased by 5.","Reverses the horizontal shift.","Correctly interprets every transformation.","Interchanges the horizontal and vertical constants.","Uses unrelated transformations."],
  ["1.13","2","Medium","no-calculator","A table has constant second differences and nonconstant first differences for equally spaced inputs. Which model type is most appropriate?",["Linear","Quadratic","Exponential","Sinusoidal"],"B","Constant second differences indicate a quadratic model.","Confuses constant first differences with constant second differences.","Correctly identifies the quadratic signature.","Confuses constant ratios with second differences.","No periodic evidence is given."],
  ["1.11","1","Medium","no-calculator","When p(x)=2x³−3x²+4x−5 is divided by x−2, what is the remainder?",["3","7","11","15"],"B","By the Remainder Theorem, p(2)=16−12+8−5=7.","Arithmetic error in evaluating p(2).","Correctly applies the Remainder Theorem.","Omits the constant term.","Adds absolute values of several terms."],
  ["1.8","1","Hard","no-calculator","For which x is (x−1)/(x+2)≤0?",["(−∞,−2)∪[1,∞)","(−2,1]","[−2,1]","(−∞,1]"],"B","A sign chart with critical values −2 and 1 gives (−2,1], excluding x=−2.","Selects the positive-sign intervals.","Correct sign interval with the zero included and undefined value excluded.","Incorrectly includes the denominator zero.","Fails to account for the sign change at x=−2."],
  ["1.14","3","Hard","calculator","A cubic regression for data is y=0.42x³−1.8x²+0.65x+7.1. What is the predicted change in y from x=2.4 to x=3.1, to the nearest hundredth?",["0.23","0.64","1.29","3.43"],"A","Evaluating the model gives y(3.1)−y(2.4)≈0.23.","Correct calculator evaluation of the change.","Uses an approximate rate with an incorrect interval.","Uses the later output minus an incorrectly rounded earlier output.","Adds or otherwise combines the two outputs incorrectly."],
  ["1.4","3","Hard","calculator","For f(x)=x⁴−6x²+2, what is the average rate of change from x=1.2 to x=2.7, to the nearest tenth?",["−3.5","6.3","10.6","16.0"],"C","[f(2.7)−f(1.2)]/(2.7−1.2)≈10.6.","Reverses or mis-enters the endpoint calculation.","Uses an incorrect interval length.","Correct calculator evaluation of the secant slope.","Reports approximately the output change, not the rate."],
  ["2.3","3","Easy","no-calculator","For f(x)=7(1.12)^x, which statement is true?",["f decreases by 12% per unit","f increases by 12% per unit","f increases by 112% per unit","f has a constant increase of 0.12"],"B","The growth factor 1.12 means a 12% increase per unit.","Treats a factor above 1 as decay.","Correctly interprets 1+0.12.","Uses the entire factor as the percent increase.","Confuses multiplicative and additive change."],
  ["2.4","1","Medium","no-calculator","Which expression is equivalent to 5·2^(3x−1)?",["(5/2)·8^x","10·8^x","5·6^x−1","(5/2)·6^x"],"A","2^(3x−1)=2^(3x)/2=8^x/2.","Correct exponent decomposition.","Multiplies by 2 instead of dividing.","Distributes the exponent incorrectly.","Incorrectly replaces the factor 2³ with 6."],
  ["2.13","1","Medium","no-calculator","What is the solution to log₃(x−1)+log₃(x+1)=2?",["x=√10","x=3","x=−√10","x=10"],"A","Combine logs: log₃(x²−1)=2, so x²=10; the domain requires x>1.","Correct equation and domain restriction.","Solves x²=9 instead of x²=10.","Keeps the extraneous negative root.","Fails to take the square root."],
  ["2.10","2","Medium","no-calculator","If f(x)=4^(x−2)+1, which formula gives f⁻¹(x)?",["log₄(x−1)+2","log₄(x+1)−2","4^(x+2)−1","log_(1/4)(x−1)+2"],"A","Swap x and y, then solve x−1=4^(y−2), giving y=log₄(x−1)+2.","Correctly reverses the transformations.","Uses the shifts with incorrect signs.","Does not form an inverse.","Uses the reciprocal base, which changes the sign."],
  ["2.7","1","Easy","no-calculator","If f(x)=2x−5 and g(x)=x²+1, what is (g∘f)(x)?",["(x²+1)²−5","(2x−4)²+1","(2x−5)²−1","(2x−5)²+1"],"D","Substitute f(x) into g: (2x−5)²+1.","Applies f after g rather than g after f.","Subtracts 5 before doubling the input.","Uses the correct inner function but subtracts 1.","Correct composition in the stated order."],
  ["2.6","3","Medium","calculator","For x=0,1,2,3,4, a quantity has values 6.1, 9.0, 13.6, 20.2, 30.5. Which claim is best supported?",["A linear model, because first differences are nearly constant","An exponential model, because successive ratios are near 1.5","A quadratic model, because second differences are exactly constant","No model, because the values are not integers"],"B","The successive ratios are approximately 1.48,1.51,1.49,1.51.","The first differences increase substantially.","Correctly uses nearly constant ratios.","The second differences are not exactly constant.","Integer outputs are not required for modeling."],
  ["2.15","2","Hard","no-calculator","Points from y=ab^x lie on a line when log₁₀(y) is plotted against x. If the line has slope 0.3010, what is b approximately?",["0.301","1.301","2","10.301"],"C","The slope equals log₁₀(b), so b=10^0.3010≈2.","Confuses the logarithm with its argument.","Incorrectly adds 1 to the given slope.","Correctly exponentiates base 10.","Adds 10 rather than exponentiating."],
  ["2.5","3","Hard","calculator","A culture has 480 cells at t=0 and 1,260 cells at t=5 hours. Under an exponential model, how many cells are predicted at t=8, to the nearest whole cell?",["1,728","2,181","2,248","3,308"],"C","The hourly factor is (1260/480)^(1/5); 480 times this factor^8 is about 2,248.","Uses an incorrect linear increase.","Uses a prematurely rounded growth factor.","Correct exponential interpolation/extrapolation.","Applies the five-hour factor eight times."],
  ["2.14","3","Hard","calculator","A logarithmic regression is y=4.8+2.3ln(x). What x gives y=12, to the nearest tenth?",["8.4","15.2","22.9","31.7"],"C","Solve ln x=(12−4.8)/2.3, so x≈22.9.","Uses the logarithm value as x.","Uses base-10 exponentiation.","Correctly exponentiates with base e.","Divides 12 by 2.3 before exponentiating."],
  ["3.3","1","Easy","no-calculator","What is the exact value of cos(5π/6)?",["−√3/2","−1/2","1/2","√3/2"],"A","The reference angle is π/6 and cosine is negative in Quadrant II.","Correct reference value and sign.","Uses the sine reference value.","Uses the sine value with wrong sign.","Uses the cosine value with wrong sign."],
  ["3.5","2","Medium","no-calculator","For y=−4sin(3x)+2, what are the amplitude and period?",["Amplitude 4, period 2π/3","Amplitude −4, period 3","Amplitude 2, period 2π","Amplitude 4, period 3π"],"A","Amplitude is |−4|=4 and period is 2π/3.","Correctly reads both parameters.","Amplitude cannot be negative and the period is not the coefficient.","Confuses vertical shift with amplitude.","Multiplies rather than divides to find period."],
  ["3.6","1","Medium","no-calculator","Which function has midline y=−1, amplitude 3, period π, and a maximum at x=0?",["3cos(2x)−1","3sin(2x)−1","−3cos(x)−1","3cos(x/2)−1"],"A","A cosine maximum at 0 with amplitude 3 and B=2 has period π.","Correctly satisfies all four stated features.","Has midline crossing at x=0, not a maximum.","Has period 2π and a minimum at 0.","Has period 4π rather than π."],
  ["3.10","1","Hard","no-calculator","On 0≤x<2π, what are the solutions to 2sin²x−sin x−1=0?",["{π/2,3π/2,2π}","{π/6,5π/6,3π/2}","{π/6,5π/6,π}","{0,π/2,π,3π/2}"],"B","Factor (2sin x+1)(sin x−1)=0, giving sin x=1 or −1/2.","Uses values for sin x=±1 and includes an excluded endpoint.","Includes π/6,5π/6,3π/2 correctly.","Uses the positive one-half reference angles and adds π.","Uses zeros and extrema of sine rather than solving the equation."],
  ["3.7","3","Medium","calculator","A sinusoidal model is T(t)=18+7sin((π/6)(t−2)), where t is hours. What is T(5.5), to the nearest tenth?",["11.2","19.8","24.8","25.0"],"C","Substitution gives 18+7sin(7π/12)≈24.8.","Uses the negative of the sine value.","Uses degree mode or an incorrect phase shift.","Correct radian-mode evaluation.","Uses the maximum without evaluating."],
  ["3.9","1","Medium","no-calculator","What is arctan(−√3) on the principal interval (−π/2,π/2)?",["−π/3","−2π/3","π/3","2π/3"],"A","The principal angle with tangent −√3 is −π/3.","Correctly identifies the principal value.","Has the right tangent but lies outside the principal interval.","Uses the angle with the wrong sign.","Has the wrong sign and lies outside the interval."],
  ["3.12","1","Medium","no-calculator","Which expression is equivalent to (1−cos²x)/sin x where sin x≠0?",["sin x","cos x","tan x","1"],"A","Use 1−cos²x=sin²x, then divide by sin x.","Correct Pythagorean identity and cancellation.","Uses the wrong squared function.","Introduces an extra division by cosine.","Cancels the numerator incorrectly."],
  ["3.13","2","Medium","calculator","The polar point (r,θ)=(−4,5π/6) has which rectangular coordinates?",["(−2√3,2)","(2√3,−2)","(−2√3,−2)","(2,−2√3)"],"B","x=r cosθ=2√3 and y=r sinθ=−2.","Fails to apply the negative radius to y.","Correctly applies the negative radius to both coordinates.","Uses the signs for a positive radius.","Interchanges sine and cosine."],
  ["3.14","2","Hard","calculator","For r=2+2cosθ, which statement best describes the graph?",["A cardioid symmetric about the polar axis with a cusp at the pole","A circle centered at (2,0) with radius 2 and tangent to the pole","A four-petal rose symmetric about both coordinate axes with petal length 2","A cardioid symmetric about θ=π/2 with a cusp above the pole"],"A","The form a+a cosθ is a right-facing cardioid with r=0 at θ=π.","Correct classification, symmetry, and cusp.","Confuses the polar equation with a rectangular circle tangent to the pole.","Confuses the equation with a rose of the form r=a cos(2θ).","Uses the symmetry and orientation associated with a sine-based cardioid."],
  ["3.15","3","Hard","calculator","For r(θ)=3+sin(2θ), what is the average rate of change of r from θ=0.4 to θ=1.1, to the nearest hundredth?",["−0.13","0.13","0.62","1.12"],"B","[r(1.1)−r(0.4)]/(1.1−0.4)≈0.13.","Reverses the subtraction.","Correct calculator evaluation in radians.","Uses only the change in r.","Uses a derivative-like calculation instead of the average rate."]
];

const frq = [
  ["function-concepts","1","2","Medium","calculator","A function f is modeled by f(x)=0.5x³−2x²−x+6 on −2≤x≤5.",["Find the average rate of change of f on [1,4].","Use technology to approximate all real zeros of f in the interval to three decimals.","Determine the intervals in the stated domain where f(x)>0, and justify from the zeros and a sign analysis."],[["The average rate is −0.5.","Shows [f(4)−f(1)]/3=(2−3.5)/3=−0.5."],["The zeros are approximately −1.646, 2.000, and 3.646.","Reports all three roots to three decimals."],["f(x)>0 on (−1.646,2)∪(3.646,5].","Uses alternating signs or test values and respects the domain."]]],
  ["function-concepts","2","2","Medium","calculator","Let g(x)=3·1.4^x−5.",["Find g(2.5) to three decimals and state whether it is above or below the horizontal asymptote.","Solve g(x)=20 to three decimals.","Write g⁻¹(x) and state its domain."],[["g(2.5)≈1.957.","The value is above the asymptote y=−5."],["x=log₁.₄(25/3)≈6.301.","Shows an equation equivalent to 1.4^x=25/3."],["g⁻¹(x)=log₁.₄((x+5)/3).","The inverse domain is x>−5."]]],
  ["function-concepts","1","1","Hard","calculator","A rational function is h(x)=(x²−x−6)/(x²−4x+3).",["Identify every x-intercept, vertical asymptote, and hole.","Find the horizontal asymptote and explain using end behavior.","Solve h(x)=2, excluding values outside the domain."],[["The x-intercept is (−2,0), the vertical asymptote is x=1, and the hole is (3,5/2).","Factors h=(x−3)(x+2)/[(x−1)(x−3)] and retains the restriction x≠3."],["The horizontal asymptote is y=1.","Uses the ratio of equal-degree leading coefficients or equivalent end-behavior reasoning."],["x=4.","Solves (x+2)/(x−1)=2 and verifies x=4 is allowed."]]],
  ["function-concepts","2","2","Hard","calculator","A function p has values p(0)=2, p(1)=5, p(2)=13, p(3)=35, and p(4)=97.",["Compute successive ratios and explain why a simple exponential model is not exact.","Find constants a and b so p(x)=a·2^x+b·3^x matches p(0) and p(1).","Use the model to predict p(5), and compare it with the pattern in the table."],[["The ratios 5/2, 13/5, 35/13, and 97/35 are not constant.","Connects nonconstant ratios to failure of an exact single exponential."],["a=1 and b=1, so p(x)=2^x+3^x.","Solves a+b=2 and 2a+3b=5."],["p(5)=32+243=275.","Shows the model reproduces the listed values and extends their pattern."]]],
  ["function-concepts","2","2","Medium","calculator","For x>0, let q(x)=ln(x)+2/x.",["Find q(1) and q(e²) exactly.","Use technology to approximate the absolute minimum value of q and an x-value where it occurs on 0.2≤x≤8.","Explain the end behavior of q as x approaches 0 from the right and as x increases without bound."],[["q(1)=2 and q(e²)=2+2/e².","Substitutes into both terms of q."],["The minimum is approximately 1.693 at x≈2.000.","Reports a technology-supported global minimum on the closed interval."],["q(x)→∞ as x→0⁺ and q(x)→∞ as x→∞.","Uses 2/x for the left-end behavior and ln x for the right-end behavior."]]],

  ["modeling-nonperiodic","1","3","Medium","calculator","A ball’s height y, in meters, is modeled as a quadratic function of time t, in seconds. Measurements give (t,y)=(0,2),(2,10),(5,7).",["Construct the quadratic model y=at²+bt+c by giving a system and solving for a, b, and c.","Find the average rate of change in height from t=1 to t=4, with units.","A student uses the model at t=20. Explain one limitation of that prediction."],[["The system is c=2, 4a+2b+c=10, and 25a+5b+c=7.","Solving gives y=−t²+6t+2."],["The average rate is [y(4)−y(1)]/3=(10−7)/3=1 meter per second.","Interprets the value as average vertical change over the interval."],["The prediction is an extrapolation far beyond the measured times and may be physically impossible.","Connects the limitation to the data interval or ground impact."]]],
  ["modeling-nonperiodic","2","3","Medium","calculator","A medication sample contains 160 milligrams at t=0 hours and 80 milligrams at t=4 hours. Assume an exponential model M(t)=ab^t.",["Use the two measurements to determine a and b and write the model.","Find the average rate of change from t=2 to t=6, with units.","Explain why the model should not be used to claim the sample reaches exactly 0 milligrams at a finite time."],[["a=160 and b=(1/2)^(1/4), so M(t)=160(1/2)^(t/4).","Uses both data points to determine the parameters."],["The average rate is approximately −14.142 milligrams per hour.","Uses [M(6)−M(2)]/4 and includes units."],["The exponential model approaches 0 asymptotically but is never exactly 0 for finite t.","Distinguishes model behavior from a finite zero."]]],
  ["modeling-nonperiodic","1","3","Hard","calculator","Daily profit P, in hundreds of dollars, is quadratic in production x, measured in hundreds of units. Profit is zero at x=20 and x=80, and P(50)=90.",["Construct a quadratic model for P by determining its leading coefficient.","Find the average rate of change of profit from x=30 to x=60, with contextual units.","Explain why the model should not automatically be extrapolated to x=200."],[["P(x)=−0.1(x−20)(x−80).","Uses 90=a(30)(−30) to obtain a=−0.1."],["The average rate is [P(60)−P(30)]/30=1 hundred dollars per hundred units.","Interprets the rate as about 1 dollar of profit per additional unit over the interval."],["Production 200 is outside the observed or stated operating range, so quadratic extrapolation may be unreliable.","Connects the limitation to model assumptions rather than algebra alone."]]],
  ["modeling-nonperiodic","2","3","Medium","calculator","A tree is 1.8 meters tall when planted and approaches a limiting height of 9.3 meters. After 5 years it is 6.803 meters tall. Use H(t)=L−Ab^t.",["Use the information to determine L, A, and b to three decimals and write the model.","Find the average rate of change from t=0 to t=5, with units.","Explain one reason the model may not accurately predict the height of every individual tree after 40 years."],[["L=9.3, A=7.5, and b≈0.803, so H(t)=9.3−7.5(0.803)^t.","Uses H(0)=1.8 and H(5)=6.803 to determine the parameters."],["The average rate is (6.803−1.8)/5≈1.001 meters per year.","Interprets the result over the first five years."],["Individual growth depends on environmental and biological factors not represented by the fixed model.","Identifies a contextual assumption or source of variability."]]],
  ["modeling-nonperiodic","2","3","Hard","calculator","Water temperature T, in degrees Celsius, is modeled logarithmically by depth x in meters. Measurements are T(1)=18 and T(4)=24. Use T(x)=a+b ln x.",["Use the measurements to determine a and b and write the model.","Find the average rate of change in temperature from x=1 to x=4, with units.","Explain why the model cannot be used for x≤0 and why very large-depth extrapolation may be unreasonable."],[["a=18 and b=6/ln4, so T(x)=18+(6/ln4)ln x.","Uses both measurements in a system for a and b."],["The average rate is (24−18)/(4−1)=2 degrees Celsius per meter.","Interprets the rate over depths 1 through 4 meters."],["The logarithm requires x>0, and the fitted relationship is supported only near the measured depths.","Addresses both the mathematical domain and contextual extrapolation."]]],

  ["modeling-periodic","3","3","Medium","no-calculator","At a pier, water depth has midline 7 meters, amplitude 3 meters, period 12 hours, and a maximum at t=0 hours.",["Give five consecutive key points for one cycle beginning at t=0 and state the midline.","Construct a cosine model d(t) for the depth.","On 0<t<3, state whether d is increasing or decreasing and whether its rate of change is increasing or decreasing."],[["The key points are (0,10),(3,7),(6,4),(9,7),(12,10).","The midline is d=7 and the points support a two-cycle sketch by repetition."],["d(t)=7+3cos((π/6)t).","Uses amplitude 3, vertical shift 7, period 12, and the maximum phase."],["The depth is decreasing and its rate of change is decreasing on 0<t<3.","Uses the first quarter-cycle’s downward, concave-down behavior."]]],
  ["modeling-periodic","3","3","Medium","no-calculator","A Ferris-wheel seat ranges from 4 meters to 24 meters and completes a revolution every 16 seconds. At t=0 the rider is at the minimum height.",["Give five consecutive key points for one cycle and state the midline.","Construct a cosine model h(t) for height.","On 0<t<4, state whether h is increasing or decreasing and whether its rate of change is increasing or decreasing."],[["The key points are (0,4),(4,14),(8,24),(12,14),(16,4).","The midline is h=14 and the points support a two-cycle sketch by repetition."],["h(t)=14−10cos((π/8)t).","Uses amplitude 10, vertical shift 14, period 16, and the minimum phase."],["Height is increasing and its rate of change is increasing on 0<t<4.","Uses the first quarter-cycle’s upward, concave-up behavior."]]],
  ["modeling-periodic","3","3","Hard","no-calculator","Daylight lasts 9.5 hours at t=0 months, 14.5 hours at t=6, and follows a 12-month cycle.",["Give five consecutive key points for one cycle and state the midline.","Construct a cosine model L(t) for daylight hours.","On 3<t<6, state whether L is increasing or decreasing and whether its rate of change is increasing or decreasing."],[["The key points are (0,9.5),(3,12),(6,14.5),(9,12),(12,9.5).","The midline is L=12 and the points support a two-cycle sketch by repetition."],["L(t)=12−2.5cos((π/6)t).","Uses amplitude 2.5, vertical shift 12, period 12, and the minimum phase."],["Daylight is increasing while its rate of change is decreasing on 3<t<6.","Uses the second quarter-cycle’s upward, concave-down behavior."]]],
  ["modeling-periodic","3","3","Medium","no-calculator","A piston oscillates 6 centimeters on each side of equilibrium, has period 0.5 second, and passes equilibrium upward at t=0.",["Give five consecutive key points for one cycle and state the midline.","Construct a sine model s(t) for displacement.","On 1/8<t<1/4, state whether s is increasing or decreasing and whether its rate of change is increasing or decreasing."],[["The key points are (0,0),(1/8,6),(1/4,0),(3/8,−6),(1/2,0).","The midline is s=0 and the points support a two-cycle sketch by repetition."],["s(t)=6sin(4πt).","Uses amplitude 6, period 1/2, and the upward midline phase."],["Displacement is decreasing and its rate of change is decreasing on 1/8<t<1/4.","Uses the second quarter-cycle’s downward, concave-down behavior."]]],
  ["modeling-periodic","3","3","Hard","no-calculator","A beacon’s horizontal coordinate ranges from −5 meters to 5 meters, has period 3 seconds, and is at its maximum at t=1/2 second.",["Give five consecutive key points beginning at the maximum and state the midline.","Construct a cosine model x(t) for the coordinate.","On 1/2<t<5/4, state whether x is increasing or decreasing and whether its rate of change is increasing or decreasing."],[["The key points are (1/2,5),(5/4,0),(2,−5),(11/4,0),(7/2,5).","The midline is x=0 and the points support a two-cycle sketch by repetition."],["x(t)=5cos((2π/3)(t−1/2)).","Uses amplitude 5, period 3, and the stated maximum phase."],["The coordinate is decreasing and its rate of change is decreasing on 1/2<t<5/4.","Uses the first quarter-cycle’s downward, concave-down behavior."]]],

  ["symbolic-manipulations","2","1","Medium","no-calculator","Use exact algebraic methods; show supporting work.",["Solve log₂(x−3)=4.","Solve 2^(x+1)=32.","Rewrite 2^(log₂(x−3)+1) in a form without logarithms, and state the domain."],[["x=19.","Verifies that x−3=16 and x is in the logarithm’s domain."],["x=4.","Uses x+1=5."],["The expression is 2(x−3), with x>3.","Uses inverse-function rules while preserving the original domain."]]],
  ["symbolic-manipulations","2","1","Hard","no-calculator","Use exact algebraic methods; show supporting work.",["Solve 3^(2x)−10·3^x+9=0.","Solve log₃(x)+log₃(x−2)=1.","Rewrite ln((e^(2x)√y)/z³) as a sum and difference of logarithms, where y,z>0."],[["x=0 or x=2.","Substitutes u=3^x, factors (u−1)(u−9), and returns to x."],["x=3.","Solves x(x−2)=3 and rejects x=−1 by the domain."],["The expression is 2x+(1/2)ln y−3ln z.","Applies product, power, and quotient rules correctly."]]],
  ["symbolic-manipulations","3","1","Medium","no-calculator","Angles are measured in radians. Give exact values and supporting work.",["Determine every x in 0≤x<2π satisfying 2sin x=√3.","Find the real number x for which arctan(2x−1)=π/4.","Express (sec x−cos x)/tan x using one trigonometric function, wherever the original is defined."],[["x=π/3 or x=2π/3.","Uses the reference angle and both positive-sine quadrants."],["x=1.","Applies tangent to both sides and solves 2x−1=1."],["The expression simplifies to sin x.","Uses reciprocal, quotient, and Pythagorean identities with valid cancellation."]]],
  ["symbolic-manipulations","3","1","Hard","no-calculator","Each equation is restricted to one full cycle, 0≤x<2π.",["Find the solution set of cos(2x)=sin x.","Find the solution set of tan²x=3.","Convert (1−cos(2x))/sin x to an equivalent single-function expression on its domain."],[["x=π/6, 5π/6, or 3π/2.","Uses 1−2sin²x=sin x and factors."],["x=π/3, 2π/3, 4π/3, or 5π/3.","Solves tan x=±√3 over the full interval."],["The expression is 2sin x.","Uses 1−cos(2x)=2sin²x and cancels sin x where nonzero."]]],
  ["symbolic-manipulations","2","1","Hard","no-calculator","Use exact exponential and logarithmic methods; show supporting work.",["Solve 4^x−5·2^x+4=0.","Solve ln(x+2)−ln x=ln3.","Rewrite log_b((x³√y)/z²) as a sum and difference, where b>0, b≠1, and x,y,z>0."],[["x=0 or x=2.","Substitutes u=2^x and factors (u−1)(u−4)."],["x=1.","Combines logarithms to (x+2)/x=3 and respects x>0."],["The expression is 3log_b x+(1/2)log_b y−2log_b z.","Applies product, power, and quotient rules correctly."]]]
];

const mcqDifficulties = [
  "Medium","Hard","Easy","Hard","Medium","Easy","Medium","Medium","Very Hard","Hard","Very Hard",
  "Easy","Medium","Hard","Medium","Easy","Hard","Very Hard","Very Hard","Hard",
  "Easy","Medium","Hard","Very Hard","Medium","Medium","Easy","Hard","Hard","Very Hard"
];
const frqDifficulties = [
  "Medium","Easy","Hard","Very Hard","Medium","Easy","Medium","Very Hard","Medium","Very Hard",
  "Easy","Hard","Hard","Medium","Very Hard","Easy","Hard","Medium","Hard","Hard"
];
const frqTopics = [
  "1.4","2.3","1.11","2.6","2.11","1.14","2.5","1.14","2.5","2.14",
  "3.7","3.7","3.7","3.5","3.7","2.13","2.13","3.10","3.10","2.13"
];
for (let i=0;i<mcq.length;i++) mcq[i][2]=mcqDifficulties[i];
for (let i=0;i<frq.length;i++) frq[i][3]=frqDifficulties[i];

const unitNode = { "1":"unit-1-polynomial-and-rational-functions", "2":"unit-2-exponential-and-logarithmic-functions", "3":"unit-3-trigonometric-and-polar-functions" };
const stable = value => JSON.stringify(value, Object.keys(value).sort());
const hashItem = item => {
  const copy = structuredClone(item);
  delete copy.provenance.content_sha256;
  return createHash("sha256").update(JSON.stringify(copy)).digest("hex");
};
const base = (id, type, unit, topic, practice, difficulty, archetype) => ({
  schema_version:"1.0.0", package_id:id, content_key:id, content_version:1, difficulty,
  exam_pack_ref:{exam_code:"ap_precalculus",school_year:"2026-27",exam_pack_version:"1.0.0"},
  item_type:type, archetype_ref:{archetype_key:archetype,version:"1.0.0"},
  taxonomy_refs:[
    {scheme_key:"ap-precalculus-2026-27",scheme_version:"1.0.0",node_key:unitNode[unit]},
    {scheme_key:"ap-precalculus-2026-27",scheme_version:"1.0.0",node_key:`topic-${topic}`},
    {scheme_key:"ap-precalculus-2026-27",scheme_version:"1.0.0",node_key:`practice-${practice}`}
  ]
});

const packages = [];
for (let i=0;i<mcq.length;i++) {
  const [topic,practice,difficulty,mode,stem,choices,key,reasoning,...rationales]=mcq[i];
  const id=`apprecalc-mcq-${String(i+21).padStart(3,"0")}`;
  const paired=choices.map((choice,j)=>({choice,rationale:rationales[j],correct:"ABCD"[j]===key}));
  const correct=paired.find(x=>x.correct);
  const distractors=paired.filter(x=>!x.correct);
  const balancedKey="ABCD"[i%4];
  distractors.splice("ABCD".indexOf(balancedKey),0,correct);
  const item={...base(id,"mcq",topic[0],topic,practice,difficulty,"ap-precalculus-mcq"),
    stimuli:[{stimulus_key:"directions",ordinal:1,kind:"text",payload:{text:`${mode==="calculator"?"Calculator use is permitted.":"No calculator is permitted."}`,calculator_mode:mode},source_refs:[SOURCE_REF]}],
    mcq_choices:distractors.map((entry,j)=>({choice_key:"ABCD"[j],choice_text:entry.choice,is_correct:entry.correct,rationale:entry.rationale})),
    canonical_answers:[balancedKey],
    parts:[{part_key:"question",ordinal:1,prompt:`${stem}\n\n${distractors.map((entry,j)=>`${"ABCD"[j]}. ${entry.choice}`).join("\n")}`,stimulus_refs:["directions"],response_modalities:["choice"],points:1,criteria:[{criterion_key:"correct-answer",points:1,description:"Select the unique correct response.",required_evidence:[balancedKey,reasoning],accepted_variants:["Only a displayed choice that is mathematically identical to the keyed response may be treated as equivalent."],insufficient_responses:["An unkeyed choice without a valid ambiguity finding."],contradictions:["A choice or rationale that conflicts with the governing domain, representation, units, or model conditions."],minimum_fix:"Select the keyed response after correcting the first invalid mathematical step.",deterministic_checks:[{check_type:"choice-key",parameters:{correct_key:balancedKey}}]}]}],
    accessibility:{language:"en",screen_reader_review_required:false,accommodation_notes:"All mathematical information is provided in text."},
    review_notes:{expected_reasoning:reasoning,teaching_explanation:reasoning,minimum_fix:"Correct the first invalid algebraic, graphical, numerical, or modeling step, then recompute under the stated conditions.",transfer_candidate:`Create a new Topic ${topic} item with different values, representation, and surface context.`,delayed_retrieval_candidate:`Reassess Topic ${topic} after a delay without reusing this stem or answer choices.`,known_boundary_cases:["Accept only the keyed choice unless another displayed choice is mathematically identical.","Reject the item if a reasonable interpretation makes more than one displayed choice correct."],originality_statement:ORIGINALITY},
    provenance:{source_refs:[SOURCE_REF],fact_pack_version:"2026-07-28",authoring_prompt_version:"CODEX_PRECALCULUS_DIFFICULTY_QA_2026_07_28",generated_by:"codex",generated_at:GENERATED_AT,content_sha256:""}
  };
  item.provenance.content_sha256=hashItem(item); packages.push(item);
}

for (let i=0;i<frq.length;i++) {
  const [task,unit,practice,difficulty,mode,scenario,prompts,answers]=frq[i];
  const id=`apprecalc-frq-${String(i+17).padStart(3,"0")}`;
  const parts=prompts.map((prompt,j)=>({
    part_key:`part-${"abc"[j]}`,ordinal:j+1,label:`(${"abc"[j]})`,prompt,stimulus_refs:["scenario"],response_modalities:["typed-text","typed-math"],points:2,
    criteria:answers[j].map((description,k)=>({
      criterion_key:`part-${"abc"[j]}-criterion-${k+1}`,points:1,description,required_evidence:[description],
      accepted_variants:["Any mathematically equivalent response with the required setup, interpretation, or justification."],
      insufficient_responses:["A bare answer when the criterion requires construction, supporting work, contextual interpretation, domain restrictions, or model limitations."],
      contradictions:["Do not award when the response directly contradicts the required function behavior, domain, units, representation, or contextual conclusion."],
      minimum_fix:`Add or correct the evidence needed to establish: ${description}`,
      deterministic_checks:[{check_type:"criterion-points",parameters:{expected_points:1}}]
    }))
  }));
  const topic=frqTopics[i];
  const item={...base(id,"frq",unit,topic,practice,difficulty,`ap-precalculus-frq-${task}`),frq_form:"long",canonical_answers:[answers.flat().join(" | ")],
    stimuli:[{stimulus_key:"scenario",ordinal:1,kind:"text",payload:{text:scenario,calculator_mode:mode},source_refs:[SOURCE_REF]}],
    parts,
    accessibility:{language:"en",screen_reader_review_required:false,accommodation_notes:"The prompt is complete in text; any graphing work may be described by labeled features during accessibility review."},
    scoring_contract:{total_points:6,part_count:3,points_per_part:2,calculator_mode:mode,carry_forward_rule:"A later criterion may earn when an earlier arithmetic error is carried forward consistently and the later reasoning remains valid.",rounding_rule:"Accept exact values or values correctly rounded to the precision requested.",units_rule:"Units are required when the prompt or criterion asks for contextual interpretation.",ambiguity_rule:"Escalate a valid but unlisted interpretation rather than forcing a score."},
    development_cases:{full_credit:"Provides all six required pieces of mathematical evidence.","partial_credit":"Provides valid work for some independently decidable criteria but omits at least one required conclusion or justification.","no_credit":"Provides no relevant function relationship, model, or symbolic reasoning.","equivalent":"Uses an algebraically or graphically equivalent representation.","contradictory":"States a correct value but pairs it with an incompatible domain, unit, trend, or interpretation.","ambiguous":"Uses notation whose mathematical meaning cannot be determined reliably."},
    review_notes:{expected_reasoning:answers.flat().join(" | "),teaching_explanation:"Connect every conclusion to the applicable function representation, symbolic relationship, or contextual assumption.",minimum_fix:"Repair the earliest missing setup, representation, or justification needed for the next unearned criterion.",transfer_candidate:`Create a new ${task} FRQ for Topic ${topic} with a different function family, data structure, and context.`,delayed_retrieval_candidate:`Reassess Topic ${topic} later with no shared wording, values, or scenario.`,known_boundary_cases:["Award each one-point criterion independently.","Carry-forward arithmetic may earn later reasoning credit when the method remains valid.","Do not award a modeling limitation for a generic statement unrelated to the given context."],originality_statement:ORIGINALITY},
    provenance:{source_refs:[SOURCE_REF],fact_pack_version:"2026-07-28",authoring_prompt_version:"CODEX_PRECALCULUS_DIFFICULTY_QA_2026_07_28",generated_by:"codex",generated_at:GENERATED_AT,content_sha256:""}
  };
  item.provenance.content_sha256=hashItem(item); packages.push(item);
}

await mkdir(OUT,{recursive:true});
for (const item of packages) await writeFile(`${OUT}/${item.package_id}.json`,`${JSON.stringify(item,null,2)}\n`);

const mcqItems=packages.filter(x=>x.item_type==="mcq");
const frqItems=packages.filter(x=>x.item_type==="frq");
let md=`# AP Precalculus Practice Packet\n\nOriginal Cramapple practice aligned to the AP Precalculus Course and Exam Description effective Fall 2026. This is not College Board material.\n\n## Multiple-choice questions\n\n`;
for (const [i,item] of mcqItems.entries()) md+=`${i+1}. *${item.stimuli[0].payload.calculator_mode==="calculator"?"Calculator permitted":"No calculator"}.* ${item.parts[0].prompt}\n\n`;
md+=`## Free-response questions\n\n`;
for (const [i,item] of frqItems.entries()) {
  const task=item.archetype_ref.archetype_key.replace("ap-precalculus-frq-","").split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ");
  md+=`### FRQ ${i+1} — ${task} (${item.stimuli[0].payload.calculator_mode==="calculator"?"calculator":"no calculator"})\n\n${item.stimuli[0].payload.text}\n\n`;
  for (const part of item.parts) md+=`${part.label} ${part.prompt}\n\n`;
}
md+=`## Answer key and scoring guidance\n\n### MCQ key\n\n${mcqItems.map((x,i)=>`${i+1}. ${x.canonical_answers[0]}`).join("\n")}\n\n`;
for (const [i,item] of frqItems.entries()) {
  md+=`### FRQ ${i+1} — 6 points\n\n`;
  for (const part of item.parts) md+=`- ${part.label} ${part.criteria.map(c=>`1 pt: ${c.description}`).join(" | ")}\n`;
  md+="\n";
}
await writeFile(PACKET,md);
console.log(`Wrote ${mcqItems.length} MCQs, ${frqItems.length} FRQs, and ${PACKET}`);
