import { criterion as c, frq, mcq } from "./lib.mjs";

const R = (a, b, d, e) => [a, b, d, e];
const V = ["Equivalent calculus-based reasoning with consistent units earns credit."];

export const apphycm = {
  prefix: "apphycm",
  examCode: "ap_physics_c_mechanics",
  examPackVersionId: "ab92fc0f-7bab-4ea2-a1bc-7f03130ab7a9",
  factPackId: "1rc_z7A4CmhDx1Ya6zJswnKYm2wtOrLsJRK-7qBzDxG0",
  frozenMaxFrq: 16,
  frozenMaxMcq: 20,
  expectedFrq: 18,
  expectedMcq: 22,
  calculusBased: true,
  unitSlugs: {
    1: "unit-1-kinematics",
    2: "unit-2-force-and-translational-dynamics",
    3: "unit-3-work-energy-and-power",
    4: "unit-4-linear-momentum",
    5: "unit-5-torque-and-rotational-dynamics",
    6: "unit-6-energy-and-momentum-of-rotating-systems",
    7: "unit-7-oscillations",
  },
  items: [
    frq(1, "1.5", "Parametric projectile with drag-free motion", "Translation Between Representations", "long",
      "A projectile is launched from the origin with speed v₀ at angle θ above horizontal. Air resistance is negligible.",
      ["Write the velocity and position vectors as functions of time and relate their components to motion graphs.", "Derive the time to return to launch height and horizontal range.", "Determine the radius of curvature at the top of the trajectory using normal acceleration."],
      [
        c("a-velocity", "Gives v(t)=v₀cosθ i+(v₀sinθ-gt) j.", "Obtains velocity from the constant acceleration vector.", "Include both components and the downward g term.", V),
        c("a-position", "Gives r(t)=v₀cosθ t i+(v₀sinθ t-(1/2)gt²) j.", "Integrates velocity with the origin initial condition.", "Apply r(0)=0 to both components.", V),
        c("b-time", "Derives t_f=2v₀sinθ/g for the nonzero return time.", "Sets y(t)=0 and excludes t=0.", "Factor the vertical-position expression before solving.", V),
        c("b-range", "Derives R=v₀²sin(2θ)/g.", "Substitutes t_f into horizontal position and uses the double-angle identity.", "Use the horizontal velocity component.", V),
        c("c-normal", "At the top uses a_n=g and speed v₀cosθ.", "Recognizes acceleration is perpendicular to horizontal velocity there.", "Use the full downward acceleration as normal acceleration.", V),
        c("c-radius", "Obtains curvature radius ρ=v₀²cos²θ/g.", "Uses a_n=v²/ρ.", "Solve the normal-acceleration relation for radius.", V),
      ], "v and r follow constant-acceleration component equations; t_f=2v₀sinθ/g, R=v₀²sin2θ/g, and top-of-flight curvature radius is v₀²cos²θ/g.", "Medium"),

    frq(2, "2.9", "Quadratic-drag terminal speed", "Mathematical Routines", "long",
      "A small object falls vertically from rest through a fluid. Downward is positive and the drag magnitude is cv².",
      ["Write the differential equation and determine terminal speed.", "Solve for speed as a function of time.", "Sketch speed and acceleration versus time and identify their limiting values."],
      [
        c("a-equation", "Writes m dv/dt=mg-cv².", "Correct signs for downward weight and upward drag.", "Use drag opposite the downward velocity.", V),
        c("a-terminal", "Obtains v_t=sqrt(mg/c).", "Sets dv/dt=0 at terminal speed.", "Solve the force balance for positive speed.", V),
        c("b-separate", "Separates variables as dv/[g(1-v²/v_t²)]=dt.", "Reexpresses the equation using v_t.", "Keep the square on the speed ratio.", V),
        c("b-solution", "Obtains v(t)=v_t tanh(gt/v_t).", "Applies v(0)=0 to the separated solution.", "Use the initial condition to remove the integration constant.", V),
        c("c-speed", "Sketches monotonic speed approaching v_t with decreasing slope.", "Correct initial value and horizontal asymptote.", "Show no overshoot of terminal speed.", V),
        c("c-accel", "Sketches acceleration decreasing from g to 0.", "Uses a=g[1-(v/v_t)²].", "Label both endpoint values.", V),
      ], "m dv/dt=mg-cv² gives v_t=sqrt(mg/c) and v(t)=v_t tanh(gt/v_t); speed approaches v_t while acceleration falls from g to zero.", "Hard"),

    frq(2, "2.10", "Conical-pendulum dynamics", "Translation Between Representations", "short",
      "A mass m on a string of length L moves in a horizontal circle with the string at constant angle θ from vertical.",
      ["Draw a free-body diagram and translate it into vertical and radial equations.", "Derive angular speed and period in terms of L, g, and θ."],
      [
        c("a-forces", "Shows only tension along the string and weight downward.", "Correct free-body diagram without a separate centripetal force.", "Treat centripetal force as the radial net force.", V),
        c("a-equations", "Writes Tcosθ=mg and Tsinθ=mω²(Lsinθ).", "Correct vertical balance and radial dynamics.", "Use circle radius Lsinθ.", V),
        c("b-result", "Derives ω=sqrt[g/(Lcosθ)] and period 2πsqrt(Lcosθ/g).", "Eliminates tension and solves consistently.", "Cancel sinθ only after writing the radial equation.", V),
      ], "Tcosθ=mg and Tsinθ=mω²Lsinθ yield ω=sqrt[g/(Lcosθ)] and T_period=2πsqrt(Lcosθ/g).", "Medium"),

    frq(2, "2.6", "Inverse-square force measurement", "Experimental Design and Analysis", "short",
      "A small satellite mock-up is attracted toward a fixed source by a central force believed to have magnitude K/r². Position and acceleration can be measured.",
      ["Design a data analysis that tests the inverse-square model without assuming K.", "State a graph and a criterion that would distinguish the model from a 1/r force."],
      [
        c("a-data", "Measures radial acceleration at several separations while keeping both masses unchanged.", "Relevant independent and dependent variables plus mass control.", "Use separation as the independent variable.", V),
        c("b-graph", "Plots acceleration versus 1/r² and expects a line through the origin.", "Correct linearization of a=K/(mr²).", "Place 1/r² on the horizontal axis.", V),
        c("b-distinguish", "Compares residuals or linear fit with an acceleration-versus-1/r plot.", "Provides a falsifiable comparison between exponents.", "Use the same measured points for both candidate models.", V),
      ], "Measure a(r) and test linearity of a versus 1/r² through the origin; compare with a versus 1/r to discriminate the force law.", "Medium"),

    frq(2, "2.1", "Center of mass under an external force", "Qualitative/Quantitative Translation", "short",
      "Two masses connected by a light spring slide on a frictionless line. A constant external force F is applied only to the first mass.",
      ["Predict the center-of-mass acceleration and explain why internal spring motion does not alter it.", "Describe how the individual accelerations can vary while the prediction remains true."],
      [
        c("a-result", "States a_CM=F/(m₁+m₂).", "Uses total external force divided by total mass.", "Apply Newton's second law to the two-mass system.", V),
        c("a-internal", "Explains that spring forces cancel in the system force sum.", "Correct internal-force cancellation.", "Identify the equal-and-opposite internal pair.", V),
        c("b-individual", "Explains that spring compression changes individual forces/accelerations but their mass-weighted average stays F/(m₁+m₂).", "Distinguishes internal dynamics from center-of-mass motion.", "Relate m₁a₁+m₂a₂ to F.", V),
      ], "The system center of mass has constant acceleration F/(m₁+m₂); internal spring forces change individual accelerations but cancel in the total force.", "Medium"),

    frq(3, "3.2", "Work by a position-dependent force", "Mathematical Routines", "short",
      "A particle moves from x=0 to x=L under F(x)=F₀(1-x²/L²) in the +x direction.",
      ["Calculate the work done by the force.", "If the particle starts from rest with mass m, determine its speed at x=L."],
      [
        c("a-integral", "Evaluates W=∫₀ᴸF₀(1-x²/L²)dx=(2/3)F₀L.", "Correct bounds and antiderivative.", "Integrate both terms over the stated interval.", V),
        c("b-energy", "Uses W=ΔK=(1/2)mv².", "Correct work-energy connection from rest.", "Set initial kinetic energy to zero.", V),
        c("b-speed", "Obtains v=sqrt(4F₀L/(3m)).", "Solves the energy equation correctly.", "Include the factor of two from kinetic energy.", V),
      ], "W=(2/3)F₀L and work-energy gives v=sqrt[4F₀L/(3m)].", "Medium"),

    frq(3, "3.5", "Power from a time-dependent speed", "Translation Between Representations", "short",
      "A motor pulls a mass on a horizontal surface so that v(t)=at² while the resistive force has constant magnitude f.",
      ["Determine the motor's force and instantaneous power as functions of time.", "Sketch power versus time and explain the contributions from acceleration and resistance."],
      [
        c("a-force", "Uses acceleration dv/dt=2at and obtains F_motor=2mat+f.", "Correct force balance along the motion.", "Include the resistive force in addition to ma.", V),
        c("a-power", "Obtains P=(2mat+f)at²=2ma²t³+fat².", "Uses P=Fv with the motor force.", "Multiply the complete motor force by speed.", V),
        c("b-graph", "Sketches nonnegative increasing power with quadratic and cubic contributions and zero at t=0.", "Graph matches the derived expression.", "Show the cubic term dominating at large time.", V),
      ], "F_motor=2mat+f and P=Fv=2ma²t³+fat²; the power starts at zero and the acceleration-related cubic term eventually dominates.", "Medium"),

    frq(3, "3.3", "Potential-well period investigation", "Experimental Design and Analysis", "long",
      "A particle moves near a stable equilibrium x₀ in an unknown smooth potential U(x). Position versus time and static force versus position can be measured.",
      ["Describe how to estimate the effective spring constant near x₀.", "Predict the small-oscillation period and test it for several amplitudes.", "Explain how the data reveal the range where the harmonic approximation fails."],
      [
        c("a-equilibrium", "Locates x₀ where measured force is zero with restoring direction on both sides.", "Correct stable-equilibrium criterion.", "Check the sign of force around the zero.", V),
        c("a-slope", "Fits F versus x near x₀ and uses k_eff=-dF/dx at x₀.", "Correct local force slope.", "Use only the near-equilibrium linear region.", V),
        c("b-period", "Predicts T=2πsqrt(m/k_eff).", "Correct small-oscillation period.", "Use measured particle mass and effective stiffness.", V),
        c("b-test", "Measures periods from repeated position-time cycles for several small amplitudes.", "A replicable period measurement is stated.", "Average over multiple cycles.", V),
        c("c-harmonic", "Expects period approximately independent of amplitude in the harmonic range.", "Correct harmonic-model signature.", "Compare measured periods with the prediction.", V),
        c("c-failure", "Identifies systematic amplitude-dependent period or nonlinear F-x residuals as breakdown evidence.", "A concrete failure criterion is provided.", "Use residuals/trends rather than a single noisy point.", V),
      ], "Estimate k_eff=-dF/dx at the stable equilibrium, predict T=2πsqrt(m/k_eff), and test amplitude independence plus force-linearity residuals.", "Hard"),

    frq(4, "4.2", "Impulse from an exponentially decaying force", "Mathematical Routines", "short",
      "A particle initially has momentum p₀ in the +x direction. It experiences F(t)=-F₀e^{-t/τ} for t≥0.",
      ["Determine its momentum as a function of time and its long-time momentum.", "State the condition under which it reverses direction."],
      [
        c("a-momentum", "Integrates dp/dt=-F₀e^{-t/τ} to obtain p(t)=p₀-F₀τ(1-e^{-t/τ}).", "Correct impulse and initial condition.", "Integrate from 0 to t and add p₀.", V),
        c("a-limit", "Finds p(∞)=p₀-F₀τ.", "Correct exponential limit.", "Let e^{-t/τ} approach zero.", V),
        c("b-reverse", "States reversal occurs if F₀τ>p₀, with the equality case approaching rest.", "Correct signed-momentum criterion.", "Compare total opposing impulse with initial momentum.", V),
      ], "p(t)=p₀-F₀τ(1-e^{-t/τ}); p∞=p₀-F₀τ, so reversal occurs when F₀τ>p₀.", "Medium"),

    frq(4, "4.4", "Two-dimensional elastic collision", "Translation Between Representations", "long",
      "A puck of mass m moving at speed v along +x collides elastically with an identical puck initially at rest. Afterward the first moves at angle θ above +x and the second at angle φ below +x.",
      ["Draw before-and-after momentum vectors and write component conservation equations.", "Use energy conservation to show the outgoing velocity vectors are perpendicular.", "For θ=30°, determine both final speed magnitudes and φ."],
      [
        c("a-vectors", "Shows initial momentum mv along +x and two final momentum vectors whose y components cancel.", "Correct vector geometry.", "Label both final angles and magnitudes.", V),
        c("a-components", "Writes v=v₁cosθ+v₂cosφ and 0=v₁sinθ-v₂sinφ.", "Correct x and y momentum equations after canceling m.", "Keep signs consistent above and below x.", V),
        c("b-energy", "Writes v²=v₁²+v₂² for identical masses in an elastic collision.", "Correct kinetic-energy equation.", "Cancel the common one-half mass factor.", V),
        c("b-dot", "Combines momentum vector addition with energy to obtain v₁·v₂=0.", "Correct perpendicularity proof.", "Square the vector momentum equation and compare with energy.", V),
        c("c-angle", "Finds φ=60°.", "Uses perpendicular outgoing directions with θ=30°.", "Make the angle between final velocities 90°.", V),
        c("c-speeds", "Finds v₁=v cos30° and v₂=v sin30°.", "Correct resolution of initial velocity along perpendicular final directions.", "Use momentum components with φ=60°.", V),
      ], "Momentum and elastic-energy conservation imply v₁·v₂=0. For θ=30°, φ=60°, v₁=vcos30°, and v₂=vsin30°.", "Hard"),

    frq(4, "4.3", "Collision momentum experiment", "Experimental Design and Analysis", "short",
      "Two carts collide on a level track. Motion sensors record both velocities; cart masses are known.",
      ["Describe an analysis that tests momentum conservation and classifies the collision as elastic or inelastic.", "State how uncertainty should be propagated into the comparisons."],
      [
        c("a-momentum", "Calculates total momentum immediately before and after using signed velocities.", "Correct system momentum at matched times.", "Use a consistent positive direction.", V),
        c("a-energy", "Calculates total kinetic energy before and after to classify elasticity.", "Correct independent energy comparison.", "Use one-half mv² for each cart.", V),
        c("b-uncertainty", "Compares differences with combined measurement uncertainty or uncertainty intervals rather than exact equality.", "A defensible uncertainty-aware decision rule.", "Propagate mass and velocity uncertainties into totals.", V),
      ], "Compare signed total momentum and total kinetic energy across the collision with propagated uncertainty; momentum agreement tests isolation and energy agreement classifies elasticity.", "Medium"),

    frq(5, "5.6", "Massive-pulley acceleration", "Mathematical Routines", "long",
      "Masses m₁>m₂ hang from a light cord over a pulley of radius R and constant rotational inertia I. The cord does not slip and axle friction is negligible.",
      ["Write the translational equation for each mass and the rotational equation for the pulley.", "Derive the magnitude of the masses' acceleration and the pulley's angular acceleration.", "Determine both cord tensions and compare them physically."],
      [
        c("a-mass1", "Writes m₁g-T₁=m₁a for the descending mass.", "Correct sign and forces for m₁.", "Use downward as positive for the heavier mass.", V),
        c("a-mass2", "Writes T₂-m₂g=m₂a for the rising mass.", "Correct sign and forces for m₂.", "Use upward as positive for the lighter mass.", V),
        c("a-pulley", "Writes (T₁-T₂)R=Iα with a=αR.", "Correct torque and no-slip relation.", "Keep the two tensions distinct.", V),
        c("b-result", "Derives a=(m₁-m₂)g/[m₁+m₂+I/R²] and α=a/R.", "Correct elimination and effective-inertia term.", "Substitute the tension equations into the torque equation.", V),
        c("c-tensions", "Obtains T₁=m₁(g-a) and T₂=m₂(g+a).", "Correct tension expressions.", "Solve each mass equation after finding a.", V),
        c("c-compare", "States T₁>T₂ because their difference supplies the pulley's angular acceleration.", "Correct physical interpretation of unequal tensions.", "Connect tension difference to nonzero pulley torque.", V),
      ], "The equations give a=(m₁-m₂)g/[m₁+m₂+I/R²], α=a/R, T₁=m₁(g-a), and T₂=m₂(g+a), with T₁>T₂.", "Hard"),

    frq(5, "5.5", "Rotational equilibrium by force sensors", "Experimental Design and Analysis", "short",
      "A rigid beam with unknown center of mass is held horizontal by two vertical force sensors at known positions.",
      ["Describe how force and torque data locate the center of mass.", "Explain how repeating with added known masses can validate the result."],
      [
        c("a-force", "Uses F₁+F₂=Mg to determine or check the beam weight.", "Correct vertical equilibrium.", "Include both sensor forces.", V),
        c("a-torque", "Uses torque balance about one sensor to solve for x_CM from the measured other force.", "Correct lever-arm method.", "Choose a pivot that removes one sensor torque.", V),
        c("b-validation", "Adds known masses at known locations and predicts new sensor readings using the same x_CM.", "A quantitative independent validation is proposed.", "Include added-mass torques in the prediction.", V),
      ], "Apply F₁+F₂=Mg and zero net torque about either support to solve x_CM; validate by predicting sensor readings after placing known masses.", "Medium"),

    frq(6, "6.6", "Circular-orbit energy and escape", "Mathematical Routines", "long",
      "A satellite of mass m is in a circular orbit of radius r around a planet of mass M.",
      ["Derive orbital speed, kinetic energy, potential energy, and total energy.", "Determine the minimum additional energy required for escape from that position.", "If orbital radius doubles, compare speed, period, and total energy."],
      [
        c("a-speed", "Derives v=sqrt(GM/r) from gravity supplying centripetal force.", "Correct circular-orbit dynamics.", "Cancel satellite mass before solving.", V),
        c("a-kinetic", "Finds K=GMm/(2r).", "Substitutes orbital speed into one-half mv².", "Retain the factor one-half.", V),
        c("a-energies", "Finds U=-GMm/r and E=-GMm/(2r).", "Correct signs and total.", "Add K and U.", V),
        c("b-escape", "Finds required added energy GMm/(2r) to reach E=0.", "Correct marginal-escape energy.", "Compare initial negative total energy with zero at infinity.", V),
        c("c-speedperiod", "For 2r, gives v reduced by sqrt2 and period multiplied by 2sqrt2.", "Correct radius scaling for v and T.", "Use v proportional r^-1/2 and T proportional r^3/2.", V),
        c("c-energy", "States total energy is half as negative, E'=-GMm/(4r).", "Correct inverse-radius scaling and sign.", "Do not describe the larger-orbit energy as more negative.", V),
      ], "v=sqrt(GM/r), K=GMm/(2r), U=-GMm/r, E=-GMm/(2r); escape requires GMm/(2r). At 2r, v/√2, T×2√2, and E=-GMm/(4r).", "Medium"),

    frq(6, "6.5", "Rolling body down a ramp", "Translation Between Representations", "short",
      "A rigid body with I=κMR² rolls without slipping from rest through vertical drop h.",
      ["Represent the energy transformation and derive final speed.", "Explain how κ changes translational speed and why static friction does no mechanical work in the ideal model."],
      [
        c("a-energy", "Writes Mgh=(1/2)Mv²+(1/2)Iω² with v=ωR.", "Includes both kinetic-energy forms and no-slip constraint.", "Substitute I=κMR² only after writing energy.", V),
        c("a-speed", "Derives v=sqrt[2gh/(1+κ)].", "Correct algebraic solution.", "Factor one-half Mv²(1+κ).", V),
        c("b-meaning", "States larger κ gives smaller v and explains ideal static friction has zero work because the contact point is instantaneously at rest.", "Correct physical interpretation.", "Distinguish static friction from sliding friction.", V),
      ], "Mgh=(1/2)Mv²(1+κ), so v=sqrt[2gh/(1+κ)]; larger rotational inertia leaves less energy in translation.", "Medium"),

    frq(6, "6.3", "Angular impulse from a torque pulse", "Translation Between Representations", "short",
      "A wheel with constant I starts with angular velocity -ω₀. A torque τ(t)=τ_max sin(πt/T) acts for 0≤t≤T in the positive direction.",
      ["Sketch torque versus time and determine the angular impulse.", "Determine final angular velocity and the condition for reversal."],
      [
        c("a-impulse", "Evaluates ∫₀ᵀτ_max sin(πt/T)dt=2τ_maxT/π.", "Correct area/integral of the torque pulse.", "Use the stated bounds and sine argument.", V),
        c("b-final", "Uses I(ω_f+ω₀)=2τ_maxT/π and obtains ω_f=-ω₀+2τ_maxT/(πI).", "Correct signed angular-momentum change.", "Include the negative initial angular velocity.", V),
        c("b-reverse", "States positive-direction reversal occurs when 2τ_maxT/(πI)>ω₀.", "Correct threshold comparison.", "Compare angular impulse with initial angular-momentum magnitude.", V),
      ], "Angular impulse is 2τ_maxT/π; ω_f=-ω₀+2τ_maxT/(πI), with reversal when the positive change exceeds ω₀.", "Medium"),

    frq(6, "6.2", "Torque-work flywheel test", "Experimental Design and Analysis", "long",
      "A motor applies a measured torque τ(θ) to a flywheel of known I while angular position and angular speed are recorded.",
      ["Design an analysis that tests rotational work-energy.", "Specify numerical and graphical comparisons.", "Identify controls and a diagnostic for unmodeled friction."],
      [
        c("a-work", "Computes motor work over an interval as ∫τ(θ)dθ.", "Correct rotational-work expression and bounds.", "Use torque as a function of angular position.", V),
        c("a-energy", "Computes ΔK_rot=(1/2)I(ω_f²-ω_i²).", "Correct rotational kinetic-energy change.", "Use the same interval endpoints as the work calculation.", V),
        c("b-graph", "Plots cumulative torque work against rotational kinetic-energy change and expects slope one.", "A quantitative work-energy test is specified.", "Compare matched intervals with uncertainty.", V),
        c("b-power", "Optionally checks instantaneous motor power τω against the measured kinetic-energy change rate.", "Correct independent dynamic check.", "Use angular speed, not angular acceleration, in power.", V),
        c("c-controls", "Keeps flywheel configuration/I and motor calibration fixed.", "Relevant mechanical and measurement controls.", "Prevent inertia changes across trials.", V),
        c("c-friction", "Interprets a systematic shortfall of ΔK relative to motor work that grows with angle as frictional loss.", "Specific residual signature and direction.", "Do not label random scatter alone as friction.", V),
      ], "Compare ∫τdθ with (1/2)I(ω_f²-ω_i²), using cumulative-work versus kinetic-energy plots and residuals to detect friction.", "Hard"),

    frq(7, "7.3", "Oscillator phase-space ellipse", "Translation Between Representations", "short",
      "A mass obeys x''+ω²x=0 with amplitude A.",
      ["Starting from energy, derive the relation between velocity and position.", "Sketch the trajectory in v-versus-x phase space and indicate direction for x(0)=A, v(0)=0."],
      [
        c("a-relation", "Derives v²+ω²x²=ω²A².", "Correct energy or solution-based phase relation.", "Use total energy (1/2)mω²A².", V),
        c("b-shape", "Sketches an ellipse with x intercepts ±A and v intercepts ±ωA.", "Correct axes and intercepts.", "Label both positive and negative extremes.", V),
        c("b-direction", "Shows clockwise motion from (A,0) toward negative v.", "Correct initial acceleration and phase-space direction.", "At x=A, acceleration is negative.", V),
      ], "Energy gives v²+ω²x²=ω²A², an ellipse in v-x space traversed clockwise from (A,0).", "Medium"),

    mcq(1, "1.2", "Acceleration from position", "For x(t)=Ct⁴, acceleration is",
      ["4Ct³", "12Ct²", "24Ct", "Ct²"], 1,
      R("Two time derivatives give v=4Ct³ and a=12Ct².",
        "This is the first derivative, velocity, rather than acceleration.",
        "This takes a third derivative and therefore gives jerk.",
        "This reduces the exponent without applying the power-rule coefficients."), "Easy"),
    mcq(1, "1.3", "Velocity-graph displacement", "The signed area under a velocity-versus-time graph equals",
      ["acceleration", "displacement", "force", "kinetic energy"], 1,
      R("The time integral of velocity is the signed change in position.",
        "Acceleration is the slope of velocity versus time, not its area.",
        "Force requires mass times acceleration and is not a velocity-time area.",
        "Kinetic energy depends on speed squared and mass, not graph area."), "Easy"),

    mcq(2, "2.2", "Normal force on an incline", "A block rests on a frictionless incline at angle θ. The normal force is",
      ["mg", "mg sinθ", "mg cosθ", "mg tanθ"], 2,
      R("The normal force balances the perpendicular weight component mg cosθ.",
        "This ignores the incline angle and uses the full weight.",
        "This is the component parallel to the incline, not perpendicular.",
        "This ratio does not represent a component of weight."), "Easy"),
    mcq(2, "2.8", "Spring equilibrium stability", "For U(x)=(1/2)kx² with k>0, x=0 is stable because",
      ["U has a local minimum", "U has a local maximum", "force is constant", "energy is negative"], 0,
      R("The potential has positive curvature and a local minimum at equilibrium.",
        "A local maximum corresponds to unstable equilibrium.",
        "The force -kx varies with position and is not constant.",
        "The chosen potential is nonnegative and energy sign is not the stability criterion."), "Easy"),
    mcq(2, "2.9", "Linear drag time constant", "For m dv/dt=-bv, the characteristic decay time is",
      ["b/m", "m/b", "mb", "1/(mb)"], 1,
      R("The solution e^{-bt/m} has time constant τ=m/b.",
        "This is the decay rate with units of inverse time, not the time constant.",
        "This product does not have time units.",
        "This reciprocal product also has incorrect dimensions."), "Easy"),
    mcq(2, "2.10", "Circular orbit net force", "A particle in uniform circular motion has",
      ["zero acceleration", "constant velocity vector", "inward acceleration v²/r", "outward net force"], 2,
      R("Its changing velocity direction requires inward acceleration v²/r.",
        "This confuses constant speed with zero acceleration.",
        "The velocity vector rotates continuously and is not constant.",
        "The net force is inward; an outward force is not required in an inertial frame."), "Easy"),

    mcq(3, "3.2", "Variable-force work integral", "The work done from x=a to x=b by F(x) is",
      ["∫ₐᵇF(x)dx", "dF/dx", "F(b)-F(a) always", "∫F(t)dt"], 0,
      R("Mechanical work along x is the position integral of force over the path.",
        "This is the force gradient, not accumulated work.",
        "Endpoint force difference does not generally equal work.",
        "A time integral of force is impulse, not work."), "Easy"),
    mcq(3, "3.3", "Force from potential", "For U(x)=Ax³, the force is",
      ["3Ax²", "-3Ax²", "-Ax²", "-3Ax"], 1,
      R("The negative spatial derivative gives F=-dU/dx=-3Ax².",
        "This takes the derivative but omits the required negative sign.",
        "This keeps the negative sign but omits the power-rule factor three.",
        "This reduces the exponent too far and has the wrong dependence."), "Easy"),
    mcq(3, "3.4", "Turning point in a potential", "At a one-dimensional classical turning point with total energy E,",
      ["U=0 always", "U=E and speed is zero", "force must be zero", "kinetic energy is maximum"], 1,
      R("At a turning point K=0, so total energy equals potential energy.",
        "Potential zero depends on reference choice and is not the turning criterion.",
        "Force can be nonzero at a turning point and reverse the motion.",
        "Kinetic energy is zero rather than maximum at the turning point."), "Medium"),
    mcq(3, "3.5", "Instantaneous power", "A force F acts on a particle with velocity v. Instantaneous power is",
      ["F·v", "F×v", "F/v", "dF/dt"], 0,
      R("Instantaneous mechanical power is the scalar product F·v.",
        "A cross product gives a vector and does not represent energy-transfer rate.",
        "Dividing force by speed has incorrect units.",
        "Force-change rate is unrelated to power without motion information."), "Easy"),

    mcq(4, "4.1", "Momentum from a velocity field", "For constant mass m and v(t), net force equals",
      ["m∫vdt", "m dv/dt", "v dm/dt only", "mv²"], 1,
      R("For constant mass, F=dp/dt=m dv/dt.",
        "This gives mass times displacement, not force.",
        "This term applies to mass change and omits ordinary acceleration.",
        "This expression lacks the length scale needed for force."), "Easy"),
    mcq(4, "4.2", "Impulse of a pulse", "A force F₀e^{-t/τ} acts from t=0 to infinity. Its impulse is",
      ["F₀/τ", "F₀τ", "F₀τ²", "zero"], 1,
      R("Integrating the exponential over time gives F₀τ.",
        "This divides by the time scale and has force-per-time units.",
        "This includes an extra time factor and has incorrect impulse units.",
        "A positive decaying force has nonzero area."), "Easy"),
    mcq(4, "4.3", "Center-of-mass momentum", "For a system of total mass M, total momentum is",
      ["M times center-of-mass velocity", "sum of speeds", "always zero", "center-of-mass acceleration"], 0,
      R("By definition p_total=Mv_CM for fixed total mass.",
        "Speeds lack directions and masses, so they cannot form total momentum.",
        "Total momentum is zero only in a special center-of-momentum frame.",
        "Acceleration relates to force, not momentum itself."), "Easy"),
    mcq(4, "4.4", "Perfectly inelastic collision", "In an isolated perfectly inelastic collision,",
      ["momentum and kinetic energy are conserved", "momentum is conserved but kinetic energy is not", "kinetic energy is conserved but momentum is not", "neither total energy nor momentum is conserved"], 1,
      R("Isolation conserves momentum, while sticking converts some kinetic energy to internal energy.",
        "This incorrectly treats sticking as an elastic interaction.",
        "This reverses the two conservation results.",
        "Total energy and momentum remain conserved; only kinetic energy decreases."), "Easy"),

    mcq(5, "5.3", "Torque cross product", "Torque about an origin is",
      ["r·F", "r×F", "F/r", "dF/dt"], 1,
      R("Torque is the vector cross product r×F.",
        "The dot product gives a scalar related to directional projection, not torque.",
        "Dividing force by distance has incorrect torque units.",
        "Force-change rate is not rotational moment."), "Easy"),
    mcq(5, "5.6", "Angular acceleration", "For constant rotational inertia I, net torque is",
      ["Iω", "I dω/dt", "ω/I", "dI/dt only"], 1,
      R("Rotational Newton's second law is τ_net=Iα=I dω/dt.",
        "Iω is angular momentum, not torque.",
        "This quotient has incorrect dimensions and reverses the relation.",
        "Changing inertia alone does not state the full torque relation."), "Easy"),

    mcq(6, "6.1", "Rotational kinetic energy", "A rigid body rotating at angular speed ω has kinetic energy",
      ["Iω", "(1/2)Iω²", "I/ω²", "(1/2)Mω²"], 1,
      R("Summing element kinetic energies gives K=(1/2)Iω².",
        "This is angular momentum, not energy.",
        "This inverses the angular-speed dependence and has wrong units.",
        "Total mass cannot replace rotational inertia without geometry."), "Easy"),
    mcq(6, "6.3", "Angular impulse", "Angular impulse over a time interval equals",
      ["∫τdt", "∫τdθ", "dL/dt", "I/ω"], 0,
      R("The time integral of net torque equals the change in angular momentum.",
        "The angle integral of torque is rotational work.",
        "dL/dt is instantaneous torque, not accumulated angular impulse.",
        "This quotient is neither angular impulse nor dimensionally correct."), "Easy"),
    mcq(6, "6.5", "Rolling constraint", "For rolling without slipping, center-of-mass speed is",
      ["ω/R", "ωR", "R/ω", "independent of ω"], 1,
      R("The no-slip contact constraint is v_CM=ωR.",
        "This divides angular speed by radius and gives incorrect units.",
        "This takes the reciprocal dependence and gives incorrect units.",
        "This ignores the kinematic constraint tying translation to rotation."), "Easy"),
    mcq(6, "6.6", "Orbital period scaling", "For circular orbits about the same mass, doubling radius multiplies period by",
      ["sqrt2", "2", "2sqrt2", "4"], 2,
      R("Kepler scaling T∝r^{3/2} gives 2^{3/2}=2sqrt2.",
        "This uses the orbital-speed square-root factor instead of period scaling.",
        "This assumes period is directly proportional to radius.",
        "This applies a square dependence rather than the three-halves power."), "Medium"),

    mcq(7, "7.2", "SHM angular frequency", "For m x''+kx=0, angular frequency is",
      ["k/m", "sqrt(k/m)", "sqrt(m/k)", "m/k"], 1,
      R("Comparing with x''+ω²x=0 gives ω=sqrt(k/m).",
        "This is ω², not angular frequency.",
        "This is proportional to the period scale and inverts the ratio.",
        "This is the square of the time scale, not angular frequency."), "Easy"),
    mcq(7, "7.4", "Oscillator total energy", "For amplitude A in ideal SHM with spring constant k, total energy is",
      ["kA", "(1/2)kA²", "k/A²", "(1/2)mA²"], 1,
      R("At a turning point all energy is spring potential (1/2)kA².",
        "This omits one power of amplitude and has force-distance mismatch.",
        "This inverses the amplitude dependence and has wrong units.",
        "Mass alone cannot replace spring stiffness in the turning-point energy."), "Easy"),
  ],
};
