import { criterion as c, frq, mcq } from "./lib.mjs";

const R = (a, b, d, e) => [a, b, d, e];
const V = ["Equivalent calculus-based reasoning with consistent units earns credit."];

export const apphycem = {
  prefix: "apphycem",
  examCode: "ap_physics_c_em",
  examPackVersionId: "841a88cc-773c-44e5-97fa-6504f8667689",
  factPackId: "1AwMAtwpUj798kRROyz4O8q9w36YubauEeB7122mrJM0",
  frozenMaxFrq: 16,
  frozenMaxMcq: 20,
  expectedFrq: 18,
  expectedMcq: 22,
  calculusBased: true,
  unitSlugs: {
    8: "unit-8-electric-charges-fields-and-gauss-s-law",
    9: "unit-9-electric-potential",
    10: "unit-10-conductors-and-capacitors",
    11: "unit-11-electric-circuits",
    12: "unit-12-magnetic-fields-and-electromagnetism",
    13: "unit-13-electromagnetic-induction",
  },
  items: [
    frq(8, "8.4", "Field on the axis of a charged ring", "Mathematical Routines", "long",
      "A thin ring of radius R carries total charge Q uniformly. Point P is on its axis a distance z from the center.",
      ["Set up the electric-field integral and explain which components cancel.", "Evaluate the axial electric field.", "Check the result at z=0 and for z much larger than R."],
      [
        c("a-element", "Uses dq=(Q/2πR)R dφ and distance sqrt(R²+z²).", "Correct ring charge element and geometry.", "Relate arc length R dφ to dq.", V),
        c("a-cancel", "Explains transverse components cancel pairwise while axial components add.", "Correct symmetry argument.", "Resolve each dE along the ring axis.", V),
        c("b-integral", "Writes E_z=∫k z dq/(R²+z²)^{3/2}.", "Correct Coulomb element and projection.", "Keep z and the common distance outside the φ integral.", V),
        c("b-result", "Obtains E_z=kQz/(R²+z²)^{3/2}.", "Correct evaluated field and direction sign.", "Integrate dq to Q.", V),
        c("c-center", "Finds E=0 at z=0 by symmetry.", "Correct center limit.", "Substitute z=0 into the field expression.", V),
        c("c-far", "For z≫R obtains E≈kQ/z², the point-charge limit.", "Correct leading far-field behavior.", "Neglect R² relative to z² only in the stated limit.", V),
      ], "Transverse components cancel and E_z=∫kz dq/(R²+z²)^{3/2}=kQz/(R²+z²)^{3/2}; it is zero at center and approaches kQ/z² far away.", "Medium"),

    frq(8, "8.6", "Gaussian surfaces for planar charge", "Translation Between Representations", "short",
      "An infinite nonconducting sheet has uniform surface charge density σ>0.",
      ["Draw a pillbox Gaussian surface and represent the electric-field directions.", "Use Gauss's law to derive the field magnitude on either side and compare with a conducting surface."],
      [
        c("a-diagram", "Shows a pillbox crossing the sheet with equal fields normal and away on both sides.", "Correct surface orientation and symmetry.", "Show flux only through the two flat faces.", V),
        c("b-sheet", "Uses 2EA=σA/ε₀ to obtain E=σ/(2ε₀).", "Correct enclosed charge and two-face flux.", "Do not include flux through the curved side.", V),
        c("b-conductor", "States immediately outside a conductor E=σ/ε₀ because interior field is zero and only one external face contributes to a boundary pillbox.", "Correct factor-of-two comparison and reason.", "Distinguish nonconducting isolated sheet symmetry from conductor boundary conditions.", V),
      ], "A symmetric pillbox gives 2EA=σA/ε₀, so E=σ/(2ε₀) on each side. Just outside a conductor, the boundary field is σ/ε₀.", "Medium"),

    frq(8, "8.5", "Electric-flux probe experiment", "Experimental Design and Analysis", "short",
      "A computer model reports electric-field vectors on a fine grid around a localized charged object. Closed surfaces of adjustable size and shape can be drawn.",
      ["Describe a numerical procedure to test Gauss's law for several surfaces.", "State controls, a convergence check, and the expected result for surfaces enclosing no charge."],
      [
        c("a-sum", "Approximates flux by summing E·n ΔA over small surface elements.", "Correct discrete approximation to the closed-surface flux integral.", "Use outward normals and signed dot products.", V),
        c("b-quality", "Refines surface elements until the flux estimate stabilizes while keeping enclosed charge fixed.", "A numerical convergence test and control are given.", "Compare successive grid refinements.", V),
        c("b-empty", "Predicts net flux approximately zero for any closed surface enclosing zero net charge, even if local E is nonzero.", "Correct Gauss-law result and distinction between field and flux.", "Use enclosed rather than nearby external charge.", V),
      ], "Sum E·nΔA over the closed surface, refine the mesh to convergence, and compare with Q_enclosed/ε₀; zero enclosed charge gives zero net flux.", "Medium"),

    frq(8, "8.4", "Field of a nonuniform line charge", "Qualitative/Quantitative Translation", "long",
      "A rod lies from x=0 to L with linear charge density λ(x)=λ₀x/L. Point P is on the x-axis at x=2L.",
      ["Set up and evaluate the electric field at P.", "Determine total rod charge and compare the exact field with a point-charge estimate at the rod's center.", "Explain the far-distance behavior if P is moved to x=D≫L."],
      [
        c("a-element", "Uses dq=(λ₀x/L)dx and separation 2L-x, with field in +x.", "Correct charge element, distance, and direction.", "Use source coordinate x from 0 to L.", V),
        c("a-integral", "Writes E=(kλ₀/L)∫₀ᴸ x/(2L-x)² dx.", "Correct Coulomb integral and bounds.", "Square the source-to-field distance.", V),
        c("a-result", "Evaluates E=(kλ₀/L)[1-ln2].", "Correct positive exact result.", "Use a substitution such as u=2L-x and retain dimensions.", V),
        c("b-charge", "Finds Q=∫₀ᴸλ dx=λ₀L/2.", "Correct total charge.", "Integrate the nonuniform density.", V),
        c("b-compare", "Constructs a point estimate using Q and an explicitly chosen representative distance and notes it is approximate because P is not far compared with L.", "Reasonable quantitative comparison with limitation.", "Do not claim exact point-charge equivalence at 2L.", V),
        c("c-far", "States E≈kQ/D² in +x for D≫L.", "Correct monopole far-field limit.", "Use total charge and neglect rod size only in the far limit.", V),
      ], "E=(kλ₀/L)∫₀ᴸx/(2L-x)²dx=(kλ₀/L)(1-ln2) in +x; Q=λ₀L/2, and far away the rod behaves as point charge Q.", "Hard"),

    frq(9, "9.2", "Potential of a charged disk", "Mathematical Routines", "long",
      "A thin disk of radius R has uniform surface charge density σ. Point P is on its axis at z>0, with V(∞)=0.",
      ["Build the disk from rings and calculate the potential at P.", "Obtain the axial electric field from the potential.", "Check the limits z≫R and z→0⁺."],
      [
        c("a-ring", "Uses ring charge dq=σ2πr dr and distance sqrt(r²+z²).", "Correct differential ring construction.", "Integrate ring radius from 0 to R.", V),
        c("a-integral", "Writes V=∫₀ᴿ kσ2πr dr/sqrt(r²+z²).", "Correct scalar-potential integral.", "Do not project scalar potential.", V),
        c("a-result", "Obtains V=(σ/2ε₀)(sqrt(R²+z²)-z).", "Correct evaluation for z>0.", "Apply V(∞)=0 consistently.", V),
        c("b-field", "Uses E_z=-dV/dz to get (σ/2ε₀)[1-z/sqrt(R²+z²)].", "Correct sign and derivative.", "Differentiate both square-root and -z terms.", V),
        c("c-far", "Shows V≈k(σπR²)/z for z≫R.", "Correct point-charge limit with total charge.", "Keep the leading term of the square-root expansion.", V),
        c("c-surface", "Finds E_z→σ/(2ε₀) as z→0⁺.", "Correct locally infinite-sheet limit.", "Substitute the one-sided limit into E_z.", V),
      ], "Ring integration gives V=(σ/2ε₀)(sqrt(R²+z²)-z), so E_z=(σ/2ε₀)[1-z/sqrt(R²+z²)], with correct point-charge and sheet limits.", "Hard"),

    frq(9, "9.3", "Charge moving through a potential landscape", "Translation Between Representations", "short",
      "Along x, potential is V(x)=V₀[1-(x/L)²] for |x|≤L. A positive charge q is released from rest at x=0.",
      ["Sketch V(x), U(x), and E_x(x).", "Determine the charge's speed at x=L and describe the equilibrium at x=0."],
      [
        c("a-graphs", "Shows downward parabolas for V and U=qV, and E_x=2V₀x/L² as a line through the origin.", "Correct shapes, relative signs, and field relation.", "Use E_x=-dV/dx.", V),
        c("b-speed", "Uses (1/2)mv²=q[V(0)-V(L)]=qV₀ to obtain v=sqrt(2qV₀/m).", "Correct energy conservation and endpoints.", "Use the potential drop for a positive charge.", V),
        c("b-equilibrium", "Identifies x=0 as unstable because U has a local maximum and a displacement produces force away from zero.", "Correct stability interpretation.", "Use the curvature of U or sign of E around the origin.", V),
      ], "E_x=2V₀x/L²; energy gives v(L)=sqrt(2qV₀/m). Since U=qV has a maximum at x=0, the equilibrium is unstable.", "Medium"),

    frq(9, "9.2", "Potential mapping and field comparison", "Experimental Design and Analysis", "short",
      "A voltage probe maps potential on a conducting sheet between irregular electrodes held at fixed potentials.",
      ["Describe how to obtain the electric-field components from the measured grid.", "Give an uncertainty-aware test that the electrostatic field is conservative."],
      [
        c("a-components", "Uses central finite differences E_x≈-[V(x+Δx)-V(x-Δx)]/(2Δx) and similarly for E_y.", "Correct numerical negative gradients.", "Use symmetric neighboring points where possible.", V),
        c("b-loop", "Approximates ∮E·dl around several closed grid loops and expects results consistent with zero.", "Correct conservative-field test.", "Use signed tangential components around each loop.", V),
        c("b-uncertainty", "Compares loop sums with propagated voltage/spacing uncertainty and refines the grid.", "A quantitative rather than exact-equality decision rule.", "Report whether zero lies within uncertainty.", V),
      ], "Estimate E=-∇V with centered differences; test conservativeness by showing closed-loop sums ∮E·dl are consistent with zero within propagated uncertainty.", "Hard"),

    frq(10, "10.2", "Charge redistribution between spheres", "Qualitative/Quantitative Translation", "short",
      "Conducting spheres of radii R and 2R are far apart, connected briefly by a thin wire, and isolated with total charge Q>0.",
      ["Determine the final charge on each sphere.", "Compare their surface fields and surface charge densities after equilibrium."],
      [
        c("a-potential", "Sets kQ₁/R=kQ₂/(2R), so Q₂=2Q₁.", "Uses equal conductor potentials at equilibrium.", "Combine equal potential with Q₁+Q₂=Q.", V),
        c("a-charges", "Finds Q₁=Q/3 and Q₂=2Q/3.", "Correct charge conservation solution.", "State which charge belongs to which radius.", V),
        c("b-fields", "Finds E₁=kQ/(3R²) and E₂=kQ/(6R²), so the smaller sphere has twice the field and surface charge density.", "Correct surface-field and area comparison.", "Use E=kQ_i/R_i² and σ=Q_i/(4πR_i²).", V),
      ], "Equal potentials give Q_R=Q/3 and Q_2R=2Q/3. The smaller sphere has twice the surface field and twice the surface charge density.", "Medium"),

    frq(10, "10.4", "Dielectric insertion experiment", "Experimental Design and Analysis", "long",
      "A parallel-plate capacitor can be charged, disconnected, and filled with slabs of unknown dielectric. Charge, voltage, plate area, and separation can be measured.",
      ["Design a procedure to determine dielectric constant κ.", "Predict voltage, field, and stored energy after insertion at fixed free charge.", "Describe controls and a check for partial filling or leakage."],
      [
        c("a-baseline", "Measures initial C₀=Q/V₀ for the empty capacitor with known geometry.", "Correct baseline capacitance measurement.", "Disconnect the source before dielectric insertion.", V),
        c("a-kappa", "After full insertion measures V and uses κ=C/C₀=V₀/V at fixed Q.", "Correct fixed-charge relation.", "Verify free charge remains unchanged.", V),
        c("b-voltage", "Predicts V and E decrease by factor κ.", "Uses C=κC₀ and fixed Q.", "Apply E=V/d with unchanged separation.", V),
        c("b-energy", "Predicts stored energy decreases by factor κ.", "Uses U=Q²/(2C) at fixed charge.", "Do not use fixed-voltage energy scaling.", V),
        c("c-controls", "Keeps plate geometry, initial charge, and slab placement fixed and minimizes humidity/leakage.", "Relevant electrical/geometric controls.", "Name at least two controls.", V),
        c("c-check", "Checks Q before/after or repeats with reversed insertion; nonuniform dependence on insertion depth flags partial filling/fringing.", "Concrete leakage/geometry diagnostic.", "Use a measurement that separates material response from lost charge.", V),
      ], "With the source disconnected, κ=V₀/V after full insertion. Voltage, field, and energy each fall by factor κ; verify fixed Q and full geometry.", "Medium"),

    frq(11, "11.1", "Radially varying current density", "Mathematical Routines", "short",
      "A cylindrical wire of radius R carries current density J(r)=J₀(1-r²/R²) in the axial direction.",
      ["Determine total current.", "Determine the radius enclosing half the total current."],
      [
        c("a-current", "Evaluates I=∫₀ᴿJ(r)2πr dr=(π/2)J₀R².", "Correct area element and evaluated integral.", "Integrate over the circular cross-section.", V),
        c("b-enclosed", "Uses I(a)=πJ₀[a²-a⁴/(2R²)] and sets it to I/2.", "Correct partial-current expression and condition.", "Use radius a as the upper integration bound.", V),
        c("b-radius", "Obtains a=R sqrt(1-1/sqrt2), choosing the physical root.", "Correct algebraic solution within 0<a<R.", "Let y=a²/R² and solve y-y²/2=1/4.", V),
      ], "I=(π/2)J₀R². Half is enclosed at a=R√(1-1/√2).", "Hard"),

    frq(11, "11.5", "Two-loop circuit equations", "Translation Between Representations", "long",
      "Two meshes share a resistor R₃. The left mesh has ideal emf ε₁ and resistor R₁; the right has opposing emf ε₂ and resistor R₂. Clockwise mesh currents are i₁ and i₂.",
      ["Draw current directions and write both mesh equations.", "Solve for i₁ and i₂ in matrix form.", "Explain how the shared-branch current and power verify charge and energy conservation."],
      [
        c("a-left", "Writes (R₁+R₃)i₁-R₃i₂=ε₁ with consistent chosen polarities.", "Correct shared-resistor contribution in left loop.", "Use shared current i₁-i₂.", V),
        c("a-right", "Writes -R₃i₁+(R₂+R₃)i₂=-ε₂ for the stated opposing source, or an equivalent fully consistent convention.", "Correct right-loop signs.", "State any alternate source traversal convention.", V),
        c("b-matrix", "Represents the simultaneous equations with the symmetric resistance matrix.", "Correct coefficients and source vector.", "Keep off-diagonal terms -R₃.", V),
        c("b-solution", "Solves with determinant D=R₁R₂+R₁R₃+R₂R₃ and gives algebraically consistent currents.", "Correct simultaneous solution under the stated convention.", "Use Cramer's rule or matrix inversion carefully.", V),
        c("c-junction", "Identifies shared-branch current as i₁-i₂ with signs satisfying junction conservation.", "Correct relation between mesh and branch currents.", "Check current sums at either shared node.", V),
        c("c-power", "States source power equals total resistor dissipation when signed source powers and I²R terms are summed.", "Correct energy-conservation verification.", "Include possible source absorption if a current enters a positive terminal.", V),
      ], "Using clockwise mesh currents: (R₁+R₃)i₁-R₃i₂=ε₁ and -R₃i₁+(R₂+R₃)i₂=-ε₂. Shared current is i₁-i₂; signed source power equals resistor heating.", "Hard"),

    frq(11, "11.3", "Temperature-dependent resistivity", "Experimental Design and Analysis", "short",
      "A metal wire is placed in a temperature-controlled bath. Its voltage and current can be measured at small current.",
      ["Design a procedure to determine the temperature coefficient α in ρ=ρ₀[1+α(T-T₀)].", "State a graph, controls, and a heating diagnostic."],
      [
        c("a-data", "Measures R=V/I at multiple stabilized bath temperatures using low current.", "Correct resistance-temperature dataset.", "Wait for thermal equilibrium at each temperature.", V),
        c("b-graph", "Plots R/R₀-1 versus T-T₀; the slope is α.", "Correct linearization for fixed geometry.", "Measure or define R₀ at T₀.", V),
        c("b-quality", "Keeps wire geometry fixed and checks that reversing/reducing measurement current gives the same R, limiting self-heating.", "Relevant control and diagnostic.", "Use current-dependence as a self-heating check.", V),
      ], "Measure low-current R across stabilized temperatures and plot R/R₀-1 against T-T₀; slope α, with current-reduction checks for self-heating.", "Medium"),

    frq(11, "11.8", "RC discharge differential equation", "Qualitative/Quantitative Translation", "short",
      "A capacitor C initially at charge Q₀ discharges through resistor R.",
      ["Derive charge and current versus time, including signs.", "Explain the meaning of the time constant and compare the energy dissipated in R with initial capacitor energy."],
      [
        c("a-solution", "From q/C+R dq/dt=0 obtains q=Q₀e^{-t/(RC)} and i=dq/dt=-(Q₀/RC)e^{-t/(RC)}.", "Correct differential equation, initial condition, and current sign.", "Define current sign relative to positive capacitor charge.", V),
        c("b-time", "States at t=RC charge is Q₀/e and every additional RC multiplies charge by e^{-1}.", "Correct physical time-constant interpretation.", "Use exponential fraction rather than claiming full discharge.", V),
        c("b-energy", "States total resistor heat equals initial Q₀²/(2C) for an ideal source-free circuit.", "Correct energy conservation over complete discharge.", "Use the initial capacitor energy.", V),
      ], "q=Q₀e^{-t/RC}, i=-(Q₀/RC)e^{-t/RC}; after one RC, q=Q₀/e, and total resistor heat is Q₀²/(2C).", "Medium"),

    frq(12, "12.2", "Velocity selector and mass spectrometer", "Mathematical Routines", "long",
      "Positive ions pass through crossed uniform fields E and B₁, then enter a region with only uniform B₂ perpendicular to their velocity.",
      ["Derive the selected speed for undeflected ions.", "Derive the circular radius in the second region and an expression for mass-to-charge ratio.", "Explain how changing E or B₁ affects which ions pass while changing B₂ affects separation."],
      [
        c("a-forces", "Sets qE=qvB₁ for opposite electric and magnetic forces.", "Correct selector force balance.", "Use mutually perpendicular velocity and magnetic field.", V),
        c("a-speed", "Obtains v=E/B₁ independent of ion mass and charge magnitude.", "Correct selected speed.", "Cancel q only for nonzero charge.", V),
        c("b-radius", "Uses qvB₂=mv²/r to obtain r=mv/(qB₂).", "Correct magnetic circular motion.", "Cancel one factor of v.", V),
        c("b-mq", "Obtains m/q=rB₁B₂/E.", "Correct substitution of selected speed.", "Substitute v=E/B₁ into the radius equation.", V),
        c("c-selector", "States increasing E raises selected speed while increasing B₁ lowers it.", "Correct selector parameter trends.", "Use the ratio E/B₁.", V),
        c("c-analyzer", "States larger B₂ reduces all radii and can change spatial separation according to r∝1/B₂.", "Correct analyzer-field effect.", "Keep selected speed fixed during this comparison.", V),
      ], "Undeflected ions have v=E/B₁. In B₂, r=mv/(qB₂), hence m/q=rB₁B₂/E.", "Medium"),

    frq(12, "12.4", "Toroid from Ampere's law", "Translation Between Representations", "short",
      "An ideal toroid has N tightly wound turns carrying current I, inner radius a, and outer radius b.",
      ["Draw an Amperian circle and derive B(r) for a<r<b.", "State the ideal field for r<a and r>b and explain the approximations."],
      [
        c("a-loop", "Uses a concentric circular Amperian path and symmetry to make B tangent and constant.", "Correct geometry and symmetry.", "Choose radius r within the windings.", V),
        c("a-result", "From B(2πr)=μ₀NI obtains B=μ₀NI/(2πr).", "Correct enclosed current and field.", "Count all N linked turns.", V),
        c("b-regions", "States ideal B≈0 for r<a and r>b because net linked current is zero for appropriate Amperian surfaces, with leakage neglected.", "Correct ideal-region result and approximation.", "Distinguish ideal symmetry from real fringing/leakage.", V),
      ], "For a<r<b, B=μ₀NI/(2πr) tangent to concentric circles; ideal fields in the central hole and outside are approximately zero.", "Medium"),

    frq(12, "12.3", "Magnetic dipole torque test", "Experimental Design and Analysis", "short",
      "A small N-turn coil of known area A carries adjustable current I in a uniform magnetic field B. Its plane angle can be varied and torque measured.",
      ["Design a test of τ=NIAB sinθ, defining θ.", "State a linearized graph, controls, and how to determine B if it is unknown."],
      [
        c("a-procedure", "Measures torque over several angles between the coil's magnetic moment and B while holding N,A,I fixed.", "Correct angle definition and controlled sweep.", "Define θ between the coil normal and field.", V),
        c("b-graph", "Plots τ versus sinθ and expects slope NIAB.", "Correct linearization and slope.", "Use signed torque or magnitudes consistently.", V),
        c("b-field", "Determines B=slope/(NIA) while controlling coil geometry/current and subtracting zero-field torsion torque.", "Correct parameter extraction and systematic control.", "Account for apparatus torque unrelated to B.", V),
      ], "Vary θ between magnetic moment and B, plot torque versus sinθ, and obtain B from slope/(NIA) after background-torque correction.", "Medium"),

    frq(13, "13.2", "Sliding rod motional emf", "Mathematical Routines", "long",
      "A conducting rod of length ℓ slides right at speed v on frictionless rails in uniform magnetic field B into the page. The rails close through resistor R.",
      ["Determine induced emf, current, and current direction.", "Determine magnetic force on the rod and external force required for constant speed.", "Show that external mechanical power equals resistor heating."],
      [
        c("a-emf", "Obtains emf=Bℓv from magnetic force on charges or flux change.", "Correct motional-emf magnitude.", "Use the rod length perpendicular to v and B.", V),
        c("a-current", "Obtains I=Bℓv/R.", "Correct Ohm-law current.", "Use total circuit resistance R.", V),
        c("a-direction", "Gives counterclockwise current, producing field out of the page to oppose increasing into-page flux.", "Correct Lenz-law direction.", "State the rod-current direction consistently.", V),
        c("b-force", "Finds magnetic force magnitude IℓB=B²ℓ²v/R opposite motion.", "Correct force and direction.", "Use the current-carrying rod force.", V),
        c("b-external", "States equal rightward external force is needed for constant speed.", "Correct zero-net-force condition.", "Balance the magnetic drag.", V),
        c("c-power", "Shows F_ext v=B²ℓ²v²/R=I²R.", "Exact mechanical-electrical power equality.", "Substitute the derived current.", V),
      ], "emf=Bℓv, I=Bℓv/R counterclockwise, magnetic drag B²ℓ²v/R, and F_extv=I²R.", "Medium"),

    frq(13, "13.4", "Inductor energy and RL decay", "Qualitative/Quantitative Translation", "short",
      "An inductor L carries steady current I₀. The source is removed and the inductor discharges through resistor R.",
      ["Derive current versus time and interpret the inductor voltage immediately after switching.", "Determine total heat dissipated and explain the inductor's role in current continuity."],
      [
        c("a-current", "From L di/dt+Ri=0 obtains i=I₀e^{-Rt/L}.", "Correct RL differential equation and initial condition.", "Use time constant L/R.", V),
        c("a-voltage", "States the inductor reverses terminal polarity as needed so v_L(0⁺)=-RI₀ under the chosen loop sign, opposing sudden current decrease.", "Correct polarity role and magnitude.", "Apply Kirchhoff's rule at the switching instant.", V),
        c("b-energy", "States total resistor heat equals initial magnetic energy (1/2)LI₀² and current remains continuous at t=0.", "Correct energy and continuity explanation.", "Do not claim current drops instantly to zero.", V),
      ], "i=I₀e^{-Rt/L}; the inductor reverses voltage polarity to maintain current continuity, and its initial (1/2)LI₀² becomes resistor heat.", "Medium"),

    mcq(8, "8.1", "Coulomb-force scaling", "Two point charges remain fixed while their separation triples. The force magnitude becomes",
      ["three times", "one-third", "one-ninth", "one-twenty-seventh"], 2,
      R("Coulomb force varies as 1/r², so tripling r divides force by nine.",
        "This applies direct rather than inverse distance scaling.",
        "This uses inverse-linear scaling and misses the square.",
        "This incorrectly uses an inverse-cube relation."), "Easy"),
    mcq(8, "8.3", "Field of a negative charge", "The electric field due to an isolated negative point charge points",
      ["radially outward", "radially inward", "tangent to circles", "nowhere because potential is negative"], 1,
      R("The field points in the force direction on a positive test charge, toward a negative source.",
        "This is the direction for a positive source charge.",
        "This confuses electric point-charge geometry with magnetic field around a current.",
        "Negative potential does not imply zero electric field."), "Easy"),
    mcq(8, "8.4", "Line-charge element", "For a line charge λ(s), the differential charge element is",
      ["λ ds", "λ dA", "λ dV", "ds/λ"], 0,
      R("Linear density times differential length gives dq=λ ds.",
        "This uses an area element appropriate to surface charge density.",
        "This uses a volume element appropriate to volume charge density.",
        "This inverts the density relation and has incorrect units."), "Easy"),
    mcq(8, "8.5", "Flux through a tilted surface", "Uniform E crosses flat area A whose normal makes angle θ with E. Electric flux is",
      ["EA sinθ", "EA cosθ", "EA/ cosθ", "zero for every θ"], 1,
      R("Flux is the dot product EA cosθ using the surface normal.",
        "This uses the angle with the surface rather than the stated angle with its normal.",
        "This divides by the projection factor instead of multiplying.",
        "Flux is zero only when E is tangent to the surface."), "Easy"),
    mcq(8, "8.6", "Gauss-law external charges", "Charges outside a closed Gaussian surface contribute to",
      ["net enclosed charge", "local field but zero net flux contribution", "neither field nor flux anywhere", "enclosed charge with opposite sign"], 1,
      R("External charges can affect E locally, but their field lines enter and leave with zero net closed-surface flux.",
        "This incorrectly counts external charge as enclosed.",
        "This ignores the electric field from external sources.",
        "This invents an opposite-sign enclosed charge."), "Medium"),

    mcq(9, "9.1", "Potential energy of two charges", "Two positive point charges are brought closer together. Their electric potential energy",
      ["decreases", "increases", "stays zero", "becomes negative"], 1,
      R("For like charges U=kq₁q₂/r is positive and increases as separation decreases.",
        "This reverses the inverse-distance dependence for positive U.",
        "This assumes a zero reference means all separations have zero energy.",
        "Negative potential energy applies to opposite-sign charges."), "Easy"),
    mcq(9, "9.2", "Potential from a point charge", "With V(∞)=0, point-charge potential is",
      ["kq/r", "kq/r²", "kqr", "kr/q"], 0,
      R("Integrating the point-charge field from infinity gives V=kq/r.",
        "This confuses potential with electric-field magnitude.",
        "This makes potential grow with distance instead of approach zero.",
        "This inverts charge dependence and has incorrect units."), "Easy"),
    mcq(9, "9.3", "Energy conservation in electrostatics", "A positive charge moves spontaneously in a static electric field. It tends toward",
      ["higher potential and higher U", "lower potential and lower U", "higher potential and lower U", "unchanged kinetic energy always"], 1,
      R("For q>0, U=qV, so electric force accelerates it toward lower V and lower U.",
        "This sends the charge uphill in potential energy without external work.",
        "For positive charge, higher V means higher, not lower, potential energy.",
        "A potential-energy decrease generally appears as increased kinetic energy."), "Easy"),

    mcq(10, "10.1", "Conductor surface field", "In electrostatic equilibrium, the electric field just outside a conductor is",
      ["tangent to the surface", "normal to the surface", "zero for every charged conductor", "parallel to surface current"], 1,
      R("Any tangential field would move surface charge, so equilibrium field is normal.",
        "This would drive free charges along the surface and violate equilibrium.",
        "Interior field is zero, but exterior normal field can be nonzero.",
        "Electrostatic equilibrium has no sustained surface current."), "Easy"),
    mcq(10, "10.4", "Dielectric at fixed voltage", "A dielectric with κ>1 fully fills a capacitor that remains connected to an ideal battery. Stored energy",
      ["decreases by κ", "is unchanged", "increases by κ", "becomes zero"], 2,
      R("At fixed V, C increases by κ and U=(1/2)CV² increases by κ.",
        "This uses the fixed-charge result instead of the fixed-voltage condition.",
        "This ignores the capacitance increase while voltage is held fixed.",
        "A dielectric does not eliminate field energy while the battery remains connected."), "Medium"),

    mcq(11, "11.1", "Current-density integral", "Total current through a surface is",
      ["∫J·dA", "∫J·dl", "dJ/dt", "J/A"], 0,
      R("Current is the flux of current density through the cross-sectional area.",
        "A line integral does not sum flow through a surface.",
        "Time rate of current density is not total current.",
        "Dividing by area reverses the density-to-total relation."), "Easy"),
    mcq(11, "11.2", "Series current", "In a steady series circuit, current through each element is",
      ["the same", "proportional to resistance", "zero after each resistor", "largest nearest the battery"], 0,
      R("Charge cannot accumulate at ideal series junctions, so one current passes every element.",
        "Voltage drop, not current, scales with resistance in series.",
        "Resistors dissipate energy but do not consume charge current.",
        "Current is not depleted with distance from the source."), "Easy"),
    mcq(11, "11.3", "Wire resistance geometry", "A wire's length doubles and radius doubles with resistivity unchanged. Its resistance becomes",
      ["2R", "R", "R/2", "R/4"], 2,
      R("R=ρL/(πr²); length ×2 and area ×4 give R/2.",
        "This includes length change but ignores the fourfold area increase.",
        "This assumes length and radius effects cancel linearly.",
        "This includes area change but ignores doubled length."), "Medium"),
    mcq(11, "11.4", "Maximum power in a resistor", "For a fixed resistor R connected across ideal voltage V, power is",
      ["V²/R", "VR", "R/V²", "V/R²"], 0,
      R("Using I=V/R in P=IV gives P=V²/R.",
        "This multiplies rather than divides by resistance and has wrong units.",
        "This takes the reciprocal voltage dependence.",
        "This introduces an extra resistance factor in the denominator."), "Easy"),
    mcq(11, "11.6", "Loop-rule origin", "Kirchhoff's loop rule for a steady circuit follows from conservation of",
      ["charge", "energy", "mass", "magnetic flux only"], 1,
      R("The signed potential changes around a closed loop sum to zero by energy conservation.",
        "Charge conservation underlies the junction rule instead.",
        "Mass conservation does not determine circuit voltage changes.",
        "Magnetic flux matters for induced emf, not the general steady loop rule alone."), "Easy"),
    mcq(11, "11.8", "Charging-current initial value", "An uncharged capacitor connects through R to ideal emf ε. Immediately after closing, current is",
      ["0", "ε/R", "εC", "infinite for any R"], 1,
      R("Initially V_C=0, so the full emf appears across R and I=ε/R.",
        "Zero current is the long-time result, not the initial result.",
        "Multiplying emf by capacitance gives charge, not current.",
        "The resistor limits the current to a finite value."), "Easy"),

    mcq(12, "12.1", "Magnetic field divergence", "Gauss's law for magnetism states",
      ["∮B·dA=0", "∮B·dA=μ₀Q", "∮B·dl=0 always", "∇×B=0 everywhere"], 0,
      R("Closed-surface magnetic flux is zero because no magnetic monopoles are observed.",
        "This inserts electric charge into the magnetic flux law.",
        "Magnetic circulation can be nonzero around current.",
        "Magnetic curl is nonzero where current density is present."), "Easy"),
    mcq(12, "12.2", "Magnetic force work", "A static magnetic field acting alone on a point charge does",
      ["positive work", "negative work", "zero work", "work qvB every second"], 2,
      R("Magnetic force is perpendicular to velocity, so F·v=0 and speed is unchanged.",
        "This assumes the perpendicular force has a component along motion.",
        "This assumes the force always opposes motion rather than bends it.",
        "qvB is a force magnitude, not a work rate."), "Easy"),
    mcq(12, "12.4", "Ampere-law enclosed current", "For a long ideal solenoid with n turns per length, interior field is",
      ["μ₀nI", "μ₀I/(2πr)", "nI/μ₀", "zero"], 0,
      R("Ampere's law for an ideal long solenoid gives B=μ₀nI inside.",
        "This is the field around a long straight wire.",
        "This divides by μ₀ and has incorrect units.",
        "The exterior is approximately zero; the interior is not."), "Easy"),

    mcq(13, "13.1", "Magnetic flux", "Uniform B crosses a single loop of area A at angle θ to the area normal. Flux is",
      ["BA sinθ", "BA cosθ", "B/A", "zero for all θ"], 1,
      R("Magnetic flux is B·A=BA cosθ using the area normal.",
        "This uses the complementary angle measured from the plane.",
        "Dividing field by area has incorrect flux units.",
        "Flux vanishes only when the field is parallel to the loop plane."), "Easy"),
    mcq(13, "13.3", "Magnetic braking", "A conducting plate entering a magnetic-field region experiences a force opposing motion because",
      ["eddy currents obey Lenz's law", "charge disappears", "magnetic fields do positive work directly", "resistance becomes zero"], 0,
      R("Induced eddy-current fields oppose the changing flux and create magnetic drag.",
        "Charge is conserved; it circulates rather than disappearing.",
        "Magnetic force redirects charges while mechanical energy becomes heat.",
        "Finite resistance is what dissipates eddy-current energy as heat."), "Medium"),
    mcq(13, "13.4", "Inductor energy", "Energy stored in an ideal inductor carrying current I is",
      ["LI²", "(1/2)LI²", "L/I²", "(1/2)CI²"], 1,
      R("Integrating power Li(di/dt) over time gives U=(1/2)LI².",
        "This omits the factor one-half from building current from zero.",
        "This inverts current dependence and has wrong units.",
        "This substitutes capacitance for inductance."), "Easy"),
  ],
};
