import { criterion as c, frq, mcq } from "./lib.mjs";

const R = (a, b, d, e) => [a, b, d, e];
const V = ["Equivalent algebraically correct reasoning with consistent units earns credit."];

export const apphy2 = {
  prefix: "apphy2",
  examCode: "ap_physics_2",
  examPackVersionId: "f584ab0d-114a-4520-9649-42e3e9a2fd22",
  factPackId: "10jX6Pmtd6vxhg-iqKAPh56UCyjy5l4kLFZC2AOaUo84",
  frozenMaxFrq: 16,
  frozenMaxMcq: 20,
  expectedFrq: 18,
  expectedMcq: 22,
  calculusBased: false,
  unitSlugs: {
    9: "unit-9-thermodynamics",
    10: "unit-10-electric-force-field-and-potential",
    11: "unit-11-electric-circuits",
    12: "unit-12-magnetism-and-electromagnetism",
    13: "unit-13-geometric-optics",
    14: "unit-14-waves-sound-and-physical-optics",
    15: "unit-15-modern-physics",
  },
  items: [
    frq(9, "9.1", "Molecular speed at two temperatures", "Qualitative/Quantitative Translation", "short",
      "Two sealed containers hold the same ideal gas. Container B has four times the absolute temperature of Container A.",
      ["Compare the molecules' root-mean-square speeds and justify the comparison.", "Compare the average molecular kinetic energies and explain why gas amount does not affect either ratio."],
      [
        c("a-speed", "States that the rms speed in B is twice that in A.", "Uses v_rms proportional to the square root of absolute temperature.", "Apply the square root to the temperature ratio of four.", V),
        c("b-energy", "States that average molecular kinetic energy in B is four times that in A.", "Uses average kinetic energy proportional to absolute temperature.", "Use the direct temperature ratio for kinetic energy.", V),
        c("b-amount", "Explains that these are per-molecule quantities set by temperature and molecular mass, which is the same in both samples.", "Correctly distinguishes per-molecule averages from total internal energy.", "State why changing molecule count would not change the ratios.", V),
      ], "v_rms scales as sqrt(T), so B has twice the rms speed; average molecular kinetic energy scales as T, so it is four times as large.", "Medium"),

    frq(9, "9.3", "Calorimeter specific-heat investigation", "Experimental Design and Analysis", "short",
      "A heated metal sample is placed in known-mass water inside an insulated cup. Thermometers and a balance are available.",
      ["Describe the measurements and energy equation needed to determine the metal's specific heat.", "Identify one important assumption and one method for reducing uncertainty."],
      [
        c("a-data", "Measures metal and water masses, both initial temperatures, and the final equilibrium temperature.", "All quantities needed for the calorimetry equation are specified.", "Include separate initial temperatures and the shared final temperature.", V),
        c("a-equation", "Uses m_m c_m(T_f-T_mi)+m_w c_w(T_f-T_wi)=0 and solves for c_m.", "Heat lost and gained have consistent signs.", "Set the net thermal-energy change of metal plus water to zero.", V),
        c("b-quality", "Assumes negligible heat exchange with cup/surroundings and proposes repeated trials or a lid/rapid transfer.", "Names a consequential loss mechanism and a concrete mitigation.", "Connect the uncertainty control to unwanted heat transfer.", V),
      ], "Measure both masses and initial temperatures plus final equilibrium temperature; solve energy balance for c_m while minimizing heat exchange with the surroundings.", "Medium"),

    frq(9, "9.4", "Rectangular thermodynamic cycle", "Translation Between Representations", "long",
      "One mole of ideal gas follows a clockwise rectangular cycle on a P-V diagram: (V₀,P₀) to (V₀,3P₀) to (2V₀,3P₀) to (2V₀,P₀) and back.",
      ["Sketch the cycle with arrows and label where temperature is greatest.", "Determine the net work done by the gas per cycle.", "Determine the net heat added per cycle and explain the sign using the first law."],
      [
        c("a-cycle", "Shows the four stated vertices and clockwise arrows.", "Correct geometry, labels, and direction.", "Place volume horizontally and pressure vertically.", V),
        c("a-temperature", "Identifies (2V₀,3P₀) as the highest-temperature state.", "Uses T proportional to PV for fixed mole number.", "Compare the products PV at the four corners.", V),
        c("b-area", "Finds the enclosed area as (2P₀)(V₀)=2P₀V₀.", "Uses pressure height 3P₀-P₀ and volume width 2V₀-V₀.", "Use the rectangle's differences, not its absolute coordinates.", V),
        c("b-sign", "States that clockwise orientation makes net work by the gas positive.", "Correct sign convention linked to direction.", "Compare expansion pressure with compression pressure.", V),
        c("c-cycle", "States that internal-energy change over a full cycle is zero.", "Recognizes return to the initial thermodynamic state.", "Use internal energy as a state quantity.", V),
        c("c-heat", "Concludes Q_net=W_net=2P₀V₀ is positive.", "Applies the first law consistently over the cycle.", "Set ΔU_cycle=0 before relating heat and work.", V),
      ], "The highest temperature is at (2V₀,3P₀). Clockwise enclosed area gives W_net=2P₀V₀; since ΔU_cycle=0, Q_net=2P₀V₀.", "Hard"),

    frq(10, "10.6", "Capacitor plate separation", "Qualitative/Quantitative Translation", "short",
      "A charged parallel-plate capacitor is disconnected from its battery. Its plate separation is then doubled while charge remains fixed.",
      ["Predict how capacitance, voltage, electric field, and stored energy change.", "Explain which predictions would differ if the battery remained connected."],
      [
        c("a-fixedq", "States C halves, V doubles, E remains approximately constant, and U doubles.", "Uses C=εA/d, V=Q/C, E=V/d, and U=Q²/(2C).", "Track the fixed charge through all four relations.", V),
        c("b-connected", "States that with the battery connected V would remain fixed and charge would halve.", "Correctly changes the controlled quantity from Q to V.", "Let charge adjust through Q=CV.", V),
        c("b-energy", "States that connected-case energy would halve and field would halve.", "Uses U=(1/2)CV² and E=V/d with fixed V.", "Recompute energy and field under the fixed-voltage condition.", V),
      ], "Disconnected: C→C/2, V→2V, E unchanged, U→2U. Connected: V fixed, Q→Q/2, E→E/2, U→U/2.", "Hard"),

    frq(10, "10.3", "Electric-field mapping with a probe", "Experimental Design and Analysis", "short",
      "Two conducting shapes are held at fixed different potentials on conductive paper. A voltmeter probe can sample locations.",
      ["Describe how to map equipotential lines and infer the electric-field direction and relative magnitude.", "Identify one control and one measurement practice that improves the map."],
      [
        c("a-map", "Locates multiple points with the same measured potential and connects them into equipotential lines.", "A workable equipotential mapping procedure is given.", "Use several points for each selected voltage.", V),
        c("a-field", "Draws electric field perpendicular to equipotentials from high to low potential, stronger where lines are closer.", "Correct direction and spacing interpretation.", "Relate potential change per distance to field magnitude.", V),
        c("b-quality", "Keeps electrode voltages fixed and samples a regular fine grid or repeats readings.", "A relevant control and precision practice are stated.", "Control the source and improve spatial sampling.", V),
      ], "Map equal-voltage points, then draw E perpendicular from high to low potential; closer equipotential spacing means stronger field.", "Medium"),

    frq(10, "10.7", "Charged-particle energy diagram", "Translation Between Representations", "long",
      "A proton starts from rest at electric potential 800 V and moves to a region at 200 V. Neglect gravity.",
      ["Represent the changes in electric potential energy and kinetic energy with an energy bar chart.", "Calculate the proton's kinetic energy in electron-volts and joules.", "Determine its speed and describe how the answers change for an electron released through the same potential difference in the physically accelerating direction."],
      [
        c("a-bars", "Shows a 600 eV decrease in proton electric potential energy and equal kinetic-energy increase.", "Energy conservation and correct sign for positive charge.", "Use ΔU=qΔV for the proton.", V),
        c("b-ev", "Calculates proton kinetic energy as 600 eV.", "Uses the 600 V potential drop for one elementary charge.", "Convert volts to electron-volts for a proton.", V),
        c("b-joule", "Converts 600 eV to 9.61×10⁻¹⁷ J.", "Uses 1 eV=1.602×10⁻¹⁹ J.", "Multiply, rather than divide, by the joule-per-eV conversion.", V),
        c("c-speed", "Calculates proton speed about 3.39×10⁵ m/s.", "Uses K=(1/2)mv² with proton mass.", "Solve the kinetic-energy relation with SI units.", V),
        c("c-electron-energy", "States an electron gains the same 600 eV when accelerated through a 600 V magnitude difference.", "Uses energy magnitude |qΔV|.", "Choose the direction that lowers the electron's potential energy.", V),
        c("c-electron-speed", "States the electron's speed is greater because its mass is much smaller.", "Correct mass dependence at equal kinetic energy.", "Compare speeds using v proportional to 1/sqrt(m).", V),
      ], "The proton loses 600 eV of electric potential energy and gains 600 eV=9.61×10⁻¹⁷ J, giving v≈3.39×10⁵ m/s. An electron gains the same energy magnitude but moves faster.", "Medium"),

    frq(11, "11.5", "Bridge-circuit current analysis", "Mathematical Routines", "long",
      "A 12 V ideal battery supplies two parallel branches. Branch 1 contains 4 Ω and 8 Ω in series; Branch 2 contains 6 Ω and 6 Ω in series.",
      ["Determine the equivalent resistance and total current.", "Determine the current and power in each resistor.", "Explain how the junction and loop rules are satisfied."],
      [
        c("a-branches", "Finds each branch resistance as 12 Ω.", "Correct series combinations.", "Add resistances within each branch.", V),
        c("a-equivalent", "Finds two 12 Ω branches in parallel give 6 Ω and total current 2 A.", "Correct parallel equivalent and Ohm-law current.", "Combine branches before using the battery voltage.", V),
        c("b-current", "Finds 1 A in each branch and therefore in each series resistor.", "Uses equal branch voltage and series-current continuity.", "Divide 12 V by each 12 Ω branch.", V),
        c("b-power1", "Finds powers 4 W and 8 W in the 4 Ω and 8 Ω resistors.", "Uses P=I²R with 1 A.", "Compute power separately for each resistance.", V),
        c("b-power2", "Finds 6 W in each 6 Ω resistor.", "Correct power for both identical branch-2 elements.", "Use the 1 A branch current.", V),
        c("c-rules", "Shows 2 A splits into 1 A+1 A and each branch voltage drop totals 12 V.", "Explicit junction and loop checks.", "Verify both current conservation and voltage sums.", V),
      ], "Each branch is 12 Ω; together they give 6 Ω and 2 A total. Each branch carries 1 A; powers are 4 W, 8 W, 6 W, and 6 W.", "Medium"),

    frq(11, "11.3", "Wire resistivity experiment", "Experimental Design and Analysis", "short",
      "Several wires of the same material but different measured lengths and diameters are available with a low-voltage source, ammeter, and voltmeter.",
      ["Describe how to determine the material's resistivity.", "State a graph that linearizes the measurements and identify two controls."],
      [
        c("a-resistance", "Measures V and I for each wire and calculates R=V/I while avoiding substantial heating.", "A feasible resistance measurement is specified.", "Measure both voltage across and current through each wire.", V),
        c("b-graph", "Plots R against L/A; the slope is resistivity.", "Uses R=ρL/A with correct axes and slope meaning.", "Compute cross-sectional area from diameter.", V),
        c("b-controls", "Keeps material and temperature fixed, or explicitly controls source current to limit heating.", "Two variables that affect resistance are controlled.", "Name material and temperature as controls.", V),
      ], "Measure R=V/I, calculate L/A, and use the slope of R versus L/A as resistivity while controlling material and temperature.", "Medium"),

    frq(11, "11.8", "RC charging at one time constant", "Qualitative/Quantitative Translation", "short",
      "An initially uncharged capacitor charges through a resistor from an ideal battery. At t=RC it has reached about 63% of its final charge.",
      ["Compare capacitor voltage, resistor voltage, and current at t=0, t=RC, and long time.", "Explain the energy destination as charging proceeds."],
      [
        c("a-values", "States V_C changes 0→0.63ε→ε, V_R changes ε→0.37ε→0, and current changes ε/R→0.37ε/R→0.", "Correct exponential charging benchmarks.", "Use loop voltage at each stated time.", V),
        c("a-trends", "Explains that capacitor voltage rises while resistor voltage and current fall.", "Qualitative trends agree with the values.", "Connect current to the shrinking resistor voltage.", V),
        c("b-energy", "Explains that the battery supplies energy, half ultimately stored in the ideal capacitor and half dissipated thermally in R.", "Correct ideal RC energy accounting.", "Distinguish stored electric energy from resistor heating.", V),
      ], "At 0, RC, and long time: V_C=0,0.63ε,ε; V_R=ε,0.37ε,0; I=ε/R,0.37ε/R,0. Battery energy becomes capacitor energy and resistor heat.", "Hard"),

    frq(12, "12.3", "Force between parallel wires", "Mathematical Routines", "short",
      "Two long parallel wires 0.20 m apart carry currents 5.0 A and 8.0 A in the same direction. Consider a 1.5 m segment and use μ₀=4π×10⁻⁷ T·m/A.",
      ["Determine the magnetic field of the first wire at the second and the force on the segment.", "State the force direction and how it changes if one current reverses."],
      [
        c("a-field", "Calculates B=μ₀I₁/(2πd)=5.0×10⁻⁶ T.", "Correct straight-wire field and substitution.", "Use the 0.20 m wire separation.", V),
        c("a-force", "Calculates F=I₂LB=6.0×10⁻⁵ N.", "Correct force magnitude on the 1.5 m segment.", "Multiply field by the second current and segment length.", V),
        c("b-direction", "States same-direction currents attract; reversing one current makes the force repulsive with unchanged magnitude.", "Correct right-hand-rule comparison.", "Change direction, not the absolute current values.", V),
      ], "B₁=5.0×10⁻⁶ T and F=I₂LB=6.0×10⁻⁵ N. Same-direction currents attract; reversing one makes them repel.", "Medium"),

    frq(12, "12.4", "Coil induction investigation", "Experimental Design and Analysis", "long",
      "A bar magnet moves along the axis of a coil connected to a voltage sensor. The magnet's speed can be controlled.",
      ["Design a procedure to test how peak induced emf depends on magnet speed.", "Identify variables, controls, and a graph.", "Predict the voltage trace when the magnet enters and leaves the coil and explain its signs."],
      [
        c("a-procedure", "Moves the same magnet through the same coil at several measured speeds and records peak emf.", "A repeatable speed-emf test is specified.", "Measure speed and voltage for each pass.", V),
        c("b-variables", "Uses magnet speed as independent variable and peak emf magnitude as dependent variable.", "Variables are correctly assigned.", "Do not use time as the independent variable for the across-trial test.", V),
        c("b-controls", "Keeps magnet orientation/path, coil turns/area, and closest approach fixed.", "Relevant flux factors are controlled.", "Name at least two fixed geometry/source properties.", V),
        c("b-graph", "Plots peak |emf| versus speed and expects an approximately linear trend over a controlled range.", "Graph tests the flux-change-rate prediction.", "Use magnitude for the speed-dependence comparison.", V),
        c("c-pulses", "Predicts opposite-sign voltage pulses for entering and leaving.", "Recognizes opposite signs of magnetic-flux change.", "Show the trace returning near zero between/after events.", V),
        c("c-lenz", "Explains each sign using induced current opposing the corresponding flux change.", "Applies Lenz's law to both motions.", "Relate sign to change in flux, not merely magnet polarity.", V),
      ], "Hold magnet/coil geometry fixed, vary measured speed, and plot peak |emf| versus speed. Entry and exit produce opposite-sign pulses because the flux changes have opposite signs.", "Medium"),

    frq(13, "13.2", "Concave-mirror ray diagram", "Translation Between Representations", "short",
      "An object is placed between the focal point F and center of curvature C of a concave mirror.",
      ["Draw two principal rays and locate the image.", "State the image's orientation, relative size, and whether it is real or virtual."],
      [
        c("a-rays", "Draws a parallel ray reflecting through F and a ray through C reflecting back on itself.", "Two valid principal rays are shown.", "Apply the reflection rules at the mirror surface.", V),
        c("a-location", "Places the ray intersection beyond C in front of the mirror.", "Correct image location for F<d_o<C.", "Extend reflected rays to their actual intersection.", V),
        c("b-properties", "States that the image is real, inverted, and enlarged.", "All three properties match the ray diagram.", "Use actual reflected-ray convergence to classify the image.", V),
      ], "The reflected rays converge beyond C, producing a real, inverted, enlarged image.", "Medium"),

    frq(13, "13.4", "Unknown-lens focal length", "Experimental Design and Analysis", "short",
      "An unknown converging lens, illuminated object, screen, and meterstick are available.",
      ["Describe a procedure to determine focal length using several object positions.", "State a graph whose slope/intercept can be used and one uncertainty precaution."],
      [
        c("a-procedure", "For several object distances greater than f, focuses a sharp real image and measures d_o and d_i from the lens center.", "Multiple valid object-image pairs are collected.", "Measure from the lens's optical center.", V),
        c("b-graph", "Uses 1/d_i=1/f-1/d_o, plotting 1/d_i versus 1/d_o with intercept 1/f and slope -1.", "Correct linear form and parameter extraction.", "State both axes and how f comes from the intercept.", V),
        c("b-quality", "Repeats focus judgments or uses distant-object focusing as an independent check.", "A concrete precision/check method is provided.", "Reduce subjective screen-focus uncertainty.", V),
      ], "Measure focused d_o,d_i pairs and plot 1/d_i versus 1/d_o; the intercept is 1/f and expected slope is -1.", "Medium"),

    frq(14, "14.5", "Doppler shift from an approaching source", "Mathematical Routines", "short",
      "A stationary observer hears a 680 Hz siren approaching at 25 m/s through still air where sound speed is 340 m/s.",
      ["Calculate the observed frequency while the source approaches.", "Predict the frequency immediately after it passes and explain the discontinuous change in the idealized model."],
      [
        c("a-formula", "Uses f'=f v/(v-v_s) for an approaching source.", "Correct source-motion Doppler relation and sign.", "Subtract source speed from wave speed in the denominator.", V),
        c("a-value", "Calculates f'≈734 Hz.", "Correct numerical evaluation.", "Evaluate 680×340/315.", V),
        c("b-after", "Uses f'=f v/(v+v_s)≈630 Hz after passing and explains the radial velocity changes from approach to recession.", "Correct receding frequency and physical explanation.", "Change the denominator sign after passage.", V),
      ], "Approaching: f'=680(340)/(340-25)≈734 Hz. Receding: f'=680(340)/(340+25)≈630 Hz.", "Medium"),

    frq(14, "14.3", "Polarizer transmission test", "Experimental Design and Analysis", "short",
      "A light sensor is placed behind two ideal linear polarizers. The first polarizer is fixed and the second can rotate.",
      ["Describe measurements that test the angular dependence of transmitted intensity.", "State the graph or comparison expected from the model and one control."],
      [
        c("a-procedure", "Measures transmitted intensity for multiple relative angles from 0° to 90°.", "A sufficient angular sweep is described.", "Record background-corrected intensity at several angles.", V),
        c("b-model", "Tests I=I_max cos²θ by plotting I versus cos²θ and expecting a straight line through the origin.", "Correct Malus-law linearization.", "Use relative polarizer angle, not absolute laboratory angle.", V),
        c("b-control", "Keeps incident source intensity, sensor position, and polarizer spacing fixed.", "At least one consequential control is identified.", "Prevent source/geometry changes from mimicking angular dependence.", V),
      ], "Measure intensity versus relative angle and plot I against cos²θ; ideal data form a line through the origin when source and geometry are controlled.", "Medium"),

    frq(15, "15.2", "Hydrogen transition spectrum", "Translation Between Representations", "long",
      "A hydrogen atom transitions from n=4 to n=2. Use E_n=-13.6 eV/n², h=4.14×10⁻¹⁵ eV·s, and c=3.00×10⁸ m/s.",
      ["Represent the transition on an energy-level diagram.", "Determine the emitted photon energy, frequency, and wavelength.", "Explain how absorption for the reverse transition differs."],
      [
        c("a-diagram", "Shows a downward arrow from n=4 to n=2 on correctly ordered levels.", "Correct direction and labeled levels.", "Indicate photon emission for a downward transition.", V),
        c("b-levels", "Calculates E₄=-0.850 eV and E₂=-3.40 eV.", "Correct level energies.", "Keep the negative bound-state signs.", V),
        c("b-photon", "Finds photon energy 2.55 eV.", "Uses magnitude of E_final-E_initial.", "Report positive emitted-photon energy.", V),
        c("b-frequency", "Calculates f≈6.16×10¹⁴ Hz.", "Uses f=E/h with eV-consistent h.", "Divide 2.55 eV by the given eV·s constant.", V),
        c("b-wavelength", "Calculates λ≈4.87×10⁻⁷ m or 487 nm.", "Uses λ=c/f.", "Convert meters to nanometers consistently if used.", V),
        c("c-reverse", "States the reverse requires absorption of a photon with exactly the same 2.55 eV energy.", "Correct discrete-level absorption condition.", "Do not claim any energy above threshold produces the same bound transition.", V),
      ], "E₄=-0.850 eV and E₂=-3.40 eV, so emission is 2.55 eV with f≈6.16×10¹⁴ Hz and λ≈487 nm; reverse absorption requires the same photon energy.", "Medium"),

    frq(15, "15.7", "Radioactive sample activity", "Mathematical Routines", "short",
      "A radioactive isotope has a half-life of 6.0 h. A sample initially contains 8.0×10¹² undecayed nuclei.",
      ["Determine the number remaining and the fraction decayed after 18 h.", "If each decay releases 0.80 MeV, determine total released energy in joules using 1 eV=1.602×10⁻¹⁹ J."],
      [
        c("a-remaining", "After three half-lives, calculates N=N₀/8=1.0×10¹².", "Correct repeated-halving model.", "Count 18 h as three half-life intervals.", V),
        c("a-fraction", "Finds 7/8 or 87.5% decayed.", "Subtracts remaining fraction from one.", "Report the fraction that decayed, not the fraction remaining.", V),
        c("b-energy", "Uses 7.0×10¹² decays and obtains about 0.897 J.", "Multiplies decays by 0.80 MeV and converts eV to joules.", "Convert megaelectron-volts to electron-volts before the joule conversion.", V),
      ], "After 18 h, 1.0×10¹² remain and 7/8 have decayed. Energy=(7.0×10¹²)(0.80×10⁶ eV)(1.602×10⁻¹⁹ J/eV)≈0.897 J.", "Medium"),

    frq(15, "15.5", "Photoelectric stopping-potential graph", "Experimental Design and Analysis", "short",
      "A photocell with unknown cathode work function is illuminated by several known light frequencies above threshold. A variable reverse voltage measures stopping potential.",
      ["Describe how to measure a stopping potential for each frequency.", "State the graph that determines Planck's constant and work function, including slope and intercept."],
      [
        c("a-procedure", "For each frequency, increases reverse voltage until photocurrent just reaches zero and records that stopping potential.", "Correct operational definition of stopping potential.", "Use the zero-current threshold, not the open-circuit voltage.", V),
        c("b-graph", "Plots stopping potential V_s versus frequency f and expects a straight line.", "Correct variables for eV_s=hf-φ.", "Place frequency on the horizontal axis.", V),
        c("b-parameters", "Identifies slope h/e and vertical intercept -φ/e.", "Correct extraction of both requested constants.", "Use electron charge to convert slope/intercept.", V),
      ], "Measure the reverse voltage that reduces photocurrent to zero. A plot of V_s versus f has slope h/e and intercept -φ/e.", "Medium"),

    mcq(9, "9.2", "Ideal-gas molecule count", "At fixed temperature and volume, doubling the number of ideal-gas molecules makes pressure",
      ["half as large", "unchanged", "twice as large", "four times as large"], 2,
      R("From PV=NkT, pressure is directly proportional to molecule count at fixed V and T.",
        "This applies an inverse relation between pressure and molecule count.",
        "This ignores the added molecular collisions with the container walls.",
        "This incorrectly squares the factor by which molecule count changes."), "Easy"),
    mcq(9, "9.5", "Thermal conduction rate", "Two rods have equal dimensions and temperature difference. Rod A has twice Rod B's thermal conductivity. The steady conduction rate through A is",
      ["half as large", "the same", "twice as large", "four times as large"], 2,
      R("Conduction rate kAΔT/L is directly proportional to thermal conductivity k.",
        "This reverses the conductivity dependence, treating better conduction as slower transfer.",
        "This ignores the only property that differs between the rods.",
        "This squares the conductivity factor even though the relation is linear."), "Easy"),
    mcq(9, "9.6", "Entropy of spontaneous mixing", "Two different ideal gases initially separated at the same temperature mix in an insulated container. The total entropy",
      ["decreases", "stays constant", "increases", "becomes zero"], 2,
      R("Spontaneous mixing increases the number of accessible arrangements and therefore total entropy.",
        "This reverses the second-law direction for spontaneous mixing.",
        "This treats insulation as preventing entropy change rather than preventing energy transfer.",
        "This confuses an arbitrary entropy reference with the positive mixing change."), "Medium"),

    mcq(10, "10.2", "Charge sharing by conductors", "Identical isolated conducting spheres carry charges +6Q and 0. They touch and separate. Each sphere then has charge",
      ["+Q", "+2Q", "+3Q", "+6Q"], 2,
      R("Total charge +6Q is conserved and divides equally between identical spheres, giving +3Q each.",
        "This divides the total charge among six imagined portions instead of two spheres.",
        "This loses +2Q of charge and violates conservation.",
        "This leaves all charge on the original sphere despite contact between identical conductors."), "Easy"),
    mcq(10, "10.5", "Potential and electric field", "At a point where electric potential is zero, the electric field",
      ["must be zero", "must be infinite", "may be nonzero", "must point upward"], 2,
      R("Potential value can be zero while its spatial change, and hence electric field, is nonzero.",
        "This confuses a potential reference value with zero potential change.",
        "This assumes zero potential produces a singular field without physical basis.",
        "This assigns a direction from no geometric information."), "Medium"),
    mcq(10, "10.7", "Charge accelerated through voltage", "An electron accelerated from rest through a potential difference magnitude ΔV gains kinetic energy",
      ["eΔV", "ΔV/e", "e/ΔV", "eΔV²"], 0,
      R("The kinetic-energy gain magnitude is |qΔV|=eΔV.",
        "This divides voltage by charge, producing neither energy units nor the correct dependence.",
        "This inverts the voltage dependence and gives incorrect units.",
        "This incorrectly makes energy quadratic rather than linear in potential difference."), "Easy"),

    mcq(11, "11.4", "Resistor power at doubled voltage", "The voltage across a fixed resistor is doubled. Its power dissipation becomes",
      ["half", "twice", "four times", "unchanged"], 2,
      R("For fixed R, P=V²/R, so doubling voltage multiplies power by four.",
        "This applies an inverse voltage dependence not present in resistor power.",
        "This uses P proportional to V and misses the square.",
        "This ignores the increased current and voltage across the resistor."), "Easy"),
    mcq(11, "11.6", "Kirchhoff loop sign", "Traversing an ideal battery from its negative terminal to its positive terminal in a loop equation contributes",
      ["+emf", "-emf", "zero", "emf squared"], 0,
      R("Moving from negative to positive terminal is a potential rise of +emf.",
        "This assigns the sign for traversing from positive to negative terminal.",
        "This ignores the battery's nonzero potential change.",
        "This squares a voltage despite Kirchhoff's rule summing potential changes."), "Easy"),
    mcq(11, "11.7", "Junction current", "Currents 2.0 A and 3.5 A enter a junction. If one current leaves, its magnitude is",
      ["1.5 A", "2.75 A", "5.5 A", "7.0 A"], 2,
      R("Charge conservation requires outgoing current 2.0+3.5=5.5 A.",
        "This subtracts entering currents rather than summing them.",
        "This averages the entering currents, which does not conserve charge flow.",
        "This doubles one entering current without applying the junction rule."), "Easy"),
    mcq(11, "11.8", "RC long-time behavior", "A capacitor in series with a resistor has been connected to a DC battery for a very long time. The circuit current is",
      ["battery voltage divided by R", "zero", "infinite", "set only by C"], 1,
      R("At long time the capacitor is fully charged and behaves as an open circuit, so current is zero.",
        "This describes the instant just after connecting an initially uncharged capacitor.",
        "This treats the capacitor as a zero-resistance short at steady state.",
        "This ignores that capacitance affects the transient time, not the final DC current."), "Easy"),

    mcq(12, "12.1", "Magnetic-field direction around wire", "A long straight wire carries current upward. At a point directly east of the wire, the magnetic field points",
      ["north", "south", "into the page", "out of the page"], 2,
      R("The right-hand rule with thumb upward gives field into the page on the wire's east side.",
        "This points along a horizontal compass direction rather than tangent to the circular field.",
        "This reverses the tangential direction given by the right-hand rule.",
        "This is the direction on the west side of the wire, not the east side."), "Medium"),
    mcq(12, "12.2", "Charged-particle radius", "A charged particle moves perpendicular to uniform B. If its speed doubles with q, m, and B fixed, its circular-path radius",
      ["halves", "stays the same", "doubles", "quadruples"], 2,
      R("From r=mv/(|q|B), radius is directly proportional to speed.",
        "This applies an inverse speed dependence, reversing the magnetic orbit relation.",
        "This ignores the increased momentum at the larger speed.",
        "This incorrectly squares the speed factor in a linear relation."), "Easy"),
    mcq(12, "12.4", "Lenz-law direction", "The magnetic flux into the page through a loop is increasing. The induced current is",
      ["clockwise", "counterclockwise", "zero", "alternating without cause"], 1,
      R("The loop creates field out of the page to oppose the increase, requiring counterclockwise current.",
        "Clockwise current produces field into the page and would reinforce the increasing flux.",
        "A changing flux necessarily induces emf in a conducting loop.",
        "The flux changes in one direction, so no unexplained alternating current follows."), "Medium"),

    mcq(13, "13.1", "Law of reflection", "A ray strikes a plane mirror at 25° measured from the normal. Its reflection angle measured from the normal is",
      ["25°", "50°", "65°", "75°"], 0,
      R("The law of reflection makes the reflection angle equal to the 25° incidence angle.",
        "This doubles the incidence angle rather than matching it.",
        "This converts the angle to one measured from the mirror surface.",
        "This subtracts the incidence angle from 100° without a reflection-law basis."), "Easy"),
    mcq(13, "13.2", "Plane-mirror image", "A plane mirror forms an image that is",
      ["real and inverted", "virtual and upright", "real and enlarged", "virtual and inverted"], 1,
      R("A plane mirror produces a virtual, upright image of equal size behind the mirror.",
        "This treats backward extensions as actual converging rays and reverses orientation.",
        "This incorrectly gives both real convergence and magnification.",
        "This correctly identifies virtuality but incorrectly flips the image."), "Easy"),
    mcq(13, "13.3", "Refraction toward normal", "Light enters glass from air at an oblique angle. Because glass has larger refractive index, the ray bends",
      ["toward the normal", "away from the normal", "parallel to the surface always", "back along itself always"], 0,
      R("Snell's law makes the angle smaller in the higher-index glass, bending toward the normal.",
        "This is the bending direction for travel from higher to lower index.",
        "This would require a special limiting geometry, not ordinary refraction.",
        "This describes normal incidence reflection rather than oblique transmission."), "Easy"),

    mcq(14, "14.2", "Wave frequency in a new medium", "A periodic wave crosses into a medium where its speed decreases. Its frequency",
      ["decreases", "increases", "stays the same", "becomes zero"], 2,
      R("Frequency is fixed by the source and remains continuous at the boundary; wavelength decreases.",
        "This assumes frequency changes with speed while overlooking the source timing.",
        "This makes frequency rise to preserve wavelength, but wavelength is the quantity that changes.",
        "This treats the boundary as stopping the periodic source."), "Easy"),
    mcq(14, "14.4", "Electromagnetic wave fields", "In an electromagnetic wave in vacuum, electric and magnetic fields are",
      ["parallel to each other", "perpendicular to each other and propagation", "both along propagation", "unrelated in direction"], 1,
      R("The E field, B field, and propagation direction are mutually perpendicular.",
        "This removes the cross-product geometry that determines wave propagation.",
        "This treats both transverse fields as longitudinal.",
        "This ignores the fixed right-handed relationship between the wave fields."), "Medium"),
    mcq(14, "14.5", "Doppler frequency recession", "A sound source moves away from a stationary observer. The observed frequency is",
      ["greater than emitted", "less than emitted", "equal for every speed", "zero immediately"], 1,
      R("Recession increases spacing between arriving wavefronts, so observed frequency is lower.",
        "This describes approaching motion, where wavefronts are compressed.",
        "This ignores the source's radial motion relative to the observer.",
        "This assumes any recession stops arrivals rather than reducing their rate."), "Easy"),

    mcq(15, "15.3", "Emission-line origin", "A bright atomic emission line is produced when an electron",
      ["moves to a lower energy level", "moves to a higher level without input", "remains in one level", "loses its charge"], 0,
      R("A downward transition releases a photon whose energy equals the level difference.",
        "An upward transition requires absorption rather than spontaneous emission of the line.",
        "No energy difference is released while the electron remains in one state.",
        "Atomic emission does not change the electron's fundamental charge."), "Easy"),
    mcq(15, "15.6", "Compton scattering outcome", "In Compton scattering, an X-ray photon transfers energy and momentum to an electron. The scattered photon's wavelength is generally",
      ["shorter", "longer", "unchanged for all angles", "zero"], 1,
      R("After losing energy to the electron, the photon has lower frequency and longer wavelength.",
        "Shorter wavelength would mean the photon gained energy from the initially resting electron.",
        "This ignores the angle-dependent momentum transfer central to Compton scattering.",
        "A zero wavelength would imply unbounded photon energy, violating energy conservation."), "Medium"),
    mcq(15, "15.8", "Beta-minus decay", "In beta-minus decay, a neutron changes into",
      ["a proton, electron, and antineutrino", "a proton and photon only", "two neutrons", "an alpha particle"], 0,
      R("Beta-minus decay produces a proton, emitted electron, and electron antineutrino.",
        "This omits both the electron and antineutrino required for charge and lepton accounting.",
        "This increases neutron number without producing the observed beta particle.",
        "This confuses beta decay with emission of a helium nucleus."), "Medium"),
  ],
};
