import { criterion as c, frq, mcq } from "./lib.mjs";

const R = (a, b, d, e) => [a, b, d, e];
const V = ["Equivalent algebraically correct reasoning with consistent units earns credit."];

export const apphy1 = {
  prefix: "apphy1",
  examCode: "ap_physics_1",
  examPackVersionId: "29c719dc-701b-470f-9e49-fab981722d3f",
  factPackId: "1WTHwHrJujEuBzAXsL92zQdnHXlE-cvgsArE_FOVdR1g",
  frozenMaxFrq: 18,
  frozenMaxMcq: 26,
  expectedFrq: 16,
  expectedMcq: 24,
  calculusBased: false,
  unitSlugs: {
    1: "unit-1-kinematics",
    2: "unit-2-force-and-translational-dynamics",
    3: "unit-3-work-energy-and-power",
    4: "unit-4-linear-momentum",
    5: "unit-5-torque-and-rotational-dynamics",
    6: "unit-6-energy-and-momentum-of-rotating-systems",
    7: "unit-7-oscillations",
    8: "unit-8-fluids",
  },
  items: [
    frq(1, "1.4", "River-crossing reference frames", "Translation Between Representations", "long",
      "A rescue boat moves at 4.0 m/s due north relative to the water while the river flows at 3.0 m/s east relative to shore. The river is 120 m wide.",
      [
        "Draw a vector diagram that relates the boat-water, water-shore, and boat-shore velocities.",
        "Determine the boat's speed and direction relative to shore.",
        "Determine the crossing time and downstream displacement.",
      ],
      [
        c("a-vector-sum", "Shows v_boat,shore as the vector sum of the northward 4.0 m/s and eastward 3.0 m/s velocities.", "Perpendicular labeled component vectors and a northeast resultant.", "Add the relative-velocity vectors head to tail.", V),
        c("b-speed", "Calculates the shore-frame speed as 5.0 m/s.", "Uses the 3-4-5 right triangle.", "Compute the magnitude from both perpendicular components.", V),
        c("b-direction", "Gives the direction as about 37° east of north.", "Uses tan θ=3/4 with a direction statement.", "State the reference direction as well as the angle.", V),
        c("c-time", "Calculates a 30 s crossing time from the northward component.", "Uses 120 m divided by 4.0 m/s.", "Use the across-river component, not the resultant speed.", V),
        c("c-drift", "Calculates a 90 m downstream displacement.", "Uses the 3.0 m/s current for 30 s.", "Multiply the current speed by the crossing time.", V),
        c("c-connection", "Explains that the current changes eastward position but not the northward crossing rate.", "Connects independent perpendicular components to the results.", "Distinguish the roles of the two velocity components.", V),
      ], "The shore-frame velocity is 3.0 m/s east plus 4.0 m/s north: 5.0 m/s at 37° east of north. The boat crosses in 30 s and drifts 90 m east.", "Medium"),

    frq(1, "1.3", "Motion-graph cart investigation", "Experimental Design and Analysis", "short",
      "A cart released from rest moves down a straight ramp. Available equipment includes a motion sensor, meterstick, and adjustable ramp.",
      [
        "Describe a procedure and measurements that can determine whether the cart's acceleration is constant.",
        "State what graph you would construct and what feature would support constant acceleration.",
      ],
      [
        c("a-procedure", "Records velocity at equal time intervals for one fixed ramp angle using the motion sensor.", "A repeatable time series with the ramp angle controlled.", "Specify what is measured and what is held fixed.", V),
        c("b-graph", "Plots velocity versus time and identifies its slope as acceleration.", "Correct axes and physical meaning of slope.", "Use velocity on the vertical axis and time on the horizontal axis.", V),
        c("b-evidence", "States that an approximately straight line with constant slope supports constant acceleration.", "A falsifiable graphical criterion is given.", "Name the expected line shape and slope behavior.", V),
      ], "Measure velocity at equal times, plot velocity versus time, and infer constant acceleration from an approximately linear graph with constant slope.", "Medium"),

    frq(2, "2.2", "Elevator scale and free-body diagrams", "Translation Between Representations", "short",
      "A 60 kg passenger stands on a scale in an elevator accelerating upward at 1.5 m/s². Use g=9.8 m/s².",
      [
        "Draw and label a free-body diagram for the passenger.",
        "Use the diagram to determine the scale reading and explain why it exceeds the passenger's weight.",
      ],
      [
        c("a-fbd", "Shows only upward normal force and downward weight on the passenger.", "Two correctly directed forces with no invented motion force.", "Draw forces acting on the passenger, not forces exerted by the passenger.", V),
        c("b-value", "Calculates N=m(g+a)=678 N.", "Applies the upward net-force equation with consistent signs.", "Write N-mg=ma before substituting.", V),
        c("b-explanation", "Explains that an upward net force requires the normal force to exceed weight.", "Links force imbalance to upward acceleration.", "Compare the two vertical forces using Newton's second law.", V),
      ], "For the passenger, N upward and mg downward give N-mg=ma, so N=60(9.8+1.5)=678 N.", "Easy"),

    frq(2, "2.7", "Static-friction threshold experiment", "Experimental Design and Analysis", "long",
      "A wooden block rests on a board whose angle can be increased slowly. A protractor and balance are available.",
      [
        "Design a procedure to determine the coefficient of static friction between the block and board.",
        "Identify the measured quantities, one important control, and a way to reduce uncertainty.",
        "Derive the relationship used to calculate the coefficient from the critical angle.",
      ],
      [
        c("a-procedure", "Increases the angle slowly and records the angle at which slipping just begins.", "The onset of motion is used as the static-friction threshold.", "Define an observable criterion for the critical angle.", V),
        c("b-measures", "Measures the critical angle and repeats the measurement for multiple trials.", "Relevant measurement and replication are specified.", "Record the angle for several independent releases.", V),
        c("b-control", "Keeps the same contacting surfaces and surface condition for all trials.", "A variable affecting friction is controlled.", "Name a surface-related control.", V),
        c("b-uncertainty", "Averages repeated critical angles or brackets the onset angle from both directions.", "A concrete uncertainty-reduction method is included.", "Repeat and average or report an angular interval.", V),
        c("c-forces", "Uses mg sinθ down the plane and N=mg cosθ.", "Correct components are identified at the threshold.", "Resolve weight parallel and perpendicular to the board.", V),
        c("c-result", "Obtains μ_s=tanθ_c from mg sinθ_c=μ_s mg cosθ_c.", "Threshold force balance leads to the correct expression.", "Set limiting static friction equal to the downhill component.", V),
      ], "At impending slip, mg sinθ_c=μ_s mg cosθ_c, so μ_s=tanθ_c. Repeat the slowly increased-angle measurement with unchanged surfaces.", "Medium"),

    frq(2, "2.9", "Banked curve without friction", "Mathematical Routines", "short",
      "A car travels at 20 m/s around a frictionless banked curve of radius 50 m. Use g=9.8 m/s².",
      [
        "Derive the relation between banking angle, speed, radius, and g.",
        "Calculate the banking angle and explain which force component supplies the centripetal acceleration.",
      ],
      [
        c("a-relations", "Uses N cosθ=mg and N sinθ=mv²/r.", "Correct vertical and radial force equations.", "Resolve the normal force into vertical and inward components.", V),
        c("a-derive", "Derives tanθ=v²/(rg).", "Eliminates the normal force correctly.", "Divide the inward equation by the vertical equation.", V),
        c("b-result", "Calculates θ≈39.2° and identifies the inward normal-force component as centripetal.", "Numerical substitution and physical interpretation are both correct.", "Evaluate tanθ=400/490 and name the inward force component.", V),
      ], "N cosθ=mg and N sinθ=mv²/r give tanθ=v²/(rg); θ=tan⁻¹(400/490)≈39.2°.", "Medium"),

    frq(2, "2.1", "Center-of-mass motion after separation", "Qualitative/Quantitative Translation", "short",
      "Two carts initially move together on a nearly frictionless track. A compressed spring between them is released, pushing them apart without any external horizontal force.",
      [
        "Predict how the center-of-mass velocity changes during the separation and justify your prediction.",
        "If one cart has twice the mass of the other, compare the magnitudes of their momentum changes and velocity changes.",
      ],
      [
        c("a-com", "States that the center-of-mass velocity remains constant.", "Connects zero external horizontal force to constant system momentum.", "Use the system's external force, not the internal spring forces.", V),
        c("b-momentum", "States that the carts receive equal-magnitude opposite momentum changes.", "Uses the equal and opposite internal impulses.", "Compare momentum changes before comparing speeds.", V),
        c("b-speed", "States that the lighter cart has twice the magnitude of velocity change.", "Uses equal momentum change and the 2:1 mass ratio.", "Relate velocity change inversely to mass.", V),
      ], "With no external horizontal force, center-of-mass velocity is unchanged. The impulses and momentum changes are equal and opposite; the lighter cart's speed change is twice the heavier cart's.", "Medium"),

    frq(3, "3.2", "Variable pulling-force work", "Mathematical Routines", "long",
      "A 2.0 kg cart starts from rest on a horizontal frictionless track. The applied force increases uniformly from 0 N at x=0 to 12 N at x=6.0 m.",
      [
        "Represent force versus position and determine the work done over 6.0 m.",
        "Determine the cart's speed at x=6.0 m.",
        "Determine the average power delivered if the trip takes 3.0 s, and explain why the final instantaneous power is different.",
      ],
      [
        c("a-graph", "Represents a straight line from (0,0) to (6.0 m,12 N).", "Correct axes, endpoints, and linear trend.", "Show force on the vertical axis and position on the horizontal axis.", V),
        c("a-work", "Calculates work as the triangular area, 36 J.", "Uses one-half times base times height.", "Find the area under the force-position graph.", V),
        c("b-energy", "Uses W=ΔK with initial kinetic energy zero.", "Connects net work to the kinetic-energy change.", "Apply the work-energy theorem.", V),
        c("b-speed", "Calculates v=6.0 m/s.", "Solves 36=(1/2)(2.0)v².", "Solve the kinetic-energy equation for speed.", V),
        c("c-average", "Calculates average power as 12 W.", "Uses total work divided by 3.0 s.", "Divide energy transferred by elapsed time.", V),
        c("c-instant", "Explains that final instantaneous power is Fv=72 W because both force and speed are largest at the end.", "Distinguishes average power from the endpoint rate.", "Use the final force and final speed for instantaneous power.", V),
      ], "The triangular area under F versus x is 36 J. Work-energy gives v=6.0 m/s; average power is 12 W, while final power is (12 N)(6.0 m/s)=72 W.", "Medium"),

    frq(3, "3.4", "Two-path energy comparison", "Qualitative/Quantitative Translation", "short",
      "Identical sleds start from rest at the same height and reach the same lower height on two frictionless tracks of different shapes.",
      [
        "Compare their final speeds and justify your prediction.",
        "Compare their travel times and explain why energy conservation alone cannot determine that comparison.",
      ],
      [
        c("a-speed", "States that the final speeds are equal.", "Uses equal loss of gravitational potential energy and identical mass.", "Relate the same vertical drop to the same kinetic-energy gain.", V),
        c("a-equation", "Supports the comparison with v=sqrt(2gΔh).", "A correct algebraic energy relation is shown.", "Show how mass cancels from the energy equation.", V),
        c("b-time", "States that travel times need not be equal because the speeds along the paths depend on track shape.", "Distinguishes endpoint energy from the history of motion.", "Explain why equal final speed does not imply equal average speed or path length.", V),
      ], "Both sleds have v=sqrt(2gΔh), but their travel times can differ because path length and the speed acquired along each path depend on track shape.", "Medium"),

    frq(3, "3.5", "Motor efficiency investigation", "Experimental Design and Analysis", "short",
      "A small motor lifts known masses vertically through a measured height. A stopwatch and electrical power meter are available.",
      [
        "Describe measurements and a calculation that determine the motor's efficiency.",
        "Identify one source of systematic energy loss and explain how it affects the result.",
      ],
      [
        c("a-output", "Determines mechanical output energy as mgh and output power as mgh/t.", "Mass, height, and time are measured and used correctly.", "Calculate the gravitational energy gained per elapsed time.", V),
        c("a-efficiency", "Calculates efficiency as (mgh/t)/P_electric or mgh/(P_electric t).", "Compares useful output with electrical input.", "Form a dimensionless output-to-input ratio.", V),
        c("b-loss", "Identifies a specific loss such as bearing friction or electrical heating and states that it makes efficiency less than one.", "A real loss mechanism and its directional effect are given.", "Connect the named loss to energy not appearing as gravitational potential energy.", V),
      ], "Measure m, h, t, and input power. Efficiency is mgh/(P_electric t); frictional and thermal losses reduce the value below one.", "Easy"),

    frq(3, "3.3", "Spring potential-energy graph", "Translation Between Representations", "short",
      "An ideal spring has force magnitude F=k|x| about equilibrium.",
      [
        "Sketch force and potential energy versus displacement from -A to +A.",
        "Explain how the graphs show the locations of maximum speed and turning points for an attached mass.",
      ],
      [
        c("a-force", "Shows a restoring-force line through the origin with negative slope in a signed F-versus-x graph.", "Force direction opposes displacement.", "Represent the signed relation F=-kx.", V),
        c("a-energy", "Shows a nonnegative parabola U=(1/2)kx² with a minimum at x=0.", "Correct shape and symmetry for spring energy.", "Make the energy zero/minimum at equilibrium and symmetric.", V),
        c("b-motion", "Identifies maximum speed at x=0 and zero speed at x=±A using energy exchange.", "Correctly links graph values to kinetic energy.", "Compare potential energy at equilibrium and the turning points.", V),
      ], "F=-kx is linear with negative slope; U=(1/2)kx² is an upward parabola. Speed is greatest at x=0 and zero at x=±A.", "Medium"),

    frq(4, "4.4", "Ballistic-pendulum collision", "Mathematical Routines", "long",
      "A 0.020 kg clay pellet moving horizontally embeds in a 0.980 kg block suspended as a pendulum. The combined mass rises 0.45 m. Use g=9.8 m/s².",
      [
        "Determine the speed immediately after the collision.",
        "Determine the pellet's speed immediately before impact.",
        "Explain which conservation law applies during each stage and why kinetic energy is not conserved in the collision.",
      ],
      [
        c("a-energy", "Uses (1/2)Mv_f²=Mgh for the postcollision rise.", "Mechanical energy is applied only after impact.", "Relate the immediate postcollision kinetic energy to the later height.", V),
        c("a-speed", "Calculates v_f≈2.97 m/s.", "Uses sqrt(2gh) with h=0.45 m.", "Evaluate the postcollision speed numerically.", V),
        c("b-momentum", "Uses m_p v_p=(m_p+m_b)v_f during impact.", "Horizontal momentum is conserved over the brief collision.", "Write momentum before and after embedding.", V),
        c("b-speed", "Calculates v_p≈149 m/s.", "Uses the 0.020 kg to 1.000 kg mass ratio.", "Solve the momentum equation for pellet speed.", V),
        c("c-stages", "States momentum conservation for impact and mechanical-energy conservation for the rise.", "Correct laws are assigned to distinct time intervals.", "Separate the short collision from the subsequent swing.", V),
        c("c-inelastic", "Explains that deformation/internal energy during embedding reduces kinetic energy.", "Names the physical destination of lost mechanical energy.", "Do not claim total energy is destroyed.", V),
      ], "The rise gives v_f=sqrt(2gh)=2.97 m/s. Momentum during embedding gives v_p=(1.000/0.020)(2.97)≈149 m/s. Collision kinetic energy becomes internal energy.", "Hard"),

    frq(4, "4.2", "Force-time sensor impulse", "Translation Between Representations", "short",
      "A force sensor records a triangular force-time pulse on a 0.50 kg cart: force rises from 0 to 8.0 N in 0.20 s and returns to 0 by 0.50 s. The cart initially moves at -1.0 m/s.",
      [
        "Use the graph description to determine the impulse and final velocity.",
        "Explain how the sign of the area determines whether the cart reverses direction.",
      ],
      [
        c("a-impulse", "Calculates impulse as the triangular area, 2.0 N·s.", "Uses one-half times 0.50 s times 8.0 N.", "Find the complete signed area under force versus time.", V),
        c("a-velocity", "Calculates p_f=-0.50+2.0=1.50 kg·m/s and v_f=3.0 m/s.", "Initial momentum and impulse are combined with signs.", "Include the negative initial momentum before dividing by mass.", V),
        c("b-direction", "Explains that positive impulse exceeds the magnitude of the initial negative momentum, so final momentum is positive.", "Connects signed graph area to reversal.", "Compare impulse with initial momentum, not merely with initial velocity.", V),
      ], "Impulse is (1/2)(0.50)(8.0)=2.0 N·s. Initial momentum is -0.50 kg·m/s, so final momentum is +1.50 kg·m/s and v_f=+3.0 m/s.", "Medium"),

    frq(5, "5.4", "Rotational-inertia rolling race", "Qualitative/Quantitative Translation", "short",
      "A solid sphere and a thin spherical shell have equal mass and radius and roll without slipping from rest down the same incline.",
      [
        "Predict which reaches the bottom first and justify using rotational inertia.",
        "Compare their final translational speeds for the same vertical drop.",
      ],
      [
        c("a-prediction", "Predicts that the solid sphere arrives first.", "Recognizes its smaller I/(MR²) value.", "Compare dimensionless rotational-inertia factors.", V),
        c("a-reason", "Explains that less energy is required for rotation at a given translational speed, producing greater acceleration.", "Links inertia to the energy/acceleration split.", "State why smaller rotational inertia increases translational acceleration.", V),
        c("b-speed", "States that the solid sphere has the greater final translational speed and supports it with v²=2gh/[1+I/(MR²)].", "Correct same-height rolling-energy comparison.", "Include both translational and rotational kinetic energy.", V),
      ], "The solid sphere has smaller I/(MR²), so it accelerates more and reaches a greater speed: v²=2gh/[1+I/(MR²)].", "Medium"),

    frq(5, "5.5", "Meterstick rotational equilibrium", "Experimental Design and Analysis", "long",
      "A nonuniform meterstick is supported horizontally at the 20 cm and 80 cm marks. A force sensor measures one support force; the stick's mass is known.",
      [
        "Design a procedure to locate the stick's center of mass using equilibrium measurements.",
        "Write the force and torque relationships needed.",
        "Describe a consistency check and one uncertainty-reduction method.",
      ],
      [
        c("a-measure", "Measures both support locations and one support force while the stick is stationary.", "Sufficient equilibrium data are identified.", "State how the second support force will be inferred.", V),
        c("a-infer", "Uses vertical force balance to infer the other support force.", "Applies F_1+F_2=mg.", "Include the stick's weight in vertical balance.", V),
        c("b-pivot", "Chooses a support as torque pivot so its unknown force has zero lever arm.", "A convenient torque origin is stated.", "Name the pivot used in the torque equation.", V),
        c("b-torque", "Uses F_2(x_2-x_1)=mg(x_cm-x_1) or an equivalent signed equation.", "Correct lever arms and torque balance.", "Use perpendicular horizontal distances from the chosen pivot.", V),
        c("c-check", "Checks that the computed center lies between 0 and 100 cm and reproduces both balances.", "A physically meaningful consistency test is provided.", "Substitute the result back into force and torque balance.", V),
        c("c-uncertainty", "Repeats with different support locations and averages compatible center-of-mass estimates.", "A concrete replication strategy is given.", "Change support geometry while keeping the stick unchanged.", V),
      ], "Use F_1+F_2=mg and torque balance about either support, such as F_2(x_2-x_1)=mg(x_cm-x_1), then repeat with new support positions.", "Medium"),

    frq(7, "7.3", "Oscillation phase from graphs", "Translation Between Representations", "short",
      "A mass-spring oscillator starts at maximum positive displacement A at t=0 and has period T.",
      [
        "Sketch position, velocity, and acceleration versus time for one period with aligned time axes.",
        "Explain the phase relationships and identify when kinetic energy is maximum.",
      ],
      [
        c("a-graphs", "Shows x beginning at +A, v beginning at zero and negative, and acceleration beginning at its most negative value.", "Correct initial conditions and sinusoidal shapes.", "Align all three graphs at t=0.", V),
        c("b-phase", "States that acceleration is opposite position and velocity is shifted by one-quarter period from position.", "Correct qualitative phase relations.", "Use a=-ω²x and the direction of motion.", V),
        c("b-energy", "Identifies maximum kinetic energy at equilibrium crossings t=T/4 and 3T/4.", "Connects maximum speed to x=0.", "Mark both equilibrium crossings in one period.", V),
      ], "x starts at +A, v at 0 toward negative x, and a at -a_max. Speed and kinetic energy peak at T/4 and 3T/4.", "Medium"),

    frq(7, "7.4", "Damped-oscillator energy test", "Experimental Design and Analysis", "short",
      "A cart attached to a spring oscillates with slowly decreasing amplitude. A motion sensor records position versus time.",
      [
        "Describe how to use the data to test whether a constant fraction of mechanical energy is lost each cycle.",
        "State what plotted relationship would support that model.",
      ],
      [
        c("a-amplitudes", "Extracts successive peak amplitudes A_n from the position-time record.", "Uses comparable turning points one cycle apart.", "Measure peaks on the same side or use absolute amplitudes.", V),
        c("a-energy", "Uses E_n=(1/2)kA_n² and compares E_(n+1)/E_n.", "Correctly relates turning-point amplitude to energy.", "Square amplitudes before forming the energy ratio.", V),
        c("b-test", "States that an approximately constant E_(n+1)/E_n, or a straight line in ln(E_n) versus cycle number, supports constant fractional loss.", "A clear model-discrimination criterion is provided.", "Specify the expected constant ratio or linearized trend.", V),
      ], "Measure successive amplitudes, compute energies proportional to A_n², and test whether E_(n+1)/E_n is approximately constant.", "Hard"),

    mcq(1, "1.2", "Stopping distance from a velocity graph",
      "A bicycle's velocity decreases uniformly from 12 m/s to 0 in 4.0 s. How far does it travel while stopping?",
      ["12 m", "24 m", "36 m", "48 m"], 1,
      R("The triangular area under velocity versus time is (1/2)(4.0 s)(12 m/s)=24 m.",
        "This uses final speed times one second and ignores the four-second interval.",
        "This incorrectly uses three-quarters of the enclosing rectangle rather than one-half.",
        "This uses the full rectangle 12×4, as if velocity stayed at 12 m/s."), "Easy"),
    mcq(1, "1.5", "Projectile horizontal range",
      "A ball rolls horizontally from a 20 m-high ledge at 5.0 m/s. Neglect air resistance and use g=10 m/s². How far from the ledge does it land?",
      ["5.0 m", "10 m", "20 m", "25 m"], 1,
      R("The fall time is sqrt(2h/g)=2.0 s, so horizontal range is (5.0)(2.0)=10 m.",
        "This uses a one-second fall time, omitting the square-root calculation from vertical motion.",
        "This treats the 20 m vertical height as though it were the horizontal range.",
        "This multiplies horizontal speed by height, mixing incompatible quantities instead of using time."), "Medium"),
    mcq(1, "1.4", "Relative velocity of trains",
      "Train A moves east at 30 m/s while Train B moves east at 20 m/s. What is A's velocity relative to B?",
      ["10 m/s east", "10 m/s west", "50 m/s east", "50 m/s west"], 0,
      R("For same-direction motion, v_A/B=30-20=10 m/s east.",
        "This subtracts the speeds but reverses the relative direction.",
        "This adds same-direction velocities, which is appropriate for opposite-direction closing speed.",
        "This both adds the speeds and assigns the direction opposite A's motion."), "Easy"),

    mcq(2, "2.3", "Third-law force pair",
      "A truck collides with a small car. During contact, which comparison of interaction forces is correct?",
      ["Truck on car is larger", "Car on truck is larger", "Forces are equal in magnitude and opposite", "Forces are equal only if masses match"], 2,
      R("Newton's third law gives equal-magnitude opposite forces on the two different vehicles.",
        "This infers force from vehicle size, confusing force equality with differing accelerations.",
        "This is Newton's third-law pair; unequal masses produce unequal accelerations, not unequal forces.",
        "This wrongly makes the third-law equality depend on equal masses."), "Easy"),
    mcq(2, "2.6", "Gravitational field scaling",
      "At a distance r from a planet's center the gravitational field is g₀. At distance 2r it is",
      ["4g₀", "2g₀", "g₀/2", "g₀/4"], 3,
      R("The inverse-square relation g=GM/r² makes doubling radius reduce the field to g₀/4.",
        "This applies direct-square scaling instead of inverse-square scaling.",
        "This assumes field is directly proportional to radius rather than inversely proportional to radius squared.",
        "This applies an inverse-linear relation and misses the square on distance."), "Medium"),
    mcq(2, "2.7", "Static versus kinetic friction",
      "A horizontal push on a stationary crate increases from zero but remains below the threshold for slipping. The friction force",
      ["is always μ_sN", "matches the push in magnitude", "is zero until slipping", "equals μ_kN"], 1,
      R("Static friction adjusts to match the applied push until its maximum value is reached.",
        "This treats the maximum μ_sN as the friction value for every subthreshold push.",
        "This ignores static friction, which acts before any slipping begins.",
        "This uses the kinetic-friction formula even though the crate remains stationary."), "Medium"),
    mcq(2, "2.8", "Spring-force direction",
      "An ideal horizontal spring is stretched 0.15 m to the right of equilibrium. If k=80 N/m, the spring force on the attached block is",
      ["12 N right", "12 N left", "533 N left", "0 N"], 1,
      R("Hooke's law F=-kx gives magnitude 12 N directed left, opposite the rightward displacement.",
        "This calculates the correct magnitude but drops the restoring-force direction encoded by the negative sign.",
        "This divides k by displacement instead of multiplying, producing the wrong units and magnitude.",
        "This assumes force vanishes away from equilibrium rather than at equilibrium."), "Easy"),
    mcq(2, "2.9", "Vertical-circle normal force",
      "A rider moves through the bottom of a vertical circular track at speed v. Which radial equation is correct if inward is upward?",
      ["N+mg=mv²/r", "N-mg=mv²/r", "mg-N=mv²/r", "N=mg"], 1,
      R("At the bottom, inward is upward, so the inward net force is N-mg=mv²/r.",
        "This adds weight as inward even though weight points outward/downward at the bottom.",
        "This reverses the net-force signs and would describe inward as downward.",
        "This imposes vertical equilibrium despite the required centripetal acceleration."), "Hard"),
    mcq(2, "2.1", "Center-of-mass location",
      "Masses 1.0 kg and 3.0 kg are at x=0 and x=4.0 m, respectively. The center of mass is at",
      ["1.0 m", "2.0 m", "3.0 m", "4.0 m"], 2,
      R("x_cm=(1×0+3×4)/(1+3)=3.0 m, closer to the larger mass.",
        "This places the center near the smaller mass by reversing the mass weighting.",
        "This takes the unweighted midpoint and ignores the unequal masses.",
        "This places the center exactly on the 3.0 kg mass rather than between the masses."), "Medium"),

    mcq(3, "3.1", "Kinetic-energy speed scaling",
      "If an object's speed triples while its mass is unchanged, its translational kinetic energy becomes",
      ["3 times as large", "6 times as large", "9 times as large", "unchanged"], 2,
      R("Because K=(1/2)mv², tripling v multiplies kinetic energy by 3²=9.",
        "This assumes kinetic energy is directly proportional to speed and misses the square.",
        "This multiplies the speed factor by two instead of squaring it.",
        "This ignores the speed dependence in the kinetic-energy expression."), "Easy"),
    mcq(3, "3.2", "Work by an angled force",
      "A 50 N force pulls a crate 4.0 m while directed 60° above the horizontal displacement. The work by this force is",
      ["50 J", "100 J", "173 J", "200 J"], 1,
      R("Work is Fd cos60°=(50)(4.0)(0.5)=100 J.",
        "This multiplies only force by cos60° and omits displacement.",
        "This uses sin60° instead of the component parallel to horizontal displacement.",
        "This uses Fd without accounting for the 60° angle."), "Easy"),
    mcq(3, "3.3", "Potential from force direction",
      "In one dimension, a conservative force points in the +x direction throughout a region. As x increases, potential energy",
      ["increases", "decreases", "stays constant", "must be zero"], 1,
      R("A positive force points toward decreasing potential energy, so U decreases as x increases.",
        "This assumes force points toward increasing potential rather than down the potential-energy landscape.",
        "This would require zero force, contradicting the stated nonzero +x force.",
        "This confuses the arbitrary zero of potential energy with its spatial change."), "Medium"),
    mcq(3, "3.4", "Loop-the-loop energy",
      "A bead starts from rest at height h above the bottom of a frictionless track. Its speed at the bottom is",
      ["gh", "sqrt(gh)", "sqrt(2gh)", "2gh"], 2,
      R("Conservation of energy mgh=(1/2)mv² gives v=sqrt(2gh).",
        "This reports an energy-per-mass quantity with units of speed squared, not speed.",
        "This omits the factor of two arising from the one-half in kinetic energy.",
        "This omits the square root and therefore has incorrect velocity units."), "Easy"),
    mcq(3, "3.5", "Average power climbing stairs",
      "A 70 kg student climbs 3.0 m vertically in 5.0 s. Using g=10 m/s², the average power is",
      ["42 W", "140 W", "420 W", "2100 W"], 2,
      R("Average power=mgh/t=(70)(10)(3.0)/5.0=420 W.",
        "This divides by an extra factor of ten after computing gravitational energy.",
        "This omits the 3.0 m height and divides weight by time.",
        "This calculates the gravitational energy but fails to divide by elapsed time."), "Easy"),
    mcq(3, "3.4", "Frictional energy accounting",
      "A block slides down a rough ramp and reaches the bottom slower than an identical block on a frictionless ramp. For the rough-ramp system, the missing mechanical energy primarily becomes",
      ["mass", "thermal energy", "momentum", "gravitational field strength"], 1,
      R("Kinetic friction transforms mechanical energy into thermal energy of the block and ramp.",
        "This violates mass conservation by treating dissipated mechanical energy as new mass.",
        "This confuses a vector motion quantity with the form into which energy is transferred.",
        "This treats the planet's field strength as an energy storage destination."), "Easy"),

    mcq(4, "4.1", "Momentum vector change",
      "A 2.0 kg ball moving 3.0 m/s east rebounds at 1.0 m/s west. Its change in momentum is",
      ["4 kg·m/s east", "4 kg·m/s west", "8 kg·m/s east", "8 kg·m/s west"], 3,
      R("Taking east positive, Δp=2(-1)-2(3)=-8 kg·m/s, or 8 kg·m/s west.",
        "This subtracts speed magnitudes without accounting for the reversal in direction.",
        "This finds a magnitude associated with adding speeds but assigns the wrong direction.",
        "This calculates only the final momentum magnitude and omits the initial momentum."), "Medium"),
    mcq(4, "4.3", "Explosion momentum",
      "An object initially at rest explodes into two pieces. One piece has momentum 6 kg·m/s east. The other piece has momentum",
      ["6 kg·m/s east", "6 kg·m/s west", "0", "determined by kinetic-energy conservation"], 1,
      R("Initial total momentum is zero, so the second piece must have 6 kg·m/s west.",
        "This gives a nonzero 12 kg·m/s final total momentum without external impulse.",
        "This ignores the momentum carried by the second fragment after the explosion.",
        "This uses kinetic-energy conservation, which need not hold in an energy-releasing explosion."), "Easy"),
    mcq(4, "4.4", "Elastic collision signature",
      "Which pair of quantities is conserved for an isolated two-object elastic collision?",
      ["Momentum only", "Kinetic energy only", "Momentum and kinetic energy", "Speed of each object"], 2,
      R("An elastic collision conserves both total momentum and total kinetic energy.",
        "This describes all isolated collisions but omits the defining elastic-collision energy condition.",
        "This ignores momentum conservation for an isolated system.",
        "This confuses conservation of total quantities with each object's individual speed remaining unchanged."), "Easy"),

    mcq(5, "5.4", "Disk and ring angular acceleration",
      "A uniform disk and a thin ring have the same mass and radius. The same tangential force is applied at each rim. Compared with the ring's angular acceleration, the disk's angular acceleration is",
      ["twice as large", "the same", "half as large", "four times as large"], 0,
      R("The torques match, while I_disk=(1/2)MR² and I_ring=MR², so α_disk is twice α_ring.",
        "Equal torque does not give equal angular acceleration when the rotational inertias differ.",
        "This reverses the inverse relationship between angular acceleration and rotational inertia.",
        "The inertia ratio is two, not four, for objects with the same mass and radius."), "Medium"),
    mcq(5, "5.4", "Point-mass rotational inertia",
      "A point mass is moved from radius R to radius 2R about a fixed axis. Its rotational inertia becomes",
      ["2I", "4I", "I/2", "I/4"], 1,
      R("For a point mass I=mr², doubling radius makes inertia four times as large.",
        "This assumes rotational inertia is directly proportional to radius rather than radius squared.",
        "This applies an inverse-linear relationship instead of a direct-square relationship.",
        "This applies an inverse-square relationship, reversing the effect of moving mass outward."), "Easy"),
    mcq(5, "5.6", "Angular acceleration of a disk",
      "A net torque of 6.0 N·m acts on a disk with rotational inertia 2.0 kg·m². Its angular acceleration is",
      ["0.33 rad/s²", "3.0 rad/s²", "8.0 rad/s²", "12 rad/s²"], 1,
      R("Rotational Newton's second law gives α=τ/I=6.0/2.0=3.0 rad/s².",
        "This divides inertia by torque, taking the reciprocal of the correct relation.",
        "This adds torque and rotational inertia instead of forming their quotient.",
        "This multiplies torque by inertia rather than dividing."), "Easy"),

    mcq(7, "7.2", "Mass-spring period scaling",
      "The mass on an ideal spring is increased from m to 4m with k unchanged. The oscillation period becomes",
      ["T/4", "T/2", "2T", "4T"], 2,
      R("Since T=2πsqrt(m/k), multiplying mass by four doubles the period.",
        "This applies inverse direct scaling and also ignores the square-root dependence.",
        "This assumes inverse square-root scaling, reversing the effect of added mass.",
        "This assumes period is directly proportional to mass rather than its square root."), "Medium"),
    mcq(7, "7.4", "SHM energy at half amplitude",
      "For an ideal spring oscillator of amplitude A, what fraction of total energy is spring potential energy at x=A/2?",
      ["1/4", "1/2", "3/4", "1"], 0,
      R("U/E=[(1/2)k(A/2)²]/[(1/2)kA²]=1/4.",
        "This assumes energy is proportional to displacement rather than displacement squared.",
        "This gives the kinetic-energy fraction at x=A/2, not the spring potential fraction.",
        "This incorrectly treats half-amplitude as a turning point where all energy is potential."), "Medium"),

    mcq(8, "8.3", "Apparent weight underwater",
      "A 500 N object experiences a 120 N buoyant force while fully submerged and is otherwise unsupported. Its apparent weight is",
      ["120 N", "380 N", "500 N", "620 N"], 1,
      R("Apparent weight is weight minus buoyant force: 500-120=380 N.",
        "This reports only the buoyant force rather than the remaining downward force.",
        "This ignores the upward buoyant force and leaves the full weight unchanged.",
        "This adds buoyancy to weight even though the forces point in opposite directions."), "Easy"),
  ],
};
