"""Calculus BC units 1-3 share one CED and an identical taxonomy topic set with AB (verified
2026-10-10: 32 topics each, zero asymmetric difference). This writes the BC rows from AB's
already-checked rows without re-running the models or editing any content: body, items, caution
and title are copied verbatim and the provenance records the re-key. Product Owner decision
required before applying -- the production protocol does not describe a re-key path."""
import pathlib
out = pathlib.Path(__file__).resolve().parent / "out"
sql = """-- generated by rekey_bc.py; do not hand-edit.
-- AP Calculus BC units 1-3 from the checked AP Calculus AB rows of batch
-- ap-calculus-ab-reference-u1-u3-2026-10-10. Content is copied verbatim; only subject_key changes.
begin;
insert into app.unit_reference_entries
  (subject_key, unit_number, owner_topic_code, topic_codes, kind, title, body, items,
   visual_asset_ref, caution, status, source_note)
select 'ap_calculus_bc', unit_number, owner_topic_code, topic_codes, kind, title, body, items,
       visual_asset_ref, caution, 'published',
       source_note || '; re-keyed from ap_calculus_ab (same CED and identical taxonomy topics for units 1-3)'
from app.unit_reference_entries
where subject_key = 'ap_calculus_ab' and unit_number between 1 and 3 and status = 'published'
on conflict (subject_key, owner_topic_code, kind, title) do nothing;

insert into app.topic_memory_hooks
  (reference_entry_id, kind, hook_text, expands_to, when_to_use, caution, status, source_note)
select bc.reference_entry_id, h.kind, h.hook_text, h.expands_to, h.when_to_use, h.caution, 'published',
       h.source_note || '; re-keyed from ap_calculus_ab'
from app.topic_memory_hooks h
join app.unit_reference_entries ab on ab.reference_entry_id = h.reference_entry_id
join app.unit_reference_entries bc
  on bc.subject_key = 'ap_calculus_bc' and bc.owner_topic_code = ab.owner_topic_code
 and bc.kind = ab.kind and bc.title = ab.title
where ab.subject_key = 'ap_calculus_ab' and ab.unit_number between 1 and 3
on conflict (reference_entry_id, hook_text) do nothing;
commit;
"""
p = out / "load_ap_calculus_bc_u1_u3_rekey.sql"
p.write_text(sql)
print(f"{p.name}: written (NOT applied; awaiting Product Owner decision)")
