#!/usr/bin/env python3
"""TASK-0065: build one idempotent Open Hand teaching-item load per subject.

Input : docs/research/open_hand_teaching_batch_2026_10_06/SCOPE_UNITS_1-3.json
Output: docs/research/open_hand_teaching_batch_2026_10_06/load/<subject>.sql

Each output file is a single DO block (the Supabase MCP hangs on multi-statement
writes). The items travel as one dollar-quoted jsonb literal; the block:
  * resolves the subject's published, non-retired exam pack version at run time
    (pack ids differ between Development and Production); when a subject has
    more than one, it uses the one that already holds Open Hand teaching items;
  * per item, skips the content_key if it already exists in that pack;
  * inserts content_items + content_item_versions as draft, the four
    mcq_choices, and one primary 'authored' topic cell;
  * walks the publish gates in order: version draft -> reviewed_approved
    (review_status question_review_approved) -> published; item likewise;
  * registers the item in app.open_hand_teaching_items (source 'generated');
  * releases any active 'spare' teaching row for the same subject + topic.
No serving taxonomy labels are written, so the items never enter scoring.
"""
import json, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
SRC = os.path.join(ROOT, 'docs/research/open_hand_teaching_batch_2026_10_06/SCOPE_UNITS_1-3.json')
OUT = os.path.join(ROOT, 'docs/research/open_hand_teaching_batch_2026_10_06/load')

EXCLUDE = {
    'ap-calculus-ab': {'1.2', '1.11', '1.12', '1.13', '1.16'},
    'ap-statistics': {'1.12', '2.3', '3.6', '3.14'},
    'biology': {'1.1', '1.4', '1.7', '2.9', '3.2', '3.3'},
}
# content_key prefix follows each subject's existing casing convention.
PREFIX = {'biology': 'APBIO-OHT-', 'ap-statistics': 'APSTATS-OHT-',
          'ap-chemistry': 'apchem-oht-', 'ap-calculus-ab': 'apcalcab-oht-'}
# Taxonomy source versions are identical in Development and Production.
TSV = {'biology': 'c676d1fc-3b58-4896-89e3-852d9bd1f81b',
       'ap-statistics': 'dae3c72e-82ca-4960-9552-1b034bd347e5',
       'ap-chemistry': 'cbe3116f-6ef5-410c-b535-e9fb711c4c2c',
       'ap-calculus-ab': '33b4408b-0ecc-4c7a-b0b1-612db81164a1'}
OWNER = 'f5a26c6b-3566-4d58-9e97-979fbb947564'  # approved_by when the profile exists
NOTE = 'TASK-0065 batch 2026-10-06'
CELL_SOURCE = 'task0065_oht_generated_2026_10_06'
JTAG = '$oht0065json$'

TEMPLATE = r"""-- TASK-0065 Open Hand teaching items: {subject} ({n} items). Generated by
-- scripts/content-seed/task0065_load/build_load_sql.py. Idempotent: re-running
-- skips content_keys already present in the target pack.
do $oht0065$
declare
  v_subject text := '{subject}';
  v_tsv uuid := '{tsv}';
  v_owner uuid := (select p.user_id from app.profiles p where p.user_id = '{owner}');
  v_items jsonb := {jtag}{payload}{jtag}::jsonb;
  v_pv uuid; v_npv int;
  r jsonb; c jsonb;
  v_ci uuid; v_civ uuid; v_key text; v_correct text;
  v_loaded int := 0; v_skipped int := 0; v_released int := 0;
begin
  select count(*) into v_npv
  from app.exam_pack_versions epv join app.exam_packs ep on ep.id = epv.exam_pack_id
  join app.subjects s on s.id = ep.subject_id
  where s.subject_key = v_subject and epv.status = 'published' and epv.retired_at is null;
  if v_npv = 0 then
    raise exception 'task0065: no published, non-retired exam pack version for %', v_subject;
  end if;
  -- Prefer the published pack that already holds teaching items (two exist for
  -- Statistics in Development); otherwise require exactly one.
  select epv.id into v_pv
  from app.exam_pack_versions epv join app.exam_packs ep on ep.id = epv.exam_pack_id
  join app.subjects s on s.id = ep.subject_id
  where s.subject_key = v_subject and epv.status = 'published' and epv.retired_at is null
    and (v_npv = 1 or exists (select 1 from app.open_hand_teaching_items t
                              join app.content_items ci on ci.id = t.content_item_id
                              where ci.exam_pack_version_id = epv.id))
  order by (select count(*) from app.open_hand_teaching_items t join app.content_items ci on ci.id = t.content_item_id
            where ci.exam_pack_version_id = epv.id) desc, epv.id
  limit 1;
  if v_pv is null then
    raise exception 'task0065: % has % published packs and none holds teaching items; pick one explicitly', v_subject, v_npv;
  end if;

  for r in select * from jsonb_array_elements(v_items) loop
    v_key := r->>'content_key';
    if exists (select 1 from app.content_items where exam_pack_version_id = v_pv and content_key = v_key) then
      v_skipped := v_skipped + 1;
      continue;
    end if;
    if jsonb_array_length(r->'choices') <> 4
       or (select count(*) from jsonb_array_elements(r->'choices') x where (x->>'is_correct')::boolean) <> 1 then
      raise exception 'task0065: % must have 4 choices with exactly one correct', v_key;
    end if;
    if not exists (select 1 from app.taxonomy_topics tt where tt.taxonomy_source_version = v_tsv
                   and tt.topic_code = r->>'topic_code') then
      raise exception 'task0065: topic % not in taxonomy %', r->>'topic_code', v_tsv;
    end if;
    select x->>'choice_key' into v_correct from jsonb_array_elements(r->'choices') x
    where (x->>'is_correct')::boolean;

    insert into app.content_items (exam_pack_version_id, content_key, item_type, title, status)
    values (v_pv, v_key, 'mcq', r->>'title', 'draft')
    returning id into v_ci;

    insert into app.content_item_versions (content_item_id, version_num, stem, content_hash, status,
      review_status, rubric_type, evaluator_strategy, canonical_answer_1)
    values (v_ci, 1, r->>'stem', md5(v_key), 'draft', 'tutor_review_pending', 'mcq', 'rule_based_mcq', v_correct)
    returning id into v_civ;

    for c in select * from jsonb_array_elements(r->'choices') loop
      insert into app.mcq_choices (content_item_version_id, choice_key, choice_text, is_correct, rationale)
      values (v_civ, c->>'choice_key', c->>'choice_text', (c->>'is_correct')::boolean, c->>'rationale');
    end loop;

    insert into app.content_item_cells (content_item_version_id, content_item_id, taxonomy_source_version,
      topic_code, skill_code, is_primary, assignment_status, source, model_run_id)
    values (v_civ, v_ci, v_tsv, r->>'topic_code', null, true, 'authored', '{cell_source}',
      'TASK-0065 Open Hand teaching batch 2026-10-06 (authored to this topic; checked per CHECK_RESULTS.md)');

    -- Publish gates: enforce_publish_gate (approved review_status),
    -- tg_content_pipeline_guard_publish (published only from reviewed_approved),
    -- enforce_mcq_stem_choice_sync (runs on publish; choices exist by now).
    update app.content_item_versions set status = 'reviewed_approved', review_status = 'question_review_approved',
      approved_by = v_owner, approved_at = now() where id = v_civ;
    update app.content_item_versions set status = 'published', published_at = now() where id = v_civ;
    update app.content_items set status = 'reviewed_approved' where id = v_ci;
    update app.content_items set status = 'published' where id = v_ci;

    insert into app.open_hand_teaching_items (content_item_id, topic_code, source, note)
    values (v_ci, r->>'topic_code', 'generated', '{note}')
    on conflict (content_item_id) do nothing;
    v_loaded := v_loaded + 1;
  end loop;

  -- Return superseded spares (same subject + topic) to scoring.
  with rel as (
    update app.open_hand_teaching_items t set released_at = now()
    from app.content_items ci, app.exam_pack_versions epv, app.exam_packs ep, app.subjects s
    where ci.id = t.content_item_id and epv.id = ci.exam_pack_version_id and ep.id = epv.exam_pack_id
      and s.id = ep.subject_id and s.subject_key = v_subject
      and t.source = 'spare' and t.released_at is null
      and exists (select 1 from app.open_hand_teaching_items g
                  join app.content_items gci on gci.id = g.content_item_id
                  where g.source = 'generated' and g.released_at is null and g.note = '{note}'
                    and g.topic_code = t.topic_code and gci.exam_pack_version_id = v_pv
                    and gci.status = 'published')
    returning t.content_item_id)
  select count(*) into v_released from rel;

  raise notice 'task0065 %: pack %, loaded %, skipped %, spares released %', v_subject, v_pv, v_loaded, v_skipped, v_released;
end
$oht0065$;
"""

def main():
    items = json.load(open(SRC))
    os.makedirs(OUT, exist_ok=True)
    by = {}
    for it in items:
        s = it['subject_key']
        if it['topic_code'] in EXCLUDE.get(s, set()):
            continue
        assert len(it['choices']) == 4 and sum(c['is_correct'] for c in it['choices']) == 1
        assert sorted(c['choice_key'] for c in it['choices']) == ['A', 'B', 'C', 'D']
        for c in it['choices']:
            assert c['choice_text'].strip() and c['rationale'].strip(), (s, it['topic_code'])
        by.setdefault(s, []).append({
            'content_key': PREFIX[s] + it['topic_code'],
            'topic_code': it['topic_code'],
            'title': it['topic_title'],
            'stem': it['stem'],
            'choices': [{k: c[k] for k in ('choice_key', 'choice_text', 'is_correct', 'rationale')}
                        for c in sorted(it['choices'], key=lambda c: c['choice_key'])],
        })
    for s, rows in sorted(by.items()):
        keys = [r['content_key'] for r in rows]
        assert len(keys) == len(set(keys)), s
        payload = json.dumps(rows, ensure_ascii=False, separators=(',', ':'))
        assert JTAG not in payload and '$oht0065$' not in payload
        sql = TEMPLATE.format(subject=s, n=len(rows), tsv=TSV[s], owner=OWNER, jtag=JTAG,
                              payload=payload, cell_source=CELL_SOURCE, note=NOTE)
        path = os.path.join(OUT, f'{s}.sql')
        open(path, 'w').write(sql)
        print(s, len(rows), path, len(sql))

if __name__ == '__main__':
    main()
