begin;
do $$ begin if exists (select 1 from app.content_items where exam_pack_version_id='2d88ba5e-a6a3-43b8-bfae-9e5505a178a7' and content_key='APBIO-MCQ-SV-025-v3') then raise exception 'already loaded'; end if; end $$;
with item_ins as (
  insert into app.content_items (id, exam_pack_version_id, content_key, item_type, title, status)
  select gen_random_uuid(), '2d88ba5e-a6a3-43b8-bfae-9e5505a178a7', 'APBIO-MCQ-SV-025-v3', 'mcq', 'Aquaporin knockout and swelling rate', 'draft' returning id
), version_ins as (
  insert into app.content_item_versions (id, content_item_id, version_num, stem, stimulus, content_hash, status, review_status, canonical_answer_1)
  select gen_random_uuid(), id, 1, $q$Red blood cells contain aquaporin-1 (AQP1) channels. When wild-type red blood cells are moved into a hypotonic solution, they swell and lyse in about 20 seconds. Red blood cells from mice lacking AQP1 also swell and lyse in the same solution, but only after about 60 seconds, which is 3 times as long as the wild type. The solutions and internal osmolarities are identical in both groups. Which explanation best accounts for the difference?$q$, null, md5('APBIO-MCQ-SV-025-v3'), 'draft', 'tutor_review_pending', 'A' from item_ins returning id
)
insert into app.mcq_choices (id, content_item_version_id, choice_key, choice_text, is_correct, rationale)
select gen_random_uuid(), id, 'A', $q$Without AQP1, water still crosses by diffusing through the phospholipid bilayer, but more slowly, so the cells swell and lyse after a longer time.$q$, true, $q$Aquaporins speed water movement; without them, osmosis still occurs across the bilayer, but at a lower rate.$q$ from version_ins union all select gen_random_uuid(), id, 'B', $q$AQP1 channels use ATP to push water into the cell, so cells lacking them have less energy to draw in water.$q$, false, $q$Water moves by osmosis down its gradient; aquaporins are passive channels that do not use ATP.$q$ from version_ins union all select gen_random_uuid(), id, 'C', $q$The knockout cells have a lower internal solute concentration, so the osmotic gradient is smaller and swelling is slower.$q$, false, $q$The problem states that the solutions and internal osmolarities are identical, so the gradient is the same in both groups.$q$ from version_ins union all select gen_random_uuid(), id, 'D', $q$Without AQP1, water cannot cross the plasma membrane, so the knockout cells swell only because solutes enter them over time.$q$, false, $q$The knockout cells lyse in a hypotonic solution, which requires water entry, so water still crosses the membrane.$q$ from version_ins;
do $$ declare h text; begin
 select md5(civ.stem||'|'||string_agg(c.choice_key||':'||c.choice_text||':'||c.is_correct::text||':'||c.rationale,'|' order by c.choice_key)) into h from app.content_items ci join app.content_item_versions civ on civ.content_item_id=ci.id join app.mcq_choices c on c.content_item_version_id=civ.id where ci.content_key='APBIO-MCQ-SV-025-v3' and ci.exam_pack_version_id='2d88ba5e-a6a3-43b8-bfae-9e5505a178a7' group by civ.stem;
 if h is distinct from '833542fd09e496f0280577337ef36101' then raise exception 'hash mismatch %', h; end if; end $$;
create temporary table t on commit drop as select ci.id item_id, civ.id version_id, gen_random_uuid() lab_id, gen_random_uuid() vd_id, gen_random_uuid() cell_vd from app.content_items ci join app.content_item_versions civ on civ.content_item_id=ci.id where ci.content_key='APBIO-MCQ-SV-025-v3' and ci.exam_pack_version_id='2d88ba5e-a6a3-43b8-bfae-9e5505a178a7';
update app.content_items i set status='reviewed_approved', updated_at=now() from t where i.id=t.item_id;
update app.content_item_versions v set status='reviewed_approved', review_status='question_review_approved', approved_at=now(), approved_by='f5a26c6b-3566-4d58-9e97-979fbb947564' from t where v.id=t.version_id;
update app.content_items i set status='published', updated_at=now() from t where i.id=t.item_id;
update app.content_item_versions v set status='published', published_at=now() from t where v.id=t.version_id;
update app.content_items i set status='published', updated_at=now() from t where i.id=t.item_id;
insert into app.content_taxonomy_labels (content_taxonomy_label_id,content_item_id,label_version,label_scope,required_units,max_required_unit,primary_unit,assessed_topics,taxonomy_source_version,taxonomy_confidence,label_status,source,model_run_id,created_by)
select lab_id,item_id,1,'serving','{2}'::int[],2,2,array[]::text[],'c676d1fc-3b58-4896-89e3-852d9bd1f81b'::uuid,'provisional','provisional_model','apbio_025v3_restore_2026_10_03','apbio-025v3-restore-2026-10-03 (gemini-3.8-flash + deepseek-v4-pro blind: topic 2.6, unit 2)','f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid from t;
insert into app.content_taxonomy_validation_decisions (validation_decision_id,content_taxonomy_label_id,decided_by,decision,decision_source,reviewed_primary_unit,reviewed_required_units,notes)
select vd_id,lab_id,'f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid,'confirmed','automated_spot_check',2,'{2}'::int[],'Product Owner chat instruction 2026-10-03 (restore Biology 025-v3). Two-checker blind consensus: topic 2.6, unit 2.' from t;
update app.content_taxonomy_labels l set label_status='validated', validated_by='f5a26c6b-3566-4d58-9e97-979fbb947564'::uuid, validated_at=now(), validation_decision_id=t.vd_id, validated_against_version_id=t.version_id, validated_against_taxo_hash=app.taxonomy_relevant_hash(t.version_id) from t where l.content_taxonomy_label_id=t.lab_id;
insert into app.content_item_cells (content_item_version_id,content_item_id,taxonomy_source_version,topic_code,skill_code,is_primary,assignment_status,source,model_run_id,validated_by,validated_at,validation_decision_id)
select version_id,item_id,'c676d1fc-3b58-4896-89e3-852d9bd1f81b'::uuid,'2.6',null,true,'validated','apbio_025v3_restore_2026_10_03','apbio-025v3-restore-2026-10-03 (topic 2.6 by both checkers)',null,now(),cell_vd from t;
select ci.content_key, civ.status, l.label_status, l.validated_against_taxo_hash=app.taxonomy_relevant_hash(civ.id) hash_ok, (select count(*) from app.mcq_choices where content_item_version_id=civ.id) nchoices from t join app.content_items ci on ci.id=t.item_id join app.content_item_versions civ on civ.id=t.version_id join app.content_taxonomy_labels l on l.content_taxonomy_label_id=t.lab_id;
commit;