#!/usr/bin/env python3
"""Generate chunked Production apply files (APPROVAL-0127) using gen_sql.py's body()/apply_targets() unchanged.
gen_sql.py is executed with Path.write_text disabled so the original full files are not rewritten."""
import pathlib, json
HERE = pathlib.Path(__file__).resolve().parent
_orig_write = pathlib.Path.write_text
pathlib.Path.write_text = lambda self, *a, **k: None
ns = {"__file__": str(HERE / "gen_sql.py"), "__name__": "gen_sql"}
import sys; _argv = sys.argv; sys.argv = [sys.argv[0]]
exec(compile((HERE / "gen_sql.py").read_text(), "gen_sql.py", "exec"), ns)
sys.argv = _argv
pathlib.Path.write_text = _orig_write

APPROVAL = "'APPROVAL-0127'"
CHUNK = 25
t_clean = ns["t_clean"]; assert len(t_clean) == 191
chunks = [t_clean[i:i + CHUNK] for i in range(0, len(t_clean), CHUNK)]
manifest = []
for i, ch in enumerate(chunks, 1):
    name = f"prod_apply_chunk_{i:02d}.sql"
    hdr = (f"-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk {i:02d}/{len(chunks)} ({len(ch)} of 191 clean_match rows)\n"
           f"-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,\n"
           f"-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.\n")
    (HERE / name).write_text(hdr + ns["body"]("stem-choice-cleanup-2026-10-06", APPROVAL, ch, ns["reason_apply"], True))
    manifest.append({"file": name, "n": len(ch), "version_ids": [t[0] for t in ch], "content_keys": [t[1] for t in ch],
                     "to_md5": [ns["md5"](t[3]) for t in ch]})
t_rev = ns["t_rev"]; assert len(t_rev) == 7
(HERE / "prod_apply_review7_approved.sql").write_text(
    "-- Stem/choice cleanup 2026-10-06 -- review7 PRODUCTION APPLY, Approval: APPROVAL-0127. Generated by gen_chunks.py.\n" +
    ns["body"]("stem-choice-cleanup-review7-2026-10-06", APPROVAL, t_rev,
               "stem/choice cleanup (reviewed): inline answer-choice list removed, trailing assumption sentence kept; choices, units and topics unchanged", True))
manifest.append({"file": "prod_apply_review7_approved.sql", "n": 7, "version_ids": [t[0] for t in t_rev],
                 "content_keys": [t[1] for t in t_rev], "to_md5": [ns["md5"](t[3]) for t in t_rev]})
(HERE / "chunks_manifest.json").write_text(json.dumps(manifest, indent=1) + "\n")
for m in manifest: print(m["file"], m["n"], (HERE / m["file"]).stat().st_size)
