-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 04/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "27ef02be-bead-4584-8fbe-e26f6f7c3b5d",
"content_key": "apchem-mcq-011",
"from_md5": "e853c722b9ecacdf761c1c7858e85a47",
"to_stem": "Doubling [A] quadruples the rate while other concentrations remain fixed. The reaction is",
"choices_md5": "4737a13de1f31bb382ea476e5afaba04"
},
{
"version_id": "2038acfa-ec05-4cc8-b1d3-8d126b2a6461",
"content_key": "apchem-mcq-012",
"from_md5": "3aad50d32cb82567f35ca8c8d2270e21",
"to_stem": "A catalyst speeds a reaction because it",
"choices_md5": "6e282afcca07bed6ff5b807a7b032267"
},
{
"version_id": "ec5e88d3-622a-482a-b89d-cefc3cf7afd5",
"content_key": "apchem-mcq-013",
"from_md5": "34e151472b3461e15441aae405f6e96b",
"to_stem": "A 100 g metal absorbs 2.50 kJ and warms by 50.0°C. Its specific heat is",
"choices_md5": "b6cbb289b5db41e2ff05201f4ab81a6e"
},
{
"version_id": "9e7fff7f-3d3c-491a-9b12-4aaba7890769",
"content_key": "apchem-mcq-014",
"from_md5": "779e1d1adc1964af5e7e837af1f04e52",
"to_stem": "If ΔH is negative for a process at constant pressure, the system",
"choices_md5": "ec7eefb4ffae7761f78bd97925a80f7b"
},
{
"version_id": "e47eb90a-bc6a-4f7e-a10c-3b7b4a66a9ef",
"content_key": "apchem-mcq-015",
"from_md5": "746345d6a0f5a58156fcc43c0ccf03cd",
"to_stem": "For a reaction with Q<K, the system initially shifts",
"choices_md5": "b3a059c829b0c5f37d3127ac74ca6cec"
},
{
"version_id": "1c65cbef-2352-4274-b12e-05f781c3a9e7",
"content_key": "apchem-mcq-016",
"from_md5": "ac7a2930d487cbc6ee0176b9be89c352",
"to_stem": "Adding an inert gas at constant volume and constant temperature does not change an ideal-gas equilibrium because",
"choices_md5": "80cf77856d3afe585eb37f3ff49c64a4"
},
{
"version_id": "f79fcfa0-ec2e-4c06-a21b-abe42c8b4f3b",
"content_key": "apchem-mcq-018",
"from_md5": "bc3e937cfb1777deaa7f5637e53b07da",
"to_stem": "A buffer contains comparable amounts of HA and A⁻. Adding a small amount of H⁺ primarily causes",
"choices_md5": "6aa4c7f3919b9c648bbb65989f8aaef0"
},
{
"version_id": "cc5c9ef2-1b56-4ec4-902c-5bfa11b61c71",
"content_key": "apchem-mcq-019",
"from_md5": "465d19e8b01c33cbc9187671345e5797",
"to_stem": "At constant temperature and pressure, a process is thermodynamically favorable when",
"choices_md5": "9aa2c1db5413184604ea9a14e2d33aa9"
},
{
"version_id": "93e8cec6-75df-4826-b28a-37dbbe6100a0",
"content_key": "apchem-mcq-020",
"from_md5": "a4cf1a4a5b1d166aa3dc0664eb472b06",
"to_stem": "For a galvanic cell under standard conditions, E°cell>0 implies",
"choices_md5": "1f8dcdc40d496e176362891c01c27a95"
},
{
"version_id": "1ddc5cee-33ed-4b0d-aa0b-185da24a051e",
"content_key": "apchem-mcq-021",
"from_md5": "bbe6c056583dc6ac04bac4c8c97726a9",
"to_stem": "A sample of pure glucose (C6H12O6, molar mass = 180.16 g/mol) has a mass of 90.0 g. How many moles of glucose does the sample contain?",
"choices_md5": "41b677f178b06157ca9286885dd1397a"
},
{
"version_id": "e6ee9d9a-9633-4bf5-8370-ed02fe2fdb46",
"content_key": "apchem-mcq-022",
"from_md5": "dea33aa31e1f3742b3c0b835fa9f760a",
"to_stem": "What is the ground-state electron configuration of the Fe3+ ion (Fe, Z = 26, ground-state configuration [Ar]3d^6 4s^2)?",
"choices_md5": "d7108655a2d6271704289538a900e40e"
},
{
"version_id": "99803fab-c449-4a33-8a8e-859eee468990",
"content_key": "apchem-mcq-023",
"from_md5": "a8cca9ce5ed30261876bdea13ff8f911",
"to_stem": "The photoelectron spectrum of a neutral atom of an unknown element shows exactly four peaks. Listed in order of decreasing binding energy, the relative peak areas (relative numbers of electrons) are 2, 2, 6, and 2. Identify the element.",
"choices_md5": "38b9a8d1d7289f78c3923f5fead2002a"
},
{
"version_id": "89a2d1d9-1c53-45e0-8037-659ccb349392",
"content_key": "apchem-mcq-024",
"from_md5": "203422a14e103f6ff619c0332c62a1bb",
"to_stem": "The first ionization energy of magnesium (738 kJ/mol) is greater than that of aluminum (578 kJ/mol), even though aluminum has a higher nuclear charge. Which statement correctly explains this trend?",
"choices_md5": "e382a2f60450a537af8b39f016be7e3f"
},
{
"version_id": "0c3b7b61-5083-4f8f-aced-2e0d50ea22b5",
"content_key": "apchem-mcq-025",
"from_md5": "4252b945e3a300262ac7b33e38cd7974",
"to_stem": "Based on electronegativity differences (using the Pauling scale: Cs = 0.79, C = 2.55, H = 2.20, O = 3.44, F = 3.98, N = 3.04), which pair of atoms would be predicted to form a bond with the greatest ionic character?",
"choices_md5": "393ccda3ce4edad9cb3b0102b5845c62"
},
{
"version_id": "0a535dc3-dbc8-456d-a9fd-5e228246be63",
"content_key": "apchem-mcq-026",
"from_md5": "b0794d5230341c5385b15de6a150b34e",
"to_stem": "Which of the following species requires an expanded (greater than octet) valence shell around its central atom in its best Lewis structure?",
"choices_md5": "c3cf58d68ea97cb0790f3b6f269589a1"
},
{
"version_id": "f68af92a-ea07-43b1-9567-553ad9d4f703",
"content_key": "apchem-mcq-027",
"from_md5": "d9848cc804490a9a97a66d22804aea78",
"to_stem": "The nitrite ion, NO2-, is represented by two equivalent resonance contributors in which nitrogen forms one N=O double bond and one N–O single bond (with the negative charge delocalized by resonance). In this Lewis structure, what is the formal charge on the singly-bonded oxygen atom?",
"choices_md5": "63a0e6e07d6cb5f1d108c635f5a52e01"
},
{
"version_id": "8c5798af-66dc-4e70-a7a4-522e217784a3",
"content_key": "apchem-mcq-028",
"from_md5": "c369f99731ec8f6c97ef820464ede051",
"to_stem": "What are the electron-domain geometry and molecular (molecular-domain) shape of SF4?",
"choices_md5": "72a35296ee4e4be8e096f2e7bda83fdf"
},
{
"version_id": "0d6df8e6-6334-459c-9b1e-a7044546e314",
"content_key": "apchem-mcq-029",
"from_md5": "0629abf5742b933bda4752c2055eac15",
"to_stem": "Which substance is expected to have the highest normal boiling point?",
"choices_md5": "f07b395704ec8b7e646e01367129ff08"
},
{
"version_id": "0a499374-2bed-4302-9eee-5bc170186ca0",
"content_key": "apchem-mcq-030",
"from_md5": "64449b8c2939e0fd147613f1427b9e6e",
"to_stem": "CH3F and CH3OH have similar molar masses (34 g/mol and 32 g/mol, respectively), yet CH3OH has a substantially higher boiling point (65C) than CH3F (-78C). What best explains this difference?",
"choices_md5": "125a1d2272a57f9a54b38145f8f20887"
},
{
"version_id": "0baf4908-dc68-4ede-85ef-934d4cec725d",
"content_key": "apchem-mcq-031",
"from_md5": "12a40d06ad7efe89b33fca8ad506f701",
"to_stem": "A solid sample conducts electricity well in both its solid and molten states, is malleable (can be hammered into sheets without shattering), and has a moderately high melting point. What type of solid is this sample most likely to be?",
"choices_md5": "03730c76ea269cf0b889d2250e873aec"
},
{
"version_id": "c9df7103-b591-4276-844b-e60c9f74654f",
"content_key": "apchem-mcq-032",
"from_md5": "08b6430662c7412938c4d7fa69132393",
"to_stem": "A rigid 2.00 L container holds 0.500 mol of an ideal gas at 27C. What is the pressure of the gas? (R = 0.08206 L*atm/(mol*K))",
"choices_md5": "bc45d0a6a955722f19b954b134b0250b"
},
{
"version_id": "9e049c05-c49e-4b95-b4b9-a777c60c0d2e",
"content_key": "apchem-mcq-033",
"from_md5": "2a5c69328f95b5b0f6db644bbbbd27dc",
"to_stem": "Separate rigid containers hold samples of He(g) and O2(g) at the same temperature. According to kinetic molecular theory, which statement correctly compares the two samples?",
"choices_md5": "c03cd82826a5ebdce6b79ad758ca49b3"
},
{
"version_id": "9c848fdb-a55d-4e02-a30b-9c49cf007b4b",
"content_key": "apchem-mcq-034",
"from_md5": "e85311fc18641cc6c7b3a098d0aea642",
"to_stem": "Under which set of conditions would a real gas be expected to deviate most significantly from ideal gas behavior, and why?",
"choices_md5": "a68bbf7dbcd6fb6c6d82b311937f22d6"
},
{
"version_id": "abaf2bd3-3b9e-40fd-8737-c11733abbcdd",
"content_key": "apchem-mcq-035",
"from_md5": "ce603f7519b03035bf22d3117d93f9f4",
"to_stem": "As the temperature of water increases, the solubility of a gas such as O2(g) in the water generally decreases. Which statement best explains this observation?",
"choices_md5": "5b337265f1c178ce816084a116818343"
},
{
"version_id": "33ce2b12-d3ad-4bb2-b893-06e5202f7836",
"content_key": "apchem-mcq-036",
"from_md5": "f4eebdbd07f4456943711e03e55fb475",
"to_stem": "A colored solution has a molar absorptivity of 1.50 x 10^3 M^-1 cm^-1 at its wavelength of maximum absorbance. When placed in a cuvette with a 1.00 cm path length, the solution's absorbance is measured as 0.750. What is the molar concentration of the solution?",
"choices_md5": "5c587fad5a1e09bcd327b95b7ca15564"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
