-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 06/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "93314114-a6e2-497a-9b99-0f16cd20c9c2",
"content_key": "apchem-mcq-065",
"from_md5": "b41541f8ed95dce2accbdca0a5ea7682",
"to_stem": "Four buffer solutions are prepared using the same conjugate acid-base pair (same pKa). Which combination would provide the greatest buffer capacity?",
"choices_md5": "17ebb94eeccac0c42c002605071f7dcc"
},
{
"version_id": "e99c96f2-e0c4-47a6-8a42-993fafcf83a2",
"content_key": "apchem-mcq-067",
"from_md5": "2f88c4b88dfb95ce5611ad87b9f694c7",
"to_stem": "A galvanic cell is built from a Zn electrode in 1.0 M Zn(NO3)2 and a Cu electrode in 1.0 M Cu(NO3)2, connected by a wire and a salt bridge. E standard reduction (Cu2+/Cu) = +0.34 V; E standard reduction (Zn2+/Zn) = -0.76 V. Which statement correctly identifies the cathode and the direction of electron flow?",
"choices_md5": "6fb0795886269fa09f3645016ed7ceb0"
},
{
"version_id": "c5d5b783-6e2a-49db-9674-9df23e6b1bbe",
"content_key": "apchem-mcq-068",
"from_md5": "88f7504938662fc905e4df5f0196b8a7",
"to_stem": "A galvanic cell has a cathode half-reaction Ag+ + e- -> Ag(s), E = +0.80 V, and an anode half-reaction Pb(s) -> Pb2+ + 2e-, E(Pb2+/Pb) = -0.13 V. The overall balanced reaction transfers n = 2 mol electrons. What is deltaG for the cell reaction, and is it thermodynamically favorable?",
"choices_md5": "d3a2e17e1b70eb172c79fa1d7273a2df"
},
{
"version_id": "6e65dac8-3016-4cca-9461-77cbff9621b4",
"content_key": "apchem-mcq-069",
"from_md5": "a2d1daa1bb3b1b71e2e372373a4ebdea",
"to_stem": "For the cell Zn(s) | Zn2+(aq) || Cu2+(aq) | Cu(s), E°cell = +1.10 V. If [Cu2+] is decreased to well below 1 M while [Zn2+] remains at 1 M, how does the actual cell potential Ecell compare to E standard cell, and why?",
"choices_md5": "b171cddfb9b49cb50614f835c9ceca82"
},
{
"version_id": "701f1361-022e-4827-820b-60359240f885",
"content_key": "apchem-mcq-070",
"from_md5": "73de3426850ea75a06c020b488708038",
"to_stem": "A constant current of 2.00 A is passed through molten CaCl2 for 3.00 hours, depositing Ca(s) at the cathode via Ca2+ + 2e- -> Ca(s) (molar mass of Ca = 40.08 g/mol). What mass of Ca(s) is deposited?",
"choices_md5": "6dbc9837170225401e76bd1536b31c16"
},
{
"version_id": "80ab716d-cb3c-4226-a9c2-627e21309f9e",
"content_key": "apphy2-mcq-010",
"from_md5": "beb16cc6a960879abcf813d3e13ae402",
"to_stem": "A particle with charge q moves with speed v in a direction parallel to a uniform magnetic field of magnitude B. The magnetic force on the particle is--",
"choices_md5": "1fee493380a7dd0cc5ed7f59bfe814c5"
},
{
"version_id": "f8952991-b8db-4914-89a9-0a537f6ec5ae",
"content_key": "apphy2-mcq-012",
"from_md5": "a15c7e0ecc2d99f69d6b6acff7b3f763",
"to_stem": "Lenz's law determines the induced current's",
"choices_md5": "ab7e7785cd3be4b5ccdeb868f300f9a6"
},
{
"version_id": "6d4fc26b-a60d-4fc0-83e5-9f272a68994c",
"content_key": "apphy2-mcq-013",
"from_md5": "42eab5c0e0505142d89eb0dfa584af4b",
"to_stem": "A beam of monochromatic light travels from air into glass. As the light crosses the boundary, its frequency--",
"choices_md5": "0d851750eddd115c392bb5cd506194ba"
},
{
"version_id": "d1204237-373b-4ad7-a36c-803c6656cfd9",
"content_key": "apphy2-mcq-014",
"from_md5": "012b30ba3ba63cfa2c2c3300964b7a87",
"to_stem": "A converging lens forms a real inverted image when the object is",
"choices_md5": "14c1fb9544acc59f8e133ce5b6287d3a"
},
{
"version_id": "9d1fee80-d912-43d6-8746-f2795f09787b",
"content_key": "apphy2-mcq-016",
"from_md5": "f5daf84f84e428609edc5d18028e9e41",
"to_stem": "A periodic wave has frequency 5.0 Hz and wavelength 0.60 m. What is its speed?",
"choices_md5": "8d4fa6805c3a8fb7631d097c22b983ae"
},
{
"version_id": "0975e43b-f228-403c-8b10-3bb449942a51",
"content_key": "apphy2-mcq-017",
"from_md5": "c46f84c89cfd55fb02a7b7adfd0e0dee",
"to_stem": "Two coherent sources, initially in phase, emit waves of the same wavelength. Constructive interference at a point occurs when the path difference between the waves is",
"choices_md5": "d814e348c2bbd469bacceae272bf7b51"
},
{
"version_id": "21247dc8-cf80-4098-b5bc-a84792d7ca10",
"content_key": "apphy2-mcq-019",
"from_md5": "1a5d64c2478fcad2dfff3a7a4c07abbe",
"to_stem": "A photon has energy",
"choices_md5": "fc118c584dafdeeb7649d1e515e9f4e1"
},
{
"version_id": "eeae7b54-8e4a-4a14-bb34-d2c46a628fc0",
"content_key": "apphy2-mcq-020",
"from_md5": "32f70727e5d5a1c098c4e3acf3cbb2af",
"to_stem": "In the photoelectric effect, increasing the frequency of light above the threshold frequency primarily increases",
"choices_md5": "44f26c8cc3c8a06230df4595e6210198"
},
{
"version_id": "904498ef-0e49-49f1-99d5-98c5c53deb7b",
"content_key": "apphy2-mcq-031",
"from_md5": "810bbea9e2f953fbf36a052ad15689f8",
"to_stem": "A long straight wire carries current upward. At a point directly east of the wire, the magnetic field points",
"choices_md5": "26e2411117fd8d977cffe9b5b7616c7e"
},
{
"version_id": "9add92ae-19a8-4b53-aaeb-24362f0f4842",
"content_key": "apphy2-mcq-032",
"from_md5": "f981d2a7f7491d5df1d9d85910fde935",
"to_stem": "A charged particle moves perpendicular to uniform B. If its speed doubles with q, m, and B fixed, its circular-path radius",
"choices_md5": "eeaa3a58b4095409a165ef0318377f16"
},
{
"version_id": "5664df1f-203d-47f1-a544-227bbf2bfeb6",
"content_key": "apphy2-mcq-033",
"from_md5": "7ecddc0881000be0a7b7d8df2b4e2f91",
"to_stem": "The magnetic flux into the page through a loop is increasing. The induced current is",
"choices_md5": "9e343de23582cb6dea9d748700a475eb"
},
{
"version_id": "1124f048-e37b-4337-9cb6-b3305820973b",
"content_key": "apphy2-mcq-034",
"from_md5": "169a03545c4e72a25d5c69f8ed98ca02",
"to_stem": "A ray strikes a plane mirror at 25° measured from the normal. Its reflection angle measured from the normal is",
"choices_md5": "056f731e0a5dd84df0501efc383aeab5"
},
{
"version_id": "baebe382-6429-4f75-a28f-e0e40e964daa",
"content_key": "apphy2-mcq-035",
"from_md5": "c3aa52763411f19bcd28bebb39d9d571",
"to_stem": "A plane mirror forms an image that is",
"choices_md5": "4fca05b86ac1412cc5ac6e1b1db606cb"
},
{
"version_id": "1ff33c89-a38e-43f1-b83d-88261d6ba0ac",
"content_key": "apphy2-mcq-036",
"from_md5": "e2d051534c67627f58f7a024d519b07d",
"to_stem": "Light enters glass from air at an oblique angle. Because glass has larger refractive index, the ray bends",
"choices_md5": "63410fef6f622d3ff1b584133f3451c0"
},
{
"version_id": "f9bd3c8d-0ee2-4783-902f-e721a867b065",
"content_key": "apphy2-mcq-037",
"from_md5": "695b04bf731200d4a8d4a01a41397240",
"to_stem": "A periodic wave crosses into a medium where its speed decreases. Its frequency",
"choices_md5": "723954e520bd97794f6949de88d3be98"
},
{
"version_id": "81d4eb9c-d8b7-4df1-a229-8abd0aab3af3",
"content_key": "apphy2-mcq-038",
"from_md5": "4e32d7b354c3187aa5fd691cfa07319e",
"to_stem": "In an electromagnetic wave in vacuum, electric and magnetic fields are",
"choices_md5": "a2cf160c70e8bb866b7ab2b5f654a6fb"
},
{
"version_id": "d7a58c0f-488b-4eae-946a-2bb6223f4e20",
"content_key": "apphy2-mcq-039",
"from_md5": "b96af133974aaf75393f5054c0fdccdd",
"to_stem": "A sound source moves away from a stationary observer. The observed frequency is",
"choices_md5": "3706881860956e794245e795f6345be3"
},
{
"version_id": "c0cf1fa7-2e01-4dca-85e2-6e1dad5bb9b4",
"content_key": "apphy2-mcq-040",
"from_md5": "472ff0fcee5e239b2250ef38696158bc",
"to_stem": "A bright atomic emission line is produced when an electron",
"choices_md5": "19cb92b9b43743ced269bd2c1a307291"
},
{
"version_id": "88061f49-923f-46f4-830c-ad9ef63db3d8",
"content_key": "apphy2-mcq-041",
"from_md5": "dbe1254714254d327424cbfecb96c702",
"to_stem": "In Compton scattering, an X-ray photon transfers energy and momentum to an electron. The scattered photon's wavelength is generally",
"choices_md5": "a681a699a9b072c4228eb3db362eb729"
},
{
"version_id": "425aa4fb-4a89-4c9a-965f-024d59f67674",
"content_key": "apphy2-mcq-042",
"from_md5": "9aac244c9222682f23e9a684261e57e9",
"to_stem": "In beta-minus decay, a neutron changes into",
"choices_md5": "00e06df410fea1220d1e2098d1c76cc4"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
