-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 05/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "58bd9254-2451-49bb-bad2-eeac957d595a",
"content_key": "apchem-mcq-037",
"from_md5": "4d169225112a98c062e52400adf0d76e",
"to_stem": "A photon of ultraviolet (UV) light is compared to a photon of infrared (IR) light. Which statement correctly ranks their energies and justifies the ranking?",
"choices_md5": "c8a6d591fa5e1e3a1003596cb74f0716"
},
{
"version_id": "a43ad81a-5ac8-4f74-8d40-2b88f7c30f0c",
"content_key": "apchem-mcq-038",
"from_md5": "04e734f1581ef70734789c05b4f285f9",
"to_stem": "A chemist needs to recover acetone (boiling point 56 °C) from a homogeneous mixture of acetone and water (boiling point 100 °C). The two liquids are miscible and do not form an azeotrope. Which technique is most appropriate, and why?",
"choices_md5": "351cbdbf7d10d155d11c0dc80f9d621b"
},
{
"version_id": "e5477db9-0823-45d2-9f56-d031977b10d7",
"content_key": "apchem-mcq-039",
"from_md5": "3275dc9e6fe314d5c4814cf32fd9d1c3",
"to_stem": "A student dilutes 25.0 mL of a 2.00 M stock solution to a final total volume of 200.0 mL. What is the molarity of the resulting diluted solution?",
"choices_md5": "9c6eabb1d65bd7b71cda58f2d27a4b6f"
},
{
"version_id": "7c443eb4-8aad-493d-a4d3-02190ca66b7f",
"content_key": "apchem-mcq-040",
"from_md5": "4d5e98f6e3cd59b14edfe6445ee1089d",
"to_stem": "A student reacts 5.4 g of Al (molar mass 27.0 g/mol) with 3.2 g of O2 (molar mass 32.0 g/mol) according to the balanced equation 4Al(s) + 3O2(g) -> 2Al2O3(s) (molar mass Al2O3 = 102.0 g/mol). What mass of Al2O3 is produced, assuming the reaction goes to completion?",
"choices_md5": "b9ab7a3d610cae4095f3824d99465d62"
},
{
"version_id": "257f5379-6555-4286-b85b-7a41fba7842a",
"content_key": "apchem-mcq-041",
"from_md5": "9d0e89e3beaef44640d7246b6d3680c2",
"to_stem": "Aqueous solutions of Pb(NO3)2 and KI are mixed, forming a yellow precipitate: Pb(NO3)2(aq) + 2KI(aq) -> PbI2(s) + 2KNO3(aq). Which equation correctly represents the net ionic equation for this reaction?",
"choices_md5": "5583dd7cad3c60daf456e2d58ce29570"
},
{
"version_id": "02408752-a11b-40fd-b99f-5d5abc5abf5e",
"content_key": "apchem-mcq-042",
"from_md5": "761e8b3d94c2c0fa06a3e93f7bb0ea1a",
"to_stem": "In the reaction Zn(s) + 2AgNO3(aq) -> Zn(NO3)2(aq) + 2Ag(s), which species is the oxidizing agent, and how does its oxidation state change?",
"choices_md5": "125abfbf3cda6dc90f24d1ebc70ba247"
},
{
"version_id": "99b2b547-b2a8-49a9-bf16-c692589ec7c6",
"content_key": "apchem-mcq-043",
"from_md5": "c9c4c1e033a55f18ce6e01660bde7b2a",
"to_stem": "Which type of chemical reaction is represented by CaCO3(s) -> CaO(s) + CO2(g) upon heating?",
"choices_md5": "74758df1b46806294c168059ab7d7823"
},
{
"version_id": "b050e0db-5eb9-45c9-a00a-4d40a08c13cb",
"content_key": "apchem-mcq-044",
"from_md5": "a5be18aa02acf3fcc967839ca012a993",
"to_stem": "A 25.00 mL sample of HCl(aq) is titrated to the equivalence point using 0.100 M NaOH(aq), requiring 32.50 mL of titrant according to HCl(aq) + NaOH(aq) -> NaCl(aq) + H2O(l). What is the concentration of the HCl solution?",
"choices_md5": "ceb03c601adfc778e4d8067097d5068d"
},
{
"version_id": "3b490535-520e-4500-98b6-e83034141f46",
"content_key": "apchem-mcq-045",
"from_md5": "1447001874d980c6256a0323108387bb",
"to_stem": "Dinitrogen pentoxide decomposes according to the equation 2 N2O5(g) -> 4 NO2(g) + O2(g). At a certain point during the reaction, O2 is forming at a rate of 0.015 M/s. What is the rate of disappearance of N2O5 at that same instant?",
"choices_md5": "f17369f9e70f65c806bb5d6d1656672a"
},
{
"version_id": "938c2a66-d889-4b80-bfb0-858f425e30d0",
"content_key": "apchem-mcq-046",
"from_md5": "2f4ed3be144c547bcc94706619946948",
"to_stem": "The elementary step 2 X(g) + Y(g) -> products is proposed as part of a reaction mechanism. Which rate law is consistent with this elementary step?",
"choices_md5": "d0dc7aa87641d3dc10a1b9f358db2010"
},
{
"version_id": "06cc21e7-d68c-4a8f-a463-a13dcae0d066",
"content_key": "apchem-mcq-047",
"from_md5": "094c6fbe298a4d16c05f775a400c6615",
"to_stem": "A one-step reaction has an activation energy for the forward reaction, Ea(fwd), of 45 kJ/mol and an overall enthalpy change, deltaH, of -20 kJ/mol. What is the activation energy for the reverse reaction, Ea(rev)?",
"choices_md5": "76f9539fae7ad6ab45fb84ff87add55d"
},
{
"version_id": "4d27c8d2-8521-4043-a254-09a6f5c85998",
"content_key": "apchem-mcq-048",
"from_md5": "7b8c7a5318dbd49d78b88f4f50c1242d",
"to_stem": "Which of the following correctly describes how a catalyst increases the rate of a chemical reaction?",
"choices_md5": "692a405e96f2ac377c90f7cc7c7d8da0"
},
{
"version_id": "ad10a23b-bc26-45e7-ab78-47c9cea66001",
"content_key": "apchem-mcq-049",
"from_md5": "235b16ec0a24dea12afda7a46b60fc1f",
"to_stem": "A student dissolves a sample of solid ammonium nitrate in water inside a coffee-cup calorimeter. As the solid dissolves, the temperature of the solution drops from 25.0 C to 18.5 C. Which statement correctly describes this dissolution process?",
"choices_md5": "50803c06235bff406950c8b46f8db630"
},
{
"version_id": "7456dabc-c72b-49a3-976f-76cc224fcd83",
"content_key": "apchem-mcq-051",
"from_md5": "ac31acb0372d6f59e99fbb8f8619b50e",
"to_stem": "Using average bond enthalpies (H-H = 436 kJ/mol, Cl-Cl = 243 kJ/mol, H-Cl = 431 kJ/mol), estimate deltaH for the reaction: H2(g) + Cl2(g) -> 2 HCl(g)",
"choices_md5": "3b88f3038475fd338c639c41fd7d6514"
},
{
"version_id": "389fc6e4-cd85-4680-9722-0932d615c709",
"content_key": "apchem-mcq-052",
"from_md5": "387751842e5dbb43c826fd20aa0f4073",
"to_stem": "Given standard enthalpies of formation Delta Hf standard: CH4(g) = -74.8 kJ/mol, CO2(g) = -393.5 kJ/mol, H2O(l) = -285.8 kJ/mol, and O2(g) = 0 kJ/mol, calculate Delta H(rxn) for: CH4(g) + 2 O2(g) -> CO2(g) + 2 H2O(l)",
"choices_md5": "dcee3a45203864e1788663da3afd98eb"
},
{
"version_id": "2f157e6c-4421-4989-a060-67b59ed1d9e0",
"content_key": "apchem-mcq-053",
"from_md5": "225419cab1ad13d755576dcd822589e2",
"to_stem": "Given the following thermochemical equations:\n(1) C(s) + O2(g) -> CO2(g), deltaH1 = -393.5 kJ\n(2) CO(g) + 1/2 O2(g) -> CO2(g), deltaH2 = -283.0 kJ\nUse Hess's Law to find deltaH for: C(s) + 1/2 O2(g) -> CO(g)",
"choices_md5": "bfeaf01b1b6ef62bf42be6e6a49b54cf"
},
{
"version_id": "3171c639-e6e3-4775-9961-b83609deec9e",
"content_key": "apchem-mcq-054",
"from_md5": "99b7dc82667b67d3aebf59d26d8b5736",
"to_stem": "For the heterogeneous equilibrium CaCO3(s) <-> CaO(s) + CO2(g), which expression correctly represents the equilibrium constant, Kc?",
"choices_md5": "4793d431804dd91237629519589e46f2"
},
{
"version_id": "187c11be-5220-4b94-9e0a-a5c1b1f7c720",
"content_key": "apchem-mcq-055",
"from_md5": "84c1fca60d68f7c0115a19c33631bb85",
"to_stem": "At a given temperature, a reaction has Kc = 4.3 x 10^-9. What does this value indicate about the reaction mixture at equilibrium?",
"choices_md5": "402c8f93e43da942ba41f2a4cb16b123"
},
{
"version_id": "3ce5264a-7c9e-42b2-a4a0-65227fee2021",
"content_key": "apchem-mcq-056",
"from_md5": "52821c51577eb901273de78233a79c86",
"to_stem": "For N2(g) + 3H2(g) <-> 2NH3(g), Kc = 0.50 at a certain temperature. A reaction mixture is sampled and Qc is calculated to be 2.0. Which statement correctly describes how the system will respond?",
"choices_md5": "a93818be453123671cd7fd3e27b231d6"
},
{
"version_id": "fbbbb532-1691-4ea7-bda7-729e1fb15a1c",
"content_key": "apchem-mcq-058",
"from_md5": "ce64acf42b18a58de37cb6608e098b99",
"to_stem": "In the reaction HSO4-(aq) + H2O(l) <-> H3O+(aq) + SO4^2-(aq), which species is the conjugate base of HSO4-?",
"choices_md5": "ae1b276f40a14fbbf100891a0840f6de"
},
{
"version_id": "913eb429-6989-4f9f-ad24-98ee98b55a93",
"content_key": "apchem-mcq-059",
"from_md5": "c84f05cf825ae52d9c20c2e02114f95e",
"to_stem": "What is the pOH of a 0.0025 M HCl solution at 25 C? (HCl is a strong acid.)",
"choices_md5": "4ca0fc9e111281be0548f86d4a0534dc"
},
{
"version_id": "b71d2ae6-5884-490e-b44b-3335aa936980",
"content_key": "apchem-mcq-060",
"from_md5": "ca751d54465c7dbd9b8238e55d46a5d2",
"to_stem": "A 0.10 M solution of a weak monoprotic acid HA has Ka = 1.0x10^-5. Assuming the approximation x much less than 0.10 is valid, what is the pH of the solution?",
"choices_md5": "ad9c78549873c1fb0956597539556188"
},
{
"version_id": "c68402dd-2032-41bc-91fb-84b1c0d9d529",
"content_key": "apchem-mcq-062",
"from_md5": "152612ca27ace151721e661a9339d0ef",
"to_stem": "Which of the following hypohalous acids is the strongest acid, and why?",
"choices_md5": "7b0dd30c6f3ea0e4bebe429b19cb6b70"
},
{
"version_id": "aa03ff47-9e9b-4401-83d8-636f6d537918",
"content_key": "apchem-mcq-063",
"from_md5": "1a64a3724e3ddc39d54af856cfd5795a",
"to_stem": "During the titration of a weak monoprotic acid with NaOH, the pH at the half-equivalence point is measured to be 4.74. What is the Ka of the acid?",
"choices_md5": "45b6968476f6b3f5f1e7244effac1099"
},
{
"version_id": "a3b6c60a-1b4e-47d7-8c19-93abbcb05e03",
"content_key": "apchem-mcq-064",
"from_md5": "216b9b8fef376f56c202aa4d7b4b5d53",
"to_stem": "A buffer solution contains 0.30 M sodium acetate (CH3COONa) and 0.15 M acetic acid (CH3COOH), where acetic acid has Ka = 1.8x10^-5 (pKa = 4.74). What is the pH of this buffer?",
"choices_md5": "6e5531f86b528041a3719d38077d7c6e"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
