-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 03/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "f4ea3f50-3a6d-460e-b40a-1be96890e04b",
"content_key": "apcalcbc-mcq-045",
"from_md5": "f9695ec647af855423e8a05b96c6888d",
"to_stem": "A curve is given by x=t+sin t and y=1−cos t. What is d²y/dx² at t=1, to the nearest thousandth?",
"choices_md5": "9e329682bdac19824c08e523ad9fb663"
},
{
"version_id": "194278ff-5e81-4785-a965-ce99467e3adc",
"content_key": "apcalcbc-mcq-046",
"from_md5": "5fb80aedf337eb6c908c339e066f7e60",
"to_stem": "What is the sum of Σ[n=1 to ∞] 5(−1/3)^(n−1)?",
"choices_md5": "cb2f15426be81c351d537344a77c9b97"
},
{
"version_id": "29374f52-56b5-4d44-8d07-182d10f36644",
"content_key": "apcalcbc-mcq-047",
"from_md5": "0d515435cbbfdfd1c9a0fe84ea5db0e6",
"to_stem": "Which statement describes Σ[n=1 to ∞](−1)^(n+1)/√n?",
"choices_md5": "8c5a7d6302e809bddcdf73e56bd49cde"
},
{
"version_id": "65eb803d-fa43-4292-81fe-dc81a672befc",
"content_key": "apcalcbc-mcq-048",
"from_md5": "1af2660bc176d514dba0a3144d40e7d3",
"to_stem": "What is the interval of convergence of Σ[n=1 to ∞](x−2)^n/(n3^n)?",
"choices_md5": "d4a8354db5690e28399dfb1c3d50e833"
},
{
"version_id": "4db8a57a-2691-4428-9e8c-2e806f26df40",
"content_key": "apcalcbc-mcq-049",
"from_md5": "707627b45bc38a14beddbe71ef6e8972",
"to_stem": "The degree-5 Maclaurin polynomial for sin x is used at x=0.7. Which is a valid Lagrange error bound?",
"choices_md5": "c2ba8402b642198275e340c4e51a4efc"
},
{
"version_id": "6fb0f714-1f8b-47fd-9c84-2caf309ee9f1",
"content_key": "apcalcbc-mcq-050",
"from_md5": "678f52c4cdf09a64c9fc1d81c0e46635",
"to_stem": "What is the coefficient of x⁷ in the Maclaurin series for x²e^(−x)?",
"choices_md5": "bffad66e4f4b94898f5c3923eb091511"
},
{
"version_id": "2f26bf80-3101-48fd-960f-526221f2a464",
"content_key": "apcalcbc-mcq-ab-021",
"from_md5": "575d6b06c192c30964109a41afeac1b3",
"to_stem": "What is lim(x→2) (x²−4)/(x−2)?",
"choices_md5": "2e9f06f5e3cc5c17fc410d7a82b5b7b0"
},
{
"version_id": "98425cfb-20e4-4325-a0bd-cb5a1a3050a2",
"content_key": "apcalcbc-mcq-ab-022",
"from_md5": "c231ce20d0e1c12ce4075e92c2d85cda",
"to_stem": "Let f(x)=kx+1 for x<2 and f(x)=x²−1 for x≥2. For what value of k is f continuous at x=2?",
"choices_md5": "974d9e9326ac34f5f2c4c96b9bd74788"
},
{
"version_id": "d690b8fc-67ea-4ad9-85d4-2408e38a3cf6",
"content_key": "apcalcbc-mcq-ab-024",
"from_md5": "72e282b336b9a4253187298e2c835cd5",
"to_stem": "What is lim(x→∞) (5x²−x+4)/(2x²+3)?",
"choices_md5": "d65b8564fb770d5a7de48cdd75232aa8"
},
{
"version_id": "98d30b24-d358-4a14-b7ff-11a9251c86b4",
"content_key": "apcalcbc-mcq-ab-025",
"from_md5": "163d8c51894d4e4254859bc35d7363bc",
"to_stem": "Which expression equals f′(3)?",
"choices_md5": "ee91542a00e0bdb6499ae40880646da9"
},
{
"version_id": "3b0ec592-ec60-4dc7-8aa3-3db8a02c0cb9",
"content_key": "apcalcbc-mcq-ab-026",
"from_md5": "6a4c960b7d73c682605172bb98276792",
"to_stem": "If f(x)=x²e^x, what is f′(1)?",
"choices_md5": "c053b0503fbe903d211b172701dd8741"
},
{
"version_id": "ff2d65f4-eb9b-4a30-907f-42bb3d2e82ea",
"content_key": "apcalcbc-mcq-ab-027",
"from_md5": "3f06ad188a925fb63f30f269787032a8",
"to_stem": "What is d/dx[sec x tan x]?",
"choices_md5": "a2708819463195919a1e9981c92586eb"
},
{
"version_id": "30fe73a6-7911-46a5-9c5e-81425aa46ba2",
"content_key": "apcalcbc-mcq-ab-028",
"from_md5": "4edecb38995411da32ab1f8855ea8115",
"to_stem": "Which statement is always true?",
"choices_md5": "f362a993850c28d4cb926e6e5c88ffff"
},
{
"version_id": "afefdd33-23f9-45d1-a64b-0a3f5f5b2e94",
"content_key": "apcalcbc-mcq-ab-029",
"from_md5": "1f31314b9a4be0cf34c3aa429075e131",
"to_stem": "If f(x)=sin(x²), what is f′(x)?",
"choices_md5": "73ed09b63183318715899bc228e023a4"
},
{
"version_id": "05fb2931-3b7b-4114-ba57-26a1c687ca52",
"content_key": "apcalcbc-mcq-ab-030",
"from_md5": "5f9d1879a1e73c671414d6a6c2d8f58e",
"to_stem": "For the curve x²+y²=25, what is dy/dx at (3,4)?",
"choices_md5": "ba5d55849cc489dc741e158273a71fe3"
},
{
"version_id": "94bf5ab0-4fc3-4b53-bac9-62ed9de33fe1",
"content_key": "apcalcbc-mcq-mv045",
"from_md5": "6372dcfc0358bd2e8ade629f2820dd7f",
"to_stem": "Use Euler's method with step size 0.5 to estimate y(1) for y′=x+y and y(0)=1.",
"choices_md5": "45d4df2389e7427d62cf0e3659d3e2d0"
},
{
"version_id": "6202f329-6245-4fef-ab40-0a7b8a14c525",
"content_key": "apcalcbc-mcq-mv046",
"from_md5": "46b1f0b4affb1327bc47b12b12593373",
"to_stem": "A population follows dP/dt=0.18P(1−P/900). At what population is the instantaneous growth rate greatest?",
"choices_md5": "efbcc042f3c5c8c4e2fa3f9ea3cefef4"
},
{
"version_id": "c431bc9c-5cfe-4059-96f8-98e8589d8410",
"content_key": "apcalcbc-mcq-mv050",
"from_md5": "5a831203ab90c0d8ca50218326e2d5fb",
"to_stem": "What is the length of y=x² from x=0 to x=1.4, to the nearest thousandth?",
"choices_md5": "a34eb742b6c61325a88964ea96369681"
},
{
"version_id": "d22a425d-8702-43f4-bc38-554f355e04ae",
"content_key": "apchem-mcq-001",
"from_md5": "ae15b06b8d9666316c1533de59080c83",
"to_stem": "A 9.00 g sample of water (18.0 g mol⁻¹) contains how many moles?",
"choices_md5": "d24e9edf757cd74f5f20191cbe421094"
},
{
"version_id": "67816f8d-f41f-4c58-a4ae-4966efc7a318",
"content_key": "apchem-mcq-003",
"from_md5": "1532a8a46e227c2acddb4c4c1c1af0da",
"to_stem": "Which species has a trigonal planar molecular geometry?",
"choices_md5": "415f74d11b81dc9498cf7912fe3c2abd"
},
{
"version_id": "c360ba4c-aa2e-4be8-9808-431775a9dae4",
"content_key": "apchem-mcq-004",
"from_md5": "80288597029318229752978e50eed2bf",
"to_stem": "Why does solid NaCl not conduct while molten NaCl does?",
"choices_md5": "37cf28f62f76a0baf986128f5e746d3e"
},
{
"version_id": "b1befb18-d6df-43af-ab68-ddb88423ed33",
"content_key": "apchem-mcq-005",
"from_md5": "7a00c0f2aca1e4bb70acaa295453a43a",
"to_stem": "At the same temperature, which gas sample has the greatest average particle speed?",
"choices_md5": "1ac65376816a9de90615269d7eebfe1e"
},
{
"version_id": "fadd26cc-8d63-4c1d-9d58-9c8550792e36",
"content_key": "apchem-mcq-008",
"from_md5": "4667f18b17f88bd28c1d7eac5964a7a0",
"to_stem": "A gas occupies 2.0 L at 1.0 atm. At constant temperature and fixed amount of gas, its volume at 4.0 atm is",
"choices_md5": "6e2a3f8b46d67708266811baff214385"
},
{
"version_id": "c5b49ad8-9764-4ded-b73b-f6bbf8d612a0",
"content_key": "apchem-mcq-009",
"from_md5": "445df89195b5c90ddbbea5e41151853e",
"to_stem": "For 2 H₂ + O₂ → 2 H₂O, how many moles of water form from 3.0 mol O₂ with excess H₂?",
"choices_md5": "ddacfd9502cba88737d91d43db229334"
},
{
"version_id": "d99a02b1-d931-4bfb-babe-69bcd837c5fd",
"content_key": "apchem-mcq-010",
"from_md5": "092948f8161e340ca354e93371248ea7",
"to_stem": "Which ions are spectators when AgNO₃(aq) and NaCl(aq) form AgCl(s)?",
"choices_md5": "52654bba06e3710ee0e52cdecb860884"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
