-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 01/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "d5ce86ce-69e0-4e02-80d6-12b2e47cfb19",
"content_key": "apcalcab-mcq-021",
"from_md5": "575d6b06c192c30964109a41afeac1b3",
"to_stem": "What is lim(x→2) (x²−4)/(x−2)?",
"choices_md5": "2e9f06f5e3cc5c17fc410d7a82b5b7b0"
},
{
"version_id": "f187cb9b-ad82-4c0a-bf31-1fe9bc88b111",
"content_key": "apcalcab-mcq-022",
"from_md5": "c231ce20d0e1c12ce4075e92c2d85cda",
"to_stem": "Let f(x)=kx+1 for x<2 and f(x)=x²−1 for x≥2. For what value of k is f continuous at x=2?",
"choices_md5": "974d9e9326ac34f5f2c4c96b9bd74788"
},
{
"version_id": "84b735fd-c0c5-43e9-a061-3c1d49d6faa6",
"content_key": "apcalcab-mcq-023",
"from_md5": "370bb7f4735808ca9cb1609f808a7203",
"to_stem": "A function f is continuous on [1,4], with f(1)=−2 and f(4)=5. Which conclusion is guaranteed?",
"choices_md5": "890c9d96c8eae5adab319a3668b03251"
},
{
"version_id": "83a5e4bd-4243-45ae-99f3-4dc2b20277d6",
"content_key": "apcalcab-mcq-024",
"from_md5": "72e282b336b9a4253187298e2c835cd5",
"to_stem": "What is lim(x→∞) (5x²−x+4)/(2x²+3)?",
"choices_md5": "d65b8564fb770d5a7de48cdd75232aa8"
},
{
"version_id": "282b516f-24df-4efd-a6b4-4bd707b27ade",
"content_key": "apcalcab-mcq-025",
"from_md5": "163d8c51894d4e4254859bc35d7363bc",
"to_stem": "Which expression equals f′(3)?",
"choices_md5": "ee91542a00e0bdb6499ae40880646da9"
},
{
"version_id": "b96d3255-5b0b-41d0-acc9-879ff0ce95f4",
"content_key": "apcalcab-mcq-026",
"from_md5": "6a4c960b7d73c682605172bb98276792",
"to_stem": "If f(x)=x²e^x, what is f′(1)?",
"choices_md5": "c053b0503fbe903d211b172701dd8741"
},
{
"version_id": "46c685fa-6f73-4fec-8e6a-65f76f20688b",
"content_key": "apcalcab-mcq-027",
"from_md5": "3f06ad188a925fb63f30f269787032a8",
"to_stem": "What is d/dx[sec x tan x]?",
"choices_md5": "a2708819463195919a1e9981c92586eb"
},
{
"version_id": "4f821f8a-e0d2-4335-a0f9-d7f0f45eab31",
"content_key": "apcalcab-mcq-028",
"from_md5": "4edecb38995411da32ab1f8855ea8115",
"to_stem": "Which statement is always true?",
"choices_md5": "f362a993850c28d4cb926e6e5c88ffff"
},
{
"version_id": "d78139a9-7f07-47dd-a1d7-2b74588b00f4",
"content_key": "apcalcab-mcq-029",
"from_md5": "1f31314b9a4be0cf34c3aa429075e131",
"to_stem": "If f(x)=sin(x²), what is f′(x)?",
"choices_md5": "73ed09b63183318715899bc228e023a4"
},
{
"version_id": "a5a73c42-6cb3-4671-957d-6cd3f8e8498a",
"content_key": "apcalcab-mcq-030",
"from_md5": "5f9d1879a1e73c671414d6a6c2d8f58e",
"to_stem": "For the curve x²+y²=25, what is dy/dx at (3,4)?",
"choices_md5": "ba5d55849cc489dc741e158273a71fe3"
},
{
"version_id": "33b9f803-7914-45e3-8bcc-ca8997821a45",
"content_key": "apcalcab-mcq-031",
"from_md5": "284f1bee24f7f0ea202058e0f23fd418",
"to_stem": "A particle has position s(t)=t³−4.7t²+2.1t+6 meters. What is its velocity at t=2.35 seconds, to the nearest hundredth?",
"choices_md5": "590d366e3cd1989e257c7db80fd4cddb"
},
{
"version_id": "1a14dfca-2526-4774-86f5-95384856fa6b",
"content_key": "apcalcab-mcq-032",
"from_md5": "f3a686ed5c148557a6d22556de1535c9",
"to_stem": "The radius of a circular stain is increasing at 0.37 centimeter per minute. When the radius is 5.2 centimeters, how fast is its area increasing, to the nearest tenth?",
"choices_md5": "f541111146a9e977d4f5221ad5a8adc0"
},
{
"version_id": "46ed1137-6d05-41ee-ba4f-33c75138bbfe",
"content_key": "apcalcab-mcq-033",
"from_md5": "7452e7ba109480cf057cc110cf68610a",
"to_stem": "Using the linearization of f(x)=√x at x=4, which approximation is obtained for √4.1?",
"choices_md5": "6ac7a87e7432fb62c1c7ac81bc6c48b2"
},
{
"version_id": "a6963891-72c1-4665-912f-948599fcbfa4",
"content_key": "apcalcab-mcq-034",
"from_md5": "ded91d7f6821ec73de774969c22ee417",
"to_stem": "What is lim(x→0) (e^(2x)−1)/x?",
"choices_md5": "6b8b93ae019bbb715ba446cd7f60bffb"
},
{
"version_id": "4cc3b370-f56b-47ca-a7cf-4e0b32a06595",
"content_key": "apcalcab-mcq-035",
"from_md5": "666e929a4bccf326b0285be4409893e1",
"to_stem": "What are the critical numbers of f(x)=x³−3x?",
"choices_md5": "5d231e48fc7ee79429a53ce24d20c444"
},
{
"version_id": "cadbc0c7-61d6-4c34-87df-70fecd83e14c",
"content_key": "apcalcab-mcq-036",
"from_md5": "5fc20335a95b62e8903f3bcfba4ec8cd",
"to_stem": "For f(x)=x² on [1,3], the Mean Value Theorem guarantees a c in (1,3) with f′(c) equal to the average rate of change. What is c?",
"choices_md5": "b1ff27192d944a369611ffd8e4e7d276"
},
{
"version_id": "69954758-6a5e-4473-ad33-a5fcef96399f",
"content_key": "apcalcab-mcq-037",
"from_md5": "b57d32b7522a9673d70fa8200ae4bdd7",
"to_stem": "A differentiable function has f′(x)=x³−3.2x²−1.1x+2.4 on −2≤x≤4. At which x-value does f have a local maximum, to the nearest thousandth?",
"choices_md5": "fb52844b2e40930100be768c3fcce6e0"
},
{
"version_id": "4bf6926a-7c55-48f7-b4db-9fc672a14731",
"content_key": "apcalcab-mcq-038",
"from_md5": "3e142708ae459953852e8051310636d2",
"to_stem": "If f″(x)=6x−12, on which interval is f concave up?",
"choices_md5": "ba7fd45cfd4f2998a3702dd1d42a8599"
},
{
"version_id": "3d5aa0f8-6b75-4490-b338-4d83c9ba3f18",
"content_key": "apcalcab-mcq-039",
"from_md5": "7e4352fc1a07742dad0f27dfe434a53e",
"to_stem": "A rectangle has perimeter 20. What is its greatest possible area?",
"choices_md5": "ae15464b8d916138d0e8205e2615d4ac"
},
{
"version_id": "172ee07f-0692-45f6-bcf0-413062e46d4d",
"content_key": "apcalcab-mcq-040",
"from_md5": "33c15bdc61282eb600e99d8ae2a4ca55",
"to_stem": "Values of f are shown: x=0, 0.7, 1.9, 3.0 and f(x)=2.1, 2.8, 1.6, 3.4. What is the right Riemann-sum approximation for ∫₀³ f(x)dx?",
"choices_md5": "5068f6ad32449d0efbccb02b14c22304"
},
{
"version_id": "4785a80b-e6df-44f8-80b9-0a24c715da30",
"content_key": "apcalcab-mcq-041",
"from_md5": "1396436004fded3634f8419e4266efb0",
"to_stem": "If F(x)=∫₁^(x²) √(1+t³) dt, what is F′(x)?",
"choices_md5": "ae17c92b14cb036463bf0dded64b62bc"
},
{
"version_id": "8a70d356-3323-498f-bf1c-ed157a9c1d4a",
"content_key": "apcalcab-mcq-042",
"from_md5": "a622e5c2d88c4c116c464ec56879c261",
"to_stem": "If f is odd and integrable on [−3,3], what is ∫₋₃³ f(x)dx?",
"choices_md5": "114542f432cefa7f7b6528aea0f42a6d"
},
{
"version_id": "4513a5d9-2989-4839-9009-7cddd4eadfe1",
"content_key": "apcalcab-mcq-043",
"from_md5": "ce74d9b79f09934fa52596a3b1b57c31",
"to_stem": "Which is an antiderivative of 2x cos(x²)?",
"choices_md5": "7c711698f8a7f7cffe48c2f639da9b3d"
},
{
"version_id": "c8d4f7c2-7aec-4ffa-a03f-d301e5d36127",
"content_key": "apcalcab-mcq-044",
"from_md5": "fc250d0c4256b006b7d289c76dd625c9",
"to_stem": "Let f(x)=e^(−x²). What is the average value of f on [0,1.6], to the nearest thousandth?",
"choices_md5": "46d3c5bece110abe8af3da95d7fc1e47"
},
{
"version_id": "f5374b3d-e3ff-44b7-91df-5a17e34fe98a",
"content_key": "apcalcab-mcq-047",
"from_md5": "2795375ec2f91c6e7151bd71928d3321",
"to_stem": "What is the area between y=x and y=x² on 0≤x≤1?",
"choices_md5": "6ad818adc7356097571035876f0c69d3"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
