-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 07/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "3d8748d0-fdb6-47fa-bf9a-378ac440435c",
"content_key": "apphycem-mcq-010",
"from_md5": "3ea14a48f97f973ec98010215c32369d",
"to_stem": "For capacitor discharge through R, charge follows",
"choices_md5": "885e231f011856980877a144ac0f77ed"
},
{
"version_id": "ca322b9b-4d53-4c08-bda8-81028cb9bb4f",
"content_key": "apphycem-mcq-011",
"from_md5": "e85a4c4e079358cd8d9d773b7b9dadb8",
"to_stem": "A 2.0 uF capacitor, initially charged to 12 V, discharges through a 500 kOhm resistor. Approximately how long does it take for the charge to fall to 37% of its initial value?",
"choices_md5": "5d96f244176f0ccfed582730013b1182"
},
{
"version_id": "4dbb7d4d-c572-46f3-9947-afcc9b107162",
"content_key": "apphycem-mcq-012",
"from_md5": "087da4719c192317501b57c71b57c37b",
"to_stem": "Kirchhoff's junction rule follows from conservation of",
"choices_md5": "8c1afc63b4a1258ae361bfaae8664a5f"
},
{
"version_id": "af65207c-0029-4d96-811a-492016f25afb",
"content_key": "apphycem-mcq-014",
"from_md5": "a1e64bb0518846313b8720a7c4c59a60",
"to_stem": "Ampère's law in magnetostatics is useful when symmetry makes",
"choices_md5": "526f4a7a5a07a5b32ff3a9e7b164b083"
},
{
"version_id": "cb00852c-7a3d-409a-9ef3-4d8716c7edbf",
"content_key": "apphycem-mcq-015",
"from_md5": "13d69b7a15ea1568315a2f8db3e0a5e9",
"to_stem": "The differential magnetic force on a current element is",
"choices_md5": "713a866730b03873a83159e1ef77ca15"
},
{
"version_id": "a27c0b98-41a7-45a4-906c-785a810d239f",
"content_key": "apphycem-mcq-016",
"from_md5": "393f4ee9802159f000fb1b4f86fc07b7",
"to_stem": "Faraday's law in integral form states that the emf around a closed loop, the line integral of E around the loop, is equal to--",
"choices_md5": "31fdfd7374e5360be96132d4817e27f8"
},
{
"version_id": "ce80e748-3c79-42d0-aead-c1aec5bdd52a",
"content_key": "apphycem-mcq-017",
"from_md5": "d87788d24df418f65902331440f5c8f8",
"to_stem": "For an LR circuit connected to a DC source, current approaches steady state with time constant",
"choices_md5": "48b08fd285e4a15db8209137a60259a2"
},
{
"version_id": "9f841d49-4f7e-434f-8497-2f7e17361062",
"content_key": "apphycem-mcq-020",
"from_md5": "d7965d60e31e4d5c19954cb5bd719bfd",
"to_stem": "Induced electric fields from changing magnetic flux are",
"choices_md5": "38c6b85a5aabbe27777e29e6e9839778"
},
{
"version_id": "4e0dadc5-b0d6-45ec-a829-f565a271884e",
"content_key": "apphycem-mcq-031",
"from_md5": "2f6cfee087c71bb8514e6c63bcad6c8f",
"to_stem": "Total current through a surface is",
"choices_md5": "52b2097e5fe80e69f97f47df61e160f0"
},
{
"version_id": "ce5636a2-ac51-4d6a-bd7a-9525d7c25408",
"content_key": "apphycem-mcq-032",
"from_md5": "924bb61894a669e31cdfc3e95fd28b64",
"to_stem": "In a steady series circuit, current through each element is",
"choices_md5": "d0d3c9521dee65d4ba77cc5201566b06"
},
{
"version_id": "4ccd67cf-6aed-4fb7-851d-edbb005d51d7",
"content_key": "apphycem-mcq-033",
"from_md5": "ce975107d2f56a2c9bd8aea731bc8617",
"to_stem": "A wire's length doubles and radius doubles with resistivity unchanged. Its resistance becomes",
"choices_md5": "2e77823625cd78dfb159e3ef3c406e2f"
},
{
"version_id": "6fe06345-fde5-40eb-b532-04effab6cc25",
"content_key": "apphycem-mcq-035",
"from_md5": "ef25ebb3a80cea7db391699f931d4cc7",
"to_stem": "Kirchhoff's loop rule for a steady circuit follows from conservation of",
"choices_md5": "9b0ea3a64113295c4dfc905eb9f5a577"
},
{
"version_id": "cd96dd11-e6ad-428b-a95a-f20886b9b911",
"content_key": "apphycem-mcq-036",
"from_md5": "16bdade13e744fa67e9d506203bf0e0d",
"to_stem": "An uncharged capacitor connects through R to ideal emf ε. Immediately after closing, current is",
"choices_md5": "bdb0bbd4ba5fd7c64a3fd6be98f985ef"
},
{
"version_id": "e612ebec-2e6a-4b04-9c5c-5d7e7b711977",
"content_key": "apphycem-mcq-037",
"from_md5": "08bdf450a7a2ac2f96539b37d8a48a8e",
"to_stem": "Gauss's law for magnetism states",
"choices_md5": "e7e6212e7111c02872a30ecbc054d38e"
},
{
"version_id": "330a4588-b35a-4460-a7cb-65ee2ece4661",
"content_key": "apphycem-mcq-038",
"from_md5": "e1729751c595f0036389d0171532151d",
"to_stem": "A static magnetic field acting alone on a point charge does",
"choices_md5": "7abc4552ad352152b5b2cfdb94094a30"
},
{
"version_id": "f643b085-a308-44ca-9625-94eabea78655",
"content_key": "apphycem-mcq-039",
"from_md5": "70ea765af0522a0b4dfad1a163e4375d",
"to_stem": "For a long ideal solenoid with n turns per length, interior field is",
"choices_md5": "80face9547c99c9296649ff378382d76"
},
{
"version_id": "f0231b54-ad44-4cae-82d7-ff1cfe0b95e7",
"content_key": "apphycem-mcq-040",
"from_md5": "65d23c6868bc8b4a6cdf5e62b21c4ff3",
"to_stem": "Uniform B crosses a single loop of area A at angle θ to the area normal. Flux is",
"choices_md5": "cc4aed348db20fab0e2ec16218ebb3ab"
},
{
"version_id": "24bfd312-4fa1-47cf-aa88-77cacab03038",
"content_key": "apphycem-mcq-041",
"from_md5": "f295f0a7544794afb06f37de62c1ac74",
"to_stem": "A conducting plate entering a magnetic-field region experiences a force opposing motion because",
"choices_md5": "0cf1214adbc8007f3e54aee2a38f13b1"
},
{
"version_id": "a3e5e87b-0940-4284-98bc-5b4b0e8f3691",
"content_key": "apphycem-mcq-042",
"from_md5": "8dad23b21d9626b00721f5d5295d5214",
"to_stem": "Energy stored in an ideal inductor carrying current I is",
"choices_md5": "13726414939b172b15b7eabb3b2f5735"
},
{
"version_id": "ad958df1-1534-4cb0-970c-df8e9328985c",
"content_key": "apphycm-mcq-005",
"from_md5": "d3e1f6aeda2ae734f4eeeac40230f906",
"to_stem": "A particle under F=-kx satisfies",
"choices_md5": "e1216161ce420bf20516f7ab32268820"
},
{
"version_id": "80dda346-3421-4f59-95fc-e7f973e1e15c",
"content_key": "apphycm-mcq-009",
"from_md5": "eeb0975b0b04af43204ba90a08f64dc1",
"to_stem": "For variable force F(t), impulse from 0 to T is",
"choices_md5": "97c4cfc2f729f7428dead8d1d2e2efe6"
},
{
"version_id": "06cab4fb-979c-4ec6-ae24-3e384ef8097a",
"content_key": "apphycm-mcq-010",
"from_md5": "f6c6c1a11f46cc28161f1489dd8eaef1",
"to_stem": "A rocket's changing-mass motion is analyzed by applying momentum conservation to",
"choices_md5": "16ccb05ebb61076f82886e1eec574503"
},
{
"version_id": "7bbc529a-7234-40c3-a573-179ab58d6a13",
"content_key": "apphycm-mcq-011",
"from_md5": "89c63f018d5ca0aa80b7f7a658753587",
"to_stem": "For angular position θ(t), angular acceleration is",
"choices_md5": "582db9211e98474a61daf7e36f8ba543"
},
{
"version_id": "6deeda4a-51fc-4932-a515-dc302ff2e27a",
"content_key": "apphycm-mcq-012",
"from_md5": "0afc33cfa3fba403c949ca05c596b6c6",
"to_stem": "Torque from potential energy U(θ), for a system whose potential energy depends only on the angle θ, is",
"choices_md5": "b6ecc0238f6b98c941f0dda09b05cf85"
},
{
"version_id": "928a5a7e-6957-4b74-9802-281e9ce3e96c",
"content_key": "apphycm-mcq-013",
"from_md5": "72761e31c786ae533f9ac74ffd0c3979",
"to_stem": "For a continuous body, moment of inertia about a chosen rotation axis is (r is the perpendicular distance of each mass element from that axis)",
"choices_md5": "1e9c09fd223cdcfaf2c635b7497b3309"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
