-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 08/8 (16 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "2a806254-1a78-4af8-b4dd-689a497ef50e",
"content_key": "apphycm-mcq-014",
"from_md5": "6089374ac56e09283dfc31eb51007570",
"to_stem": "A system experiences zero net external torque. Which of the following is true of dL/dt?",
"choices_md5": "4bae70ca8a11ed9979dc9a6e51523a8d"
},
{
"version_id": "f19dc852-061a-4060-ab50-f526132c9b24",
"content_key": "apphycm-mcq-015",
"from_md5": "93ea44c81b3198674e7edbaa67b9cfc5",
"to_stem": "The small-angle pendulum equation is",
"choices_md5": "f0a02f391aea19fce3bd368cbff5ce0d"
},
{
"version_id": "f0d61bed-eb70-4a59-a66d-b5a2c8f0c654",
"content_key": "apphycm-mcq-016",
"from_md5": "e91468e1744c0314d2c40c1d15cba409",
"to_stem": "The period for x''+ω²x=0 is",
"choices_md5": "d914ee7f2b0343195f5419dce39bcd74"
},
{
"version_id": "b7f33d69-7a41-42ba-9455-eb46472604f3",
"content_key": "apphycm-mcq-019",
"from_md5": "39bfa1446adc286eb8838182c3a0c7d2",
"to_stem": "For τ(t)=τ₀t acting on constant I, change in angular speed from 0 to T is",
"choices_md5": "904b819910e0d42032d372c0735a9f3d"
},
{
"version_id": "f415f38a-4f86-4254-92a2-51b3687c44d5",
"content_key": "apphycm-mcq-020",
"from_md5": "364ea7c84bcb7ee551ae4256eb93752d",
"to_stem": "For a physical pendulum undergoing small-angle oscillation, omega^2 equals which of the following, where d is the distance from the pivot to the center of mass and I is the moment of inertia about the pivot?",
"choices_md5": "d85fe20fd96141ab854796a03218bebf"
},
{
"version_id": "5e75e2b8-cfe6-4f8d-bec9-324d66ccd696",
"content_key": "apphycm-mcq-032",
"from_md5": "3626ad56ffb390103fe0c7bf6135618e",
"to_stem": "A force F₀e^{-t/τ} acts from t=0 to infinity. Its impulse is",
"choices_md5": "83b30ef5a4fc1ba7cb1f5ac76446be63"
},
{
"version_id": "ba498b18-fcc5-4323-977c-89cd83878f89",
"content_key": "apphycm-mcq-033",
"from_md5": "e767759a382b888b2c046f16a47e93e6",
"to_stem": "For a system of total mass M, total momentum is",
"choices_md5": "236f9b92793df9715723e3ee00be1f6c"
},
{
"version_id": "ba6e8551-c83d-4c81-8844-09674b2f42cc",
"content_key": "apphycm-mcq-034",
"from_md5": "746a970c821cbf46414cad0a852c032e",
"to_stem": "In an isolated perfectly inelastic collision,",
"choices_md5": "13fbb24e1d602d36c783ddf654724e07"
},
{
"version_id": "c352aa57-dd96-4b56-9dc1-7a95b80e8da2",
"content_key": "apphycm-mcq-035",
"from_md5": "fe5847679ba0e6dd5f2219c34f94c74b",
"to_stem": "Torque about an origin is",
"choices_md5": "4bafcb964b8bd35f09391a14e1062fb3"
},
{
"version_id": "fe698e65-d37b-4194-81c2-75504cba2deb",
"content_key": "apphycm-mcq-036",
"from_md5": "19539bc4b90b445cff642d3b6705ec40",
"to_stem": "For constant rotational inertia I, net torque is",
"choices_md5": "f20421ed9a0b2d9cdc0d1544d981e65f"
},
{
"version_id": "c1f19405-a9cd-45f3-b9d9-55a57b86b180",
"content_key": "apphycm-mcq-037",
"from_md5": "513216ecdd76ec34676ea5b25874cf1f",
"to_stem": "A rigid body rotating at angular speed ω has kinetic energy",
"choices_md5": "bacb1011d0d5e21db942aabf3fba4200"
},
{
"version_id": "6de62c61-d226-478b-88f6-fed67a05f2a8",
"content_key": "apphycm-mcq-038",
"from_md5": "47ebe7b2274014657b56c820dad3949c",
"to_stem": "Angular impulse over a time interval equals",
"choices_md5": "4588f99e54504e8d5cabab5f397ff5ac"
},
{
"version_id": "0284f245-d4ce-4c8d-95bf-3022d1cac73d",
"content_key": "apphycm-mcq-039",
"from_md5": "293c598ff3b66bdcc68a12cb8b3ae51a",
"to_stem": "For rolling without slipping, center-of-mass speed is",
"choices_md5": "524a4f35df281669d9238cfae7593011"
},
{
"version_id": "a6ce6f27-2a89-4fdb-bd4f-e462b7c09f73",
"content_key": "apphycm-mcq-040",
"from_md5": "8b3ed3698b5884aa6234a3b3e0c2157b",
"to_stem": "For circular orbits about the same mass, doubling radius multiplies period by",
"choices_md5": "0a2aaf9890014a1ddf7546848ae60584"
},
{
"version_id": "b8e9a3af-7e78-4715-8dab-7b2342d3421f",
"content_key": "apphycm-mcq-041",
"from_md5": "41304b2b39451ea03ca8a3239355397e",
"to_stem": "For m x''+kx=0, angular frequency is",
"choices_md5": "22bfb88bc3961653501aa447d39b5d9c"
},
{
"version_id": "73234415-efbc-48f4-9d1c-acad9e98b7e1",
"content_key": "apphycm-mcq-042",
"from_md5": "fad79f1474221b221c25cdc458b2a8e9",
"to_stem": "For amplitude A in ideal SHM with spring constant k, total energy is",
"choices_md5": "402b26d08b3416b059922e178ed80c18"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 16 then raise exception '%: expected 16 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
