-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY (NOT YET APPLIED; needs approval)
-- Removes the trailing "\n\nA. ..\nB. ..\nC. ..\nD. .." list from 191 published MCQ stems whose inline list is
-- byte-identical to app.mcq_choices (class clean_match in classification.json). Nothing before the list changes.
-- Generated by gen_sql.py from prod_snapshot.json. See REPORT.md.
--
-- ONE statement (a DO block, no temp tables). Idempotent: a row is updated only while md5(stem) still equals the snapshot,
-- it is still the latest published MCQ version, and its choices still match the snapshot. A re-run is a no-op.
--
-- Why the label step: app.taxonomy_relevant_hash() covers `stem`, so the write fires tg_content_versions_taxonomy_stale
-- and every current validated/provisional_model label of these items goes 'stale' (the derive trigger also nulls
-- validated_by/at/decision). select_unit_gated_practice_items requires label_status='validated' AND
-- validated_against_taxo_hash = taxonomy_relevant_hash(version), so without the carry-forward 148 currently-served
-- items would drop out of unit-gated serving. Precedent: 20261004120000_apcalcab_u1_canonical_answers_20_items.sql
-- (APPROVAL-0116) and APPROVAL-0066. Set v_approval below before running.
--
-- No trigger is disabled. Triggers fired: set_updated_at (updated_at moves), content_pipeline_guard_publish (no-op:
-- status unchanged), content_item_versions_mcq_stem_choice_sync (passes: no letter lines remain),
-- tg_content_versions_taxonomy_stale (handled), tg_content_taxonomy_labels_derive (handled). publish_gate and
-- enforce_full_exam_frq_version do not fire (column lists exclude stem).
--
-- Rollback: prod_rollback.sql (restores snapshot stems with the same label carry-forward).
do $apply$
declare
  v_approval constant text := 'PENDING';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "d5ce86ce-69e0-4e02-80d6-12b2e47cfb19",
"content_key": "apcalcab-mcq-021",
"from_md5": "575d6b06c192c30964109a41afeac1b3",
"to_stem": "What is lim(x→2) (x²−4)/(x−2)?",
"choices_md5": "2e9f06f5e3cc5c17fc410d7a82b5b7b0"
},
{
"version_id": "f187cb9b-ad82-4c0a-bf31-1fe9bc88b111",
"content_key": "apcalcab-mcq-022",
"from_md5": "c231ce20d0e1c12ce4075e92c2d85cda",
"to_stem": "Let f(x)=kx+1 for x<2 and f(x)=x²−1 for x≥2. For what value of k is f continuous at x=2?",
"choices_md5": "974d9e9326ac34f5f2c4c96b9bd74788"
},
{
"version_id": "84b735fd-c0c5-43e9-a061-3c1d49d6faa6",
"content_key": "apcalcab-mcq-023",
"from_md5": "370bb7f4735808ca9cb1609f808a7203",
"to_stem": "A function f is continuous on [1,4], with f(1)=−2 and f(4)=5. Which conclusion is guaranteed?",
"choices_md5": "890c9d96c8eae5adab319a3668b03251"
},
{
"version_id": "83a5e4bd-4243-45ae-99f3-4dc2b20277d6",
"content_key": "apcalcab-mcq-024",
"from_md5": "72e282b336b9a4253187298e2c835cd5",
"to_stem": "What is lim(x→∞) (5x²−x+4)/(2x²+3)?",
"choices_md5": "d65b8564fb770d5a7de48cdd75232aa8"
},
{
"version_id": "282b516f-24df-4efd-a6b4-4bd707b27ade",
"content_key": "apcalcab-mcq-025",
"from_md5": "163d8c51894d4e4254859bc35d7363bc",
"to_stem": "Which expression equals f′(3)?",
"choices_md5": "ee91542a00e0bdb6499ae40880646da9"
},
{
"version_id": "b96d3255-5b0b-41d0-acc9-879ff0ce95f4",
"content_key": "apcalcab-mcq-026",
"from_md5": "6a4c960b7d73c682605172bb98276792",
"to_stem": "If f(x)=x²e^x, what is f′(1)?",
"choices_md5": "c053b0503fbe903d211b172701dd8741"
},
{
"version_id": "46c685fa-6f73-4fec-8e6a-65f76f20688b",
"content_key": "apcalcab-mcq-027",
"from_md5": "3f06ad188a925fb63f30f269787032a8",
"to_stem": "What is d/dx[sec x tan x]?",
"choices_md5": "a2708819463195919a1e9981c92586eb"
},
{
"version_id": "4f821f8a-e0d2-4335-a0f9-d7f0f45eab31",
"content_key": "apcalcab-mcq-028",
"from_md5": "4edecb38995411da32ab1f8855ea8115",
"to_stem": "Which statement is always true?",
"choices_md5": "f362a993850c28d4cb926e6e5c88ffff"
},
{
"version_id": "d78139a9-7f07-47dd-a1d7-2b74588b00f4",
"content_key": "apcalcab-mcq-029",
"from_md5": "1f31314b9a4be0cf34c3aa429075e131",
"to_stem": "If f(x)=sin(x²), what is f′(x)?",
"choices_md5": "73ed09b63183318715899bc228e023a4"
},
{
"version_id": "a5a73c42-6cb3-4671-957d-6cd3f8e8498a",
"content_key": "apcalcab-mcq-030",
"from_md5": "5f9d1879a1e73c671414d6a6c2d8f58e",
"to_stem": "For the curve x²+y²=25, what is dy/dx at (3,4)?",
"choices_md5": "ba5d55849cc489dc741e158273a71fe3"
},
{
"version_id": "33b9f803-7914-45e3-8bcc-ca8997821a45",
"content_key": "apcalcab-mcq-031",
"from_md5": "284f1bee24f7f0ea202058e0f23fd418",
"to_stem": "A particle has position s(t)=t³−4.7t²+2.1t+6 meters. What is its velocity at t=2.35 seconds, to the nearest hundredth?",
"choices_md5": "590d366e3cd1989e257c7db80fd4cddb"
},
{
"version_id": "1a14dfca-2526-4774-86f5-95384856fa6b",
"content_key": "apcalcab-mcq-032",
"from_md5": "f3a686ed5c148557a6d22556de1535c9",
"to_stem": "The radius of a circular stain is increasing at 0.37 centimeter per minute. When the radius is 5.2 centimeters, how fast is its area increasing, to the nearest tenth?",
"choices_md5": "f541111146a9e977d4f5221ad5a8adc0"
},
{
"version_id": "46ed1137-6d05-41ee-ba4f-33c75138bbfe",
"content_key": "apcalcab-mcq-033",
"from_md5": "7452e7ba109480cf057cc110cf68610a",
"to_stem": "Using the linearization of f(x)=√x at x=4, which approximation is obtained for √4.1?",
"choices_md5": "6ac7a87e7432fb62c1c7ac81bc6c48b2"
},
{
"version_id": "a6963891-72c1-4665-912f-948599fcbfa4",
"content_key": "apcalcab-mcq-034",
"from_md5": "ded91d7f6821ec73de774969c22ee417",
"to_stem": "What is lim(x→0) (e^(2x)−1)/x?",
"choices_md5": "6b8b93ae019bbb715ba446cd7f60bffb"
},
{
"version_id": "4cc3b370-f56b-47ca-a7cf-4e0b32a06595",
"content_key": "apcalcab-mcq-035",
"from_md5": "666e929a4bccf326b0285be4409893e1",
"to_stem": "What are the critical numbers of f(x)=x³−3x?",
"choices_md5": "5d231e48fc7ee79429a53ce24d20c444"
},
{
"version_id": "cadbc0c7-61d6-4c34-87df-70fecd83e14c",
"content_key": "apcalcab-mcq-036",
"from_md5": "5fc20335a95b62e8903f3bcfba4ec8cd",
"to_stem": "For f(x)=x² on [1,3], the Mean Value Theorem guarantees a c in (1,3) with f′(c) equal to the average rate of change. What is c?",
"choices_md5": "b1ff27192d944a369611ffd8e4e7d276"
},
{
"version_id": "69954758-6a5e-4473-ad33-a5fcef96399f",
"content_key": "apcalcab-mcq-037",
"from_md5": "b57d32b7522a9673d70fa8200ae4bdd7",
"to_stem": "A differentiable function has f′(x)=x³−3.2x²−1.1x+2.4 on −2≤x≤4. At which x-value does f have a local maximum, to the nearest thousandth?",
"choices_md5": "fb52844b2e40930100be768c3fcce6e0"
},
{
"version_id": "4bf6926a-7c55-48f7-b4db-9fc672a14731",
"content_key": "apcalcab-mcq-038",
"from_md5": "3e142708ae459953852e8051310636d2",
"to_stem": "If f″(x)=6x−12, on which interval is f concave up?",
"choices_md5": "ba7fd45cfd4f2998a3702dd1d42a8599"
},
{
"version_id": "3d5aa0f8-6b75-4490-b338-4d83c9ba3f18",
"content_key": "apcalcab-mcq-039",
"from_md5": "7e4352fc1a07742dad0f27dfe434a53e",
"to_stem": "A rectangle has perimeter 20. What is its greatest possible area?",
"choices_md5": "ae15464b8d916138d0e8205e2615d4ac"
},
{
"version_id": "172ee07f-0692-45f6-bcf0-413062e46d4d",
"content_key": "apcalcab-mcq-040",
"from_md5": "33c15bdc61282eb600e99d8ae2a4ca55",
"to_stem": "Values of f are shown: x=0, 0.7, 1.9, 3.0 and f(x)=2.1, 2.8, 1.6, 3.4. What is the right Riemann-sum approximation for ∫₀³ f(x)dx?",
"choices_md5": "5068f6ad32449d0efbccb02b14c22304"
},
{
"version_id": "4785a80b-e6df-44f8-80b9-0a24c715da30",
"content_key": "apcalcab-mcq-041",
"from_md5": "1396436004fded3634f8419e4266efb0",
"to_stem": "If F(x)=∫₁^(x²) √(1+t³) dt, what is F′(x)?",
"choices_md5": "ae17c92b14cb036463bf0dded64b62bc"
},
{
"version_id": "8a70d356-3323-498f-bf1c-ed157a9c1d4a",
"content_key": "apcalcab-mcq-042",
"from_md5": "a622e5c2d88c4c116c464ec56879c261",
"to_stem": "If f is odd and integrable on [−3,3], what is ∫₋₃³ f(x)dx?",
"choices_md5": "114542f432cefa7f7b6528aea0f42a6d"
},
{
"version_id": "4513a5d9-2989-4839-9009-7cddd4eadfe1",
"content_key": "apcalcab-mcq-043",
"from_md5": "ce74d9b79f09934fa52596a3b1b57c31",
"to_stem": "Which is an antiderivative of 2x cos(x²)?",
"choices_md5": "7c711698f8a7f7cffe48c2f639da9b3d"
},
{
"version_id": "c8d4f7c2-7aec-4ffa-a03f-d301e5d36127",
"content_key": "apcalcab-mcq-044",
"from_md5": "fc250d0c4256b006b7d289c76dd625c9",
"to_stem": "Let f(x)=e^(−x²). What is the average value of f on [0,1.6], to the nearest thousandth?",
"choices_md5": "46d3c5bece110abe8af3da95d7fc1e47"
},
{
"version_id": "f5374b3d-e3ff-44b7-91df-5a17e34fe98a",
"content_key": "apcalcab-mcq-047",
"from_md5": "2795375ec2f91c6e7151bd71928d3321",
"to_stem": "What is the area between y=x and y=x² on 0≤x≤1?",
"choices_md5": "6ad818adc7356097571035876f0c69d3"
},
{
"version_id": "05bc02e0-3ca9-45f2-9643-e69eddd4161b",
"content_key": "apcalcab-mcq-np2-002",
"from_md5": "c3406a3037b3e8a59f4b038f1c2f9806",
"to_stem": "Which of the following limits is an indeterminate form (0/0 or infinity/infinity) to which L'Hospital's Rule may be applied directly?",
"choices_md5": "6d25e86a57b149f082b283593f421eac"
},
{
"version_id": "8801905c-357a-43b7-81b5-0f388c6685bf",
"content_key": "apcalcbc-mcq-021",
"from_md5": "e2f10f527c139cd27c297224d40c929f",
"to_stem": "What is lim(x→0) (e^(3x)−1)/x?",
"choices_md5": "3fcf12b7c380c859d23fc18d2fd7c2e2"
},
{
"version_id": "c8e50471-1357-4455-9e5b-b3365a2eed42",
"content_key": "apcalcbc-mcq-022",
"from_md5": "ee19aeaf88e1c689f693e18ea7a289aa",
"to_stem": "What is lim(x→0) ln(1+2x)/sin(3x)?",
"choices_md5": "c1e848a1f0cf9aa098b89032f1f1e2a4"
},
{
"version_id": "a548a41e-aa7b-462f-8969-fac4def77fd7",
"content_key": "apcalcbc-mcq-023",
"from_md5": "e08fbb8685057d7f3f7afa3c67b2cf4b",
"to_stem": "If f(x)=x²ln x for x>0, what is f′(1)?",
"choices_md5": "94fa43a401b842b9ed1e1fe812ab749d"
},
{
"version_id": "22757b29-3af8-40f1-8f88-4d07e2ab1b0c",
"content_key": "apcalcbc-mcq-024",
"from_md5": "0f4e1e6351d3ad32e626ffc24ddd7290",
"to_stem": "Which limit equals f″(2), provided the second derivative exists?",
"choices_md5": "d26fc51a3beec83add9196c7ec6cae30"
},
{
"version_id": "fe829169-4d22-44ab-aafa-213cf63cee84",
"content_key": "apcalcbc-mcq-025",
"from_md5": "9201ee1b2007a369c32ac9d51f321161",
"to_stem": "What is d/dx[arctan(x²)]?",
"choices_md5": "b48bfcb16a49fc44b6fe7511e6961174"
},
{
"version_id": "435c0bbd-475e-41dd-bc25-ee04f09f4754",
"content_key": "apcalcbc-mcq-026",
"from_md5": "c0b49cce16088213ed03970c2f528985",
"to_stem": "Let g=f⁻¹. If f(2)=5 and f′(2)=−3, what is g′(5)?",
"choices_md5": "e2db659ae79ed9c9c2792a37a824d651"
},
{
"version_id": "fa8b34e0-f9a9-4ebd-a3d2-7a1a077f2034",
"content_key": "apcalcbc-mcq-027",
"from_md5": "8e563ce8186bd883698322283e1cf3c0",
"to_stem": "The radius of a sphere is increasing at 0.2 centimeter per second. How fast is its volume increasing when the radius is 3 centimeters?",
"choices_md5": "54d2fd57c1028af93e79f4a9d39e39da"
},
{
"version_id": "b79f95c1-f44e-4bb9-b280-7d3c4ae2a28b",
"content_key": "apcalcbc-mcq-028",
"from_md5": "0930e2c70df5a379c8bf1eb71bb64a19",
"to_stem": "A particle has velocity v(t)=t sin(t²)−0.4. What is its acceleration at t=1.3, to the nearest thousandth?",
"choices_md5": "64a1a7630c8f4fcdaa85f9eb88008ea0"
},
{
"version_id": "bed2766f-8714-419d-9aaf-d32bb3f69c2e",
"content_key": "apcalcbc-mcq-029",
"from_md5": "0156e54ef6a9dc164af2fda4cb674ed3",
"to_stem": "If f′(x)=(x−1)(x+2), on which intervals is f increasing?",
"choices_md5": "f2c42fdedb947cf1160fcecf62acbb2e"
},
{
"version_id": "b601f7db-92e4-4dd6-9b0d-e2864d426b0f",
"content_key": "apcalcbc-mcq-030",
"from_md5": "986a78beb09e3d788573757000103144",
"to_stem": "For f(x)=e^x on [0,1], which value of c is guaranteed by the Mean Value Theorem?",
"choices_md5": "b5b8f97610afaf987a376c0e9831a5e1"
},
{
"version_id": "4a47d6f6-0bd0-4ec2-add9-40d40d51b568",
"content_key": "apcalcbc-mcq-031",
"from_md5": "8c0d9703cce2342f3740b73c00b9cedb",
"to_stem": "A differentiable function has f′(x)=x⁴−4x²+0.5 on −2≤x≤2. At which x-values does f have local maxima, to the nearest thousandth?",
"choices_md5": "900f779d7627c56843c77cab8e63aaf6"
},
{
"version_id": "c7d521ad-bc8a-404c-abd9-0e68350e7afd",
"content_key": "apcalcbc-mcq-032",
"from_md5": "0cb90ebeda42f3b5986b75040e1b58d3",
"to_stem": "If f′(x)=x²(x−1)³(x+2)², which statement is true?",
"choices_md5": "c167cdf5b35579aba49412ad735f6d12"
},
{
"version_id": "1c459529-8016-44ad-be36-dbccc2e0e7fd",
"content_key": "apcalcbc-mcq-033",
"from_md5": "c5f80854a2dff08296934c94f2a08c62",
"to_stem": "What is the value of the improper integral ∫₁^∞ 1/x² dx?",
"choices_md5": "6cb3c0e8ebca430f7fb8801d37dd3542"
},
{
"version_id": "058cb9f7-37f0-4e0d-af06-97ffa239af39",
"content_key": "apcalcbc-mcq-034",
"from_md5": "79da518ae5b949ae73372f7abaa91fb7",
"to_stem": "Which is an antiderivative of xe^x?",
"choices_md5": "f3672008d6385aa936d7da7e2c626632"
},
{
"version_id": "de0da11c-94be-4ca2-a3e5-edf6836db953",
"content_key": "apcalcbc-mcq-035",
"from_md5": "e29d10e4fa0a92d7ba869aa719058876",
"to_stem": "What is ∫1/(x²−1) dx on an interval not containing ±1?",
"choices_md5": "6af3059ae0b36a8560b5c757cae0b1ef"
},
{
"version_id": "54c79401-bf15-4533-97d2-1a634ed5ce69",
"content_key": "apcalcbc-mcq-036",
"from_md5": "43e702332abd0481035c656f177cc83c",
"to_stem": "Let G(x)=∫₀^(x²) cos(t³)dt. What is G′(1.2), to the nearest thousandth?",
"choices_md5": "7cf2d0bcb2edfa1b1ffcb99e508efcf8"
},
{
"version_id": "f54f258c-060d-4419-b6fc-8382a1b4634b",
"content_key": "apcalcbc-mcq-037",
"from_md5": "922248f7f47af939e42de2329e5e07ed",
"to_stem": "What is ∫₁^∞ (ln x)/x² dx?",
"choices_md5": "8180d2d50d4aa87e1b3689358697db57"
},
{
"version_id": "4b886041-044f-4c7a-9907-69d97a19b67f",
"content_key": "apcalcbc-mcq-038",
"from_md5": "0ed1421c219286c2012ba960b87f6473",
"to_stem": "Use Euler's method with step size 0.25 to estimate y(0.5) for y′=x²−y and y(0)=1.",
"choices_md5": "96bbb87acc3da9d2888ad30c5fed1249"
},
{
"version_id": "7ffa3a3c-5e6e-4c35-bdc7-bd6ca6d8e1ff",
"content_key": "apcalcbc-mcq-039",
"from_md5": "6a89a67533fbfe4860b3400a096c12d3",
"to_stem": "A population satisfies dP/dt=0.4P(1−P/1200) and P(0)=300. When does P reach 600, to the nearest thousandth?",
"choices_md5": "946342125b9de25407f3e1a6c7355113"
},
{
"version_id": "7e90cc29-6b7b-442f-9742-7b099d3745da",
"content_key": "apcalcbc-mcq-040",
"from_md5": "c9a0ed490442a4c04c51723ed4ddea70",
"to_stem": "What is the area between y=√x and y=x on 0≤x≤1?",
"choices_md5": "22c826b14fa54afd754ec5682e04779a"
},
{
"version_id": "2bcaf641-2acb-418e-93a5-c1fa9ee02d83",
"content_key": "apcalcbc-mcq-041",
"from_md5": "5ca7729fa1020e46bcad763d5a9f8f75",
"to_stem": "The base of a solid is 0≤x≤1.5 and 0≤y≤e^(−x²). Cross sections perpendicular to the x-axis are semicircles whose diameters lie in the base. What is the volume, to the nearest thousandth?",
"choices_md5": "a7fe63a26a844ab856d727e960cd1152"
},
{
"version_id": "7fd6e86b-00c8-4167-9cf3-2e9d94c5a0ae",
"content_key": "apcalcbc-mcq-042",
"from_md5": "c32d6a80ca46ed2865c40cfd64ec224b",
"to_stem": "A curve is given by x=t²+1 and y=t³−3t. What is dy/dx at t=1?",
"choices_md5": "0ec745da47ca59dd83113a6035bbbf98"
},
{
"version_id": "7945bd22-d0a1-4bba-8420-f193751a8118",
"content_key": "apcalcbc-mcq-043",
"from_md5": "6685a6e8d40a2c7eb4e5e11b7e6ad0f2",
"to_stem": "A particle has position r(t)=⟨t²−2t,e^(−t)⟩. What is its speed at t=1.4, to the nearest thousandth?",
"choices_md5": "064f3b54b27e78e4bd1c201ebcdb2507"
},
{
"version_id": "519b75bf-b623-404e-9ad7-da11290053dd",
"content_key": "apcalcbc-mcq-044",
"from_md5": "b40478991002e4b7418939fad51c40ff",
"to_stem": "What is the area of one petal of the polar curve r=2sin(3θ)?",
"choices_md5": "cf2320ba6d8dfd8729d4972a55c3e572"
},
{
"version_id": "f4ea3f50-3a6d-460e-b40a-1be96890e04b",
"content_key": "apcalcbc-mcq-045",
"from_md5": "f9695ec647af855423e8a05b96c6888d",
"to_stem": "A curve is given by x=t+sin t and y=1−cos t. What is d²y/dx² at t=1, to the nearest thousandth?",
"choices_md5": "9e329682bdac19824c08e523ad9fb663"
},
{
"version_id": "194278ff-5e81-4785-a965-ce99467e3adc",
"content_key": "apcalcbc-mcq-046",
"from_md5": "5fb80aedf337eb6c908c339e066f7e60",
"to_stem": "What is the sum of Σ[n=1 to ∞] 5(−1/3)^(n−1)?",
"choices_md5": "cb2f15426be81c351d537344a77c9b97"
},
{
"version_id": "29374f52-56b5-4d44-8d07-182d10f36644",
"content_key": "apcalcbc-mcq-047",
"from_md5": "0d515435cbbfdfd1c9a0fe84ea5db0e6",
"to_stem": "Which statement describes Σ[n=1 to ∞](−1)^(n+1)/√n?",
"choices_md5": "8c5a7d6302e809bddcdf73e56bd49cde"
},
{
"version_id": "65eb803d-fa43-4292-81fe-dc81a672befc",
"content_key": "apcalcbc-mcq-048",
"from_md5": "1af2660bc176d514dba0a3144d40e7d3",
"to_stem": "What is the interval of convergence of Σ[n=1 to ∞](x−2)^n/(n3^n)?",
"choices_md5": "d4a8354db5690e28399dfb1c3d50e833"
},
{
"version_id": "4db8a57a-2691-4428-9e8c-2e806f26df40",
"content_key": "apcalcbc-mcq-049",
"from_md5": "707627b45bc38a14beddbe71ef6e8972",
"to_stem": "The degree-5 Maclaurin polynomial for sin x is used at x=0.7. Which is a valid Lagrange error bound?",
"choices_md5": "c2ba8402b642198275e340c4e51a4efc"
},
{
"version_id": "6fb0f714-1f8b-47fd-9c84-2caf309ee9f1",
"content_key": "apcalcbc-mcq-050",
"from_md5": "678f52c4cdf09a64c9fc1d81c0e46635",
"to_stem": "What is the coefficient of x⁷ in the Maclaurin series for x²e^(−x)?",
"choices_md5": "bffad66e4f4b94898f5c3923eb091511"
},
{
"version_id": "2f26bf80-3101-48fd-960f-526221f2a464",
"content_key": "apcalcbc-mcq-ab-021",
"from_md5": "575d6b06c192c30964109a41afeac1b3",
"to_stem": "What is lim(x→2) (x²−4)/(x−2)?",
"choices_md5": "2e9f06f5e3cc5c17fc410d7a82b5b7b0"
},
{
"version_id": "98425cfb-20e4-4325-a0bd-cb5a1a3050a2",
"content_key": "apcalcbc-mcq-ab-022",
"from_md5": "c231ce20d0e1c12ce4075e92c2d85cda",
"to_stem": "Let f(x)=kx+1 for x<2 and f(x)=x²−1 for x≥2. For what value of k is f continuous at x=2?",
"choices_md5": "974d9e9326ac34f5f2c4c96b9bd74788"
},
{
"version_id": "d690b8fc-67ea-4ad9-85d4-2408e38a3cf6",
"content_key": "apcalcbc-mcq-ab-024",
"from_md5": "72e282b336b9a4253187298e2c835cd5",
"to_stem": "What is lim(x→∞) (5x²−x+4)/(2x²+3)?",
"choices_md5": "d65b8564fb770d5a7de48cdd75232aa8"
},
{
"version_id": "98d30b24-d358-4a14-b7ff-11a9251c86b4",
"content_key": "apcalcbc-mcq-ab-025",
"from_md5": "163d8c51894d4e4254859bc35d7363bc",
"to_stem": "Which expression equals f′(3)?",
"choices_md5": "ee91542a00e0bdb6499ae40880646da9"
},
{
"version_id": "3b0ec592-ec60-4dc7-8aa3-3db8a02c0cb9",
"content_key": "apcalcbc-mcq-ab-026",
"from_md5": "6a4c960b7d73c682605172bb98276792",
"to_stem": "If f(x)=x²e^x, what is f′(1)?",
"choices_md5": "c053b0503fbe903d211b172701dd8741"
},
{
"version_id": "ff2d65f4-eb9b-4a30-907f-42bb3d2e82ea",
"content_key": "apcalcbc-mcq-ab-027",
"from_md5": "3f06ad188a925fb63f30f269787032a8",
"to_stem": "What is d/dx[sec x tan x]?",
"choices_md5": "a2708819463195919a1e9981c92586eb"
},
{
"version_id": "30fe73a6-7911-46a5-9c5e-81425aa46ba2",
"content_key": "apcalcbc-mcq-ab-028",
"from_md5": "4edecb38995411da32ab1f8855ea8115",
"to_stem": "Which statement is always true?",
"choices_md5": "f362a993850c28d4cb926e6e5c88ffff"
},
{
"version_id": "afefdd33-23f9-45d1-a64b-0a3f5f5b2e94",
"content_key": "apcalcbc-mcq-ab-029",
"from_md5": "1f31314b9a4be0cf34c3aa429075e131",
"to_stem": "If f(x)=sin(x²), what is f′(x)?",
"choices_md5": "73ed09b63183318715899bc228e023a4"
},
{
"version_id": "05fb2931-3b7b-4114-ba57-26a1c687ca52",
"content_key": "apcalcbc-mcq-ab-030",
"from_md5": "5f9d1879a1e73c671414d6a6c2d8f58e",
"to_stem": "For the curve x²+y²=25, what is dy/dx at (3,4)?",
"choices_md5": "ba5d55849cc489dc741e158273a71fe3"
},
{
"version_id": "94bf5ab0-4fc3-4b53-bac9-62ed9de33fe1",
"content_key": "apcalcbc-mcq-mv045",
"from_md5": "6372dcfc0358bd2e8ade629f2820dd7f",
"to_stem": "Use Euler's method with step size 0.5 to estimate y(1) for y′=x+y and y(0)=1.",
"choices_md5": "45d4df2389e7427d62cf0e3659d3e2d0"
},
{
"version_id": "6202f329-6245-4fef-ab40-0a7b8a14c525",
"content_key": "apcalcbc-mcq-mv046",
"from_md5": "46b1f0b4affb1327bc47b12b12593373",
"to_stem": "A population follows dP/dt=0.18P(1−P/900). At what population is the instantaneous growth rate greatest?",
"choices_md5": "efbcc042f3c5c8c4e2fa3f9ea3cefef4"
},
{
"version_id": "c431bc9c-5cfe-4059-96f8-98e8589d8410",
"content_key": "apcalcbc-mcq-mv050",
"from_md5": "5a831203ab90c0d8ca50218326e2d5fb",
"to_stem": "What is the length of y=x² from x=0 to x=1.4, to the nearest thousandth?",
"choices_md5": "a34eb742b6c61325a88964ea96369681"
},
{
"version_id": "d22a425d-8702-43f4-bc38-554f355e04ae",
"content_key": "apchem-mcq-001",
"from_md5": "ae15b06b8d9666316c1533de59080c83",
"to_stem": "A 9.00 g sample of water (18.0 g mol⁻¹) contains how many moles?",
"choices_md5": "d24e9edf757cd74f5f20191cbe421094"
},
{
"version_id": "67816f8d-f41f-4c58-a4ae-4966efc7a318",
"content_key": "apchem-mcq-003",
"from_md5": "1532a8a46e227c2acddb4c4c1c1af0da",
"to_stem": "Which species has a trigonal planar molecular geometry?",
"choices_md5": "415f74d11b81dc9498cf7912fe3c2abd"
},
{
"version_id": "c360ba4c-aa2e-4be8-9808-431775a9dae4",
"content_key": "apchem-mcq-004",
"from_md5": "80288597029318229752978e50eed2bf",
"to_stem": "Why does solid NaCl not conduct while molten NaCl does?",
"choices_md5": "37cf28f62f76a0baf986128f5e746d3e"
},
{
"version_id": "b1befb18-d6df-43af-ab68-ddb88423ed33",
"content_key": "apchem-mcq-005",
"from_md5": "7a00c0f2aca1e4bb70acaa295453a43a",
"to_stem": "At the same temperature, which gas sample has the greatest average particle speed?",
"choices_md5": "1ac65376816a9de90615269d7eebfe1e"
},
{
"version_id": "fadd26cc-8d63-4c1d-9d58-9c8550792e36",
"content_key": "apchem-mcq-008",
"from_md5": "4667f18b17f88bd28c1d7eac5964a7a0",
"to_stem": "A gas occupies 2.0 L at 1.0 atm. At constant temperature and fixed amount of gas, its volume at 4.0 atm is",
"choices_md5": "6e2a3f8b46d67708266811baff214385"
},
{
"version_id": "c5b49ad8-9764-4ded-b73b-f6bbf8d612a0",
"content_key": "apchem-mcq-009",
"from_md5": "445df89195b5c90ddbbea5e41151853e",
"to_stem": "For 2 H₂ + O₂ → 2 H₂O, how many moles of water form from 3.0 mol O₂ with excess H₂?",
"choices_md5": "ddacfd9502cba88737d91d43db229334"
},
{
"version_id": "d99a02b1-d931-4bfb-babe-69bcd837c5fd",
"content_key": "apchem-mcq-010",
"from_md5": "092948f8161e340ca354e93371248ea7",
"to_stem": "Which ions are spectators when AgNO₃(aq) and NaCl(aq) form AgCl(s)?",
"choices_md5": "52654bba06e3710ee0e52cdecb860884"
},
{
"version_id": "27ef02be-bead-4584-8fbe-e26f6f7c3b5d",
"content_key": "apchem-mcq-011",
"from_md5": "e853c722b9ecacdf761c1c7858e85a47",
"to_stem": "Doubling [A] quadruples the rate while other concentrations remain fixed. The reaction is",
"choices_md5": "4737a13de1f31bb382ea476e5afaba04"
},
{
"version_id": "2038acfa-ec05-4cc8-b1d3-8d126b2a6461",
"content_key": "apchem-mcq-012",
"from_md5": "3aad50d32cb82567f35ca8c8d2270e21",
"to_stem": "A catalyst speeds a reaction because it",
"choices_md5": "6e282afcca07bed6ff5b807a7b032267"
},
{
"version_id": "ec5e88d3-622a-482a-b89d-cefc3cf7afd5",
"content_key": "apchem-mcq-013",
"from_md5": "34e151472b3461e15441aae405f6e96b",
"to_stem": "A 100 g metal absorbs 2.50 kJ and warms by 50.0°C. Its specific heat is",
"choices_md5": "b6cbb289b5db41e2ff05201f4ab81a6e"
},
{
"version_id": "9e7fff7f-3d3c-491a-9b12-4aaba7890769",
"content_key": "apchem-mcq-014",
"from_md5": "779e1d1adc1964af5e7e837af1f04e52",
"to_stem": "If ΔH is negative for a process at constant pressure, the system",
"choices_md5": "ec7eefb4ffae7761f78bd97925a80f7b"
},
{
"version_id": "e47eb90a-bc6a-4f7e-a10c-3b7b4a66a9ef",
"content_key": "apchem-mcq-015",
"from_md5": "746345d6a0f5a58156fcc43c0ccf03cd",
"to_stem": "For a reaction with Q<K, the system initially shifts",
"choices_md5": "b3a059c829b0c5f37d3127ac74ca6cec"
},
{
"version_id": "1c65cbef-2352-4274-b12e-05f781c3a9e7",
"content_key": "apchem-mcq-016",
"from_md5": "ac7a2930d487cbc6ee0176b9be89c352",
"to_stem": "Adding an inert gas at constant volume and constant temperature does not change an ideal-gas equilibrium because",
"choices_md5": "80cf77856d3afe585eb37f3ff49c64a4"
},
{
"version_id": "f79fcfa0-ec2e-4c06-a21b-abe42c8b4f3b",
"content_key": "apchem-mcq-018",
"from_md5": "bc3e937cfb1777deaa7f5637e53b07da",
"to_stem": "A buffer contains comparable amounts of HA and A⁻. Adding a small amount of H⁺ primarily causes",
"choices_md5": "6aa4c7f3919b9c648bbb65989f8aaef0"
},
{
"version_id": "cc5c9ef2-1b56-4ec4-902c-5bfa11b61c71",
"content_key": "apchem-mcq-019",
"from_md5": "465d19e8b01c33cbc9187671345e5797",
"to_stem": "At constant temperature and pressure, a process is thermodynamically favorable when",
"choices_md5": "9aa2c1db5413184604ea9a14e2d33aa9"
},
{
"version_id": "93e8cec6-75df-4826-b28a-37dbbe6100a0",
"content_key": "apchem-mcq-020",
"from_md5": "a4cf1a4a5b1d166aa3dc0664eb472b06",
"to_stem": "For a galvanic cell under standard conditions, E°cell>0 implies",
"choices_md5": "1f8dcdc40d496e176362891c01c27a95"
},
{
"version_id": "1ddc5cee-33ed-4b0d-aa0b-185da24a051e",
"content_key": "apchem-mcq-021",
"from_md5": "bbe6c056583dc6ac04bac4c8c97726a9",
"to_stem": "A sample of pure glucose (C6H12O6, molar mass = 180.16 g/mol) has a mass of 90.0 g. How many moles of glucose does the sample contain?",
"choices_md5": "41b677f178b06157ca9286885dd1397a"
},
{
"version_id": "e6ee9d9a-9633-4bf5-8370-ed02fe2fdb46",
"content_key": "apchem-mcq-022",
"from_md5": "dea33aa31e1f3742b3c0b835fa9f760a",
"to_stem": "What is the ground-state electron configuration of the Fe3+ ion (Fe, Z = 26, ground-state configuration [Ar]3d^6 4s^2)?",
"choices_md5": "d7108655a2d6271704289538a900e40e"
},
{
"version_id": "99803fab-c449-4a33-8a8e-859eee468990",
"content_key": "apchem-mcq-023",
"from_md5": "a8cca9ce5ed30261876bdea13ff8f911",
"to_stem": "The photoelectron spectrum of a neutral atom of an unknown element shows exactly four peaks. Listed in order of decreasing binding energy, the relative peak areas (relative numbers of electrons) are 2, 2, 6, and 2. Identify the element.",
"choices_md5": "38b9a8d1d7289f78c3923f5fead2002a"
},
{
"version_id": "89a2d1d9-1c53-45e0-8037-659ccb349392",
"content_key": "apchem-mcq-024",
"from_md5": "203422a14e103f6ff619c0332c62a1bb",
"to_stem": "The first ionization energy of magnesium (738 kJ/mol) is greater than that of aluminum (578 kJ/mol), even though aluminum has a higher nuclear charge. Which statement correctly explains this trend?",
"choices_md5": "e382a2f60450a537af8b39f016be7e3f"
},
{
"version_id": "0c3b7b61-5083-4f8f-aced-2e0d50ea22b5",
"content_key": "apchem-mcq-025",
"from_md5": "4252b945e3a300262ac7b33e38cd7974",
"to_stem": "Based on electronegativity differences (using the Pauling scale: Cs = 0.79, C = 2.55, H = 2.20, O = 3.44, F = 3.98, N = 3.04), which pair of atoms would be predicted to form a bond with the greatest ionic character?",
"choices_md5": "393ccda3ce4edad9cb3b0102b5845c62"
},
{
"version_id": "0a535dc3-dbc8-456d-a9fd-5e228246be63",
"content_key": "apchem-mcq-026",
"from_md5": "b0794d5230341c5385b15de6a150b34e",
"to_stem": "Which of the following species requires an expanded (greater than octet) valence shell around its central atom in its best Lewis structure?",
"choices_md5": "c3cf58d68ea97cb0790f3b6f269589a1"
},
{
"version_id": "f68af92a-ea07-43b1-9567-553ad9d4f703",
"content_key": "apchem-mcq-027",
"from_md5": "d9848cc804490a9a97a66d22804aea78",
"to_stem": "The nitrite ion, NO2-, is represented by two equivalent resonance contributors in which nitrogen forms one N=O double bond and one N–O single bond (with the negative charge delocalized by resonance). In this Lewis structure, what is the formal charge on the singly-bonded oxygen atom?",
"choices_md5": "63a0e6e07d6cb5f1d108c635f5a52e01"
},
{
"version_id": "8c5798af-66dc-4e70-a7a4-522e217784a3",
"content_key": "apchem-mcq-028",
"from_md5": "c369f99731ec8f6c97ef820464ede051",
"to_stem": "What are the electron-domain geometry and molecular (molecular-domain) shape of SF4?",
"choices_md5": "72a35296ee4e4be8e096f2e7bda83fdf"
},
{
"version_id": "0d6df8e6-6334-459c-9b1e-a7044546e314",
"content_key": "apchem-mcq-029",
"from_md5": "0629abf5742b933bda4752c2055eac15",
"to_stem": "Which substance is expected to have the highest normal boiling point?",
"choices_md5": "f07b395704ec8b7e646e01367129ff08"
},
{
"version_id": "0a499374-2bed-4302-9eee-5bc170186ca0",
"content_key": "apchem-mcq-030",
"from_md5": "64449b8c2939e0fd147613f1427b9e6e",
"to_stem": "CH3F and CH3OH have similar molar masses (34 g/mol and 32 g/mol, respectively), yet CH3OH has a substantially higher boiling point (65C) than CH3F (-78C). What best explains this difference?",
"choices_md5": "125a1d2272a57f9a54b38145f8f20887"
},
{
"version_id": "0baf4908-dc68-4ede-85ef-934d4cec725d",
"content_key": "apchem-mcq-031",
"from_md5": "12a40d06ad7efe89b33fca8ad506f701",
"to_stem": "A solid sample conducts electricity well in both its solid and molten states, is malleable (can be hammered into sheets without shattering), and has a moderately high melting point. What type of solid is this sample most likely to be?",
"choices_md5": "03730c76ea269cf0b889d2250e873aec"
},
{
"version_id": "c9df7103-b591-4276-844b-e60c9f74654f",
"content_key": "apchem-mcq-032",
"from_md5": "08b6430662c7412938c4d7fa69132393",
"to_stem": "A rigid 2.00 L container holds 0.500 mol of an ideal gas at 27C. What is the pressure of the gas? (R = 0.08206 L*atm/(mol*K))",
"choices_md5": "bc45d0a6a955722f19b954b134b0250b"
},
{
"version_id": "9e049c05-c49e-4b95-b4b9-a777c60c0d2e",
"content_key": "apchem-mcq-033",
"from_md5": "2a5c69328f95b5b0f6db644bbbbd27dc",
"to_stem": "Separate rigid containers hold samples of He(g) and O2(g) at the same temperature. According to kinetic molecular theory, which statement correctly compares the two samples?",
"choices_md5": "c03cd82826a5ebdce6b79ad758ca49b3"
},
{
"version_id": "9c848fdb-a55d-4e02-a30b-9c49cf007b4b",
"content_key": "apchem-mcq-034",
"from_md5": "e85311fc18641cc6c7b3a098d0aea642",
"to_stem": "Under which set of conditions would a real gas be expected to deviate most significantly from ideal gas behavior, and why?",
"choices_md5": "a68bbf7dbcd6fb6c6d82b311937f22d6"
},
{
"version_id": "abaf2bd3-3b9e-40fd-8737-c11733abbcdd",
"content_key": "apchem-mcq-035",
"from_md5": "ce603f7519b03035bf22d3117d93f9f4",
"to_stem": "As the temperature of water increases, the solubility of a gas such as O2(g) in the water generally decreases. Which statement best explains this observation?",
"choices_md5": "5b337265f1c178ce816084a116818343"
},
{
"version_id": "33ce2b12-d3ad-4bb2-b893-06e5202f7836",
"content_key": "apchem-mcq-036",
"from_md5": "f4eebdbd07f4456943711e03e55fb475",
"to_stem": "A colored solution has a molar absorptivity of 1.50 x 10^3 M^-1 cm^-1 at its wavelength of maximum absorbance. When placed in a cuvette with a 1.00 cm path length, the solution's absorbance is measured as 0.750. What is the molar concentration of the solution?",
"choices_md5": "5c587fad5a1e09bcd327b95b7ca15564"
},
{
"version_id": "58bd9254-2451-49bb-bad2-eeac957d595a",
"content_key": "apchem-mcq-037",
"from_md5": "4d169225112a98c062e52400adf0d76e",
"to_stem": "A photon of ultraviolet (UV) light is compared to a photon of infrared (IR) light. Which statement correctly ranks their energies and justifies the ranking?",
"choices_md5": "c8a6d591fa5e1e3a1003596cb74f0716"
},
{
"version_id": "a43ad81a-5ac8-4f74-8d40-2b88f7c30f0c",
"content_key": "apchem-mcq-038",
"from_md5": "04e734f1581ef70734789c05b4f285f9",
"to_stem": "A chemist needs to recover acetone (boiling point 56 °C) from a homogeneous mixture of acetone and water (boiling point 100 °C). The two liquids are miscible and do not form an azeotrope. Which technique is most appropriate, and why?",
"choices_md5": "351cbdbf7d10d155d11c0dc80f9d621b"
},
{
"version_id": "e5477db9-0823-45d2-9f56-d031977b10d7",
"content_key": "apchem-mcq-039",
"from_md5": "3275dc9e6fe314d5c4814cf32fd9d1c3",
"to_stem": "A student dilutes 25.0 mL of a 2.00 M stock solution to a final total volume of 200.0 mL. What is the molarity of the resulting diluted solution?",
"choices_md5": "9c6eabb1d65bd7b71cda58f2d27a4b6f"
},
{
"version_id": "7c443eb4-8aad-493d-a4d3-02190ca66b7f",
"content_key": "apchem-mcq-040",
"from_md5": "4d5e98f6e3cd59b14edfe6445ee1089d",
"to_stem": "A student reacts 5.4 g of Al (molar mass 27.0 g/mol) with 3.2 g of O2 (molar mass 32.0 g/mol) according to the balanced equation 4Al(s) + 3O2(g) -> 2Al2O3(s) (molar mass Al2O3 = 102.0 g/mol). What mass of Al2O3 is produced, assuming the reaction goes to completion?",
"choices_md5": "b9ab7a3d610cae4095f3824d99465d62"
},
{
"version_id": "257f5379-6555-4286-b85b-7a41fba7842a",
"content_key": "apchem-mcq-041",
"from_md5": "9d0e89e3beaef44640d7246b6d3680c2",
"to_stem": "Aqueous solutions of Pb(NO3)2 and KI are mixed, forming a yellow precipitate: Pb(NO3)2(aq) + 2KI(aq) -> PbI2(s) + 2KNO3(aq). Which equation correctly represents the net ionic equation for this reaction?",
"choices_md5": "5583dd7cad3c60daf456e2d58ce29570"
},
{
"version_id": "02408752-a11b-40fd-b99f-5d5abc5abf5e",
"content_key": "apchem-mcq-042",
"from_md5": "761e8b3d94c2c0fa06a3e93f7bb0ea1a",
"to_stem": "In the reaction Zn(s) + 2AgNO3(aq) -> Zn(NO3)2(aq) + 2Ag(s), which species is the oxidizing agent, and how does its oxidation state change?",
"choices_md5": "125abfbf3cda6dc90f24d1ebc70ba247"
},
{
"version_id": "99b2b547-b2a8-49a9-bf16-c692589ec7c6",
"content_key": "apchem-mcq-043",
"from_md5": "c9c4c1e033a55f18ce6e01660bde7b2a",
"to_stem": "Which type of chemical reaction is represented by CaCO3(s) -> CaO(s) + CO2(g) upon heating?",
"choices_md5": "74758df1b46806294c168059ab7d7823"
},
{
"version_id": "b050e0db-5eb9-45c9-a00a-4d40a08c13cb",
"content_key": "apchem-mcq-044",
"from_md5": "a5be18aa02acf3fcc967839ca012a993",
"to_stem": "A 25.00 mL sample of HCl(aq) is titrated to the equivalence point using 0.100 M NaOH(aq), requiring 32.50 mL of titrant according to HCl(aq) + NaOH(aq) -> NaCl(aq) + H2O(l). What is the concentration of the HCl solution?",
"choices_md5": "ceb03c601adfc778e4d8067097d5068d"
},
{
"version_id": "3b490535-520e-4500-98b6-e83034141f46",
"content_key": "apchem-mcq-045",
"from_md5": "1447001874d980c6256a0323108387bb",
"to_stem": "Dinitrogen pentoxide decomposes according to the equation 2 N2O5(g) -> 4 NO2(g) + O2(g). At a certain point during the reaction, O2 is forming at a rate of 0.015 M/s. What is the rate of disappearance of N2O5 at that same instant?",
"choices_md5": "f17369f9e70f65c806bb5d6d1656672a"
},
{
"version_id": "938c2a66-d889-4b80-bfb0-858f425e30d0",
"content_key": "apchem-mcq-046",
"from_md5": "2f4ed3be144c547bcc94706619946948",
"to_stem": "The elementary step 2 X(g) + Y(g) -> products is proposed as part of a reaction mechanism. Which rate law is consistent with this elementary step?",
"choices_md5": "d0dc7aa87641d3dc10a1b9f358db2010"
},
{
"version_id": "06cc21e7-d68c-4a8f-a463-a13dcae0d066",
"content_key": "apchem-mcq-047",
"from_md5": "094c6fbe298a4d16c05f775a400c6615",
"to_stem": "A one-step reaction has an activation energy for the forward reaction, Ea(fwd), of 45 kJ/mol and an overall enthalpy change, deltaH, of -20 kJ/mol. What is the activation energy for the reverse reaction, Ea(rev)?",
"choices_md5": "76f9539fae7ad6ab45fb84ff87add55d"
},
{
"version_id": "4d27c8d2-8521-4043-a254-09a6f5c85998",
"content_key": "apchem-mcq-048",
"from_md5": "7b8c7a5318dbd49d78b88f4f50c1242d",
"to_stem": "Which of the following correctly describes how a catalyst increases the rate of a chemical reaction?",
"choices_md5": "692a405e96f2ac377c90f7cc7c7d8da0"
},
{
"version_id": "ad10a23b-bc26-45e7-ab78-47c9cea66001",
"content_key": "apchem-mcq-049",
"from_md5": "235b16ec0a24dea12afda7a46b60fc1f",
"to_stem": "A student dissolves a sample of solid ammonium nitrate in water inside a coffee-cup calorimeter. As the solid dissolves, the temperature of the solution drops from 25.0 C to 18.5 C. Which statement correctly describes this dissolution process?",
"choices_md5": "50803c06235bff406950c8b46f8db630"
},
{
"version_id": "7456dabc-c72b-49a3-976f-76cc224fcd83",
"content_key": "apchem-mcq-051",
"from_md5": "ac31acb0372d6f59e99fbb8f8619b50e",
"to_stem": "Using average bond enthalpies (H-H = 436 kJ/mol, Cl-Cl = 243 kJ/mol, H-Cl = 431 kJ/mol), estimate deltaH for the reaction: H2(g) + Cl2(g) -> 2 HCl(g)",
"choices_md5": "3b88f3038475fd338c639c41fd7d6514"
},
{
"version_id": "389fc6e4-cd85-4680-9722-0932d615c709",
"content_key": "apchem-mcq-052",
"from_md5": "387751842e5dbb43c826fd20aa0f4073",
"to_stem": "Given standard enthalpies of formation Delta Hf standard: CH4(g) = -74.8 kJ/mol, CO2(g) = -393.5 kJ/mol, H2O(l) = -285.8 kJ/mol, and O2(g) = 0 kJ/mol, calculate Delta H(rxn) for: CH4(g) + 2 O2(g) -> CO2(g) + 2 H2O(l)",
"choices_md5": "dcee3a45203864e1788663da3afd98eb"
},
{
"version_id": "2f157e6c-4421-4989-a060-67b59ed1d9e0",
"content_key": "apchem-mcq-053",
"from_md5": "225419cab1ad13d755576dcd822589e2",
"to_stem": "Given the following thermochemical equations:\n(1) C(s) + O2(g) -> CO2(g), deltaH1 = -393.5 kJ\n(2) CO(g) + 1/2 O2(g) -> CO2(g), deltaH2 = -283.0 kJ\nUse Hess's Law to find deltaH for: C(s) + 1/2 O2(g) -> CO(g)",
"choices_md5": "bfeaf01b1b6ef62bf42be6e6a49b54cf"
},
{
"version_id": "3171c639-e6e3-4775-9961-b83609deec9e",
"content_key": "apchem-mcq-054",
"from_md5": "99b7dc82667b67d3aebf59d26d8b5736",
"to_stem": "For the heterogeneous equilibrium CaCO3(s) <-> CaO(s) + CO2(g), which expression correctly represents the equilibrium constant, Kc?",
"choices_md5": "4793d431804dd91237629519589e46f2"
},
{
"version_id": "187c11be-5220-4b94-9e0a-a5c1b1f7c720",
"content_key": "apchem-mcq-055",
"from_md5": "84c1fca60d68f7c0115a19c33631bb85",
"to_stem": "At a given temperature, a reaction has Kc = 4.3 x 10^-9. What does this value indicate about the reaction mixture at equilibrium?",
"choices_md5": "402c8f93e43da942ba41f2a4cb16b123"
},
{
"version_id": "3ce5264a-7c9e-42b2-a4a0-65227fee2021",
"content_key": "apchem-mcq-056",
"from_md5": "52821c51577eb901273de78233a79c86",
"to_stem": "For N2(g) + 3H2(g) <-> 2NH3(g), Kc = 0.50 at a certain temperature. A reaction mixture is sampled and Qc is calculated to be 2.0. Which statement correctly describes how the system will respond?",
"choices_md5": "a93818be453123671cd7fd3e27b231d6"
},
{
"version_id": "fbbbb532-1691-4ea7-bda7-729e1fb15a1c",
"content_key": "apchem-mcq-058",
"from_md5": "ce64acf42b18a58de37cb6608e098b99",
"to_stem": "In the reaction HSO4-(aq) + H2O(l) <-> H3O+(aq) + SO4^2-(aq), which species is the conjugate base of HSO4-?",
"choices_md5": "ae1b276f40a14fbbf100891a0840f6de"
},
{
"version_id": "913eb429-6989-4f9f-ad24-98ee98b55a93",
"content_key": "apchem-mcq-059",
"from_md5": "c84f05cf825ae52d9c20c2e02114f95e",
"to_stem": "What is the pOH of a 0.0025 M HCl solution at 25 C? (HCl is a strong acid.)",
"choices_md5": "4ca0fc9e111281be0548f86d4a0534dc"
},
{
"version_id": "b71d2ae6-5884-490e-b44b-3335aa936980",
"content_key": "apchem-mcq-060",
"from_md5": "ca751d54465c7dbd9b8238e55d46a5d2",
"to_stem": "A 0.10 M solution of a weak monoprotic acid HA has Ka = 1.0x10^-5. Assuming the approximation x much less than 0.10 is valid, what is the pH of the solution?",
"choices_md5": "ad9c78549873c1fb0956597539556188"
},
{
"version_id": "c68402dd-2032-41bc-91fb-84b1c0d9d529",
"content_key": "apchem-mcq-062",
"from_md5": "152612ca27ace151721e661a9339d0ef",
"to_stem": "Which of the following hypohalous acids is the strongest acid, and why?",
"choices_md5": "7b0dd30c6f3ea0e4bebe429b19cb6b70"
},
{
"version_id": "aa03ff47-9e9b-4401-83d8-636f6d537918",
"content_key": "apchem-mcq-063",
"from_md5": "1a64a3724e3ddc39d54af856cfd5795a",
"to_stem": "During the titration of a weak monoprotic acid with NaOH, the pH at the half-equivalence point is measured to be 4.74. What is the Ka of the acid?",
"choices_md5": "45b6968476f6b3f5f1e7244effac1099"
},
{
"version_id": "a3b6c60a-1b4e-47d7-8c19-93abbcb05e03",
"content_key": "apchem-mcq-064",
"from_md5": "216b9b8fef376f56c202aa4d7b4b5d53",
"to_stem": "A buffer solution contains 0.30 M sodium acetate (CH3COONa) and 0.15 M acetic acid (CH3COOH), where acetic acid has Ka = 1.8x10^-5 (pKa = 4.74). What is the pH of this buffer?",
"choices_md5": "6e5531f86b528041a3719d38077d7c6e"
},
{
"version_id": "93314114-a6e2-497a-9b99-0f16cd20c9c2",
"content_key": "apchem-mcq-065",
"from_md5": "b41541f8ed95dce2accbdca0a5ea7682",
"to_stem": "Four buffer solutions are prepared using the same conjugate acid-base pair (same pKa). Which combination would provide the greatest buffer capacity?",
"choices_md5": "17ebb94eeccac0c42c002605071f7dcc"
},
{
"version_id": "e99c96f2-e0c4-47a6-8a42-993fafcf83a2",
"content_key": "apchem-mcq-067",
"from_md5": "2f88c4b88dfb95ce5611ad87b9f694c7",
"to_stem": "A galvanic cell is built from a Zn electrode in 1.0 M Zn(NO3)2 and a Cu electrode in 1.0 M Cu(NO3)2, connected by a wire and a salt bridge. E standard reduction (Cu2+/Cu) = +0.34 V; E standard reduction (Zn2+/Zn) = -0.76 V. Which statement correctly identifies the cathode and the direction of electron flow?",
"choices_md5": "6fb0795886269fa09f3645016ed7ceb0"
},
{
"version_id": "c5d5b783-6e2a-49db-9674-9df23e6b1bbe",
"content_key": "apchem-mcq-068",
"from_md5": "88f7504938662fc905e4df5f0196b8a7",
"to_stem": "A galvanic cell has a cathode half-reaction Ag+ + e- -> Ag(s), E = +0.80 V, and an anode half-reaction Pb(s) -> Pb2+ + 2e-, E(Pb2+/Pb) = -0.13 V. The overall balanced reaction transfers n = 2 mol electrons. What is deltaG for the cell reaction, and is it thermodynamically favorable?",
"choices_md5": "d3a2e17e1b70eb172c79fa1d7273a2df"
},
{
"version_id": "6e65dac8-3016-4cca-9461-77cbff9621b4",
"content_key": "apchem-mcq-069",
"from_md5": "a2d1daa1bb3b1b71e2e372373a4ebdea",
"to_stem": "For the cell Zn(s) | Zn2+(aq) || Cu2+(aq) | Cu(s), E°cell = +1.10 V. If [Cu2+] is decreased to well below 1 M while [Zn2+] remains at 1 M, how does the actual cell potential Ecell compare to E standard cell, and why?",
"choices_md5": "b171cddfb9b49cb50614f835c9ceca82"
},
{
"version_id": "701f1361-022e-4827-820b-60359240f885",
"content_key": "apchem-mcq-070",
"from_md5": "73de3426850ea75a06c020b488708038",
"to_stem": "A constant current of 2.00 A is passed through molten CaCl2 for 3.00 hours, depositing Ca(s) at the cathode via Ca2+ + 2e- -> Ca(s) (molar mass of Ca = 40.08 g/mol). What mass of Ca(s) is deposited?",
"choices_md5": "6dbc9837170225401e76bd1536b31c16"
},
{
"version_id": "80ab716d-cb3c-4226-a9c2-627e21309f9e",
"content_key": "apphy2-mcq-010",
"from_md5": "beb16cc6a960879abcf813d3e13ae402",
"to_stem": "A particle with charge q moves with speed v in a direction parallel to a uniform magnetic field of magnitude B. The magnetic force on the particle is--",
"choices_md5": "1fee493380a7dd0cc5ed7f59bfe814c5"
},
{
"version_id": "f8952991-b8db-4914-89a9-0a537f6ec5ae",
"content_key": "apphy2-mcq-012",
"from_md5": "a15c7e0ecc2d99f69d6b6acff7b3f763",
"to_stem": "Lenz's law determines the induced current's",
"choices_md5": "ab7e7785cd3be4b5ccdeb868f300f9a6"
},
{
"version_id": "6d4fc26b-a60d-4fc0-83e5-9f272a68994c",
"content_key": "apphy2-mcq-013",
"from_md5": "42eab5c0e0505142d89eb0dfa584af4b",
"to_stem": "A beam of monochromatic light travels from air into glass. As the light crosses the boundary, its frequency--",
"choices_md5": "0d851750eddd115c392bb5cd506194ba"
},
{
"version_id": "d1204237-373b-4ad7-a36c-803c6656cfd9",
"content_key": "apphy2-mcq-014",
"from_md5": "012b30ba3ba63cfa2c2c3300964b7a87",
"to_stem": "A converging lens forms a real inverted image when the object is",
"choices_md5": "14c1fb9544acc59f8e133ce5b6287d3a"
},
{
"version_id": "9d1fee80-d912-43d6-8746-f2795f09787b",
"content_key": "apphy2-mcq-016",
"from_md5": "f5daf84f84e428609edc5d18028e9e41",
"to_stem": "A periodic wave has frequency 5.0 Hz and wavelength 0.60 m. What is its speed?",
"choices_md5": "8d4fa6805c3a8fb7631d097c22b983ae"
},
{
"version_id": "0975e43b-f228-403c-8b10-3bb449942a51",
"content_key": "apphy2-mcq-017",
"from_md5": "c46f84c89cfd55fb02a7b7adfd0e0dee",
"to_stem": "Two coherent sources, initially in phase, emit waves of the same wavelength. Constructive interference at a point occurs when the path difference between the waves is",
"choices_md5": "d814e348c2bbd469bacceae272bf7b51"
},
{
"version_id": "21247dc8-cf80-4098-b5bc-a84792d7ca10",
"content_key": "apphy2-mcq-019",
"from_md5": "1a5d64c2478fcad2dfff3a7a4c07abbe",
"to_stem": "A photon has energy",
"choices_md5": "fc118c584dafdeeb7649d1e515e9f4e1"
},
{
"version_id": "eeae7b54-8e4a-4a14-bb34-d2c46a628fc0",
"content_key": "apphy2-mcq-020",
"from_md5": "32f70727e5d5a1c098c4e3acf3cbb2af",
"to_stem": "In the photoelectric effect, increasing the frequency of light above the threshold frequency primarily increases",
"choices_md5": "44f26c8cc3c8a06230df4595e6210198"
},
{
"version_id": "904498ef-0e49-49f1-99d5-98c5c53deb7b",
"content_key": "apphy2-mcq-031",
"from_md5": "810bbea9e2f953fbf36a052ad15689f8",
"to_stem": "A long straight wire carries current upward. At a point directly east of the wire, the magnetic field points",
"choices_md5": "26e2411117fd8d977cffe9b5b7616c7e"
},
{
"version_id": "9add92ae-19a8-4b53-aaeb-24362f0f4842",
"content_key": "apphy2-mcq-032",
"from_md5": "f981d2a7f7491d5df1d9d85910fde935",
"to_stem": "A charged particle moves perpendicular to uniform B. If its speed doubles with q, m, and B fixed, its circular-path radius",
"choices_md5": "eeaa3a58b4095409a165ef0318377f16"
},
{
"version_id": "5664df1f-203d-47f1-a544-227bbf2bfeb6",
"content_key": "apphy2-mcq-033",
"from_md5": "7ecddc0881000be0a7b7d8df2b4e2f91",
"to_stem": "The magnetic flux into the page through a loop is increasing. The induced current is",
"choices_md5": "9e343de23582cb6dea9d748700a475eb"
},
{
"version_id": "1124f048-e37b-4337-9cb6-b3305820973b",
"content_key": "apphy2-mcq-034",
"from_md5": "169a03545c4e72a25d5c69f8ed98ca02",
"to_stem": "A ray strikes a plane mirror at 25° measured from the normal. Its reflection angle measured from the normal is",
"choices_md5": "056f731e0a5dd84df0501efc383aeab5"
},
{
"version_id": "baebe382-6429-4f75-a28f-e0e40e964daa",
"content_key": "apphy2-mcq-035",
"from_md5": "c3aa52763411f19bcd28bebb39d9d571",
"to_stem": "A plane mirror forms an image that is",
"choices_md5": "4fca05b86ac1412cc5ac6e1b1db606cb"
},
{
"version_id": "1ff33c89-a38e-43f1-b83d-88261d6ba0ac",
"content_key": "apphy2-mcq-036",
"from_md5": "e2d051534c67627f58f7a024d519b07d",
"to_stem": "Light enters glass from air at an oblique angle. Because glass has larger refractive index, the ray bends",
"choices_md5": "63410fef6f622d3ff1b584133f3451c0"
},
{
"version_id": "f9bd3c8d-0ee2-4783-902f-e721a867b065",
"content_key": "apphy2-mcq-037",
"from_md5": "695b04bf731200d4a8d4a01a41397240",
"to_stem": "A periodic wave crosses into a medium where its speed decreases. Its frequency",
"choices_md5": "723954e520bd97794f6949de88d3be98"
},
{
"version_id": "81d4eb9c-d8b7-4df1-a229-8abd0aab3af3",
"content_key": "apphy2-mcq-038",
"from_md5": "4e32d7b354c3187aa5fd691cfa07319e",
"to_stem": "In an electromagnetic wave in vacuum, electric and magnetic fields are",
"choices_md5": "a2cf160c70e8bb866b7ab2b5f654a6fb"
},
{
"version_id": "d7a58c0f-488b-4eae-946a-2bb6223f4e20",
"content_key": "apphy2-mcq-039",
"from_md5": "b96af133974aaf75393f5054c0fdccdd",
"to_stem": "A sound source moves away from a stationary observer. The observed frequency is",
"choices_md5": "3706881860956e794245e795f6345be3"
},
{
"version_id": "c0cf1fa7-2e01-4dca-85e2-6e1dad5bb9b4",
"content_key": "apphy2-mcq-040",
"from_md5": "472ff0fcee5e239b2250ef38696158bc",
"to_stem": "A bright atomic emission line is produced when an electron",
"choices_md5": "19cb92b9b43743ced269bd2c1a307291"
},
{
"version_id": "88061f49-923f-46f4-830c-ad9ef63db3d8",
"content_key": "apphy2-mcq-041",
"from_md5": "dbe1254714254d327424cbfecb96c702",
"to_stem": "In Compton scattering, an X-ray photon transfers energy and momentum to an electron. The scattered photon's wavelength is generally",
"choices_md5": "a681a699a9b072c4228eb3db362eb729"
},
{
"version_id": "425aa4fb-4a89-4c9a-965f-024d59f67674",
"content_key": "apphy2-mcq-042",
"from_md5": "9aac244c9222682f23e9a684261e57e9",
"to_stem": "In beta-minus decay, a neutron changes into",
"choices_md5": "00e06df410fea1220d1e2098d1c76cc4"
},
{
"version_id": "3d8748d0-fdb6-47fa-bf9a-378ac440435c",
"content_key": "apphycem-mcq-010",
"from_md5": "3ea14a48f97f973ec98010215c32369d",
"to_stem": "For capacitor discharge through R, charge follows",
"choices_md5": "885e231f011856980877a144ac0f77ed"
},
{
"version_id": "ca322b9b-4d53-4c08-bda8-81028cb9bb4f",
"content_key": "apphycem-mcq-011",
"from_md5": "e85a4c4e079358cd8d9d773b7b9dadb8",
"to_stem": "A 2.0 uF capacitor, initially charged to 12 V, discharges through a 500 kOhm resistor. Approximately how long does it take for the charge to fall to 37% of its initial value?",
"choices_md5": "5d96f244176f0ccfed582730013b1182"
},
{
"version_id": "4dbb7d4d-c572-46f3-9947-afcc9b107162",
"content_key": "apphycem-mcq-012",
"from_md5": "087da4719c192317501b57c71b57c37b",
"to_stem": "Kirchhoff's junction rule follows from conservation of",
"choices_md5": "8c1afc63b4a1258ae361bfaae8664a5f"
},
{
"version_id": "af65207c-0029-4d96-811a-492016f25afb",
"content_key": "apphycem-mcq-014",
"from_md5": "a1e64bb0518846313b8720a7c4c59a60",
"to_stem": "Ampère's law in magnetostatics is useful when symmetry makes",
"choices_md5": "526f4a7a5a07a5b32ff3a9e7b164b083"
},
{
"version_id": "cb00852c-7a3d-409a-9ef3-4d8716c7edbf",
"content_key": "apphycem-mcq-015",
"from_md5": "13d69b7a15ea1568315a2f8db3e0a5e9",
"to_stem": "The differential magnetic force on a current element is",
"choices_md5": "713a866730b03873a83159e1ef77ca15"
},
{
"version_id": "a27c0b98-41a7-45a4-906c-785a810d239f",
"content_key": "apphycem-mcq-016",
"from_md5": "393f4ee9802159f000fb1b4f86fc07b7",
"to_stem": "Faraday's law in integral form states that the emf around a closed loop, the line integral of E around the loop, is equal to--",
"choices_md5": "31fdfd7374e5360be96132d4817e27f8"
},
{
"version_id": "ce80e748-3c79-42d0-aead-c1aec5bdd52a",
"content_key": "apphycem-mcq-017",
"from_md5": "d87788d24df418f65902331440f5c8f8",
"to_stem": "For an LR circuit connected to a DC source, current approaches steady state with time constant",
"choices_md5": "48b08fd285e4a15db8209137a60259a2"
},
{
"version_id": "9f841d49-4f7e-434f-8497-2f7e17361062",
"content_key": "apphycem-mcq-020",
"from_md5": "d7965d60e31e4d5c19954cb5bd719bfd",
"to_stem": "Induced electric fields from changing magnetic flux are",
"choices_md5": "38c6b85a5aabbe27777e29e6e9839778"
},
{
"version_id": "4e0dadc5-b0d6-45ec-a829-f565a271884e",
"content_key": "apphycem-mcq-031",
"from_md5": "2f6cfee087c71bb8514e6c63bcad6c8f",
"to_stem": "Total current through a surface is",
"choices_md5": "52b2097e5fe80e69f97f47df61e160f0"
},
{
"version_id": "ce5636a2-ac51-4d6a-bd7a-9525d7c25408",
"content_key": "apphycem-mcq-032",
"from_md5": "924bb61894a669e31cdfc3e95fd28b64",
"to_stem": "In a steady series circuit, current through each element is",
"choices_md5": "d0d3c9521dee65d4ba77cc5201566b06"
},
{
"version_id": "4ccd67cf-6aed-4fb7-851d-edbb005d51d7",
"content_key": "apphycem-mcq-033",
"from_md5": "ce975107d2f56a2c9bd8aea731bc8617",
"to_stem": "A wire's length doubles and radius doubles with resistivity unchanged. Its resistance becomes",
"choices_md5": "2e77823625cd78dfb159e3ef3c406e2f"
},
{
"version_id": "6fe06345-fde5-40eb-b532-04effab6cc25",
"content_key": "apphycem-mcq-035",
"from_md5": "ef25ebb3a80cea7db391699f931d4cc7",
"to_stem": "Kirchhoff's loop rule for a steady circuit follows from conservation of",
"choices_md5": "9b0ea3a64113295c4dfc905eb9f5a577"
},
{
"version_id": "cd96dd11-e6ad-428b-a95a-f20886b9b911",
"content_key": "apphycem-mcq-036",
"from_md5": "16bdade13e744fa67e9d506203bf0e0d",
"to_stem": "An uncharged capacitor connects through R to ideal emf ε. Immediately after closing, current is",
"choices_md5": "bdb0bbd4ba5fd7c64a3fd6be98f985ef"
},
{
"version_id": "e612ebec-2e6a-4b04-9c5c-5d7e7b711977",
"content_key": "apphycem-mcq-037",
"from_md5": "08bdf450a7a2ac2f96539b37d8a48a8e",
"to_stem": "Gauss's law for magnetism states",
"choices_md5": "e7e6212e7111c02872a30ecbc054d38e"
},
{
"version_id": "330a4588-b35a-4460-a7cb-65ee2ece4661",
"content_key": "apphycem-mcq-038",
"from_md5": "e1729751c595f0036389d0171532151d",
"to_stem": "A static magnetic field acting alone on a point charge does",
"choices_md5": "7abc4552ad352152b5b2cfdb94094a30"
},
{
"version_id": "f643b085-a308-44ca-9625-94eabea78655",
"content_key": "apphycem-mcq-039",
"from_md5": "70ea765af0522a0b4dfad1a163e4375d",
"to_stem": "For a long ideal solenoid with n turns per length, interior field is",
"choices_md5": "80face9547c99c9296649ff378382d76"
},
{
"version_id": "f0231b54-ad44-4cae-82d7-ff1cfe0b95e7",
"content_key": "apphycem-mcq-040",
"from_md5": "65d23c6868bc8b4a6cdf5e62b21c4ff3",
"to_stem": "Uniform B crosses a single loop of area A at angle θ to the area normal. Flux is",
"choices_md5": "cc4aed348db20fab0e2ec16218ebb3ab"
},
{
"version_id": "24bfd312-4fa1-47cf-aa88-77cacab03038",
"content_key": "apphycem-mcq-041",
"from_md5": "f295f0a7544794afb06f37de62c1ac74",
"to_stem": "A conducting plate entering a magnetic-field region experiences a force opposing motion because",
"choices_md5": "0cf1214adbc8007f3e54aee2a38f13b1"
},
{
"version_id": "a3e5e87b-0940-4284-98bc-5b4b0e8f3691",
"content_key": "apphycem-mcq-042",
"from_md5": "8dad23b21d9626b00721f5d5295d5214",
"to_stem": "Energy stored in an ideal inductor carrying current I is",
"choices_md5": "13726414939b172b15b7eabb3b2f5735"
},
{
"version_id": "ad958df1-1534-4cb0-970c-df8e9328985c",
"content_key": "apphycm-mcq-005",
"from_md5": "d3e1f6aeda2ae734f4eeeac40230f906",
"to_stem": "A particle under F=-kx satisfies",
"choices_md5": "e1216161ce420bf20516f7ab32268820"
},
{
"version_id": "80dda346-3421-4f59-95fc-e7f973e1e15c",
"content_key": "apphycm-mcq-009",
"from_md5": "eeb0975b0b04af43204ba90a08f64dc1",
"to_stem": "For variable force F(t), impulse from 0 to T is",
"choices_md5": "97c4cfc2f729f7428dead8d1d2e2efe6"
},
{
"version_id": "06cab4fb-979c-4ec6-ae24-3e384ef8097a",
"content_key": "apphycm-mcq-010",
"from_md5": "f6c6c1a11f46cc28161f1489dd8eaef1",
"to_stem": "A rocket's changing-mass motion is analyzed by applying momentum conservation to",
"choices_md5": "16ccb05ebb61076f82886e1eec574503"
},
{
"version_id": "7bbc529a-7234-40c3-a573-179ab58d6a13",
"content_key": "apphycm-mcq-011",
"from_md5": "89c63f018d5ca0aa80b7f7a658753587",
"to_stem": "For angular position θ(t), angular acceleration is",
"choices_md5": "582db9211e98474a61daf7e36f8ba543"
},
{
"version_id": "6deeda4a-51fc-4932-a515-dc302ff2e27a",
"content_key": "apphycm-mcq-012",
"from_md5": "0afc33cfa3fba403c949ca05c596b6c6",
"to_stem": "Torque from potential energy U(θ), for a system whose potential energy depends only on the angle θ, is",
"choices_md5": "b6ecc0238f6b98c941f0dda09b05cf85"
},
{
"version_id": "928a5a7e-6957-4b74-9802-281e9ce3e96c",
"content_key": "apphycm-mcq-013",
"from_md5": "72761e31c786ae533f9ac74ffd0c3979",
"to_stem": "For a continuous body, moment of inertia about a chosen rotation axis is (r is the perpendicular distance of each mass element from that axis)",
"choices_md5": "1e9c09fd223cdcfaf2c635b7497b3309"
},
{
"version_id": "2a806254-1a78-4af8-b4dd-689a497ef50e",
"content_key": "apphycm-mcq-014",
"from_md5": "6089374ac56e09283dfc31eb51007570",
"to_stem": "A system experiences zero net external torque. Which of the following is true of dL/dt?",
"choices_md5": "4bae70ca8a11ed9979dc9a6e51523a8d"
},
{
"version_id": "f19dc852-061a-4060-ab50-f526132c9b24",
"content_key": "apphycm-mcq-015",
"from_md5": "93ea44c81b3198674e7edbaa67b9cfc5",
"to_stem": "The small-angle pendulum equation is",
"choices_md5": "f0a02f391aea19fce3bd368cbff5ce0d"
},
{
"version_id": "f0d61bed-eb70-4a59-a66d-b5a2c8f0c654",
"content_key": "apphycm-mcq-016",
"from_md5": "e91468e1744c0314d2c40c1d15cba409",
"to_stem": "The period for x''+ω²x=0 is",
"choices_md5": "d914ee7f2b0343195f5419dce39bcd74"
},
{
"version_id": "b7f33d69-7a41-42ba-9455-eb46472604f3",
"content_key": "apphycm-mcq-019",
"from_md5": "39bfa1446adc286eb8838182c3a0c7d2",
"to_stem": "For τ(t)=τ₀t acting on constant I, change in angular speed from 0 to T is",
"choices_md5": "904b819910e0d42032d372c0735a9f3d"
},
{
"version_id": "f415f38a-4f86-4254-92a2-51b3687c44d5",
"content_key": "apphycm-mcq-020",
"from_md5": "364ea7c84bcb7ee551ae4256eb93752d",
"to_stem": "For a physical pendulum undergoing small-angle oscillation, omega^2 equals which of the following, where d is the distance from the pivot to the center of mass and I is the moment of inertia about the pivot?",
"choices_md5": "d85fe20fd96141ab854796a03218bebf"
},
{
"version_id": "5e75e2b8-cfe6-4f8d-bec9-324d66ccd696",
"content_key": "apphycm-mcq-032",
"from_md5": "3626ad56ffb390103fe0c7bf6135618e",
"to_stem": "A force F₀e^{-t/τ} acts from t=0 to infinity. Its impulse is",
"choices_md5": "83b30ef5a4fc1ba7cb1f5ac76446be63"
},
{
"version_id": "ba498b18-fcc5-4323-977c-89cd83878f89",
"content_key": "apphycm-mcq-033",
"from_md5": "e767759a382b888b2c046f16a47e93e6",
"to_stem": "For a system of total mass M, total momentum is",
"choices_md5": "236f9b92793df9715723e3ee00be1f6c"
},
{
"version_id": "ba6e8551-c83d-4c81-8844-09674b2f42cc",
"content_key": "apphycm-mcq-034",
"from_md5": "746a970c821cbf46414cad0a852c032e",
"to_stem": "In an isolated perfectly inelastic collision,",
"choices_md5": "13fbb24e1d602d36c783ddf654724e07"
},
{
"version_id": "c352aa57-dd96-4b56-9dc1-7a95b80e8da2",
"content_key": "apphycm-mcq-035",
"from_md5": "fe5847679ba0e6dd5f2219c34f94c74b",
"to_stem": "Torque about an origin is",
"choices_md5": "4bafcb964b8bd35f09391a14e1062fb3"
},
{
"version_id": "fe698e65-d37b-4194-81c2-75504cba2deb",
"content_key": "apphycm-mcq-036",
"from_md5": "19539bc4b90b445cff642d3b6705ec40",
"to_stem": "For constant rotational inertia I, net torque is",
"choices_md5": "f20421ed9a0b2d9cdc0d1544d981e65f"
},
{
"version_id": "c1f19405-a9cd-45f3-b9d9-55a57b86b180",
"content_key": "apphycm-mcq-037",
"from_md5": "513216ecdd76ec34676ea5b25874cf1f",
"to_stem": "A rigid body rotating at angular speed ω has kinetic energy",
"choices_md5": "bacb1011d0d5e21db942aabf3fba4200"
},
{
"version_id": "6de62c61-d226-478b-88f6-fed67a05f2a8",
"content_key": "apphycm-mcq-038",
"from_md5": "47ebe7b2274014657b56c820dad3949c",
"to_stem": "Angular impulse over a time interval equals",
"choices_md5": "4588f99e54504e8d5cabab5f397ff5ac"
},
{
"version_id": "0284f245-d4ce-4c8d-95bf-3022d1cac73d",
"content_key": "apphycm-mcq-039",
"from_md5": "293c598ff3b66bdcc68a12cb8b3ae51a",
"to_stem": "For rolling without slipping, center-of-mass speed is",
"choices_md5": "524a4f35df281669d9238cfae7593011"
},
{
"version_id": "a6ce6f27-2a89-4fdb-bd4f-e462b7c09f73",
"content_key": "apphycm-mcq-040",
"from_md5": "8b3ed3698b5884aa6234a3b3e0c2157b",
"to_stem": "For circular orbits about the same mass, doubling radius multiplies period by",
"choices_md5": "0a2aaf9890014a1ddf7546848ae60584"
},
{
"version_id": "b8e9a3af-7e78-4715-8dab-7b2342d3421f",
"content_key": "apphycm-mcq-041",
"from_md5": "41304b2b39451ea03ca8a3239355397e",
"to_stem": "For m x''+kx=0, angular frequency is",
"choices_md5": "22bfb88bc3961653501aa447d39b5d9c"
},
{
"version_id": "73234415-efbc-48f4-9d1c-acad9e98b7e1",
"content_key": "apphycm-mcq-042",
"from_md5": "fad79f1474221b221c25cdc458b2a8e9",
"to_stem": "For amplitude A in ideal SHM with spring constant k, total energy is",
"choices_md5": "402b26d08b3416b059922e178ed80c18"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 191 then raise exception '%: expected 191 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
