-- Stem/choice cleanup 2026-10-06 -- PRODUCTION APPLY chunk 02/8 (25 of 191 clean_match rows)
-- Approval: APPROVAL-0127 (David Bloom, Product Owner). Generated by gen_chunks.py via gen_sql.body(); same guards,
-- idempotence and label carry-forward as prod_apply.sql; target count / postconditions are per chunk.
do $apply$
declare
  v_approval constant text := 'APPROVAL-0127';
  v_run      constant text := 'stem-choice-cleanup-2026-10-06';
  -- target rows: version_id, content_key, md5 of the stem we expect to find, the stem to write, md5 of the choices
  v_targets  constant jsonb := $tj$[
{
"version_id": "05bc02e0-3ca9-45f2-9643-e69eddd4161b",
"content_key": "apcalcab-mcq-np2-002",
"from_md5": "c3406a3037b3e8a59f4b038f1c2f9806",
"to_stem": "Which of the following limits is an indeterminate form (0/0 or infinity/infinity) to which L'Hospital's Rule may be applied directly?",
"choices_md5": "6d25e86a57b149f082b283593f421eac"
},
{
"version_id": "8801905c-357a-43b7-81b5-0f388c6685bf",
"content_key": "apcalcbc-mcq-021",
"from_md5": "e2f10f527c139cd27c297224d40c929f",
"to_stem": "What is lim(x→0) (e^(3x)−1)/x?",
"choices_md5": "3fcf12b7c380c859d23fc18d2fd7c2e2"
},
{
"version_id": "c8e50471-1357-4455-9e5b-b3365a2eed42",
"content_key": "apcalcbc-mcq-022",
"from_md5": "ee19aeaf88e1c689f693e18ea7a289aa",
"to_stem": "What is lim(x→0) ln(1+2x)/sin(3x)?",
"choices_md5": "c1e848a1f0cf9aa098b89032f1f1e2a4"
},
{
"version_id": "a548a41e-aa7b-462f-8969-fac4def77fd7",
"content_key": "apcalcbc-mcq-023",
"from_md5": "e08fbb8685057d7f3f7afa3c67b2cf4b",
"to_stem": "If f(x)=x²ln x for x>0, what is f′(1)?",
"choices_md5": "94fa43a401b842b9ed1e1fe812ab749d"
},
{
"version_id": "22757b29-3af8-40f1-8f88-4d07e2ab1b0c",
"content_key": "apcalcbc-mcq-024",
"from_md5": "0f4e1e6351d3ad32e626ffc24ddd7290",
"to_stem": "Which limit equals f″(2), provided the second derivative exists?",
"choices_md5": "d26fc51a3beec83add9196c7ec6cae30"
},
{
"version_id": "fe829169-4d22-44ab-aafa-213cf63cee84",
"content_key": "apcalcbc-mcq-025",
"from_md5": "9201ee1b2007a369c32ac9d51f321161",
"to_stem": "What is d/dx[arctan(x²)]?",
"choices_md5": "b48bfcb16a49fc44b6fe7511e6961174"
},
{
"version_id": "435c0bbd-475e-41dd-bc25-ee04f09f4754",
"content_key": "apcalcbc-mcq-026",
"from_md5": "c0b49cce16088213ed03970c2f528985",
"to_stem": "Let g=f⁻¹. If f(2)=5 and f′(2)=−3, what is g′(5)?",
"choices_md5": "e2db659ae79ed9c9c2792a37a824d651"
},
{
"version_id": "fa8b34e0-f9a9-4ebd-a3d2-7a1a077f2034",
"content_key": "apcalcbc-mcq-027",
"from_md5": "8e563ce8186bd883698322283e1cf3c0",
"to_stem": "The radius of a sphere is increasing at 0.2 centimeter per second. How fast is its volume increasing when the radius is 3 centimeters?",
"choices_md5": "54d2fd57c1028af93e79f4a9d39e39da"
},
{
"version_id": "b79f95c1-f44e-4bb9-b280-7d3c4ae2a28b",
"content_key": "apcalcbc-mcq-028",
"from_md5": "0930e2c70df5a379c8bf1eb71bb64a19",
"to_stem": "A particle has velocity v(t)=t sin(t²)−0.4. What is its acceleration at t=1.3, to the nearest thousandth?",
"choices_md5": "64a1a7630c8f4fcdaa85f9eb88008ea0"
},
{
"version_id": "bed2766f-8714-419d-9aaf-d32bb3f69c2e",
"content_key": "apcalcbc-mcq-029",
"from_md5": "0156e54ef6a9dc164af2fda4cb674ed3",
"to_stem": "If f′(x)=(x−1)(x+2), on which intervals is f increasing?",
"choices_md5": "f2c42fdedb947cf1160fcecf62acbb2e"
},
{
"version_id": "b601f7db-92e4-4dd6-9b0d-e2864d426b0f",
"content_key": "apcalcbc-mcq-030",
"from_md5": "986a78beb09e3d788573757000103144",
"to_stem": "For f(x)=e^x on [0,1], which value of c is guaranteed by the Mean Value Theorem?",
"choices_md5": "b5b8f97610afaf987a376c0e9831a5e1"
},
{
"version_id": "4a47d6f6-0bd0-4ec2-add9-40d40d51b568",
"content_key": "apcalcbc-mcq-031",
"from_md5": "8c0d9703cce2342f3740b73c00b9cedb",
"to_stem": "A differentiable function has f′(x)=x⁴−4x²+0.5 on −2≤x≤2. At which x-values does f have local maxima, to the nearest thousandth?",
"choices_md5": "900f779d7627c56843c77cab8e63aaf6"
},
{
"version_id": "c7d521ad-bc8a-404c-abd9-0e68350e7afd",
"content_key": "apcalcbc-mcq-032",
"from_md5": "0cb90ebeda42f3b5986b75040e1b58d3",
"to_stem": "If f′(x)=x²(x−1)³(x+2)², which statement is true?",
"choices_md5": "c167cdf5b35579aba49412ad735f6d12"
},
{
"version_id": "1c459529-8016-44ad-be36-dbccc2e0e7fd",
"content_key": "apcalcbc-mcq-033",
"from_md5": "c5f80854a2dff08296934c94f2a08c62",
"to_stem": "What is the value of the improper integral ∫₁^∞ 1/x² dx?",
"choices_md5": "6cb3c0e8ebca430f7fb8801d37dd3542"
},
{
"version_id": "058cb9f7-37f0-4e0d-af06-97ffa239af39",
"content_key": "apcalcbc-mcq-034",
"from_md5": "79da518ae5b949ae73372f7abaa91fb7",
"to_stem": "Which is an antiderivative of xe^x?",
"choices_md5": "f3672008d6385aa936d7da7e2c626632"
},
{
"version_id": "de0da11c-94be-4ca2-a3e5-edf6836db953",
"content_key": "apcalcbc-mcq-035",
"from_md5": "e29d10e4fa0a92d7ba869aa719058876",
"to_stem": "What is ∫1/(x²−1) dx on an interval not containing ±1?",
"choices_md5": "6af3059ae0b36a8560b5c757cae0b1ef"
},
{
"version_id": "54c79401-bf15-4533-97d2-1a634ed5ce69",
"content_key": "apcalcbc-mcq-036",
"from_md5": "43e702332abd0481035c656f177cc83c",
"to_stem": "Let G(x)=∫₀^(x²) cos(t³)dt. What is G′(1.2), to the nearest thousandth?",
"choices_md5": "7cf2d0bcb2edfa1b1ffcb99e508efcf8"
},
{
"version_id": "f54f258c-060d-4419-b6fc-8382a1b4634b",
"content_key": "apcalcbc-mcq-037",
"from_md5": "922248f7f47af939e42de2329e5e07ed",
"to_stem": "What is ∫₁^∞ (ln x)/x² dx?",
"choices_md5": "8180d2d50d4aa87e1b3689358697db57"
},
{
"version_id": "4b886041-044f-4c7a-9907-69d97a19b67f",
"content_key": "apcalcbc-mcq-038",
"from_md5": "0ed1421c219286c2012ba960b87f6473",
"to_stem": "Use Euler's method with step size 0.25 to estimate y(0.5) for y′=x²−y and y(0)=1.",
"choices_md5": "96bbb87acc3da9d2888ad30c5fed1249"
},
{
"version_id": "7ffa3a3c-5e6e-4c35-bdc7-bd6ca6d8e1ff",
"content_key": "apcalcbc-mcq-039",
"from_md5": "6a89a67533fbfe4860b3400a096c12d3",
"to_stem": "A population satisfies dP/dt=0.4P(1−P/1200) and P(0)=300. When does P reach 600, to the nearest thousandth?",
"choices_md5": "946342125b9de25407f3e1a6c7355113"
},
{
"version_id": "7e90cc29-6b7b-442f-9742-7b099d3745da",
"content_key": "apcalcbc-mcq-040",
"from_md5": "c9a0ed490442a4c04c51723ed4ddea70",
"to_stem": "What is the area between y=√x and y=x on 0≤x≤1?",
"choices_md5": "22c826b14fa54afd754ec5682e04779a"
},
{
"version_id": "2bcaf641-2acb-418e-93a5-c1fa9ee02d83",
"content_key": "apcalcbc-mcq-041",
"from_md5": "5ca7729fa1020e46bcad763d5a9f8f75",
"to_stem": "The base of a solid is 0≤x≤1.5 and 0≤y≤e^(−x²). Cross sections perpendicular to the x-axis are semicircles whose diameters lie in the base. What is the volume, to the nearest thousandth?",
"choices_md5": "a7fe63a26a844ab856d727e960cd1152"
},
{
"version_id": "7fd6e86b-00c8-4167-9cf3-2e9d94c5a0ae",
"content_key": "apcalcbc-mcq-042",
"from_md5": "c32d6a80ca46ed2865c40cfd64ec224b",
"to_stem": "A curve is given by x=t²+1 and y=t³−3t. What is dy/dx at t=1?",
"choices_md5": "0ec745da47ca59dd83113a6035bbbf98"
},
{
"version_id": "7945bd22-d0a1-4bba-8420-f193751a8118",
"content_key": "apcalcbc-mcq-043",
"from_md5": "6685a6e8d40a2c7eb4e5e11b7e6ad0f2",
"to_stem": "A particle has position r(t)=⟨t²−2t,e^(−t)⟩. What is its speed at t=1.4, to the nearest thousandth?",
"choices_md5": "064f3b54b27e78e4bd1c201ebcdb2507"
},
{
"version_id": "519b75bf-b623-404e-9ad7-da11290053dd",
"content_key": "apcalcbc-mcq-044",
"from_md5": "b40478991002e4b7418939fad51c40ff",
"to_stem": "What is the area of one petal of the polar curve r=2sin(3θ)?",
"choices_md5": "cf2320ba6d8dfd8729d4972a55c3e572"
}
]$tj$::jsonb;
  v_live jsonb; v_prior jsonb;
  n_target int; n_live int; n_upd int; n_lbl int; n_bad int;
begin
  if v_approval is null or v_approval = 'PENDING' then
    raise exception 'stem-choice-cleanup-2026-10-06: label carry-forward needs a Product Owner approval reference (set v_approval)';
  end if;
  perform pg_advisory_xact_lock(hashtext('cramapple-' || v_run));
  n_target := jsonb_array_length(v_targets);
  if n_target <> 25 then raise exception '%: expected 25 target rows, got %', v_run, n_target; end if;

  -- idempotence: only rows whose stem is still byte-identical to the expected one, still the current published
  -- MCQ version, with choices unchanged since the snapshot
  select coalesce(jsonb_agg(jsonb_build_object('version_id', t.version_id, 'from_md5', t.from_md5, 'to_stem', t.to_stem,
           'choices_md5', t.choices_md5, 'content_item_id', civ.content_item_id,
           'old_taxo_hash', app.taxonomy_relevant_hash(civ.id))), '[]'::jsonb)
    into v_live
  from jsonb_to_recordset(v_targets) as t(version_id uuid, content_key text, from_md5 text, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = t.version_id
  join app.content_items ci on ci.id = civ.content_item_id and ci.content_key = t.content_key
  where md5(civ.stem) = t.from_md5
    and civ.status = 'published' and ci.item_type = 'mcq'
    and not exists (select 1 from app.content_item_versions later
                    where later.content_item_id = civ.content_item_id and later.version_num > civ.version_num)
    and (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) = t.choices_md5;
  n_live := jsonb_array_length(v_live);
  raise notice '%: % of % target rows still match and will be updated', v_run, n_live, n_target;
  if n_live = 0 then
    return;  -- already applied (or every row drifted): nothing to do
  end if;

  -- capture every current label the stale trigger can touch (validated / provisional_model), BEFORE the write:
  -- the derive trigger nulls validated_by/at/decision when the status flips to stale. 'held' labels are not touched
  -- by the trigger but carry the same hash; re-point them too so a later hold release is not blocked by this edit.
  select coalesce(jsonb_agg(jsonb_build_object('content_taxonomy_label_id', l.content_taxonomy_label_id,
           'version_id', lv.version_id, 'label_status', l.label_status, 'validated_by', l.validated_by,
           'validated_at', l.validated_at, 'validation_decision_id', l.validation_decision_id,
           'validated_against_version_id', l.validated_against_version_id,
           'was_fresh', (l.validated_against_taxo_hash is not distinct from lv.old_taxo_hash))), '[]'::jsonb)
    into v_prior
  from jsonb_to_recordset(v_live) as lv(version_id uuid, content_item_id uuid, old_taxo_hash text)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status in ('validated', 'provisional_model', 'held');

  update app.content_item_versions civ
  set stem = lv.to_stem
  from jsonb_to_recordset(v_live) as lv(version_id uuid, from_md5 text, to_stem text)
  where civ.id = lv.version_id and md5(civ.stem) = lv.from_md5;
  get diagnostics n_upd = row_count;
  if n_upd <> n_live then raise exception '%: updated % rows, expected %', v_run, n_upd, n_live; end if;

  -- carry labels forward: restore the exact prior status/validation; re-point the hash only where it was fresh
  update app.content_taxonomy_labels l
  set label_status = p.label_status,
      validated_by = p.validated_by,
      validated_at = p.validated_at,
      validation_decision_id = p.validation_decision_id,
      validated_against_version_id = p.validated_against_version_id,
      validated_against_taxo_hash = case when p.was_fresh then app.taxonomy_relevant_hash(p.version_id)
                                         else l.validated_against_taxo_hash end,
      source_payload = l.source_payload || jsonb_build_object('carried_forward_' || replace(v_run, '-', '_'), jsonb_build_object(
        'version_id', p.version_id,
        'reason', 'stem/choice cleanup: duplicated inline answer-choice list removed from stem; question text, choices, units and topics unchanged; no relabelling',
        'approval_ref', v_approval, 'run', v_run))
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text,
       validated_by uuid, validated_at timestamptz, validation_decision_id uuid, validated_against_version_id uuid, was_fresh boolean)
  where l.content_taxonomy_label_id = p.content_taxonomy_label_id;
  get diagnostics n_lbl = row_count;

  -- postconditions
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(version_id uuid, to_stem text, choices_md5 text)
  join app.content_item_versions civ on civ.id = lv.version_id
  where civ.stem is distinct from lv.to_stem or civ.status <> 'published'
     or cardinality(app.mcq_stem_choice_desync(civ.id, civ.stem)) > 0
     or (select md5(string_agg(mc.choice_key || '|' || mc.choice_text || '|' || mc.is_correct::text, chr(10) order by mc.choice_key))
         from app.mcq_choices mc where mc.content_item_version_id = civ.id) is distinct from lv.choices_md5;
  if n_bad > 0 then raise exception '%: % rows fail stem/status/choices/desync postconditions', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_prior) as p(content_taxonomy_label_id uuid, version_id uuid, label_status text, was_fresh boolean)
  join app.content_taxonomy_labels l on l.content_taxonomy_label_id = p.content_taxonomy_label_id
  where l.label_status <> p.label_status
     or (p.was_fresh and l.validated_against_taxo_hash is distinct from app.taxonomy_relevant_hash(p.version_id));
  if n_bad > 0 then raise exception '%: % labels not carried forward', v_run, n_bad; end if;
  select count(*) into n_bad
  from jsonb_to_recordset(v_live) as lv(content_item_id uuid)
  join app.content_taxonomy_labels l on l.content_item_id = lv.content_item_id
  where l.superseded_by is null and l.label_status = 'stale';
  if n_bad > 0 then raise exception '%: % target labels left stale', v_run, n_bad; end if;

  raise notice '%: stems updated %, labels carried forward %', v_run, n_upd, n_lbl;
end
$apply$;
