import json
V=[]
def add(id,seed,diff,title,stem,key,wrongs,note,check):
    V.append({"id":id,"seed":seed,"difficulty":diff,"title":title,"stem":stem,
      "correct":{"text":key[0],"rationale":key[1]},
      "wrong":[{"text":t,"rationale":r,"error_pattern":e} for t,r,e in wrongs],
      "change_note":note,"check":check})
CALC="Calculator use is permitted.\n\n"
# ---------- 049 (3.14)
add("apprecalc-mcq-049-v1","apprecalc-mcq-049","medium","Identify a sine cardioid",
 CALC+"For r = 3 − 3sinθ, which statement best describes the graph?",
 ("A cardioid symmetric about the line θ = π/2, with a cusp at the pole and its farthest point at (6, 3π/2)",
  "Since the two coefficients have equal size (a = b = 3), r = 3 − 3sinθ is a cardioid. sin(π − θ) = sinθ, so the graph is symmetric about the line θ = π/2. r = 0 when sinθ = 1 (θ = π/2), giving the cusp at the pole, and r is largest at θ = 3π/2, where r = 3 − 3(−1) = 6."),
 [("A cardioid symmetric about the polar axis, with a cusp at the pole and its farthest point at (6, π)",
   "This is the graph of r = 3 − 3cosθ, where the cosine makes r = 6 at θ = π. For r = 3 − 3sinθ the value at θ = π is r = 3 − 3·0 = 3, not 6, and the graph is symmetric about θ = π/2, not the polar axis.",
   "Treats sine as cosine (symmetry axis and farthest point of the cosine cardioid)"),
  ("A cardioid symmetric about the line θ = π/2, with a cusp at the pole and its farthest point at (6, π/2)",
   "This is the graph of r = 3 + 3sinθ. For r = 3 − 3sinθ, at θ = π/2 the value is r = 3 − 3(1) = 0, which is the cusp itself, not a farthest point; the farthest point is at θ = 3π/2.",
   "Ignores the minus sign, so the cardioid points the wrong way"),
  ("A limaçon with an inner loop, symmetric about the line θ = π/2, whose outer loop reaches (6, 3π/2)",
   "An inner loop appears only when r takes negative values, which requires the sine coefficient to be larger in size than the constant. Here r = 3 − 3sinθ ≥ 0 for every θ (sinθ ≤ 1), and r = 0 only at θ = π/2, so the graph has a cusp at the pole and no inner loop.",
   "Thinks any limaçon-type equation that reaches r = 0 forms an inner loop")],
 "New cardioid with sine and a minus sign, described by symmetry line, cusp, and farthest point; distractors are cos/sin swap, sign error, and loop misconception.","conceptual")
add("apprecalc-mcq-049-v2","apprecalc-mcq-049","medium","Describe a three-petal rose",
 CALC+"Which statement best describes the graph of r = 5cos(3θ)?",
 ("A three-petal rose with petals of length 5, one of which is centered on the polar axis",
  "For r = a·cos(nθ) with n odd, the graph is a rose with n petals, so n = 3 gives three petals, each of length |a| = 5. At θ = 0, r = 5cos(0) = 5, so a petal tip lies on the polar axis (the other tips are at θ = 2π/3 and 4π/3, where r = 5cos(2π) = 5 and 5cos(4π) = 5)."),
 [("A six-petal rose with petals of length 5, one of which is centered on the polar axis",
   "Doubling the petal count applies to roses with an even n (for example r = 5cos(2θ) has four petals). With n = 3 odd, r = 5cos(3θ) has exactly 3 petals; the tips at θ = 0, 2π/3, 4π/3 all have r = 5, and a six-tip pattern never appears.",
   "Applies the even-n rule (2n petals) to an odd n"),
  ("A three-petal rose with petals of length 3, one of which is centered on the polar axis",
   "The petal length is the amplitude |a| = 5, not the coefficient 3 of θ. At θ = 0 the value is r = 5cos(0) = 5, so the petal reaches 5 units from the pole. The 3 only sets the number of petals.",
   "Swaps the roles of a and n"),
  ("A three-petal rose with petals of length 5, one of which is centered on the line θ = π/2",
   "That placement belongs to r = 5sin(3θ). For r = 5cos(3θ) at θ = π/2 we get r = 5cos(3π/2) = 0, so the graph passes through the pole there instead of having a petal tip; the tips are at θ = 0, 2π/3, and 4π/3.",
   "Confuses the cosine rose with the sine rose")],
 "Changes from cardioid to odd-n rose; asks petal count, length, and orientation.","conceptual")
add("apprecalc-mcq-049-v3","apprecalc-mcq-049","hard","Limaçon with an inner loop",
 CALC+"For r = 1 + 2cosθ, which statement best describes the graph?",
 ("A limaçon with an inner loop, symmetric about the polar axis, whose outer loop reaches (3, 0)",
  "The cosine makes the graph symmetric about the polar axis, and r(0) = 1 + 2 = 3 gives the outer point (3, 0). Because the coefficient of cosθ (2) is larger in size than the constant (1), r becomes negative when cosθ < −1/2 (for 2π/3 < θ < 4π/3), for example r(π) = 1 − 2 = −1, which creates an inner loop."),
 [("A cardioid with a cusp at the pole, symmetric about the polar axis, reaching (3, 0)",
   "A cardioid needs the constant and the cosine coefficient to be equal in size (as in r = 2 + 2cosθ). Here they are 1 and 2, and r(π) = 1 − 2 = −1 ≠ 0, so the graph does not simply touch the pole at θ = π; r passes through 0 at θ = 2π/3 and goes negative, forming a loop.",
   "Classifies every a + b·cosθ curve as a cardioid"),
  ("A limaçon with an inner loop, symmetric about the line θ = π/2, whose outer loop reaches (3, π/2)",
   "This is the sine version, r = 1 + 2sinθ. For r = 1 + 2cosθ, at θ = π/2 the value is r = 1 + 2·0 = 1, not 3, and the symmetry is about the polar axis because cos(−θ) = cosθ.",
   "Confuses cosine with sine (symmetry axis and farthest point)"),
  ("A limaçon with no inner loop, symmetric about the polar axis, reaching (3, 0)",
   "No inner loop occurs only when the constant is at least as large in size as the cosine coefficient. Here 1 < 2, and r(π) = 1 + 2cos π = −1 is negative; the negative r-values for 2π/3 < θ < 4π/3 trace the inner loop.",
   "Reverses the rule for when a limaçon has an inner loop")],
 "New limaçon with |a| < |b|; options contrast cardioid, sine version, and no-loop limaçon.","conceptual")
# ---------- np2-001 (1.6)
add("apprecalc-mcq-np2-001-v1","apprecalc-mcq-np2-001","easy","End behavior of an even-degree polynomial",
 "As x approaches negative infinity, what is the end behavior of h(x) = 4x^6 − 7x^3 + 2?",
 ("h(x) approaches positive infinity",
  "The leading term 4x^6 determines end behavior. The degree is even and the leading coefficient is positive, so h(x) approaches positive infinity at both ends. For example, h(−10) = 4,000,000 + 7,000 + 2 = 4,007,002."),
 [("h(x) approaches negative infinity",
   "This treats x^6 as negative when x is negative, as an odd power would be. An even power of a negative number is positive: (−10)^6 = 1,000,000, so h(−10) = 4,007,002, which is large and positive.",
   "Applies the odd-degree rule to an even-degree polynomial"),
  ("h(x) approaches 0",
   "This confuses the polynomial with a rational function whose denominator grows. A nonconstant polynomial is unbounded; h(−10) = 4,007,002 and h(−100) is even larger, so the values do not shrink toward 0.",
   "Confuses polynomial end behavior with a horizontal asymptote"),
  ("h(x) approaches 2",
   "This reads off the constant term as if it were a limiting value. The constant is dominated by 4x^6 for large |x|: h(−10) = 4,007,002, nowhere near 2.",
   "Reads the constant term as the end value")],
 "Even-degree, positive leading coefficient, x to negative infinity; distractors are sign, zero, and constant-term errors.","numeric")
add("apprecalc-mcq-np2-001-v2","apprecalc-mcq-np2-001","medium","End behavior from factored form",
 "The polynomial p is given by p(x) = −2x²(x − 3)(x + 1)(x + 4). Which statement describes the end behavior of p?",
 ("p(x) → +∞ as x → −∞, and p(x) → −∞ as x → +∞",
  "Multiplying the factors gives degree 2 + 1 + 1 + 1 = 5 and leading coefficient −2, so the leading term is −2x^5. An odd-degree polynomial with a negative leading coefficient rises to +∞ as x → −∞ and falls to −∞ as x → +∞. Check: p(−10) = −2·100·(−13)(−9)(−6) = 140,400 is positive, and p(10) = −2·100·7·11·14 = −215,600 is negative."),
 [("p(x) → −∞ as x → −∞, and p(x) → −∞ as x → +∞",
   "This counts the four factors, (x²), (x − 3), (x + 1), (x + 4), to get degree 4 (even) and so uses the −2 to send both ends to −∞. The x² factor contributes degree 2, so the degree is 5 and the ends go in opposite directions.",
   "Counts factors instead of adding multiplicities to get the degree"),
  ("p(x) → −∞ as x → −∞, and p(x) → +∞ as x → +∞",
   "This has the odd-degree shape of an upward-sloping cubic or quintic, which would be right for a positive leading coefficient. Here the leading coefficient is −2, so the ends are reversed: p is positive for large negative x and negative for large positive x.",
   "Ignores the negative leading coefficient"),
  ("p(x) → +∞ as x → −∞, and p(x) → +∞ as x → +∞",
   "This combines two slips: counting four factors (degree 4, even) and ignoring the −2. With the correct degree 5 and leading coefficient −2, the two ends go to opposite infinities.",
   "Counts factors as degree and ignores the sign of the leading coefficient")],
 "Factored form with a repeated factor; the student must add multiplicities and use the sign of the leading coefficient.","conceptual")
add("apprecalc-mcq-np2-001-v3","apprecalc-mcq-np2-001","medium","Dominant term is not the largest coefficient",
 "As x approaches positive infinity, what is the end behavior of f(x) = 100x^3 − 5x^4 + x^2?",
 ("f(x) approaches negative infinity",
  "The term of highest degree, −5x^4, dominates for large x, and its coefficient is negative, so f(x) approaches negative infinity. For example, f(100) = 100,000,000 − 500,000,000 + 10,000 = −399,990,000."),
 [("f(x) approaches positive infinity",
   "This chooses 100x^3 because it has the largest coefficient. Degree, not coefficient size, decides which term dominates. f(10) = 50,100 is still positive, but f(100) = −399,990,000, and the negative values grow without bound.",
   "Picks the dominant term by coefficient size rather than degree"),
  ("f(x) approaches 0",
   "This treats the function like a rational function with growing denominator. f(100) = −399,990,000, and the magnitude keeps growing for larger x, so the values do not approach 0.",
   "Confuses polynomial end behavior with a horizontal asymptote"),
  ("f(x) approaches −5",
   "This reports the leading coefficient as if it were the limiting value. The leading term −5x^4 grows without bound; f(100) = −399,990,000, not about −5.",
   "Reports the leading coefficient as the end value")],
 "Uses a larger coefficient on a lower-degree term to test degree vs. coefficient; x to positive infinity.","numeric")
# ---------- np2-002 (1.10)
add("apprecalc-mcq-np2-002-v1","apprecalc-mcq-np2-002","medium","Hole with its y-coordinate",
 "Let h(x) = (x² + x − 6)/(x² − 4). Which statement correctly describes the graph of h at x = 2 and at x = −2?",
 ("A hole at (2, 5/4) and a vertical asymptote at x = −2",
  "Factoring gives h(x) = (x + 3)(x − 2)/[(x − 2)(x + 2)]. The factor (x − 2) cancels, so there is a hole at x = 2 whose height is the value of the simplified function (x + 3)/(x + 2) at x = 2, which is 5/4. The factor (x + 2) stays in the denominator while the numerator (x + 3) is 1 at x = −2, so x = −2 is a vertical asymptote."),
 [("A hole at (2, 0) and a vertical asymptote at x = −2",
   "This uses the numerator x² + x − 6, which equals 0 at x = 2, as the height of the hole. The hole's height comes from the simplified function (x + 3)/(x + 2): at x = 2 it is 5/4, not 0.",
   "Uses the original numerator's value instead of the simplified function's value"),
  ("Vertical asymptotes at both x = 2 and x = −2, and no hole",
   "This sets the denominator equal to zero without factoring the numerator. The numerator also has the factor (x − 2), which cancels, so x = 2 is a hole, not an asymptote.",
   "Does not check the numerator for common factors"),
  ("A hole at (2, 1/4) and a vertical asymptote at x = −2",
   "The location of the hole is right, but its height drops the remaining numerator factor: after canceling, the function is (x + 3)/(x + 2), so the height is (2 + 3)/(2 + 2) = 5/4. Using only 1/(2 + 2) = 1/4 leaves out (x + 3).",
   "Drops the remaining numerator factor when finding the hole's height")],
 "Rational function given in expanded form; hole must be located with its y-coordinate.","numeric")
add("apprecalc-mcq-np2-002-v2","apprecalc-mcq-np2-002","medium","Two holes and one asymptote",
 "Let f(x) = (x − 1)(x + 2)(x − 5) / [(x + 2)(x − 5)(x − 3)]. Which statement is true about the graph of f?",
 ("Holes at x = −2 and x = 5, and a vertical asymptote at x = 3",
  "The factors (x + 2) and (x − 5) appear in both the numerator and denominator and cancel, giving holes at x = −2 and x = 5. After canceling, f(x) = (x − 1)/(x − 3). The factor (x − 3) remains in the denominator, and the numerator is 3 − 1 = 2 ≠ 0 at x = 3, so x = 3 is a vertical asymptote."),
 [("A hole at x = 3, and vertical asymptotes at x = −2 and x = 5",
   "This reverses the roles. The cancelled factors (x + 2) and (x − 5) produce holes, and the factor (x − 3) that does not cancel produces the vertical asymptote.",
   "Swaps which zeros of the denominator are holes and which are asymptotes"),
  ("Vertical asymptotes at x = −2, x = 3, and x = 5, and no holes",
   "This treats every zero of the denominator as an asymptote without canceling the shared factors (x + 2) and (x − 5) with the numerator.",
   "Does not cancel common factors"),
  ("Holes at x = −2, x = 3, and x = 5, and no vertical asymptotes",
   "This treats every zero of the denominator as a hole. Only the factors that cancel give holes; (x − 3) is not in the numerator, so it remains in the simplified denominator (x − 1)/(x − 3) and gives a vertical asymptote.",
   "Treats every denominator zero as a hole")],
 "Factored form with two cancelling factors and one remaining; no calculation, just classification.","conceptual")
add("apprecalc-mcq-np2-002-v3","apprecalc-mcq-np2-002","hard","Partial cancellation of a squared factor",
 "Let p(x) = (x + 1) / [(x + 1)²(x − 2)]. Which statement correctly describes the graph of p at x = −1 and at x = 2?",
 ("Vertical asymptotes at both x = −1 and x = 2, and no hole",
  "For x ≠ −1, canceling one factor of (x + 1) gives p(x) = 1/[(x + 1)(x − 2)]. The simplified denominator is still 0 at x = −1 and at x = 2, and the numerator is 1, so both are vertical asymptotes. There is no hole because a hole requires the factor to cancel completely."),
 [("A hole at x = −1 and a vertical asymptote at x = 2",
   "This assumes that canceling any common factor creates a hole. Only one of the two factors of (x + 1) in the denominator cancels; the remaining (x + 1) keeps the denominator zero at x = −1 in 1/[(x + 1)(x − 2)], so it is an asymptote.",
   "Assumes any cancellation produces a hole"),
  ("A vertical asymptote at x = 2 only, with no hole or asymptote at x = −1",
   "This removes the entire (x + 1)² as if it cancelled with the single (x + 1) in the numerator. Only one factor cancels, leaving 1/[(x + 1)(x − 2)], which is undefined with a vertical asymptote at x = −1.",
   "Cancels the whole squared factor"),
  ("A hole at x = 2 and a vertical asymptote at x = −1",
   "This swaps the roles. The factor (x − 2) appears only in the denominator and does not cancel with anything, so x = 2 is a vertical asymptote, not a hole.",
   "Swaps the roles of the two values")],
 "Tests multiplicity: a squared factor only partly cancels, so the 'hole' is actually an asymptote.","conceptual")
# ---------- np2-005 (2.13)
add("apprecalc-mcq-np2-005-v1","apprecalc-mcq-np2-005","hard","Hidden quadratic with a rejected root",
 "What is the solution set of e^(2x) − 5e^x − 14 = 0?",
 ("x = ln 7 only",
  "Let u = e^x. Then u² − 5u − 14 = (u − 7)(u + 2) = 0, so u = 7 or u = −2. Since e^x > 0 for all x, u = −2 is rejected, leaving e^x = 7 and x = ln 7."),
 [("x = 7 and x = −2",
   "These are the values of u = e^x, not of x. Converting back requires e^x = 7, which gives x = ln 7; e^x = −2 has no real solution.",
   "Stops at the values of u and does not convert back to x"),
  ("x = ln 7 and x = ln(−2)",
   "The natural logarithm of a negative number is not defined, so e^x = −2 gives no real x. This answer keeps u = −2 without rejecting it, although e^x is always positive.",
   "Does not reject the negative root of the quadratic in e^x"),
  ("No real solution",
   "This rejects the whole equation because one root is negative. The root u = 7 is positive, so e^x = 7 is solvable and x = ln 7 satisfies the equation: e^(2 ln 7) − 5·7 − 14 = 49 − 35 − 14 = 0.",
   "Concludes there is no solution after discarding one root")],
 "New coefficients so one root is negative; targets the documented failure of not rejecting e^x = negative.","numeric")
add("apprecalc-mcq-np2-005-v2","apprecalc-mcq-np2-005","medium","Quadratic form in 3^x",
 "What is the solution set of 9^x − 4·3^x + 3 = 0?",
 ("x = 0 and x = 1",
  "Since 9^x = (3^x)², let u = 3^x. Then u² − 4u + 3 = (u − 1)(u − 3) = 0, so u = 1 or u = 3. Then 3^x = 1 gives x = 0 and 3^x = 3 gives x = 1."),
 [("x = 1 and x = 3",
   "These are the values of u = 3^x. Converting back, 3^x = 1 gives x = 0 and 3^x = 3 gives x = 1, so x = 3 would give 3^3 = 27, which is not a root (9^3 − 4·27 + 3 = 729 − 108 + 3 ≠ 0).",
   "Reports the values of u as the solutions for x"),
  ("x = 0 and x = ln 3",
   "This solves 3^x = 3 with the natural log as if the base were e, giving ln 3 ≈ 1.099. Because the base is 3, 3^x = 3 gives x = 1; indeed 3^(ln 3) ≈ 3.34, not 3.",
   "Converts back with ln u instead of log base 3"),
  ("x = 1 only",
   "This keeps only u = 3 and discards u = 1. But u = 1 is a valid root: 3^x = 1 gives x = 0, and 9^0 − 4·3^0 + 3 = 1 − 4 + 3 = 0.",
   "Drops the root u = 1")],
 "Base-3 version of the hidden-quadratic equation, with both roots valid; adds the base-3 vs ln conversion error.","numeric")
add("apprecalc-mcq-np2-005-v3","apprecalc-mcq-np2-005","hard","Equation with e^(−x) term",
 "What is the solution set of e^x + 12e^(−x) = 7?",
 ("x = ln 3 and x = ln 4",
  "Multiplying every term by e^x gives e^(2x) + 12 = 7e^x, so e^(2x) − 7e^x + 12 = 0. With u = e^x: u² − 7u + 12 = (u − 3)(u − 4) = 0, so u = 3 or u = 4, which gives x = ln 3 or x = ln 4."),
 [("x = 3 and x = 4",
   "These are the values of u = e^x. Converting back requires x = ln u, so the solutions are ln 3 and ln 4; for example e^3 + 12e^(−3) ≈ 20.7, not 7.",
   "Reports u instead of x"),
  ("x = −ln 3 and x = −ln 4",
   "With u = e^(−x) the equation becomes 1/u + 12u = 7, so 12u² − 7u + 1 = 0 and u = 1/3 or 1/4. Since e^(−x) = u, x = −ln u, giving ln 3 and ln 4; writing x = ln u instead gives ln(1/3) = −ln 3 and ln(1/4) = −ln 4, which are the wrong signs.",
   "Sign error when solving for x from e^(−x)"),
  ("No real solution",
   "This comes from multiplying only the left side by e^x, giving e^(2x) + 12 = 7 and e^(2x) = −5. The right side must be multiplied too: 7e^x. The correct equation e^(2x) − 7e^x + 12 = 0 has two positive roots for e^x.",
   "Multiplies only one side of the equation by e^x")],
 "Negative exponent term must first be cleared; distractors are u-values, reciprocal sign error, and one-sided multiplication.","numeric")
# ---------- np2-006 (3.5)
add("apprecalc-mcq-np2-006-v1","apprecalc-mcq-np2-006","medium","Parameter b from cycles per time",
 "A sinusoidal function used to model a pendulum completes 9 full cycles every 6 seconds. What is the value of b in the general form y = a·sin(b(x + c)) + d, where x is in seconds?",
 ("3π",
  "One cycle takes 6/9 = 2/3 second, so the period is 2/3. Then b = 2π/period = 2π ÷ (2/3) = 3π."),
 [("π/3",
   "This uses the whole 6 seconds as the period: b = 2π/6 = π/3. The 6 seconds contain 9 cycles, so the period is 6/9 = 2/3, and b = 2π ÷ (2/3) = 3π.",
   "Uses the total time as one period"),
  ("3/2",
   "This is the frequency, 9 cycles ÷ 6 seconds = 3/2 cycles per second, used directly as b. b is the number of radians per unit, so the frequency must be multiplied by 2π: b = 2π·(3/2) = 3π.",
   "Uses frequency as b without the factor of 2π"),
  ("2/3",
   "This is the period, 6/9 = 2/3 second, used directly as b. The period and b are related by b = 2π/period, so b = 2π ÷ (2/3) = 3π.",
   "Uses the period as b")],
 "Different context and numbers (9 cycles per 6 seconds); distractors separate total-time, frequency, and period errors.","numeric")
add("apprecalc-mcq-np2-006-v2","apprecalc-mcq-np2-006","medium","Parameter b from a frequency in Hz",
 "A sound wave with a frequency of 250 Hz (250 cycles per second) is modeled by y = a·sin(b(t + c)) + d, where t is in seconds. What is the value of b?",
 ("500π",
  "A frequency of 250 cycles per second means the period is 1/250 second. Then b = 2π/period = 2π·250 = 500π."),
 [("250",
   "This uses the frequency directly as b. Each cycle spans 2π radians of the argument, so b = 2π·250 = 500π, not 250.",
   "Uses frequency as b without the factor of 2π"),
  ("π/125",
   "This treats 250 as if it were the period in seconds: b = 2π/250 = π/125. But 250 is the number of cycles per second; the period is 1/250 second, so b = 2π ÷ (1/250) = 500π.",
   "Treats the frequency as the period"),
  ("250π",
   "This uses b = π·(frequency), dropping the factor of 2. One cycle needs the argument b·t to increase by 2π, so with period 1/250 we get b = 2π·250 = 500π.",
   "Uses π instead of 2π")],
 "Hz-to-b conversion, a documented weak point; different context and numbers from the seed.","numeric")
add("apprecalc-mcq-np2-006-v3","apprecalc-mcq-np2-006","hard","Parameter b from a maximum and the next minimum",
 "A sinusoidal function y = a·sin(b(x + c)) + d, with b > 0, has a maximum at x = 3 and its next minimum at x = 11. What is the value of b?",
 ("π/8",
  "A maximum to the next minimum is half a period, so half the period is 11 − 3 = 8 and the period is 16. Then b = 2π/16 = π/8."),
 [("π/4",
   "This treats 8, the distance from a maximum to the next minimum, as a full period: 2π/8 = π/4. That distance is only half a period, so the period is 16 and b = π/8.",
   "Treats half a period as a full period"),
  ("16",
   "16 is the correct period, but b is not the period. The relationship is b = 2π/period = 2π/16 = π/8.",
   "Uses the period as b"),
  ("π/16",
   "This uses b = π/period = π/16, dropping the factor of 2. The period of a sinusoid is 2π/b, so with period 16, b = 2π/16 = π/8.",
   "Uses π instead of 2π")],
 "Requires recognizing half-period between max and min; adds a second step beyond the seed.","numeric")
# ---------- np2-007 (3.3)
add("apprecalc-mcq-np2-007-v1","apprecalc-mcq-np2-007","easy","Sine at a third-quadrant angle",
 "What is the exact value of sin(7π/6)?",
 ("−1/2",
  "7π/6 lies in the third quadrant with reference angle 7π/6 − π = π/6. Sine is negative there, so sin(7π/6) = −sin(π/6) = −1/2."),
 [("1/2",
   "This gives the reference value sin(π/6) = 1/2 but omits the negative sign. In the third quadrant the y-coordinate on the unit circle is negative.",
   "Omits the sign for the quadrant"),
  ("−√3/2",
   "The sign is right, but √3/2 is cos(π/6), the cosine reference value. The sine reference value for π/6 is 1/2, so sin(7π/6) = −1/2.",
   "Uses the cosine reference value"),
  ("√3/2",
   "This uses the cosine reference value cos(π/6) = √3/2 and also omits the negative sign for the third quadrant. The correct value is −sin(π/6) = −1/2.",
   "Uses the cosine value and omits the sign")],
 "Sine instead of cosine, third quadrant instead of second.","numeric")
add("apprecalc-mcq-np2-007-v2","apprecalc-mcq-np2-007","medium","Sine of a negative angle",
 "What is the exact value of sin(−3π/4)?",
 ("−√2/2",
  "The angle −3π/4 is measured clockwise and ends in the third quadrant, with reference angle π/4. Sine is negative there, so sin(−3π/4) = −sin(π/4) = −√2/2. Equivalently, sin(−3π/4) = −sin(3π/4) = −√2/2."),
 [("√2/2",
   "This ignores the negative sign of the angle and computes sin(3π/4) = √2/2. Since sine is odd, sin(−3π/4) = −sin(3π/4) = −√2/2.",
   "Ignores that the angle is negative"),
  ("−√3/2",
   "The sign is right, but √3/2 is a reference value for π/3, not π/4. The reference angle here is π/4, with sine value √2/2.",
   "Uses the π/3 reference value instead of the π/4 value"),
  ("√3/2",
   "This both uses the π/3 reference value (√3/2) instead of the π/4 value (√2/2) and drops the negative sign.",
   "Wrong reference value and omitted sign")],
 "Negative angle with a π/4 reference value; different value set from the seed.","numeric")
add("apprecalc-mcq-np2-007-v3","apprecalc-mcq-np2-007","medium","Unit circle point for an angle",
 "A point P starts at (1, 0) on the unit circle and moves counterclockwise through an angle of 4π/3. What are the coordinates of P?",
 ("(−1/2, −√3/2)",
  "The terminal side of 4π/3 is in the third quadrant with reference angle π/3. P = (cos(4π/3), sin(4π/3)) = (−cos(π/3), −sin(π/3)) = (−1/2, −√3/2)."),
 [("(−√3/2, −1/2)",
   "This swaps the coordinates, using sine for the x-coordinate and cosine for the y-coordinate. For π/3, cos = 1/2 and sin = √3/2, so P = (−1/2, −√3/2).",
   "Swaps the cosine and sine values"),
  ("(1/2, √3/2)",
   "This is the point for angle π/3, the reference angle, without the signs from the third quadrant. Both coordinates are negative for 4π/3.",
   "Uses the reference-angle point without quadrant signs"),
  ("(−1/2, √3/2)",
   "This is the point for 2π/3 (second quadrant). For 4π/3, which is in the third quadrant, the y-coordinate is negative: sin(4π/3) = −√3/2.",
   "Gets the sign of the y-coordinate wrong")],
 "Asks for the unit circle point rather than a single function value.","numeric")
# ---------- np2-008 (3.13)
add("apprecalc-mcq-np2-008-v1","apprecalc-mcq-np2-008","medium","Polar to rectangular with negative r (5π/6)",
 "Convert the polar coordinates (r, θ) = (−6, 5π/6) to rectangular coordinates.",
 ("(3√3, −3)",
  "x = r·cosθ = −6·(−√3/2) = 3√3, and y = r·sinθ = −6·(1/2) = −3."),
 [("(−3√3, 3)",
   "This treats r as +6 and ignores the negative sign: x = 6·(−√3/2) = −3√3, y = 6·(1/2) = 3. With r = −6, both coordinates change sign.",
   "Drops the negative sign of r"),
  ("(3√3, 3)",
   "This applies the negative sign of r to x but not to y: x = −6·(−√3/2) = 3√3 is right, but y = r·sinθ = −6·(1/2) = −3, not +3.",
   "Applies the sign of r to only one coordinate"),
  ("(−3, 3√3)",
   "This swaps the coordinates by using x = r·sinθ = −6·(1/2) = −3 and y = r·cosθ = −6·(−√3/2) = 3√3. The correct formulas are x = r·cosθ and y = r·sinθ.",
   "Swaps the cosine and sine formulas")],
 "Different angle (5π/6, second quadrant) and r; distractors are sign dropped, sign on one coordinate, and swapped.","numeric")
add("apprecalc-mcq-np2-008-v2","apprecalc-mcq-np2-008","medium","Polar to rectangular in quadrant IV",
 "Which point, in rectangular coordinates, is the polar point (r, θ) = (8, 11π/6)?",
 ("(4√3, −4)",
  "11π/6 is in the fourth quadrant with reference angle π/6. x = 8·cos(11π/6) = 8·(√3/2) = 4√3, and y = 8·sin(11π/6) = 8·(−1/2) = −4."),
 [("(4√3, 4)",
   "This uses the sine reference value 1/2 without its negative sign: y = 8·(1/2) = 4. Sine is negative in the fourth quadrant, so y = 8·(−1/2) = −4.",
   "Omits the negative sign of sine in quadrant IV"),
  ("(−4, 4√3)",
   "This uses x = r·sinθ = 8·(−1/2) = −4 and y = r·cosθ = 8·(√3/2) = 4√3, swapping the roles of cosine and sine.",
   "Swaps the cosine and sine formulas"),
  ("(4, −4√3)",
   "This uses 1/2 as the cosine of π/6 and √3/2 as the sine: x = 8·(1/2) = 4, y = 8·(−√3/2) = −4√3. The reference values are reversed; cos(π/6) = √3/2 and sin(π/6) = 1/2.",
   "Reverses the reference values for π/6")],
 "Positive r in quadrant IV; different distractor set (reference-value reversal).","numeric")
add("apprecalc-mcq-np2-008-v3","apprecalc-mcq-np2-008","hard","Polar to rectangular with negative irrational r",
 "Which point, in rectangular coordinates, is the polar point (−4√2, 3π/4)?",
 ("(4, −4)",
  "x = r·cosθ = −4√2·(−√2/2) = 4, and y = r·sinθ = −4√2·(√2/2) = −4."),
 [("(−4, 4)",
   "This ignores the negative sign of r and uses r = 4√2: x = 4√2·(−√2/2) = −4, y = 4√2·(√2/2) = 4. With r = −4√2 both coordinates change sign.",
   "Drops the negative sign of r"),
  ("(4, 4)",
   "This applies the negative sign of r to x only: x = −4√2·(−√2/2) = 4 is right, but y = −4√2·(√2/2) = −4, not 4.",
   "Applies the sign of r to only one coordinate"),
  ("(−4, −4)",
   "This applies the negative sign of r to y only: y = −4√2·(√2/2) = −4 is right, but x = −4√2·(−√2/2) = 4, not −4.",
   "Applies the sign of r to only one coordinate (the other one)")],
 "Negative radius that is irrational and angle 3π/4; the distractors isolate which coordinate loses the sign.","numeric")
# ---------- np2-009 (1.4)
add("apprecalc-mcq-np2-009-v1","apprecalc-mcq-np2-009","medium","Degree from fourth differences",
 "A function f is evaluated at equally spaced inputs x = 0, 1, 2, 3, 4, 5, giving outputs 0, 1, 16, 81, 256, 625. What is the minimum degree of a polynomial that could model these outputs?",
 ("4",
  "First differences: 1, 15, 65, 175, 369. Second: 14, 50, 110, 194. Third: 36, 60, 84. Fourth: 24, 24. The fourth differences are the first constant ones, so the minimum degree is 4."),
 [("3",
   "The third differences are 36, 60, 84, which are not constant, so a cubic cannot fit. The constant differences first appear at the fourth level (24, 24).",
   "Stops one level of differences too early"),
  ("5",
   "With 6 data points a polynomial of degree 5 can always pass through them, but the minimum degree is set by the first constant differences. The fourth differences are already constant (24, 24), so degree 4 is enough.",
   "Uses the number of points minus 1"),
  ("24",
   "24 is the value of the constant fourth difference, not the degree. The degree equals the number of the difference level that is constant, which is 4.",
   "Uses the constant difference value as the degree")],
 "Fourth-difference data (outputs 0,1,16,81,256,625) with new framing.","numeric")
add("apprecalc-mcq-np2-009-v2","apprecalc-mcq-np2-009","easy","Degree from second differences",
 "The outputs of a function at equally spaced inputs x = 1, 2, 3, 4, 5 are 5, 8, 15, 26, 41. What is the minimum degree of a polynomial that could model these outputs?",
 ("2",
  "First differences: 3, 7, 11, 15 (not constant). Second differences: 4, 4, 4 (constant). Constant second differences mean the minimum degree is 2."),
 [("1",
   "A degree-1 polynomial has constant first differences. Here the first differences 3, 7, 11, 15 keep growing (by 4 each time), so the data are not linear.",
   "Does not check whether the first differences are constant"),
  ("4",
   "4 is the value of the constant second difference, not the degree. The second differences are the first constant ones, so the degree is 2.",
   "Uses the constant difference value as the degree"),
  ("5",
   "5 is the number of data points, which does not determine the degree. The first constant differences appear at the second level (4, 4, 4), so the degree is 2.",
   "Uses the number of data points")],
 "Smaller case with second differences constant; distractors based on first differences, constant value, and number of points.","numeric")
add("apprecalc-mcq-np2-009-v3","apprecalc-mcq-np2-009","hard","Degree from a list of first differences",
 "The first differences of a function's outputs at equally spaced inputs are 4, 3, 6, 13, 24, 39. What is the minimum degree of a polynomial that could model the function?",
 ("3",
  "Taking differences of the given first differences gives the second differences of the outputs: −1, 3, 7, 11, 15. Differences of those give the third differences of the outputs: 4, 4, 4, 4, which are constant. So the minimum degree is 3."),
 [("2",
   "This treats the given list as the outputs: its second differences are constant (4, 4, 4, 4), suggesting degree 2. But the list is already the first differences of the outputs, so one more level of differences is needed, giving degree 3.",
   "Treats first differences as the outputs themselves"),
  ("4",
   "4 is the value of the constant difference, not the degree. The constant level is the third differences of the outputs, so the degree is 3.",
   "Uses the constant difference value as the degree"),
  ("5",
   "5 is one fewer than the 6 listed values, but the degree is not found by counting entries. The first constant differences appear at the third level for the outputs (4, 4, 4, 4), so the degree is 3.",
   "Uses the number of listed values")],
 "Gives first differences instead of outputs, so one extra level must be accounted for.","numeric")
# ---------- np2-010 (3.11)
add("apprecalc-mcq-np2-010-v1","apprecalc-mcq-np2-010","easy","Where secant is undefined",
 "For which value of x is sec(x) undefined?",
 ("x = 3π/2",
  "sec(x) = 1/cos(x) is undefined where cos(x) = 0, and cos(3π/2) = 0."),
 [("x = π",
   "cos(π) = −1, so sec(π) = −1 is defined. sin(π) = 0, which is where csc and cot are undefined, not sec.",
   "Confuses the zeros of sine with the zeros of cosine"),
  ("x = 5π/4",
   "cos(5π/4) = −√2/2 ≠ 0, so sec(5π/4) = −√2 is defined.",
   "Picks an angle without checking whether cosine is zero"),
  ("x = 2π/3",
   "cos(2π/3) = −1/2 ≠ 0, so sec(2π/3) = −2 is defined.",
   "Picks an angle without checking whether cosine is zero")],
 "Secant instead of cosecant; new angle values.","conceptual")
add("apprecalc-mcq-np2-010-v2","apprecalc-mcq-np2-010","medium","Where cotangent is undefined",
 "For which value of x is cot(x) undefined?",
 ("x = 2π",
  "cot(x) = cos(x)/sin(x) is undefined where sin(x) = 0, and sin(2π) = 0."),
 [("x = π/2",
   "cos(π/2) = 0 and sin(π/2) = 1, so cot(π/2) = 0/1 = 0, which is defined. π/2 is where tan is undefined, not cot.",
   "Confuses where cotangent is zero with where it is undefined"),
  ("x = 3π/4",
   "sin(3π/4) = √2/2 ≠ 0, so cot(3π/4) = (−√2/2)/(√2/2) = −1 is defined.",
   "Picks an angle without checking whether sine is zero"),
  ("x = 7π/6",
   "sin(7π/6) = −1/2 ≠ 0, so cot(7π/6) = (−√3/2)/(−1/2) = √3 is defined.",
   "Picks an angle without checking whether sine is zero")],
 "Cotangent; undefined where sine is zero.","conceptual")
add("apprecalc-mcq-np2-010-v3","apprecalc-mcq-np2-010","medium","Where sec(2x) is undefined",
 "For which value of x is sec(2x) undefined?",
 ("x = π/4",
  "sec(2x) = 1/cos(2x) is undefined where cos(2x) = 0. At x = π/4, 2x = π/2 and cos(π/2) = 0."),
 [("x = π/2",
   "This solves cos(x) = 0 and ignores the factor of 2. At x = π/2, 2x = π and cos(π) = −1, so sec(π) = −1 is defined.",
   "Ignores the coefficient 2 inside the function"),
  ("x = π",
   "This multiplies by 2 instead of dividing: setting 2x = π/2 gives x = π/4, not x = 2·(π/2) = π. At x = π, 2x = 2π and sec(2π) = 1 is defined.",
   "Multiplies by the coefficient instead of dividing"),
  ("x = 0",
   "cos(2·0) = cos(0) = 1, so sec(0) = 1 is defined. x = 0 is where sine is zero, which affects csc, not sec.",
   "Confuses the zeros of sine with the zeros of cosine")],
 "Horizontal compression inside secant; requires dividing the argument.","conceptual")
json.dump(V,open("variants_c5.json","w"),ensure_ascii=False,indent=1)
print(len(V))
