begin;

-- Seed AP Precalculus Unit 1 and AP Calculus BC Unit 1 topic point briefs.
-- These are authored as Cramapple-original point-attainment briefs for the
-- new-user home and unit selector surfaces.

with brief_seed (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_slug
) as (
  values
  ($$ap_precalculus$$,1,$$1.1$$,$$Change in Tandem$$,$$very-important$$,$$very-important$$,$$This topic studies how two quantities change together and how one quantity can be treated as a function of another.$$, $$It is the entry point for modeling: AP Precalculus questions often ask students to connect a table, graph, equation, or description to how quantities vary together.$$, $$You earn points by identifying the input and output quantities, describing how they change together, and using correct function language for the relationship.$$, $$Name the two quantities, decide which one depends on the other, then describe the change pattern using values, units, or graph behavior.$$, $$Describing each variable separately without explaining how the change in one quantity connects to the change in the other.$$, $$change-in-tandem$$),
  ($$ap_precalculus$$,1,$$1.2$$,$$Rates of Change$$,$$very-important$$,$$very-important$$,$$Rate of change compares how much the output changes for a change in input over an interval.$$, $$It is the foundation for slope, linear comparison, average rate, model interpretation, and later calculus readiness.$$, $$You earn points by computing change in output divided by change in input, preserving units, and interpreting the result in context.$$, $$Use the structure: change in output over change in input, then say what one input unit means for the output.$$, $$Reporting a slope number without units or interpreting it as an output value instead of a rate.$$, $$rates-of-change$$),
  ($$ap_precalculus$$,1,$$1.3$$,$$Rates of Change and Behavior of Graphs$$,$$very-important$$,$$very-important$$,$$A graph shows where a function increases, decreases, changes quickly, changes slowly, or has different average rates over different intervals.$$, $$AP Precalculus often asks students to connect visual graph behavior to numerical or verbal statements about change.$$, $$You earn points by using graph features to justify rate claims, including sign, steepness, and interval-specific behavior.$$, $$Pick the interval first, then describe slope sign and steepness from the graph before drawing a conclusion.$$, $$Making a global statement about the whole graph when the question asks about a specific interval.$$, $$rates-of-change-and-graphs$$),
  ($$ap_precalculus$$,1,$$1.4$$,$$Polynomial Functions and Rates of Change$$,$$very-important$$,$$very-important$$,$$Polynomial functions have smooth graph behavior whose rates of change depend on degree, leading coefficient, and local shape.$$, $$This topic connects algebraic form to graph behavior and prepares students to analyze turning behavior and end behavior.$$, $$You earn points by connecting a polynomial's expression or graph to intervals of increase and decrease, average rates, and qualitative change.$$, $$Use the polynomial's graph or values to compare how fast the output changes on named intervals.$$, $$Treating all polynomial change as constant like a linear function.$$, $$polynomial-functions-and-rates-of-change$$),
  ($$ap_precalculus$$,1,$$1.5$$,$$Polynomial Functions and Complex Zeros$$,$$very-important$$,$$very-important$$,$$Polynomial zeros can be real or complex, and nonreal complex zeros occur in conjugate pairs for polynomials with real coefficients.$$, $$Zeros connect factored form, graph x-intercepts, equation solving, and polynomial structure.$$, $$You earn points by using zeros to write factors, count degree, identify x-intercepts, and account for complex conjugate pairs.$$, $$List known zeros, convert each zero to a factor, and remember that a+bi brings a-bi when coefficients are real.$$, $$Counting only visible x-intercepts and forgetting nonreal complex zeros when reasoning about degree or factors.$$, $$polynomial-functions-and-complex-zeros$$),
  ($$ap_precalculus$$,1,$$1.6$$,$$Polynomial Functions and End Behavior$$,$$very-important$$,$$very-important$$,$$End behavior describes what a polynomial does as x becomes very large positive or very large negative.$$, $$It helps students match equations to graphs and predict long-run behavior without plotting every point.$$, $$You earn points by using degree parity and leading coefficient sign to describe left-end and right-end behavior.$$, $$Find the leading term first; its degree and coefficient control both ends of the graph.$$, $$Using a lower-degree term or a local turning point to decide end behavior.$$, $$polynomial-end-behavior$$),
  ($$ap_precalculus$$,1,$$1.7$$,$$Rational Functions and End Behavior$$,$$very-important$$,$$very-important$$,$$Rational functions are ratios of polynomials, and their end behavior depends on how numerator and denominator compare for large input values.$$, $$This is central for asymptotes, long-run modeling, and distinguishing polynomial behavior from rational behavior.$$, $$You earn points by comparing degrees or leading terms to describe horizontal or slant end behavior when appropriate.$$, $$Compare the numerator degree to the denominator degree, then state the long-run behavior that follows.$$, $$Finding zeros first when the question is asking about what happens far left or far right.$$, $$rational-functions-end-behavior$$),
  ($$ap_precalculus$$,1,$$1.8$$,$$Rational Functions and Zeros$$,$$very-important$$,$$very-important$$,$$Zeros of a rational function occur where the numerator is zero and the denominator is not zero.$$, $$This topic prevents students from confusing x-intercepts with holes or undefined values.$$, $$You earn points by solving the numerator for zeros, checking the denominator, and identifying valid intercepts separately from excluded inputs.$$, $$Factor numerator and denominator, cancel only common factors for holes, then use remaining numerator zeros for x-intercepts.$$, $$Calling a canceled factor an x-intercept instead of recognizing it as a hole.$$, $$rational-functions-and-zeros$$),
  ($$ap_precalculus$$,1,$$1.9$$,$$Rational Functions and Vertical Asymptotes$$,$$very-important$$,$$very-important$$,$$Vertical asymptotes occur at input values where a rational function becomes unbounded because the denominator approaches zero without a removable cancellation.$$, $$They are a key way rational functions differ from polynomials and a frequent graph-equation matching feature.$$, $$You earn points by finding non-canceled denominator zeros and connecting them to unbounded graph behavior.$$, $$Factor first, cancel common factors for holes, then set the remaining denominator equal to zero for vertical asymptotes.$$, $$Listing every denominator zero as a vertical asymptote without checking for removable holes.$$, $$rational-functions-vertical-asymptotes$$),
  ($$ap_precalculus$$,1,$$1.10$$,$$Rational Functions and Holes$$,$$very-important$$,$$very-important$$,$$A hole is a removable discontinuity created when the numerator and denominator share a factor that cancels.$$, $$This topic builds precise graph reasoning from algebraic structure and keeps students from overcalling asymptotes.$$, $$You earn points by identifying the canceled factor, finding the excluded x-value, and using the simplified function to find the hole's y-value when asked.$$, $$Cancel the common factor, keep the excluded x-value, then substitute that x-value into the simplified expression for the hole location.$$, $$Canceling a factor and then forgetting that the original function is still undefined at that input.$$, $$rational-functions-holes$$),
  ($$ap_precalculus$$,1,$$1.11$$,$$Equivalent Representations$$,$$very-important$$,$$very-important$$,$$Equivalent representations show the same function or relationship through equations, graphs, tables, verbal descriptions, and rewritten algebraic forms.$$, $$AP Precalculus rewards students who can move between forms and use the form that exposes the needed feature.$$, $$You earn points by matching features across representations, such as zeros, intercepts, rates, asymptotes, holes, and end behavior.$$, $$Before solving, choose the representation that makes the requested feature easiest to see.$$, $$Treating two algebraically equivalent forms as different functions without checking whether domain restrictions changed.$$, $$equivalent-representations$$),
  ($$ap_precalculus$$,1,$$1.12$$,$$Transformations of Functions$$,$$very-important$$,$$very-important$$,$$Transformations move, stretch, compress, or reflect a parent function's graph using changes inside or outside the function rule.$$, $$They let students predict graph behavior efficiently and compare model families across units.$$, $$You earn points by identifying horizontal and vertical shifts, stretches, compressions, and reflections from notation or graphs.$$, $$Separate inside changes from outside changes, then state the graph effect in order.$$, $$Reversing horizontal transformation direction or mixing up input changes with output changes.$$, $$function-transformations$$),
  ($$ap_precalculus$$,1,$$1.13$$,$$Function Model Selection and Assumption Articulation$$,$$very-important$$,$$very-important$$,$$Model selection means choosing a function type that fits a pattern, context, or data set and stating the assumptions behind that choice.$$, $$This is a distinctive AP Precalculus point skill: students must justify why a model is reasonable, not only produce an equation.$$, $$You earn points by citing evidence from data or context and explaining the assumptions and limits of the chosen model.$$, $$Name the model type, point to the pattern that supports it, and state one assumption the model depends on.$$, $$Choosing a model because it is familiar without using the data or context as evidence.$$, $$model-selection-and-assumptions$$),
  ($$ap_precalculus$$,1,$$1.14$$,$$Function Model Construction and Application$$,$$very-important$$,$$very-important$$,$$Model construction turns information from a context, table, graph, or constraints into a usable function.$$, $$It is where algebraic skill becomes decision-making: students build, apply, and interpret a model for a real situation.$$, $$You earn points by defining variables, constructing a function from given information, applying it to the requested input or output, and interpreting the result with units.$$, $$Define variables first, build the function from the constraints, then answer the contextual question rather than stopping at the equation.$$, $$Giving an equation without checking whether it answers the question or makes sense in the stated domain.$$, $$model-construction-and-application$$),
  ($$ap_calculus_bc$$,1,$$1.1$$,$$Introducing Calculus: Can Change Occur at an Instant?$$,$$very-important$$,$$somewhat-important$$,$$This topic introduces the move from average change over an interval to change at a single instant. A limit describes what average rates approach as the interval around the instant shrinks.$$, $$This is the conceptual bridge into derivatives. BC students will keep using this limiting idea later for motion, parametric curves, polar change, and series approximations.$$, $$You earn points by recognizing whether a question asks about an interval or an instant and by connecting the instant case to limiting behavior.$$, $$Ask: over an interval or at one point? If it is at one point, describe the instantaneous rate as the value approached by average rates over smaller intervals.$$, $$Trying to compute an instantaneous rate as a direct quotient with zero change in x.$$, $$instantaneous-change$$),
  ($$ap_calculus_bc$$,1,$$1.2$$,$$Defining Limits and Using Limit Notation$$,$$very-important$$,$$very-important$$,$$A limit describes the value a function approaches as x gets close to a chosen input. Limit notation names that approaching behavior precisely.$$, $$Limit notation is the language used for continuity, derivatives, infinite behavior, improper integrals, and series convergence claims.$$, $$You earn points by reading and writing the approaching input, function, direction when specified, and value approached.$$, $$Read the notation as: as x approaches c, f(x) approaches L. Keep approaches separate from equals.$$, $$Replacing the limit with f(a) automatically, or dropping the direction marker on a one-sided limit.$$, $$limit-notation$$),
  ($$ap_calculus_bc$$,1,$$1.3$$,$$Estimating Limit Values from Graphs$$,$$very-important$$,$$very-important$$,$$A graph can show what y-value a function approaches as x moves toward a chosen input from the left, right, or both sides.$$, $$Graph-based limits train students to focus on nearby behavior instead of point values, a skill that returns in continuity, asymptotes, derivative graphs, and polar/parametric contexts.$$, $$You earn points by identifying left-hand and right-hand behavior and concluding whether the two-sided limit exists.$$, $$Trace the graph toward the x-value from both sides before looking at the point on the graph.$$, $$Using a filled or open point as the limit value without checking nearby graph behavior.$$, $$estimating-limits-from-graphs$$),
  ($$ap_calculus_bc$$,1,$$1.4$$,$$Estimating Limit Values from Tables$$,$$very-important$$,$$very-important$$,$$A table can suggest a limit by showing how function values behave for x-values close to a chosen input.$$, $$Tables appear when exact formulas are not given, and BC students also use tabular evidence later for rates, accumulation, and convergence reasoning.$$, $$You earn points by using nearby table values from both sides and writing an estimate that matches the evidence.$$, $$Look inward from both sides of the table, then state the trend and estimated limit.$$, $$Choosing one table entry instead of describing the trend across nearby entries.$$, $$estimating-limits-from-tables$$),
  ($$ap_calculus_bc$$,1,$$1.5$$,$$Determining Limits Using Algebraic Properties of Limits$$,$$very-important$$,$$very-important$$,$$Limit properties let students combine simpler limits to determine limits of sums, differences, products, quotients, and composite functions.$$, $$This is where limits become a reliable calculation tool instead of only a graphical or numerical idea.$$, $$You earn points by applying a valid property, preserving expression structure, and showing setup that makes the final value follow.$$, $$Break the expression into parts, determine component limits, then apply the matching property.$$, $$Applying quotient or composition rules mechanically when the needed conditions are not met.$$, $$algebraic-properties-of-limits$$),
  ($$ap_calculus_bc$$,1,$$1.6$$,$$Determining Limits Using Algebraic Manipulation$$,$$very-important$$,$$very-important$$,$$Some limit expressions hide their behavior until they are rewritten into an equivalent useful form.$$, $$Factoring, rationalizing, simplifying, or using identities can turn a blocked expression into a solvable limit, including forms that later resemble BC improper-integral and series work.$$, $$You earn points by choosing a valid rewrite, showing the transformed expression, and evaluating from the simplified form.$$, $$When substitution is blocked, ask what equivalent form removes the obstacle.$$, $$Stopping at 0/0, or canceling terms that are not common factors.$$, $$algebraic-manipulation-for-limits$$),
  ($$ap_calculus_bc$$,1,$$1.7$$,$$Selecting Procedures for Determining Limits$$,$$very-important$$,$$very-important$$,$$This topic is about choosing the method that fits the limit problem before carrying out the calculation.$$, $$AP questions often reward recognizing the right path: direct property use, graph or table reasoning, factoring, rationalizing, one-sided analysis, or later L'Hospital's Rule.$$, $$You earn points by classifying the problem form and selecting a procedure that matches it.$$, $$Before solving, name the cue: direct substitution works, sides must be checked, factoring helps, or another strategy fits.$$, $$Defaulting to a familiar technique without checking whether the problem calls for it.$$, $$selecting-limit-procedures$$),
  ($$ap_calculus_bc$$,1,$$1.8$$,$$Determining Limits Using the Squeeze Theorem$$,$$somewhat-important$$,$$somewhat-important$$,$$The squeeze theorem finds a limit by trapping one function between two functions that approach the same value.$$, $$This is an early example of theorem-based limit reasoning where conditions force a conclusion, which is useful again in BC convergence and approximation arguments.$$, $$You earn points by showing bounds, showing both bounding limits match, and then stating the squeezed conclusion.$$, $$Write the inequality first, find the outside limits, then conclude the middle limit.$$, $$Naming the theorem without showing the bounding relationship and matching limits.$$, $$squeeze-theorem$$),
  ($$ap_calculus_bc$$,1,$$1.9$$,$$Connecting Multiple Representations of Limits$$,$$very-important$$,$$very-important$$,$$The same limit can be represented by notation, words, a graph, a table, or an equation.$$, $$AP Calculus regularly changes representation without changing the underlying mathematical claim, and BC adds more representations later through parametric, polar, and series contexts.$$, $$You earn points by identifying the same limiting behavior across representations and keeping the claim consistent.$$, $$Convert each representation into: as x approaches c, f(x) approaches L.$$, $$Matching a table or graph to a function value instead of to approach behavior.$$, $$multiple-representations-of-limits$$),
  ($$ap_calculus_bc$$,1,$$1.10$$,$$Exploring Types of Discontinuities$$,$$very-important$$,$$very-important$$,$$A discontinuity is a place where continuity fails. The type depends on whether the value, one-sided limits, or bounded behavior fails.$$, $$Naming the type helps students explain what failed rather than merely saying the graph is broken.$$, $$You earn points by classifying the discontinuity and connecting that classification to limit evidence.$$, $$Check left-hand limit, right-hand limit, and f(c), then classify based on which part fails.$$, $$Calling every gap removable or every discontinuity an asymptote without checking behavior.$$, $$types-of-discontinuities$$),
  ($$ap_calculus_bc$$,1,$$1.11$$,$$Defining Continuity at a Point$$,$$very-important$$,$$very-important$$,$$A function is continuous at a point when f(c) exists, the limit exists, and the limit equals f(c).$$, $$Continuity is a condition checklist used before applying theorems in derivatives, integrals, differential equations, and BC series-related function work.$$, $$You earn points by checking all three conditions and using them to justify whether the function is continuous.$$, $$Use the checklist: value exists, limit exists, value equals limit, then state the conclusion.$$, $$Saying a function is continuous because the graph looks connected without verifying conditions.$$, $$continuity-at-a-point$$),
  ($$ap_calculus_bc$$,1,$$1.12$$,$$Confirming Continuity over an Interval$$,$$very-important$$,$$very-important$$,$$Continuity over an interval means the function is continuous at every point in that interval.$$, $$Many AP conclusions depend on interval-level continuity, including theorem use, domain reasoning, accumulation, and convergence-adjacent function claims.$$, $$You earn points by identifying the interval, checking special points, and naming domain restrictions or endpoints that matter.$$, $$Start with the function family and domain, then check special points inside the interval.$$, $$Claiming continuity over an interval while ignoring holes, asymptotes, piecewise boundaries, or excluded domain values.$$, $$continuity-over-an-interval$$),
  ($$ap_calculus_bc$$,1,$$1.13$$,$$Removing Discontinuities$$,$$very-important$$,$$very-important$$,$$A removable discontinuity can be fixed by defining or redefining the function value so it equals the limit at that point.$$, $$This topic turns the definition of continuity into an action: find the value or parameter that makes the function continuous.$$, $$You earn points by finding the relevant limit and setting the function value or parameter equal to it.$$, $$Find the limit at the discontinuity first, then set f(c) or the parameter expression equal to that limit.$$, $$Solving for a value without showing that it matches the limiting behavior.$$, $$removing-discontinuities$$),
  ($$ap_calculus_bc$$,1,$$1.14$$,$$Connecting Infinite Limits and Vertical Asymptotes$$,$$very-important$$,$$very-important$$,$$An infinite limit describes function values growing without bound as x approaches a finite input.$$, $$Students need to distinguish unbounded behavior from finite limits, jumps, and ordinary function values; BC later reuses unbounded behavior in improper integrals.$$, $$You earn points by using limit notation to describe unbounded behavior and connecting it to a vertical asymptote when appropriate.$$, $$Check each side of the input. If f(x) grows without bound, write the infinite limit and name x = c as the vertical asymptote.$$, $$Writing only does not exist when the problem asks for behavior or an asymptote connection.$$, $$infinite-limits-and-vertical-asymptotes$$),
  ($$ap_calculus_bc$$,1,$$1.15$$,$$Connecting Limits at Infinity and Horizontal Asymptotes$$,$$very-important$$,$$very-important$$,$$A limit at infinity describes end behavior as x grows very large positive or negative.$$, $$End behavior helps students describe long-run function behavior analytically, graphically, verbally, and later in BC convergence contexts.$$, $$You earn points by identifying end behavior, writing the correct limit at infinity, and connecting a finite result to y = L.$$, $$Ask what f(x) approaches as x goes far left or far right. If it approaches L, name y = L.$$, $$Confusing vertical asymptotes with horizontal asymptotes or finite-input limits with limits at infinity.$$, $$limits-at-infinity-and-horizontal-asymptotes$$),
  ($$ap_calculus_bc$$,1,$$1.16$$,$$Working with the Intermediate Value Theorem$$,$$very-important$$,$$very-important$$,$$The Intermediate Value Theorem says a continuous function on a closed interval takes every value between its endpoint values somewhere inside the interval.$$, $$This is an early existence theorem: it proves a value occurs without finding its exact location, a style of reasoning BC students will keep using in more advanced settings.$$, $$You earn points by verifying continuity, showing the target value lies between endpoint values, and stating the existence conclusion.$$, $$Write the conditions first: continuous on [a,b], target between f(a) and f(b), therefore some c exists in (a,b).$$, $$Jumping to the conclusion without verifying continuity and the endpoint-value condition.$$, $$intermediate-value-theorem$$)
)
insert into app.topic_point_briefs (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path, practice_subject_key, practice_unit_number,
  practice_topic_code, status, published_at
)
select
  subject_key,
  unit_number,
  topic_code,
  title,
  class_importance,
  exam_importance,
  what_it_is,
  why_it_matters,
  how_points_are_earned,
  answer_move,
  common_point_loss,
  '/learn/' || replace(subject_key, '_', '-') || '/unit-' || unit_number::text || '/' || learn_more_slug,
  subject_key,
  unit_number,
  topic_code,
  'published',
  now()
from brief_seed
on conflict (subject_key, topic_code) do update
set
  unit_number = excluded.unit_number,
  title = excluded.title,
  class_importance = excluded.class_importance,
  exam_importance = excluded.exam_importance,
  what_it_is = excluded.what_it_is,
  why_it_matters = excluded.why_it_matters,
  how_points_are_earned = excluded.how_points_are_earned,
  answer_move = excluded.answer_move,
  common_point_loss = excluded.common_point_loss,
  learn_more_path = excluded.learn_more_path,
  practice_subject_key = excluded.practice_subject_key,
  practice_unit_number = excluded.practice_unit_number,
  practice_topic_code = excluded.practice_topic_code,
  status = excluded.status,
  published_at = excluded.published_at,
  updated_at = now();

do $$
declare
  v_precalc_count integer;
  v_bc_count integer;
begin
  select count(*) into v_precalc_count
  from app.topic_point_briefs
  where subject_key = 'ap_precalculus'
    and unit_number = 1
    and status = 'published';

  select count(*) into v_bc_count
  from app.topic_point_briefs
  where subject_key = 'ap_calculus_bc'
    and unit_number = 1
    and status = 'published';

  if v_precalc_count <> 14 then
    raise exception 'expected 14 AP Precalculus Unit 1 topic point briefs, found %', v_precalc_count;
  end if;

  if v_bc_count <> 16 then
    raise exception 'expected 16 AP Calculus BC Unit 1 topic point briefs, found %', v_bc_count;
  end if;
end $$;

commit;
