begin;

-- Add AP Calculus BC Unit 10 topic-guide pairs.
--
-- Grounding: docs/product/AP_CALCULUS_AB_BC_CED_FACT_PACK.md Unit 10
-- deep-tier detail. Unit 10 is BC-only and exam-assessed at 15-20%.
-- The fact pack closes the assessed convergence-test list to six named
-- tests and flags 10.14-10.15 as lower-confidence than 10.1-10.13 because
-- recent released Maclaurin-series FRQ material lacks an official scoring
-- guide as of the fact-pack update.

with brief_seed (topic_code, title, class_importance, exam_importance, what_it_is, why_it_matters, how_points_are_earned, answer_move, common_point_loss, learn_more_path) as (
  values
  ('10.1', 'Defining Convergent and Divergent Infinite Series', 'very-important', 'very-important',
   'An infinite series adds infinitely many terms, and convergence means its sequence of partial sums approaches a finite value.',
   'This is the language for all BC series work: students must distinguish term behavior from partial-sum behavior before choosing tests.',
   'You earn points by describing convergence in terms of partial sums and by recognizing that terms going to zero is necessary but not sufficient for series convergence.',
   'Ask what the partial sums do, not just what the individual terms do.',
   'Saying a series converges just because its terms approach zero.',
   '/learn/ap-calculus-bc/unit-10/defining-convergent-and-divergent-infinite-series'),
  ('10.2', 'Working with Geometric Series', 'very-important', 'very-important',
   'A geometric series has a constant ratio, and sum ar^n converges to a/(1-r) when absolute value of r is less than 1.',
   'This is the one early Unit 10 topic where the CED gives an explicit formula, so students need the ratio condition and sum formula together.',
   'You earn points by identifying a and r, checking |r|<1, and using a/(1-r) only when the convergence condition is met.',
   'Find the common ratio first; if |r|<1, use a/(1-r). If not, state that the infinite series diverges.',
   'Using the sum formula when |r| is greater than or equal to 1.',
   '/learn/ap-calculus-bc/unit-10/working-with-geometric-series'),
  ('10.3', 'The nth-Term Test for Divergence', 'very-important', 'very-important',
   'The nth-term test shows divergence when the terms of a series do not approach zero.',
   'This test is a fast gatekeeper. It can prove divergence, but it cannot prove convergence when the term limit is zero.',
   'You earn points by finding the limit of the terms and using a nonzero or nonexistent limit to conclude divergence only.',
   'Compute the term limit first; if it is not zero or does not exist, conclude the series diverges.',
   'Concluding convergence from a zero term limit.',
   '/learn/ap-calculus-bc/unit-10/nth-term-test-for-divergence'),
  ('10.4', 'Integral Test for Convergence', 'very-important', 'very-important',
   'The integral test compares a positive decreasing series to an improper integral with matching function behavior.',
   'It links continuous accumulation to discrete sums, but it only applies when the needed positivity and decreasing behavior are justified.',
   'You earn points by checking the test conditions, setting up the matching improper integral, and matching convergence or divergence conclusions.',
   'Confirm positive and decreasing behavior before using the improper integral.',
   'Using the integral test without checking that the function is positive and decreasing.',
   '/learn/ap-calculus-bc/unit-10/integral-test-for-convergence'),
  ('10.5', 'Harmonic Series and p-Series', 'very-important', 'very-important',
   'The harmonic series diverges, while p-series converge for p>1 and diverge for p<=1.',
   'These named benchmark series are the comparison backbone for many convergence decisions.',
   'You earn points by recognizing harmonic and p-series forms and using the correct p threshold.',
   'Rewrite the term to identify p, then compare p with 1 before concluding.',
   'Calling every constant multiple or shifted harmonic-like series exactly the harmonic series instead of comparing it appropriately.',
   '/learn/ap-calculus-bc/unit-10/harmonic-series-and-p-series'),
  ('10.6', 'Comparison Tests for Convergence', 'very-important', 'very-important',
   'Comparison and limit comparison tests use known positive-term benchmark series to decide convergence or divergence.',
   'The fact pack flags a real error: comparison tests require positive terms, so mixed-sign alternating series need care.',
   'You earn points by choosing an appropriate positive benchmark and using comparison direction correctly for convergence or divergence.',
   'First confirm positive terms; then choose a benchmark with known behavior and compare in the direction that supports the conclusion.',
   'Using a comparison test directly on an alternating or mixed-sign series.',
   '/learn/ap-calculus-bc/unit-10/comparison-tests-for-convergence'),
  ('10.7', 'Alternating Series Test for Convergence', 'very-important', 'very-important',
   'The alternating series test can prove convergence when alternating terms decrease in magnitude to zero.',
   'This test explains convergence that is not necessarily absolute, setting up conditional convergence and error bounds.',
   'You earn points by verifying alternation, decreasing magnitudes, and limit zero before concluding convergence.',
   'Check the sign pattern, the decreasing absolute values, and the zero limit in that order.',
   'Using the alternating series test when magnitudes do not decrease to zero.',
   '/learn/ap-calculus-bc/unit-10/alternating-series-test-for-convergence'),
  ('10.8', 'Ratio Test for Convergence', 'very-important', 'very-important',
   'The ratio test studies the limit of |a_{n+1}/a_n| and is one of the six convergence tests assessed for BC.',
   'The CED explicitly closes the assessed test list; root test and other extra methods are not assessed.',
   'You earn points by setting up the ratio limit, interpreting less than 1 as absolute convergence and greater than 1 as divergence, and using another test when the limit equals 1.',
   'Form |a_{n+1}/a_n|, take the limit, and interpret the result against 1.',
   'Using the root test or treating ratio limit 1 as convergence.',
   '/learn/ap-calculus-bc/unit-10/ratio-test-for-convergence'),
  ('10.9', 'Absolute and Conditional Convergence', 'very-important', 'very-important',
   'A series converges absolutely if the series of absolute values converges; it converges conditionally if the original converges but the absolute-value series diverges.',
   'The CED states absolute convergence implies convergence and preserves value under rearrangement, unlike conditional convergence.',
   'You earn points by testing absolute convergence first when appropriate, then distinguishing absolute from conditional convergence with both required conclusions.',
   'Test the absolute-value series, then test the original series if the absolute-value series diverges.',
   'Claiming conditional convergence without showing the original converges and the absolute-value series diverges.',
   '/learn/ap-calculus-bc/unit-10/absolute-and-conditional-convergence'),
  ('10.10', 'Alternating Series Error Bound', 'very-important', 'very-important',
   'The alternating series error bound uses the first omitted term to bound the error of an alternating-series partial sum.',
   'It turns convergence into approximation control, but only when the alternating-series conditions hold.',
   'You earn points by identifying the first omitted term and stating the error is at most its magnitude.',
   'After choosing the partial sum, find the next term not included and use its absolute value as the error bound.',
   'Using the last included term instead of the first omitted term.',
   '/learn/ap-calculus-bc/unit-10/alternating-series-error-bound'),
  ('10.11', 'Taylor Polynomial Approximations of Functions', 'very-important', 'very-important',
   'A Taylor polynomial uses derivatives at a center to approximate a function near that center.',
   'The coefficient of the nth-degree term is f^(n)(a)/n!, making derivative values at the center the raw material for the approximation.',
   'You earn points by using the correct center, derivative values, factorial denominators, and powers of x-a.',
   'Build terms from f^(n)(a)/n! times (x-a)^n, keeping the center visible.',
   'Using powers of x when the polynomial is centered at a nonzero a.',
   '/learn/ap-calculus-bc/unit-10/taylor-polynomial-approximations-of-functions'),
  ('10.12', 'Lagrange Error Bound', 'very-important', 'very-important',
   'The Lagrange error bound gives a maximum possible Taylor-polynomial error using a bound on the next derivative.',
   'Real scoring separates computing the bound from connecting it with at most or <= language, so inequality wording matters.',
   'You earn points by using the correct next derivative, factorial, distance from center, and by stating the error is at most the computed bound.',
   'Identify the next derivative and maximum bound M, compute M/(n+1)! times |x-a|^(n+1), then state an inequality.',
   'Saying the error equals the bound instead of is at most the bound.',
   '/learn/ap-calculus-bc/unit-10/lagrange-error-bound'),
  ('10.13', 'Radius and Interval of Convergence of Power Series', 'very-important', 'very-important',
   'A power series converges on an interval centered at its center, with a radius found first and endpoints tested separately.',
   'Endpoint testing is a documented high-error BC skill, and naming an appropriate endpoint test can be sufficient when paired with the right conclusion.',
   'You earn points by finding the radius, translating it into the open interval, testing both endpoints, and stating the final interval precisely.',
   'Find the center and radius, write the open interval, then test each endpoint with an assessed convergence test.',
   'Reporting only the radius or open interval without endpoint analysis.',
   '/learn/ap-calculus-bc/unit-10/radius-and-interval-of-convergence-of-power-series'),
  ('10.14', 'Taylor and Maclaurin Series for a Function', 'very-important', 'very-important',
   'A Taylor series represents a function with infinitely many Taylor terms; a Maclaurin series is a Taylor series centered at 0.',
   'The CED treats the Maclaurin series for 1/(1-x), sin x, cos x, and e^x as foundational for building other series.',
   'You earn points by using the correct base series, center, signs, powers, and factorial pattern when constructing a function series.',
   'Start from a known foundational series, then substitute, multiply, differentiate, or integrate term by term as allowed.',
   'Misremembering the signs or factorials in the foundational Maclaurin series.',
   '/learn/ap-calculus-bc/unit-10/taylor-and-maclaurin-series-for-a-function'),
  ('10.15', 'Representing Functions as Power Series', 'very-important', 'very-important',
   'Functions can be represented as power series by transforming known series, especially geometric and Maclaurin series.',
   'This topic asks students to move between a function and an infinite series form, including the interval where the representation is valid.',
   'You earn points by starting from a valid known series, performing legal algebraic or calculus transformations, and carrying the convergence interval through the transformation.',
   'Identify the parent series first, transform the function to match it, then update the interval or radius of convergence.',
   'Finding a correct series expression but omitting the interval of convergence.',
   '/learn/ap-calculus-bc/unit-10/representing-functions-as-power-series')
)
insert into app.topic_point_briefs (subject_key, unit_number, topic_code, title, class_importance, exam_importance, what_it_is, why_it_matters, how_points_are_earned, answer_move, common_point_loss, learn_more_path, practice_subject_key, practice_unit_number, practice_topic_code, source_note, status, published_at)
select 'ap_calculus_bc', 10, topic_code, title, class_importance, exam_importance, what_it_is, why_it_matters, how_points_are_earned, answer_move, common_point_loss, learn_more_path, 'ap_calculus_bc', 10, topic_code, 'cramapple-authored; new coverage 2026-08-26 for AP Calculus BC Unit 10 Infinite Sequences and Series; grounded in AP_CALCULUS_AB_BC_CED_FACT_PACK.md Unit 10 deep-tier detail: BC-only 15-20% weighting, geometric series formula, closed assessed convergence-test list, absolute versus conditional convergence, alternating series error bound, Taylor polynomial coefficients, Lagrange error-bound inequality language, radius and interval of convergence endpoint testing, and Taylor/Maclaurin series representation with lower-confidence guidance for 10.14-10.15; batch 2026-08-26-ap-calculus-bc-unit10-topic-guides; author=reviewer same session, no independent human review yet', 'published', now()
from brief_seed
on conflict (subject_key, topic_code) do update set unit_number=excluded.unit_number, title=excluded.title, class_importance=excluded.class_importance, exam_importance=excluded.exam_importance, what_it_is=excluded.what_it_is, why_it_matters=excluded.why_it_matters, how_points_are_earned=excluded.how_points_are_earned, answer_move=excluded.answer_move, common_point_loss=excluded.common_point_loss, learn_more_path=excluded.learn_more_path, practice_subject_key=excluded.practice_subject_key, practice_unit_number=excluded.practice_unit_number, practice_topic_code=excluded.practice_topic_code, source_note=excluded.source_note, status=excluded.status, published_at=coalesce(app.topic_point_briefs.published_at, excluded.published_at);

with explainer_seed (topic_code, title, core_idea, what_students_need_to_understand, how_this_becomes_points, answer_move, mini_example_question, weak_answer, point_attaining_answer, common_point_loss, practice_bridge) as (
  values
  ('10.1', 'Defining Convergent and Divergent Infinite Series',
   'A series is about accumulated sums, while a sequence is about individual terms.',
   'Students need to separate the limit of terms from the limit of partial sums. A term limit that is not zero proves divergence, but a zero term limit does not prove convergence.',
   'Points come from correct partial-sum language and avoiding overclaiming from term behavior.',
   'Ask what the partial sums do, not just what the individual terms do.',
   'If a_n approaches 0, must sum a_n converge?',
   'Yes, because the terms disappear.',
   'No. Terms approaching 0 is necessary but not sufficient; the partial sums must approach a finite value.',
   'Saying a series converges just because its terms approach zero.',
   'Back in practice, write partial sums before naming convergence.'),
  ('10.2', 'Working with Geometric Series',
   'Geometric series convergence is completely controlled by the common ratio.',
   'Students need to identify the first term and ratio from the actual series form. The formula is not a general shortcut for every repeated-looking sum.',
   'Points come from ratio identification, condition check, and correct formula use.',
   'Find the common ratio first; if |r|<1, use a/(1-r). If not, state that the infinite series diverges.',
   'For 5+5/2+5/4+..., what are a and r?',
   'a=5 and r=2 because denominators double.',
   'a=5 and r=1/2, since each term is multiplied by 1/2 to get the next term.',
   'Using the sum formula when |r| is greater than or equal to 1.',
   'Using the sum formula when |r| is greater than or equal to 1.'),
  ('10.3', 'The nth-Term Test for Divergence',
   'The nth-term test is one-directional: it detects divergence but never proves convergence.',
   'Students need to know what the test can and cannot say. A zero term limit simply means another convergence test is needed.',
   'Points come from the correct limit and the correct limited conclusion.',
   'Compute the term limit first; if it is not zero or does not exist, conclude the series diverges.',
   'If lim a_n = 0, what does the nth-term test prove?',
   'It proves the series converges.',
   'It proves nothing by itself about convergence; another test is needed.',
   'Concluding convergence from a zero term limit.',
   'Concluding convergence from a zero term limit.'),
  ('10.4', 'Integral Test for Convergence',
   'The integral test transfers convergence behavior between a series and a related improper integral.',
   'Students need to verify the hypotheses before trusting the conclusion. The integral value is usually less important than whether the integral converges.',
   'Points come from conditions, setup, and correct convergence link.',
   'Confirm positive and decreasing behavior before using the improper integral.',
   'Why is it not enough to write an integral that looks like the series?',
   'The integral automatically decides any series.',
   'The integral test requires a positive decreasing function matching the terms; without those conditions, the conclusion is not justified.',
   'Using the integral test without checking that the function is positive and decreasing.',
   'Using the integral test without checking that the function is positive and decreasing.'),
  ('10.5', 'Harmonic Series and p-Series',
   'Harmonic and p-series are benchmark behaviors, not just names to memorize.',
   'Students need to distinguish literal identity from comparison or limit comparison. A shifted or scaled harmonic-like series may diverge because it behaves like the harmonic series, not because it is literally the same series.',
   'Points come from identifying p and explaining the convergence threshold.',
   'Rewrite the term to identify p, then compare p with 1 before concluding.',
   'Does sum 3/(n+1) equal the harmonic series?',
   'Yes, it is exactly the harmonic series.',
   'No. It is not literally sum 1/n, but it diverges by comparison or limit comparison to the harmonic series.',
   'Calling every constant multiple or shifted harmonic-like series exactly the harmonic series instead of comparing it appropriately.',
   'Calling every constant multiple or shifted harmonic-like series exactly the harmonic series instead of comparing it appropriately.'),
  ('10.6', 'Comparison Tests for Convergence',
   'Comparison tests are about positive-term size relationships to known series.',
   'Students need to match both the benchmark and the inequality direction to the intended conclusion. For mixed signs, consider absolute values if testing absolute convergence.',
   'Points come from positive-term conditions, benchmark choice, and valid direction.',
   'First confirm positive terms; then choose a benchmark with known behavior and compare in the direction that supports the conclusion.',
   'Why is direct comparison risky for an alternating series?',
   'Alternating signs make convergence automatic.',
   'Comparison tests are for positive terms; for mixed signs, use absolute values or another appropriate test.',
   'Using a comparison test directly on an alternating or mixed-sign series.',
   'Using a comparison test directly on an alternating or mixed-sign series.'),
  ('10.7', 'Alternating Series Test for Convergence',
   'Alternation alone does not guarantee convergence; the magnitudes must shrink to zero.',
   'Students need to verify all conditions, not just notice a factor like (-1)^n. Missing the zero-limit or decreasing condition breaks the test.',
   'Points come from the three checks and a conclusion tied to them.',
   'Check the sign pattern, the decreasing absolute values, and the zero limit in that order.',
   'Does (-1)^n * n/(n+1) pass the alternating series test?',
   'Yes, because the signs alternate.',
   'No. The magnitudes approach 1, not 0, so the alternating series test conditions are not met.',
   'Using the alternating series test when magnitudes do not decrease to zero.',
   'Using the alternating series test when magnitudes do not decrease to zero.'),
  ('10.8', 'Ratio Test for Convergence',
   'The ratio test is powerful for factorials and exponentials but inconclusive at limit 1.',
   'Students need to remember both the interpretation and the boundary of assessed methods. If the ratio limit equals 1, the test gives no conclusion.',
   'Points come from correct ratio setup, limit evaluation, and correct inconclusive language when needed.',
   'Form |a_{n+1}/a_n|, take the limit, and interpret the result against 1.',
   'If the ratio-test limit is 1, what should you conclude?',
   'The series converges because the ratio is not greater than 1.',
   'The ratio test is inconclusive at 1, so another assessed test is needed.',
   'Using the root test or treating ratio limit 1 as convergence.',
   'Using the root test or treating ratio limit 1 as convergence.'),
  ('10.9', 'Absolute and Conditional Convergence',
   'Absolute and conditional convergence are two different strengths of convergence.',
   'Students need both parts for conditional convergence. Absolute convergence is stronger and implies ordinary convergence; conditional convergence requires a separate argument for the original series.',
   'Points come from clear absolute-value testing and precise final classification.',
   'Test the absolute-value series, then test the original series if the absolute-value series diverges.',
   'What must be true for conditional convergence?',
   'The absolute-value series must converge.',
   'The original series must converge, but the absolute-value series must diverge.',
   'Claiming conditional convergence without showing the original converges and the absolute-value series diverges.',
   'Claiming conditional convergence without showing the original converges and the absolute-value series diverges.'),
  ('10.10', 'Alternating Series Error Bound',
   'For qualifying alternating series, the next unused term controls the maximum possible error.',
   'Students need to connect the approximation S_n to term n+1, not to term n. The bound is an inequality about error size, not an exact error value.',
   'Points come from the correct omitted term and at most language.',
   'After choosing the partial sum, find the next term not included and use its absolute value as the error bound.',
   'If S_4 is used, which term bounds the alternating-series error?',
   'The fourth term, because it was the last term used.',
   'The fifth term bounds the error because it is the first omitted term. Use its magnitude.',
   'Using the last included term instead of the first omitted term.',
   'Using the last included term instead of the first omitted term.'),
  ('10.11', 'Taylor Polynomial Approximations of Functions',
   'Taylor polynomials are local approximations organized by derivative data at a center.',
   'Students need to keep the center in every term. A polynomial centered at a is written in powers of x-a, not automatically powers of x.',
   'Points come from coefficient formula, center, degree, and substitution.',
   'Build terms from f^(n)(a)/n! times (x-a)^n, keeping the center visible.',
   'For a Taylor polynomial centered at x=2, should the terms use x or x-2?',
   'Use x because x is the variable.',
   'Use powers of x-2 because the polynomial is centered at 2.',
   'Using powers of x when the polynomial is centered at a nonzero a.',
   'Using powers of x when the polynomial is centered at a nonzero a.'),
  ('10.12', 'Lagrange Error Bound',
   'A Lagrange bound is an upper limit on error, not the exact error.',
   'Students need to use the next derivative beyond the Taylor polynomial degree and communicate the result as a maximum possible error. The connection point can be lost if the inequality meaning is missing.',
   'Points come from correct form and the at most conclusion.',
   'Identify the next derivative and maximum bound M, compute M/(n+1)! times |x-a|^(n+1), then state an inequality.',
   'If a Lagrange calculation gives 0.01, what should the conclusion say?',
   'The error equals 0.01.',
   'The error is at most 0.01, or <= 0.01. The bound is a maximum, not necessarily the exact error.',
   'Saying the error equals the bound instead of is at most the bound.',
   'Saying the error equals the bound instead of is at most the bound.'),
  ('10.13', 'Radius and Interval of Convergence of Power Series',
   'Radius and interval are related but not interchangeable: radius is a distance, interval is a set of x-values after endpoint testing.',
   'Students need to keep the interval centered correctly and test endpoints one at a time. Arithmetic that shifts the center incorrectly changes the whole answer.',
   'Points come from ratio setup, limit, open interval, endpoint consideration, and final interval.',
   'Find the center and radius, write the open interval, then test each endpoint with an assessed convergence test.',
   'If a power series centered at 4 has radius 3, what open interval comes before endpoint testing?',
   '-3 < x < 3.',
   'The open interval is 1 < x < 7 because the radius extends 3 units from center 4.',
   'Reporting only the radius or open interval without endpoint analysis.',
   'Reporting only the radius or open interval without endpoint analysis.'),
  ('10.14', 'Taylor and Maclaurin Series for a Function',
   'Taylor and Maclaurin series extend polynomial approximation into infinite representation.',
   'Students need accurate foundational series before manipulating them. A small sign or factorial error can change every later term.',
   'Points come from the correct base series and valid transformation into the requested function.',
   'Start from a known foundational series, then substitute, multiply, differentiate, or integrate term by term as allowed.',
   'What is the center of a Maclaurin series?',
   'It can be any value a.',
   'A Maclaurin series is centered at 0; Taylor series is the broader term for center a.',
   'Misremembering the signs or factorials in the foundational Maclaurin series.',
   'Misremembering the signs or factorials in the foundational Maclaurin series.'),
  ('10.15', 'Representing Functions as Power Series',
   'A power-series representation includes both the series formula and where it converges to the function.',
   'Students need to track convergence restrictions through substitutions and transformations. The algebraic match alone is incomplete without the valid x-values.',
   'Points come from parent-series choice, correct transformed terms, and convergence interval.',
   'Identify the parent series first, transform the function to match it, then update the interval or radius of convergence.',
   'When using 1/(1-x)=sum x^n to represent 1/(1+3x), what substitution is natural?',
   'Use x=3x because the denominator has 3x.',
   'Use x replaced by -3x, since 1/(1+3x)=1/(1-(-3x)).',
   'Finding a correct series expression but omitting the interval of convergence.',
   'Finding a correct series expression but omitting the interval of convergence.')
)
insert into app.topic_explainers (subject_key, unit_number, topic_code, title, core_idea, what_students_need_to_understand, how_this_becomes_points, answer_move, mini_example_question, weak_answer, point_attaining_answer, common_point_loss, practice_bridge, status, source_note, published_at)
select 'ap_calculus_bc', 10, topic_code, title, core_idea, what_students_need_to_understand, how_this_becomes_points, answer_move, mini_example_question, weak_answer, point_attaining_answer, common_point_loss, practice_bridge, 'published', 'cramapple-authored; new coverage 2026-08-26 for AP Calculus BC Unit 10 Infinite Sequences and Series; grounded in AP_CALCULUS_AB_BC_CED_FACT_PACK.md Unit 10 deep-tier detail: BC-only 15-20% weighting, geometric series formula, closed assessed convergence-test list, absolute versus conditional convergence, alternating series error bound, Taylor polynomial coefficients, Lagrange error-bound inequality language, radius and interval of convergence endpoint testing, and Taylor/Maclaurin series representation with lower-confidence guidance for 10.14-10.15; batch 2026-08-26-ap-calculus-bc-unit10-topic-guides; author=reviewer same session, no independent human review yet', now()
from explainer_seed
on conflict (subject_key, topic_code) do update set unit_number=excluded.unit_number, title=excluded.title, core_idea=excluded.core_idea, what_students_need_to_understand=excluded.what_students_need_to_understand, how_this_becomes_points=excluded.how_this_becomes_points, answer_move=excluded.answer_move, mini_example_question=excluded.mini_example_question, weak_answer=excluded.weak_answer, point_attaining_answer=excluded.point_attaining_answer, common_point_loss=excluded.common_point_loss, practice_bridge=excluded.practice_bridge, status=excluded.status, source_note=excluded.source_note, published_at=coalesce(app.topic_explainers.published_at, excluded.published_at);

do $$
declare v_briefs integer; v_explainers integer; v_pairing_orphans integer; v_unit_mismatches integer; v_route_mismatches integer; v_core_matches integer; v_duplicate_explainer_fields integer;
begin
  select count(*) into v_briefs from app.topic_point_briefs where subject_key='ap_calculus_bc' and unit_number=10 and topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and status='published';
  if v_briefs <> 15 then raise exception 'expected 15 published AP Calculus BC Unit 10 briefs, got %', v_briefs; end if;
  select count(*) into v_explainers from app.topic_explainers where subject_key='ap_calculus_bc' and unit_number=10 and topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and status='published';
  if v_explainers <> 15 then raise exception 'expected 15 published AP Calculus BC Unit 10 explainers, got %', v_explainers; end if;
  select count(*) into v_pairing_orphans from (select b.subject_key,b.topic_code from app.topic_point_briefs b left join app.topic_explainers e on e.subject_key=b.subject_key and e.topic_code=b.topic_code and e.status='published' where b.subject_key='ap_calculus_bc' and b.unit_number=10 and b.topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and b.status='published' and e.topic_code is null union all select e.subject_key,e.topic_code from app.topic_explainers e left join app.topic_point_briefs b on b.subject_key=e.subject_key and b.topic_code=e.topic_code and b.status='published' where e.subject_key='ap_calculus_bc' and e.unit_number=10 and e.topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and e.status='published' and b.topic_code is null) orphans;
  if v_pairing_orphans <> 0 then raise exception 'expected 0 AP Calculus BC Unit 10 pairing orphans, got %', v_pairing_orphans; end if;
  select count(*) into v_unit_mismatches from app.topic_point_briefs b join app.topic_explainers e on e.subject_key=b.subject_key and e.topic_code=b.topic_code where b.subject_key='ap_calculus_bc' and b.topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and b.status='published' and e.status='published' and b.unit_number<>e.unit_number;
  if v_unit_mismatches <> 0 then raise exception 'expected 0 AP Calculus BC Unit 10 unit mismatches, got %', v_unit_mismatches; end if;
  select count(*) into v_route_mismatches from app.topic_point_briefs b where b.subject_key='ap_calculus_bc' and b.unit_number=10 and b.topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and b.status='published' and (b.practice_subject_key<>b.subject_key or b.practice_unit_number<>b.unit_number or b.practice_topic_code<>b.topic_code or b.learn_more_path not like '/learn/ap-calculus-bc/unit-10/%');
  if v_route_mismatches <> 0 then raise exception 'expected 0 AP Calculus BC Unit 10 route mismatches, got %', v_route_mismatches; end if;
  select count(*) into v_core_matches from app.topic_point_briefs b join app.topic_explainers e on e.subject_key=b.subject_key and e.topic_code=b.topic_code where b.subject_key='ap_calculus_bc' and b.topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and b.status='published' and e.status='published' and e.core_idea=b.what_it_is;
  if v_core_matches <> 0 then raise exception 'expected 0 AP Calculus BC Unit 10 core_idea/what_it_is matches, got %', v_core_matches; end if;
  with new_explainers as (select topic_explainer_id, mini_example_question, weak_answer, point_attaining_answer, practice_bridge from app.topic_explainers where subject_key='ap_calculus_bc' and unit_number=10 and topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15') and status='published'), field_values as (select 'mini_example_question' field_name, mini_example_question value from new_explainers union all select 'weak_answer', weak_answer from new_explainers union all select 'point_attaining_answer', point_attaining_answer from new_explainers union all select 'practice_bridge', practice_bridge from new_explainers) select count(*) into v_duplicate_explainer_fields from field_values fv join app.topic_explainers e on (e.mini_example_question=fv.value or e.weak_answer=fv.value or e.point_attaining_answer=fv.value or e.practice_bridge=fv.value) where e.status='published' and not (e.subject_key='ap_calculus_bc' and e.unit_number=10 and e.topic_code in ('10.1', '10.2', '10.3', '10.4', '10.5', '10.6', '10.7', '10.8', '10.9', '10.10', '10.11', '10.12', '10.13', '10.14', '10.15'));
  if v_duplicate_explainer_fields <> 0 then raise exception 'expected 0 AP Calculus BC Unit 10 duplicate explainer fields, got %', v_duplicate_explainer_fields; end if;
end $$;

commit;
