-- Backfill: local migration file for the AP Statistics difficulty load
-- already applied to Production 2026-09-25 via the Supabase MCP tool, in 5
-- batches (load_apstats_difficulty_batch1 through batch5, tracked only in
-- Supabase's own migration history until now). Reconstructed from a fresh
-- Production query per docs/product/TIER3_PAIR1_STATUS_2026_09_25.md.
--
-- 170 rows, all basis 'calibrated_judgement' (no attainment ratio anchor for
-- this method), proposal_run 'apstats_structural_difficulty_2026_09_25',
-- covering all live-pack AP Statistics items whose item-and-current-version
-- status was both `published` at the time of the run. 23 live-pack items had
-- no row in the source CSV and remain undifficultied -- a known, reported
-- gap, not touched by this migration.
--
-- Idempotent: the table has a unique constraint on content_item_version_id,
-- so `on conflict do nothing` makes a re-run against Production (where these
-- rows already exist) a no-op; running against Dev (where they mostly do
-- not exist) seeds the same rows there for whichever items exist in Dev.

begin;

insert into app.content_item_difficulty (
  content_item_version_id, difficulty, basis, rationale, proposal_run
)
select cur.id, v.difficulty, 'calibrated_judgement', v.rationale,
       'apstats_structural_difficulty_2026_09_25'
from (values
  ('APSTAT-MOD3-E002','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTAT-MOD3-H001-INV','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTAT-MOD4-H001-INV','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTAT-MOD4-M001','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTAT-MOD5-H001-INV','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTAT-MOD5-M001','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTAT-MOD6-H001','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTAT-MOD6-H002-INV','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTAT-MOD6-M002','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTAT-MOD7-H002-INV','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-001','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 Unit 1-2 (exploring data))'),
  ('apstats-frq-u12-002','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-003','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('apstats-frq-u12-004','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('apstats-frq-u12-005','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('apstats-frq-u12-006','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-007','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-008','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-009','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-010','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-011','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-012','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('apstats-frq-u12-013','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-014','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-015','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-016','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-017','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('apstats-frq-u12-018','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('apstats-frq-u12-019','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('apstats-frq-u12-020','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-HDG-2026-GRAPH-003','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-HDG-2026-GRAPH-005','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-007','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-008','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-HDG-2026-GRAPH-010','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-013','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-014','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-015','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-016','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-017','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-018','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-019','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-020','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-023','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-025','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-027','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-028','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-030','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-031','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-HDG-2026-GRAPH-033','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-001','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-001-CAL','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-002','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-003-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-004','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-004-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-005','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-005-CAL','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-006','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 3 base tier)'),
  ('APSTATS-MCQ-006-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 3 base tier)'),
  ('APSTATS-MCQ-008-CAL','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-009','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-009-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-010-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-011','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-011-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-013','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-013-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-014','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-014-CAL','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-016-CAL','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-018-CAL','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-019','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-020','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-021','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-022','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-023','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-024','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-025','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-026','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-027','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-028','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-029','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-030','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-031','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-032','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-033','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-034','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-035','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-036','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-037','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 3 base tier)'),
  ('APSTATS-MCQ-038','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-039','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-040','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 3 base tier)'),
  ('APSTATS-MCQ-041','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-042','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-043','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-044','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-045','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-046','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-047','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-048','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-049','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-050','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-051','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-052','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-053','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-054','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-055','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-056','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-057','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-058','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-059','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-060','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-061','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-062','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-063','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-064','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-065','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-066','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-067','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 6 base tier)'),
  ('APSTATS-MCQ-068','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-069','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 6 base tier)'),
  ('APSTATS-MCQ-070','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-071','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 6 base tier)'),
  ('APSTATS-MCQ-072','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-073','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-074','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-075','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-076','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-078','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-079','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-080','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-081','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-082','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-083','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-084','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-085','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-087','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-088','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-090','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-MCQ-091','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-092','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-093','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-MCQ-094','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-095','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 9 base tier)'),
  ('APSTATS-MCQ-096','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-097','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, unit 9 base tier)'),
  ('APSTATS-MCQ-098','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-099','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-MCQ-100','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-SFRQ-001','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-SFRQ-002','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-SFRQ-003','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-004','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-005','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-SFRQ-007','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-SFRQ-008','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('APSTATS-SFRQ-009','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-010','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-011','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-012','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-013','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('APSTATS-SFRQ-014','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('APSTATS-SFRQ-016','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('STATS-MOD1-E002','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('STATS-MOD1-E003','Easy','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C1 summary statistic, display reading, or vocabulary)'),
  ('STATS-MOD1-M001','Hard','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C3 probability/simulation, design flaw, or synthesis)'),
  ('STATS-MOD3-M007','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)'),
  ('STATS-MOD4-E005','Medium','AP Statistics structural difficulty framework (docs/research/apbio_difficulty_calibration_2026_09_22/STATISTICS_AND_CHEMISTRY.md, C2 inference procedure, design, or routine interpretation)')) as v(content_key, difficulty, rationale)
join app.content_items ci on ci.content_key = v.content_key
join lateral (
  select id from app.content_item_versions cv
  where cv.content_item_id = ci.id
  order by cv.version_num desc
  limit 1
) cur on true
on conflict (content_item_version_id) do nothing;

-- Verification:
--   select count(*) from app.content_item_difficulty
--     where proposal_run = 'apstats_structural_difficulty_2026_09_25';  -- expect 170

commit;
