begin;

-- Seed topic point briefs for the third unit of every currently seeded
-- subject. Physics 2 and Physics C: E&M use official continuous unit
-- numbering, so their third course units are Unit 11 and Unit 10.
--
-- Companion draft doc:
--   docs/product/AP_ALL_SUBJECTS_UNIT3_TOPIC_POINT_BRIEFS.md

with brief_seed (
  subject_key, unit_number, topic_code, title, unit_title,
  class_importance, exam_importance, key_move, common_point_loss, slug
) as (
  values
  ($$ap_biology$$,3,$$3.1$$,$$Enzymes$$,$$Cellular Energetics$$,$$very-important$$,$$very-important$$,$$explain how enzyme shape and substrate fit lower activation energy and increase reaction rate without being consumed$$,$$Saying enzymes add energy to a reaction instead of lowering the activation-energy barrier$$,$$enzymes$$),
  ($$ap_biology$$,3,$$3.2$$,$$Environmental Impacts on Enzyme Function$$,$$Cellular Energetics$$,$$very-important$$,$$very-important$$,$$connect temperature, pH, substrate concentration, or inhibitor type to active-site shape and enzyme activity$$,$$Treating every inhibitor as competitive, even when the prompt describes binding away from the active site$$,$$environmental-impacts-on-enzyme-function$$),
  ($$ap_biology$$,3,$$3.3$$,$$Cellular Energy$$,$$Cellular Energetics$$,$$very-important$$,$$somewhat-important$$,$$describe energy input, energy loss, and pathway sequencing in living systems without invoking the Gibbs free-energy equation$$,$$Describing a metabolic pathway as one isolated reaction instead of linked steps where one product becomes the next reactant$$,$$cellular-energy$$),
  ($$ap_biology$$,3,$$3.4$$,$$Photosynthesis$$,$$Cellular Energetics$$,$$very-important$$,$$very-important$$,$$trace light energy to excited electrons, a proton gradient, ATP and NADPH, then carbohydrate production$$,$$Memorizing Calvin-cycle details that are out of scope while missing the light-reaction energy-transfer chain$$,$$photosynthesis$$),
  ($$ap_biology$$,3,$$3.5$$,$$Cellular Respiration$$,$$Cellular Energetics$$,$$very-important$$,$$very-important$$,$$trace glucose energy through glycolysis, Krebs-cycle electron carriers, the ETC, the proton gradient, and ATP synthase$$,$$Claiming oxygen directly makes ATP instead of serving as the final electron acceptor in aerobic respiration$$,$$cellular-respiration$$),

  ($$ap_chemistry$$,3,$$3.1$$,$$Intermolecular and Interparticle Forces$$,$$Properties of Substances and Mixtures$$,$$very-important$$,$$very-important$$,$$identify the strongest relevant interaction and justify it from polarity, size, charge, or hydrogen-bonding requirements$$,$$Using hydrogen bonding for any molecule containing hydrogen, even when H is not bonded to N, O, or F$$,$$intermolecular-and-interparticle-forces$$),
  ($$ap_chemistry$$,3,$$3.2$$,$$Properties of Solids$$,$$Properties of Substances and Mixtures$$,$$very-important$$,$$very-important$$,$$classify the solid type and explain melting point, conductivity, brittleness, or malleability from its particle-level structure$$,$$Calling an ionic solid conductive as a solid, when its ions are fixed in the lattice$$,$$properties-of-solids$$),
  ($$ap_chemistry$$,3,$$3.3$$,$$Solids, Liquids, and Gases$$,$$Properties of Substances and Mixtures$$,$$somewhat-important$$,$$somewhat-important$$,$$compare particle spacing, motion, and order across phases while avoiding phase-diagram interpretation$$,$$Explaining a phase using only shape and volume instead of particle motion and spacing$$,$$solids-liquids-and-gases$$),
  ($$ap_chemistry$$,3,$$3.4$$,$$Ideal Gas Law$$,$$Properties of Substances and Mixtures$$,$$very-important$$,$$very-important$$,$$choose PV=nRT or Dalton's law, convert units consistently, and relate partial pressure to mole fraction$$,$$Using Celsius in PV=nRT or mixing pressure units with the wrong gas constant$$,$$ideal-gas-law$$),
  ($$ap_chemistry$$,3,$$3.5$$,$$Kinetic Molecular Theory$$,$$Properties of Substances and Mixtures$$,$$very-important$$,$$very-important$$,$$connect Kelvin temperature to average kinetic energy and use Maxwell-Boltzmann curves to compare particle-speed distributions$$,$$Saying heavier gas particles have greater average kinetic energy at the same temperature$$,$$kinetic-molecular-theory$$),
  ($$ap_chemistry$$,3,$$3.6$$,$$Deviation from Ideal Gas Law$$,$$Properties of Substances and Mixtures$$,$$somewhat-important$$,$$somewhat-important$$,$$explain real-gas deviations from attractions at low temperature or particle volume at high pressure$$,$$Treating all gases as most ideal at high pressure and low temperature$$,$$deviation-from-ideal-gas-law$$),
  ($$ap_chemistry$$,3,$$3.7$$,$$Solutions and Mixtures$$,$$Properties of Substances and Mixtures$$,$$very-important$$,$$very-important$$,$$distinguish homogeneous from heterogeneous mixtures and calculate molarity from moles of solute per liter of solution$$,$$Using liters of solvent instead of liters of final solution for molarity$$,$$solutions-and-mixtures$$),
  ($$ap_chemistry$$,3,$$3.8$$,$$Representations of Solutions$$,$$Properties of Substances and Mixtures$$,$$somewhat-important$$,$$somewhat-important$$,$$interpret particulate diagrams for relative concentration and solute-solvent interactions without using excluded colligative-property calculations$$,$$Counting drawn particles without checking whether the diagram represents equal volumes$$,$$representations-of-solutions$$),
  ($$ap_chemistry$$,3,$$3.9$$,$$Separation of Solutions and Mixtures$$,$$Properties of Substances and Mixtures$$,$$somewhat-important$$,$$somewhat-important$$,$$choose a separation method by the property that differs, especially filtration versus chromatography by interaction strength$$,$$Trying to separate dissolved solute from solution by ordinary filtration$$,$$separation-of-solutions-and-mixtures$$),
  ($$ap_chemistry$$,3,$$3.10$$,$$Solubility$$,$$Properties of Substances and Mixtures$$,$$very-important$$,$$very-important$$,$$predict solubility by comparing the intermolecular forces present in the solute and solvent$$,$$Using the phrase like dissolves like without naming the actual force match or mismatch$$,$$solubility$$),
  ($$ap_chemistry$$,3,$$3.11$$,$$Spectroscopy and the Electromagnetic Spectrum$$,$$Properties of Substances and Mixtures$$,$$somewhat-important$$,$$somewhat-important$$,$$match microwave, infrared, and UV-visible absorption to rotational, vibrational, and electronic transitions$$,$$Treating every absorption spectrum as evidence for electron transitions$$,$$spectroscopy-and-the-electromagnetic-spectrum$$),

  ($$ap_statistics$$,3,$$3.1$$,$$Estimators$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$somewhat-important$$,$$identify the statistic as an estimator of a population parameter and explain unbiasedness as no systematic over- or underestimation$$,$$Calling one sample result biased just because it is not exactly equal to the parameter$$,$$estimators$$),
  ($$ap_statistics$$,3,$$3.2$$,$$Sampling Distributions for Sample Proportions$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$state the mean and standard deviation of p-hat and check randomization, 10 percent, and large-counts conditions$$,$$Checking large counts with observed p-hat when the sampling distribution is built from the true p$$,$$sampling-distributions-for-sample-proportions$$),
  ($$ap_statistics$$,3,$$3.3$$,$$Constructing a Confidence Interval for a Population Proportion$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$compute a one-proportion z interval with p-hat in the standard error and verify conditions before interpreting$$,$$Using p0 from a test in the confidence-interval standard error$$,$$constructing-a-confidence-interval-for-a-population-proportion$$),
  ($$ap_statistics$$,3,$$3.4$$,$$Justifying a Claim Based on a Confidence Interval for a Population Proportion$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$decide whether a claimed parameter value is plausible by checking whether it lies inside the interval$$,$$Saying there is a certain probability the fixed parameter is inside this already-computed interval$$,$$justifying-a-claim-based-on-a-confidence-interval-for-a-population-proportion$$),
  ($$ap_statistics$$,3,$$3.5$$,$$Setting Up a Test for a Population Proportion$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$define p in context, write H0 and Ha with p, and choose the correct one- or two-sided alternative$$,$$Writing hypotheses about x, p-hat, or sample counts instead of the population proportion p$$,$$setting-up-a-test-for-a-population-proportion$$),
  ($$ap_statistics$$,3,$$3.6$$,$$p-Values$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$interpret the p-value as the chance of a result at least as extreme, assuming the null hypothesis is true$$,$$Interpreting the p-value as the probability that the null hypothesis is true$$,$$p-values$$),
  ($$ap_statistics$$,3,$$3.7$$,$$Carrying Out a Test for a Population Proportion$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$check conditions with p0, compute the z statistic using p0 in the standard error, and make a contextual conclusion$$,$$Putting p-hat under the radical in a one-proportion test statistic$$,$$carrying-out-a-test-for-a-population-proportion$$),
  ($$ap_statistics$$,3,$$3.8$$,$$Potential Errors When Performing Tests$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$define Type I and Type II errors with conditional framing and relate significance level to Type I error rate$$,$$Describing a Type I error without the phrase or idea that the null hypothesis is actually true$$,$$potential-errors-when-performing-tests$$),
  ($$ap_statistics$$,3,$$3.9$$,$$Sampling Distributions for the Difference Between Sample Proportions$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$state the center and standard deviation of p-hat1 minus p-hat2 and check conditions for both samples$$,$$Checking only one sample's large-counts condition in a two-proportion setting$$,$$sampling-distributions-for-the-difference-between-sample-proportions$$),
  ($$ap_statistics$$,3,$$3.10$$,$$Constructing a Confidence Interval for the Difference Between Two Population Proportions$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$build an unpooled two-proportion z interval and interpret it as an interval for p1 minus p2$$,$$Pooling the sample proportions in a confidence interval, which is only for the corresponding test$$,$$constructing-a-confidence-interval-for-the-difference-between-two-population-proportions$$),
  ($$ap_statistics$$,3,$$3.11$$,$$Justifying a Claim Based on a Confidence Interval for the Difference Between Two Population Proportions$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$use whether zero is inside the interval to support or reject a claim of difference$$,$$Concluding one group is larger when the interval includes zero$$,$$justifying-a-claim-based-on-a-confidence-interval-for-the-difference-between-two-population-proportions$$),
  ($$ap_statistics$$,3,$$3.12$$,$$Setting Up a Test for the Difference Between Two Population Proportions$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$define both population proportions, write hypotheses for p1 minus p2, and identify the pooled proportion for the null model$$,$$Forgetting to define which population is p1 and which is p2, making the sign of the alternative unclear$$,$$setting-up-a-test-for-the-difference-between-two-population-proportions$$),
  ($$ap_statistics$$,3,$$3.13$$,$$Carrying Out a Test for the Difference Between Two Population Proportions$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$very-important$$,$$check two-sample conditions with the pooled proportion, compute z, and conclude in context$$,$$Using the unpooled confidence-interval standard error in a two-proportion significance test$$,$$carrying-out-a-test-for-the-difference-between-two-population-proportions$$),
  ($$ap_statistics$$,3,$$3.14$$,$$Setting Up a Chi-Square Test for Homogeneity or Independence$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$somewhat-important$$,$$choose homogeneity or independence from the study design, compute expected counts, and set df from the table dimensions$$,$$Using a goodness-of-fit test when the current Unit 3 scope only includes homogeneity and independence$$,$$setting-up-a-chi-square-test-for-homogeneity-or-independence$$),
  ($$ap_statistics$$,3,$$3.15$$,$$Carrying Out a Chi-Square Test for Homogeneity or Independence$$,$$Inference for Categorical Data: Proportions$$,$$very-important$$,$$somewhat-important$$,$$calculate chi-square contributions from observed and expected counts and interpret the p-value for the categorical association question$$,$$Checking expected counts against 10 instead of the chi-square threshold that all expected counts exceed 5$$,$$carrying-out-a-chi-square-test-for-homogeneity-or-independence$$),

  ($$ap_precalculus$$,3,$$3.1$$,$$Periodic Phenomena$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$identify period, amplitude, midline, and repeated behavior in context without using calculus language$$,$$Confusing frequency with period when translating a periodic context$$,$$periodic-phenomena$$),
  ($$ap_precalculus$$,3,$$3.2$$,$$Sine, Cosine, and Tangent$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$connect unit-circle definitions to sine, cosine, tangent values and graph behavior$$,$$Treating tangent as if it has the same period and asymptotes as sine or cosine$$,$$sine-cosine-and-tangent$$),
  ($$ap_precalculus$$,3,$$3.3$$,$$Sine and Cosine Function Values$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$somewhat-important$$,$$use symmetry, reference angles, and quadrant signs to evaluate sine and cosine$$,$$Getting the reference angle right but assigning the wrong sign for the quadrant$$,$$sine-and-cosine-function-values$$),
  ($$ap_precalculus$$,3,$$3.4$$,$$Sine and Cosine Function Graphs$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$read amplitude, period, midline, extrema, and intercepts from sine and cosine graphs$$,$$Calling the vertical shift the amplitude instead of measuring amplitude from midline to maximum$$,$$sine-and-cosine-function-graphs$$),
  ($$ap_precalculus$$,3,$$3.5$$,$$Sinusoidal Functions$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$select a sine or cosine model from graph or context features and justify parameter choices$$,$$Choosing a cosine model by habit when the starting value and direction fit sine more naturally$$,$$sinusoidal-functions$$),
  ($$ap_precalculus$$,3,$$3.6$$,$$Sinusoidal Function Transformations$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$interpret a, b, c, and d in transformed sine or cosine forms as amplitude, period, phase shift, and midline$$,$$Using b as the period instead of converting period to 2pi divided by absolute b$$,$$sinusoidal-function-transformations$$),
  ($$ap_precalculus$$,3,$$3.7$$,$$Sinusoidal Function Context and Data Modeling$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$fit sinusoidal parameters to contextual data and state what each parameter means in units$$,$$Reporting a model without connecting the midline, amplitude, or period back to the context$$,$$sinusoidal-function-context-and-data-modeling$$),
  ($$ap_precalculus$$,3,$$3.8$$,$$The Tangent Function$$,$$Trigonometric and Polar Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$use tangent's period, zeros, and vertical asymptotes to graph or transform it$$,$$Using 2pi as tangent's base period instead of pi$$,$$the-tangent-function$$),
  ($$ap_precalculus$$,3,$$3.9$$,$$Inverse Trigonometric Functions$$,$$Trigonometric and Polar Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$apply the restricted ranges for inverse sine, inverse cosine, and inverse tangent$$,$$Returning an angle outside the principal range for the inverse trig function$$,$$inverse-trigonometric-functions$$),
  ($$ap_precalculus$$,3,$$3.10$$,$$Trigonometric Equations and Inequalities$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$solve using unit-circle values, periodicity, and interval restrictions, then report all solutions in the domain$$,$$Finding one solution and forgetting the second or repeated solutions in the required interval$$,$$trigonometric-equations-and-inequalities$$),
  ($$ap_precalculus$$,3,$$3.11$$,$$The Secant, Cosecant, and Cotangent Functions$$,$$Trigonometric and Polar Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$use reciprocal relationships to evaluate and graph secant, cosecant, and cotangent features$$,$$Treating reciprocal trig functions as inverse trig functions$$,$$secant-cosecant-and-cotangent-functions$$),
  ($$ap_precalculus$$,3,$$3.12$$,$$Equivalent Representations of Trigonometric Functions$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$use Pythagorean and sum identities to rewrite expressions into useful equivalent forms$$,$$Applying an identity in a way that changes the domain or loses a sign condition$$,$$equivalent-representations-of-trigonometric-functions$$),
  ($$ap_precalculus$$,3,$$3.13$$,$$Trigonometry and Polar Coordinates$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$very-important$$,$$convert between rectangular and polar coordinates using r, theta, x, and y relationships$$,$$Using arctangent without adjusting theta for the quadrant$$,$$trigonometry-and-polar-coordinates$$),
  ($$ap_precalculus$$,3,$$3.14$$,$$Polar Function Graphs$$,$$Trigonometric and Polar Functions$$,$$very-important$$,$$somewhat-important$$,$$interpret polar graphs by relating signed radius and angle to location and repeated behavior$$,$$Plotting negative r as if it were positive at the same angle$$,$$polar-function-graphs$$),
  ($$ap_precalculus$$,3,$$3.15$$,$$Rates of Change in Polar Functions$$,$$Trigonometric and Polar Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$compute and interpret average rate of change of signed radius with respect to angle$$,$$Using derivative or instantaneous-rate language in a Precalculus polar-rate question$$,$$rates-of-change-in-polar-functions$$),

  ($$ap_calculus_ab$$,3,$$3.1$$,$$The Chain Rule$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$very-important$$,$$identify the outer and inner functions and multiply by the derivative of the inside$$,$$Differentiating the outside correctly but forgetting the inner derivative$$,$$the-chain-rule$$),
  ($$ap_calculus_ab$$,3,$$3.2$$,$$Implicit Differentiation$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$very-important$$,$$differentiate both sides with respect to x, attach dy/dx to every y-term, and solve for dy/dx when needed$$,$$Differentiating y-terms as if y were the independent variable$$,$$implicit-differentiation$$),
  ($$ap_calculus_ab$$,3,$$3.3$$,$$Differentiating Inverse Functions$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$use the reciprocal-slope relationship between a function and its inverse at corresponding points$$,$$Taking the reciprocal of the wrong derivative value because the x- and y-coordinates were not swapped$$,$$differentiating-inverse-functions$$),
  ($$ap_calculus_ab$$,3,$$3.4$$,$$Differentiating Inverse Trigonometric Functions$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$apply inverse-trig derivative formulas with chain rule and domain restrictions$$,$$Using the derivative of sine, cosine, or tangent instead of the inverse-trig derivative formula$$,$$differentiating-inverse-trigonometric-functions$$),
  ($$ap_calculus_ab$$,3,$$3.5$$,$$Selecting Procedures for Calculating Derivatives$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$very-important$$,$$choose among product, quotient, chain, implicit, inverse, and inverse-trig procedures based on structure$$,$$Using the product rule on a composition that needs the chain rule$$,$$selecting-procedures-for-calculating-derivatives$$),
  ($$ap_calculus_ab$$,3,$$3.6$$,$$Calculating Higher-Order Derivatives$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$somewhat-important$$,$$differentiate repeatedly and interpret second derivatives as rates of change of rates when asked$$,$$Stopping after the first derivative when the question asks for acceleration or concavity$$,$$calculating-higher-order-derivatives$$),

  ($$ap_calculus_bc$$,3,$$3.1$$,$$The Chain Rule$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$very-important$$,$$identify the outer and inner functions and multiply by the derivative of the inside$$,$$Differentiating the outside correctly but forgetting the inner derivative$$,$$the-chain-rule$$),
  ($$ap_calculus_bc$$,3,$$3.2$$,$$Implicit Differentiation$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$very-important$$,$$differentiate both sides with respect to x, attach dy/dx to every y-term, and solve for dy/dx when needed$$,$$Differentiating y-terms as if y were the independent variable$$,$$implicit-differentiation$$),
  ($$ap_calculus_bc$$,3,$$3.3$$,$$Differentiating Inverse Functions$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$use the reciprocal-slope relationship between a function and its inverse at corresponding points$$,$$Taking the reciprocal of the wrong derivative value because the x- and y-coordinates were not swapped$$,$$differentiating-inverse-functions$$),
  ($$ap_calculus_bc$$,3,$$3.4$$,$$Differentiating Inverse Trigonometric Functions$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$somewhat-important$$,$$somewhat-important$$,$$apply inverse-trig derivative formulas with chain rule and domain restrictions$$,$$Using the derivative of sine, cosine, or tangent instead of the inverse-trig derivative formula$$,$$differentiating-inverse-trigonometric-functions$$),
  ($$ap_calculus_bc$$,3,$$3.5$$,$$Selecting Procedures for Calculating Derivatives$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$very-important$$,$$choose among product, quotient, chain, implicit, inverse, and inverse-trig procedures based on structure$$,$$Using the product rule on a composition that needs the chain rule$$,$$selecting-procedures-for-calculating-derivatives$$),
  ($$ap_calculus_bc$$,3,$$3.6$$,$$Calculating Higher-Order Derivatives$$,$$Differentiation: Composite, Implicit, and Inverse Functions$$,$$very-important$$,$$somewhat-important$$,$$differentiate repeatedly and interpret second derivatives as rates of change of rates when asked$$,$$Stopping after the first derivative when the question asks for acceleration or concavity$$,$$calculating-higher-order-derivatives$$),

  ($$ap_physics_1$$,3,$$3.1$$,$$Translational Kinetic Energy$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$compute kinetic energy from mass and speed and recognize that it depends on reference frame$$,$$Using velocity direction to make kinetic energy negative$$,$$translational-kinetic-energy$$),
  ($$ap_physics_1$$,3,$$3.2$$,$$Work$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$find signed work from the force component parallel to displacement or from area under an F-parallel versus displacement graph$$,$$Using total force magnitude when only the parallel component does work$$,$$work$$),
  ($$ap_physics_1$$,3,$$3.3$$,$$Potential Energy$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$choose a system and calculate gravitational or spring potential-energy changes from configuration$$,$$Treating the zero of potential energy as physically fixed instead of chosen for convenience$$,$$potential-energy$$),
  ($$ap_physics_1$$,3,$$3.4$$,$$Conservation of Energy$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$write an initial-energy equals final-energy plus transfer or dissipation equation for the chosen system$$,$$Putting potential energy on a single object instead of on an interacting system$$,$$conservation-of-energy$$),
  ($$ap_physics_1$$,3,$$3.5$$,$$Power$$,$$Work, Energy, and Power$$,$$somewhat-important$$,$$somewhat-important$$,$$relate average power to energy transfer per time and instantaneous power to the parallel force component times speed$$,$$Confusing a large amount of work with large power without considering time$$,$$power$$),

  ($$ap_physics_c_mechanics$$,3,$$3.1$$,$$Translational Kinetic Energy$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$compute kinetic energy as a scalar and keep reference-frame dependence in mind$$,$$Assigning a sign to kinetic energy because velocity has a sign$$,$$translational-kinetic-energy$$),
  ($$ap_physics_c_mechanics$$,3,$$3.2$$,$$Work$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$set up work as a dot product or line integral and reduce to F parallel times displacement when force is constant$$,$$Using constant-force work formulas for a variable force without integrating or using graph area$$,$$work$$),
  ($$ap_physics_c_mechanics$$,3,$$3.3$$,$$Potential Energy$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$connect conservative-force work to changes in potential energy and use slope or derivative relationships when appropriate$$,$$Treating spring potential energy as negative when a spring is compressed$$,$$potential-energy$$),
  ($$ap_physics_c_mechanics$$,3,$$3.4$$,$$Conservation of Energy$$,$$Work, Energy, and Power$$,$$very-important$$,$$very-important$$,$$identify all energy terms in initial and final states before substituting into a conservation equation$$,$$Omitting one spring, gravitational, or kinetic term from the selected system's energy equation$$,$$conservation-of-energy$$),
  ($$ap_physics_c_mechanics$$,3,$$3.5$$,$$Power$$,$$Work, Energy, and Power$$,$$somewhat-important$$,$$somewhat-important$$,$$use average power as energy per time and instantaneous power as dW/dt or force dot velocity$$,$$Using average power when the question asks for instantaneous power at a specific moment$$,$$power$$),

  ($$ap_physics_2$$,11,$$11.1$$,$$Electric Current$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$relate current to charge flow per time and describe conventional current direction without treating current as a vector$$,$$Adding currents like vector components rather than as scalar flow rates through circuit branches$$,$$electric-current$$),
  ($$ap_physics_2$$,11,$$11.2$$,$$Simple Circuits$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$translate between physical circuits and schematics using conventional-current assumptions$$,$$Calling an open switch a closed current path$$,$$simple-circuits$$),
  ($$ap_physics_2$$,11,$$11.3$$,$$Resistance, Resistivity, and Ohm's Law$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$use R equals rho ell over A, Ohm's law, and graph slopes to connect material, geometry, current, and potential difference$$,$$Treating resistivity and resistance as the same quantity$$,$$resistance-resistivity-and-ohms-law$$),
  ($$ap_physics_2$$,11,$$11.4$$,$$Electric Power$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$compare energy-transfer rates with P equals I Delta V and derived resistor power forms$$,$$Assuming the bulb with the greatest current is brightest without checking potential difference or power$$,$$electric-power$$),
  ($$ap_physics_2$$,11,$$11.5$$,$$Compound Direct Current (DC) Circuits$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$reduce series and parallel resistor networks and reason about ideal meters, wires, and battery terminal voltage$$,$$Treating parallel resistors as if the same current must pass through each branch$$,$$compound-direct-current-circuits$$),
  ($$ap_physics_2$$,11,$$11.6$$,$$Kirchhoff's Loop Rule$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$write potential-difference changes around a closed loop that sum to zero$$,$$Losing sign consistency when moving across batteries and resistors in a loop equation$$,$$kirchhoffs-loop-rule$$),
  ($$ap_physics_2$$,11,$$11.7$$,$$Kirchhoff's Junction Rule$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$apply charge conservation so current entering a junction equals current leaving$$,$$Assuming current is used up by circuit elements before reaching a junction$$,$$kirchhoffs-junction-rule$$),
  ($$ap_physics_2$$,11,$$11.8$$,$$Resistor-Capacitor (RC) Circuits$$,$$Electric Circuits$$,$$very-important$$,$$very-important$$,$$describe initial, final, charging, and discharging states qualitatively using the time constant$$,$$Multiplying one instantaneous current reading by elapsed time to get capacitor charge during charging$$,$$resistor-capacitor-rc-circuits$$),

  ($$ap_physics_c_em$$,10,$$10.1$$,$$Electrostatics with Conductors$$,$$Conductors and Capacitors$$,$$very-important$$,$$very-important$$,$$use conductor electrostatic-equilibrium facts: zero internal field, equipotential conductor, perpendicular surface field, and surface charge$$,$$Putting excess charge throughout the conductor's volume instead of on its surface$$,$$electrostatics-with-conductors$$),
  ($$ap_physics_c_em$$,10,$$10.2$$,$$Redistribution of Charge Between Conductors$$,$$Conductors and Capacitors$$,$$somewhat-important$$,$$somewhat-important$$,$$apply charge conservation and equal final potential when connected conductors share charge$$,$$Assuming identical final charges when the conductors have different capacitances or radii$$,$$redistribution-of-charge-between-conductors$$),
  ($$ap_physics_c_em$$,10,$$10.3$$,$$Capacitors$$,$$Conductors and Capacitors$$,$$very-important$$,$$very-important$$,$$derive capacitance from C equals Q over Delta V for the allowed geometry instead of defaulting to parallel plates$$,$$Force-fitting a cylindrical or spherical capacitor into C equals kappa epsilon0 A over d$$,$$capacitors$$),
  ($$ap_physics_c_em$$,10,$$10.4$$,$$Dielectrics$$,$$Conductors and Capacitors$$,$$very-important$$,$$very-important$$,$$explain dielectric polarization and use kappa relationships for field reduction, capacitance increase, and stored energy changes$$,$$Treating a dielectric as if it adds free charge to the capacitor plates$$,$$dielectrics$$)
),
briefs as (
  select
    subject_key,
    unit_number,
    topic_code,
    title,
    class_importance,
    exam_importance,
    title || ' is the ' || unit_title || ' topic where you turn the concept into an AP-ready action: ' || key_move || '.' as what_it_is,
    'It matters because Unit ' || unit_number || ' questions often award credit for connecting the model, representation, formula, or condition to a clear conclusion in context, not just for naming the topic.' as why_it_matters,
    'Points are earned when you ' || key_move || ', show the required setup or condition check, and state the result in the language of the prompt.' as how_points_are_earned,
    'First name the quantity, structure, condition, or representation the prompt is really asking about; then ' || key_move || ' before doing arithmetic or writing the final sentence.' as answer_move,
    common_point_loss,
    '/learn/' || replace(subject_key, '_', '-') || '/unit-' || unit_number || '/' || slug as learn_more_path
  from brief_seed
)
insert into app.topic_point_briefs (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path, practice_subject_key, practice_unit_number,
  practice_topic_code, status, published_at
)
select
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path, subject_key, unit_number, topic_code,
  'published', now()
from briefs
on conflict (subject_key, topic_code) do nothing;

do $verify$
declare
  v_seed_count integer;
begin
  select count(*) into v_seed_count
  from app.topic_point_briefs
  where (subject_key, unit_number) in (
    ($$ap_biology$$, 3),
    ($$ap_chemistry$$, 3),
    ($$ap_statistics$$, 3),
    ($$ap_precalculus$$, 3),
    ($$ap_calculus_ab$$, 3),
    ($$ap_calculus_bc$$, 3),
    ($$ap_physics_1$$, 3),
    ($$ap_physics_c_mechanics$$, 3),
    ($$ap_physics_2$$, 11),
    ($$ap_physics_c_em$$, 10)
  )
  and status = 'published';

  if v_seed_count < 80 then
    raise exception 'expected at least 80 published third-unit topic point briefs, found %', v_seed_count;
  end if;
end $verify$;

commit;
