begin;

-- Seed the introductory-unit topic point briefs for all 4 AP Physics
-- subjects. AP Physics 1 and AP Physics C: Mechanics both start at their
-- own Unit 1 (Kinematics). AP Physics 2 and AP Physics C: Electricity and
-- Magnetism continue the College Board's unit numbering from their
-- prerequisite course, so their first unit is Unit 9 (Thermodynamics) and
-- Unit 8 (Electric Charges, Fields, and Gauss's Law) respectively -- there
-- is no "Unit 1" for those two subjects in this taxonomy.
--
-- Content basis: docs/product/AP_PHYSICS_1_CED_FACT_PACK.md,
-- AP_PHYSICS_C_MECHANICS_CED_FACT_PACK.md, AP_PHYSICS_2_CED_FACT_PACK.md,
-- and AP_PHYSICS_C_EM_CED_FACT_PACK.md (deep-tier unit detail).
-- Companion draft docs:
--   docs/product/AP_PHYSICS_1_UNIT1_TOPIC_POINT_BRIEFS.md
--   docs/product/AP_PHYSICS_C_MECHANICS_UNIT1_TOPIC_POINT_BRIEFS.md
--   docs/product/AP_PHYSICS_2_UNIT9_TOPIC_POINT_BRIEFS.md
--   docs/product/AP_PHYSICS_C_EM_UNIT8_TOPIC_POINT_BRIEFS.md

with brief_seed (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_slug
) as (
  values
  ($$ap_physics_1$$,1,$$1.1$$,$$Scalars and Vectors in One Dimension$$,$$somewhat-important$$,$$somewhat-important$$,$$A scalar is a quantity with only a size (like speed or distance), while a vector has both size and direction (like velocity or displacement). In one dimension, direction collapses down to a plus or minus sign along a chosen axis.$$, $$Every kinematics equation you'll use this unit depends on getting signs right. If you can't tell a scalar from a vector, you'll add speeds when you should be subtracting velocities, and every later unit (forces, momentum, energy) builds on this same signed-quantity habit.$$, $$Credit comes from consistently assigning and using a sign convention (e.g., positive = rightward or upward) for every vector quantity in a problem, and from correctly identifying which given quantities are scalars (speed, distance, time) versus vectors (velocity, displacement, acceleration).$$, $$Before solving, state your positive direction in words or with an arrow, then attach the correct sign to every velocity, displacement, and acceleration value you write down -- a bare number without an implied or stated sign is not a complete vector value in 1-D.$$, $$Treating speed and velocity as interchangeable, or dropping the negative sign on a value once it's plugged into an equation.$$, $$scalars-and-vectors$$),
  ($$ap_physics_1$$,1,$$1.2$$,$$Displacement, Velocity, and Acceleration$$,$$very-important$$,$$very-important$$,$$Displacement (delta-x = x - x0) is the change in position; average velocity is displacement divided by elapsed time; average acceleration is the change in velocity divided by elapsed time. Instantaneous velocity and acceleration are what those averages approach as you shrink the time interval to something very small.$$, $$These three definitions are the vocabulary every other kinematics topic is written in -- the constant-acceleration equations, the graph slopes, and the relative-motion rules in this unit all reduce back to these two ratios.$$, $$Points come from correctly computing displacement, change in velocity, average velocity, or average acceleration from given position/velocity/time data, and from correctly distinguishing an instantaneous value (read at one moment) from an average value (computed over an interval).$$, $$When a problem gives you two positions or two velocities at two different times, explicitly compute the change (final minus initial) before dividing by the elapsed time -- don't skip straight to a memorized formula without showing the subtraction that defines it.$$, $$Reporting a velocity or acceleration found from a slope calculation as if it were instantaneous when the problem actually asked for (or gave data for) an average over an interval.$$, $$displacement-velocity-acceleration$$),
  ($$ap_physics_1$$,1,$$1.3$$,$$Representing Motion$$,$$very-important$$,$$very-important$$,$$This topic covers the three constant-acceleration kinematic equations and how motion appears on position-time, velocity-time, and acceleration-time graphs -- slopes give instantaneous rates, and areas give net changes.$$, $$Most quantitative kinematics problems on the exam are solved by picking the one correct equation from this set or by reading a value off a graph, so fluency here is the single biggest lever for points in this unit.$$, $$Points require selecting the kinematic equation that matches the known and unknown quantities, substituting correctly, and -- for graph items -- correctly matching slope-of-position-graph to velocity, slope-of-velocity-graph to acceleration, area-under-velocity-graph to displacement, and area-under-acceleration-graph to change in velocity; nonuniform-acceleration graphs are scored on qualitative shape/reasoning, not on plugging into the three equations.$$, $$Before using a constant-acceleration equation, confirm acceleration is actually constant over the interval in question -- if the acceleration is changing, switch to reading slopes and areas off the graph instead, since the constant-acceleration equations don't apply there.$$, $$Plugging numbers into a constant-acceleration equation for a motion segment where the acceleration is actually changing, instead of switching to graphical/qualitative reasoning.$$, $$representing-motion$$),
  ($$ap_physics_1$$,1,$$1.4$$,$$Reference Frames and Relative Motion$$,$$somewhat-important$$,$$somewhat-important$$,$$A reference frame is the viewpoint (moving or stationary) from which motion is measured. Acceleration comes out the same in every inertial frame, but velocity does not -- an object's velocity in one frame differs from its velocity in another by the relative velocity between the frames.$$, $$Problems describing motion 'as seen from' a moving platform (a walkway, a train, another car) only make sense once you recognize that velocities must be combined between frames while accelerations transfer over unchanged.$$, $$Points come from correctly adding or subtracting one-dimensional velocities to convert between reference frames, and from correctly stating that the acceleration of an object is the same as measured in any inertial frame.$$, $$When a problem gives motion relative to a moving frame (like a person walking on a moving walkway) restricted to one dimension, add the object's velocity in that frame to the frame's own velocity (with correct signs) to get velocity in the ground frame -- do not attempt this as a two-dimensional vector-addition problem, since 2-D relative-velocity situations are outside this course.$$, $$Trying to combine relative velocities using two-dimensional vector addition (like a boat crossing a river) when this course only holds students responsible for one-dimensional relative motion.$$, $$reference-frames-relative-motion$$),
  ($$ap_physics_1$$,1,$$1.5$$,$$Vectors and Motion in Two Dimensions$$,$$very-important$$,$$very-important$$,$$Two-dimensional motion, most often projectile motion, is analyzed by resolving vectors into perpendicular components using right-triangle trigonometry, then treating each axis as its own independent one-dimensional motion problem.$$, $$Projectile motion is the main way the course tests whether you can combine vector resolution with the kinematics equations from the previous topic, since horizontal and vertical motion happen simultaneously but must be solved separately.$$, $$Points come from correctly resolving an initial velocity into horizontal and vertical components, recognizing horizontal acceleration is zero while vertical acceleration is constant, and solving each axis with the appropriate 1-D kinematic equation before recombining results if needed.$$, $$For projectile motion, split the initial velocity into horizontal and vertical components immediately, then solve the vertical axis (constant acceleration) and horizontal axis (constant velocity) as two separate 1-D kinematics problems linked only by a shared time variable.$$, $$Using the initial launch speed directly in a kinematics equation instead of first resolving it into horizontal and vertical components.$$, $$vectors-and-2d-motion$$),
  ($$ap_physics_c_mechanics$$,1,$$1.1$$,$$Scalars and Vectors$$,$$somewhat-important$$,$$somewhat-important$$,$$A scalar is a quantity fully described by a magnitude alone (like speed or distance), while a vector requires both magnitude and direction (like velocity or displacement). In this course vectors are written in unit vector notation and combined by adding or subtracting their components separately.$$, $$Every kinematics quantity you build for the rest of Unit 1 -- displacement, velocity, acceleration -- is a vector, so component notation is the language the rest of the unit is written in.$$, $$Points come from correctly resolving a given vector into its component directions, then adding or subtracting component-by-component to find a resultant -- not from stating a final magnitude without showing the component work.$$, $$When asked for a resultant vector, add or subtract the components in each direction separately before recombining, and keep each component's sign tied to its assigned axis direction throughout.$$, $$Combining vector magnitudes directly (like adding lengths) instead of adding matching components separately.$$, $$scalars-and-vectors$$),
  ($$ap_physics_c_mechanics$$,1,$$1.2$$,$$Displacement, Velocity, and Acceleration$$,$$very-important$$,$$very-important$$,$$Displacement, average velocity, and average acceleration describe motion over a finite time interval, but instantaneous velocity and acceleration are true derivatives of position and velocity with respect to time. This is the calculus-based definition -- position, velocity, and acceleration are treated as functions of time that can be differentiated or integrated into one another.$$, $$This derivative relationship is the foundation the entire mechanics course is built on: forces, energy, and momentum problems all eventually come back to differentiating or integrating a position or velocity function.$$, $$Points are earned by correctly differentiating a given position or velocity function (or integrating in the reverse direction), and by clearly identifying whether a question is asking for an average quantity versus an instantaneous one -- these are graded as distinct calculations.$$, $$When a position or velocity function is given as an explicit expression in time, differentiate it directly to get instantaneous velocity or acceleration -- do not fall back on average-rate formulas, which only apply when you're working from two data points, not a continuous function.$$, $$Using the average velocity or average acceleration formula when the question actually asks for an instantaneous value at a specific time.$$, $$displacement-velocity-acceleration$$),
  ($$ap_physics_c_mechanics$$,1,$$1.3$$,$$Representing Motion$$,$$very-important$$,$$very-important$$,$$Under constant acceleration, motion is described by the familiar kinematic equations. When acceleration or velocity is not constant, position and velocity changes are instead found by integrating velocity or acceleration over the given time interval.$$, $$Released free-response questions in this unit consistently reward setting up the correct integral for a changing quantity over plugging into a memorized formula, so recognizing which regime you're in is the central skill of the unit.$$, $$Points are earned by first identifying whether acceleration is constant (justifying use of the kinematic equations) or a function of time (requiring integration), then executing the correct algebra or integral with correct limits of integration.$$, $$Before choosing a method, check whether acceleration is stated or shown to be constant; if it is not constant, set up the correct integral with the correct time bounds instead of reaching for the constant-acceleration equations, which do not apply.$$, $$Applying the constant-acceleration kinematic equations to a situation where acceleration is explicitly given as a function of time.$$, $$representing-motion$$),
  ($$ap_physics_c_mechanics$$,1,$$1.4$$,$$Reference Frames and Relative Motion$$,$$somewhat-important$$,$$somewhat-important$$,$$The reference frame you choose determines the magnitude and direction you measure for a moving object's velocity; converting a measurement from one inertial frame to another is done by vector addition or subtraction. Acceleration, however, is the same in every inertial frame. Unlike the algebra-based course, relative-velocity vector addition here is not restricted to one dimension -- full two-dimensional relative-velocity scenarios are in scope.$$, $$Relative motion problems test whether you can treat velocities as vectors that add and subtract across frames rather than as plain numbers, which becomes essential once 2D motion and later force/momentum problems involve multiple moving reference points.$$, $$Points are earned by correctly setting up a vector equation relating the object's velocity in one frame to its velocity in another and resolving it by components when the motion is two-dimensional, not by combining speeds as scalars.$$, $$For a relative-velocity problem, write the vector equation linking the two frames component-by-component (including both dimensions when the scenario is 2D, such as a boat-and-current problem) rather than adding or subtracting speeds directly.$$, $$Adding relative velocities as plain numbers instead of as vectors, which drops the perpendicular component of motion entirely.$$, $$reference-frames-relative-motion$$),
  ($$ap_physics_c_mechanics$$,1,$$1.5$$,$$Motion in Two or Three Dimensions$$,$$very-important$$,$$very-important$$,$$Motion in two dimensions is analyzed by splitting it into independent one-dimensional components along each axis -- each axis can have its own velocity and acceleration, and a change in motion along one axis does not affect the other. This course's quantitative ceiling is two dimensions; three-dimensional motion is only expected to be described qualitatively, not calculated.$$, $$Nearly every 2D exam question in this unit -- projectiles, launched objects, curved paths -- is really two separate 1D kinematics problems solved in parallel, so treating the axes as independent is what makes these problems manageable.$$, $$Points are earned by explicitly separating the motion into components along each axis, applying the correct kinematic or integral relationship independently to each axis, and only recombining components at the end.$$, $$Set up separate equations for each axis using that axis's own acceleration and initial velocity before solving, and only combine the two results at the very last step when a single resultant quantity (like speed or range) is requested.$$, $$Letting the acceleration or time used in one direction's equation leak into the other direction's calculation instead of keeping the two axes fully separate.$$, $$motion-in-two-or-three-dimensions$$),
  ($$ap_physics_2$$,9,$$9.1$$,$$Kinetic Theory: Temperature and Pressure$$,$$very-important$$,$$very-important$$,$$Gas pressure comes from atoms colliding with a surface -- it's the perpendicular force per area those collisions produce, and it exists at every point inside the gas, not just at the container wall. Temperature is a measure of the atoms' average kinetic energy, and the Maxwell-Boltzmann distribution shows how that energy is spread across all the atoms at a given temperature.$$, $$This unit opens the course by replacing 'temperature' and 'pressure' as vague sensations with atomic-motion definitions you'll build every other Unit 9 idea on -- internal energy, the first law, and entropy all trace back to this atomic picture.$$, $$Points come from correctly relating pressure to atomic collisions, computing or reasoning with the kinetic-energy-temperature relation, and reading qualitative features of a Maxwell-Boltzmann curve (peak location, spread, high-speed tail) to compare two temperatures or two gas samples.$$, $$When asked to compare two Maxwell-Boltzmann curves or describe how one changes with temperature, describe the shift and spread in words (peak moves to higher speed, curve flattens and widens) -- do not attempt to state or use a mathematical formula for the distribution itself, since this course only requires qualitative reading of its shape.$$, $$Describing pressure as something that only exists 'at the walls' instead of throughout the gas, or treating a higher Maxwell-Boltzmann peak speed as the only thing that changes with temperature while ignoring the spread.$$, $$kinetic-theory-temperature-pressure$$),
  ($$ap_physics_2$$,9,$$9.2$$,$$The Ideal Gas Law$$,$$very-important$$,$$very-important$$,$$The ideal gas law connects a gas's pressure, volume, temperature, and quantity of particles under the idealizations that atoms have negligible volume, move randomly, and collide elastically.$$, $$It's the single equation you'll use to predict how a gas responds when one variable is held fixed and another changes, and it's the algebraic backbone for the energy and work calculations later in this unit.$$, $$Points require correctly solving the ideal gas law for an unknown variable with consistent units (temperature in kelvin), reading values off pressure-volume, pressure-temperature, or volume-temperature graphs, and extrapolating a linear pressure-vs-temperature graph back to zero pressure to estimate absolute zero.$$, $$When a pressure-vs-temperature graph is given and the question asks for the temperature at which pressure would reach zero, extend the straight-line trend down to the temperature axis rather than assuming the answer must be zero Celsius or reading only the plotted data range.$$, $$Plugging a Celsius temperature directly into the ideal gas law instead of converting to kelvin first.$$, $$ideal-gas-law$$),
  ($$ap_physics_2$$,9,$$9.3$$,$$Thermal Energy Transfer and Equilibrium$$,$$somewhat-important$$,$$somewhat-important$$,$$Two objects in thermal contact can exchange energy by conduction, convection, or radiation; energy spontaneously flows from the higher-temperature system to the lower-temperature one until both reach the same temperature, a state called thermal equilibrium where net energy transfer stops.$$, $$This is the conceptual foundation for heating/cooling problems and for why systems drift toward equilibrium -- an idea that resurfaces qualitatively when entropy and the second law are introduced later in the unit.$$, $$Points come from correctly identifying the direction of spontaneous energy transfer (hot to cold, never the reverse), naming or distinguishing the transfer mechanism appropriate to a scenario, and stating that thermal equilibrium means zero net energy transfer, not zero atomic motion.$$, $$When asked to explain why two objects at different temperatures reach a common final temperature, frame it as the statistically most probable outcome of many random atomic collisions redistributing energy -- not as 'heat rising' or objects 'wanting' to equalize.$$, $$Describing thermal equilibrium as a state where atoms stop moving, rather than a state where net energy transfer between the two systems has stopped.$$, $$thermal-equilibrium$$),
  ($$ap_physics_2$$,9,$$9.4$$,$$The First Law of Thermodynamics$$,$$very-important$$,$$very-important$$,$$The first law is energy conservation applied to a gas's internal energy: internal energy changes because thermal energy is transferred in/out or work is done on/by the gas as its volume changes. PV diagrams let you visualize a process, and the area under the curve gives the magnitude of work done.$$, $$Nearly every quantitative Unit 9 free-response question is built around this law -- reading a PV diagram, identifying the process type, and tracking energy through heat, work, and internal energy is the core quantitative skill of the unit.$$, $$Points require correctly applying the sign conventions in the first law, computing work from a constant/average pressure and volume change (or the area under a P-V curve) for a given process, identifying which quantity is zero or constant for isovolumetric/isothermal/isobaric/adiabatic processes, and computing internal energy change for a monatomic ideal gas.$$, $$When a process is labeled adiabatic, immediately set the heat transfer to zero and get the internal energy change entirely from work -- don't try to estimate any thermal energy transfer for that step, since by definition none occurs.$$, $$Forgetting the negative sign in the work-from-pressure-and-volume-change formula, so an expanding gas (doing positive work on its surroundings) is incorrectly recorded as gaining energy from work instead of losing it.$$, $$first-law-thermodynamics$$),
  ($$ap_physics_2$$,9,$$9.5$$,$$Specific Heat and Thermal Conductivity$$,$$very-important$$,$$very-important$$,$$Specific heat tells you how much thermal energy changes a material's temperature; thermal conductivity tells you how fast thermal energy passes through a material of a given thickness and area. Both are fixed properties of the material.$$, $$These equations let you move from the qualitative hot-to-cold picture in the previous topic to actual numbers -- how much energy transferred, or how quickly -- which is tested constantly in calorimetry and conduction-rate problems.$$, $$Points come from correctly using the specific-heat equation to find heat, mass, specific heat, or temperature change (including setting heat lost equal to heat gained in two-object mixing problems), using the conduction-rate equation to find conduction rate, and treating specific heat as constant across the whole temperature change in a problem.$$, $$In any calorimetry problem, set the heat lost by the warmer object equal to the heat gained by the cooler object and solve -- do not average the two starting temperatures as a shortcut, since masses and specific heats can differ.$$, $$Assuming specific heat changes as an object's temperature changes, instead of treating it as constant throughout the process as this course requires.$$, $$specific-heat-conductivity$$),
  ($$ap_physics_2$$,9,$$9.6$$,$$Entropy and the Second Law of Thermodynamics$$,$$somewhat-important$$,$$somewhat-important$$,$$Entropy is a measure of how spread out or unavailable-to-do-work energy has become; it depends only on a system's current configuration, not its history. The second law says an isolated system's total entropy never decreases and stays constant only if every process in it is reversible.$$, $$It's the conceptual explanation for why processes in this unit -- like heat flowing hot to cold -- only ever run one direction, tying together the whole unit's picture of energy spreading toward equilibrium.$$, $$Points come from qualitatively explaining why total entropy of an isolated system increases or stays the same for a given process, correctly identifying that a non-isolated (closed) system's entropy can decrease because energy crosses its boundary, and connecting maximum entropy to thermodynamic equilibrium -- all in words, with no quantitative entropy calculation expected.$$, $$When asked to justify an entropy claim, explain it in terms of energy dispersal and probability (energy spreading among more possible configurations is far more likely than it spontaneously concentrating) -- never attempt a numeric entropy calculation, since this course tests entropy only qualitatively.$$, $$Claiming a single closed (non-isolated) part of a larger system can never lose entropy, when only the total entropy of a fully isolated system is guaranteed not to decrease.$$, $$entropy-second-law$$),
  ($$ap_physics_c_em$$,8,$$8.1$$,$$Electric Charge and Electric Force$$,$$very-important$$,$$very-important$$,$$Coulomb's law describes the electric force between two point charges: proportional to the product of the charges and inversely proportional to the square of the distance between them, directed along the line connecting them, repulsive for like charges and attractive for unlike charges.$$, $$It's the force-level foundation everything else in this unit builds on -- fields, flux, and Gauss's law are all reframings of how charges push and pull on each other, and later units on circuits and magnetism assume this is automatic.$$, $$You must set up Coulomb's law with correct magnitudes and signs, treat force as a vector (superposing components from multiple charges rather than just adding magnitudes), and correctly identify direction from the geometry.$$, $$For a system of four or fewer point charges, compute each pairwise Coulomb force as a vector, break into components along a chosen axis system, and sum components separately before combining; do not attempt this direct pairwise method for more than four charges or for continuous distributions -- that requires a field or Gauss's-law approach instead.$$, $$Adding force magnitudes directly instead of resolving each pairwise force into components before summing.$$, $$coulombs-law$$),
  ($$ap_physics_c_em$$,8,$$8.2$$,$$Conservation of Electric Charge and Charge Distribution$$,$$somewhat-important$$,$$somewhat-important$$,$$Total electric charge in an isolated system is conserved, and charge can be spread continuously as a density: linear (charge per length), surface (charge per area), or volume (charge per volume).$$, $$Every calculus-based field and Gauss's-law calculation later in the unit starts from correctly identifying which density function describes the charge and setting up the right integral to get total charge from it.$$, $$You must write the correct integral matching the dimensionality of the charge distribution, and if the density isn't uniform, keep it inside the integral rather than pulling it out as a constant.$$, $$Before integrating, identify whether the charge lives on a line, surface, or volume, name the matching density type, and write the differential element consistent with that choice -- this sets up correctly every later integral in the unit.$$, $$Using the wrong density type for the dimensionality of the object, such as treating a surface charge as if it were a volume charge.$$, $$charge-conservation-and-density$$),
  ($$ap_physics_c_em$$,8,$$8.3$$,$$Electric Fields$$,$$very-important$$,$$very-important$$,$$The electric field is the force per unit charge that would act on a small positive test charge at a point in space -- it exists at every point regardless of whether a charge is actually placed there.$$, $$Shifting from force-between-two-charges to a field that fills space is the conceptual pivot that makes flux, Gauss's law, and later potential and circuit topics possible.$$, $$You must state or use the force-per-charge field definition correctly (field is a vector, defined at a point independent of any test charge present), and correctly interpret field line diagrams -- direction from lines, relative magnitude from line density.$$, $$When asked to describe or sketch a field, treat the field as existing at the point itself, independent of any test charge, and use field-line density (not just direction) to communicate relative field strength.$$, $$Describing the field as if it only exists when a test charge is physically present at that point, rather than as a property of space itself.$$, $$electric-field-definition$$),
  ($$ap_physics_c_em$$,8,$$8.4$$,$$Electric Fields of Charge Distributions$$,$$very-important$$,$$very-important$$,$$Using calculus to find the electric field produced by a continuous (non-point) charge distribution, by integrating the contributions of infinitesimal charge elements across the distribution.$$, $$This is the direct-integration counterpart to Gauss's law: it's the calculus skill that separates this course from algebra-based physics, and it's tested on exactly the handful of geometries the course specifies.$$, $$You must set up the charge element correctly in terms of the relevant density and geometry, express the distance and direction terms as functions of the integration variable, and carry out a definite integral with correct limits.$$, $$Only attempt direct calculus integration for one of the five specified geometries -- an infinite charged wire/cylinder at a distance from its axis, a ring of charge on its axis, a semicircular arc at its center, or a finite line charge collinear with it or on its perpendicular bisector; for any other shape, this integral is not the intended tool.$$, $$Trying to integrate a full field vector when symmetry cancels one component, instead of first identifying which component survives and integrating only that one.$$, $$field-from-continuous-charge$$),
  ($$ap_physics_c_em$$,8,$$8.5$$,$$Electric Flux$$,$$somewhat-important$$,$$very-important$$,$$Electric flux measures how much electric field passes through a surface: the field times the area for a uniform field through a flat surface, or a general surface integral when the field or surface isn't uniform or flat.$$, $$Flux is the quantity Gauss's law directly relates to enclosed charge, so getting comfortable with the angle dependence here is what makes the next topic's setup step reliable.$$, $$You must account for the angle between the field and the surface's area vector (normal direction), recognizing that flux is maximized when the field is parallel to the normal and zero when the field is parallel to the surface itself.$$, $$Identify the direction of the area vector (outward normal) for the surface in question, then use the field component along that normal direction (or the full integral for non-uniform cases) rather than just multiplying field by area without accounting for orientation.$$, $$Computing flux as field times area without checking whether the field is actually perpendicular to the surface.$$, $$electric-flux$$),
  ($$ap_physics_c_em$$,8,$$8.6$$,$$Gauss's Law$$,$$very-important$$,$$very-important$$,$$Gauss's law states that the total electric flux through any closed surface equals the enclosed charge divided by the permittivity of free space.$$, $$It's the shortcut that replaces direct integration for the highly symmetric charge distributions that show up repeatedly in later units, including capacitors and conductors.$$, $$You must choose a Gaussian surface matching the actual symmetry of the charge (sphere, cylinder, or plane), use the correct area formula for that surface, express the enclosed charge using the fixed dimensions of the actual charged object (not the variable Gaussian-surface radius), and solve for the field.$$, $$Only use Gauss's law quantitatively when the charge distribution has spherical, cylindrical, or planar symmetry; for a cylindrical setup specifically, use the curved lateral surface area (never a disk's or sphere's area formula), and compute enclosed charge from the charged object's own fixed radius, not the Gaussian surface's radius.$$, $$For a cylindrical Gaussian surface, using a sphere's or disk's area formula instead of the cylinder's lateral area, or plugging the Gaussian surface's own radius into the enclosed-charge calculation instead of the charged object's actual radius.$$, $$gauss-law$$)
)
insert into app.topic_point_briefs (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path, practice_subject_key, practice_unit_number,
  practice_topic_code, status, published_at
)
select
  subject_key,
  unit_number,
  topic_code,
  title,
  class_importance,
  exam_importance,
  what_it_is,
  why_it_matters,
  how_points_are_earned,
  answer_move,
  common_point_loss,
  '/learn/' || replace(subject_key, '_', '-') || '/unit-' || unit_number::text || '/' || learn_more_slug,
  subject_key,
  unit_number,
  topic_code,
  'published',
  now()
from brief_seed
on conflict (subject_key, topic_code) do update
set
  unit_number = excluded.unit_number,
  title = excluded.title,
  class_importance = excluded.class_importance,
  exam_importance = excluded.exam_importance,
  what_it_is = excluded.what_it_is,
  why_it_matters = excluded.why_it_matters,
  how_points_are_earned = excluded.how_points_are_earned,
  answer_move = excluded.answer_move,
  common_point_loss = excluded.common_point_loss,
  learn_more_path = excluded.learn_more_path,
  practice_subject_key = excluded.practice_subject_key,
  practice_unit_number = excluded.practice_unit_number,
  practice_topic_code = excluded.practice_topic_code,
  status = excluded.status,
  published_at = excluded.published_at,
  updated_at = now();

commit;
