begin;

-- Seed AP Chemistry Unit 2 (Compound Structure and Properties, 7 topics)
-- and AP Statistics Unit 2 (Probability, Random Variables, and Probability
-- Distributions, 12 topics) topic point briefs.
--
-- AP Calculus AB Unit 2 is intentionally NOT included: all 10 of its topics
-- were already authored and published by
-- 20260820230000_seed_remaining_biology_calculus_topic_point_briefs.sql.
--
-- Content basis: docs/product/AP_CHEMISTRY_CED_FACT_PACK.md (Unit 2
-- deep-tier detail, four verbatim exclusion statements) and
-- docs/product/AP_STATISTICS_2027_CED_FACT_PACK.md (Unit 2 deep-tier detail
-- in section 10, which is UNREVIEWED pending SME sign-off).
--
-- Statistics removed-content guard (fact pack section 8): combining random
-- variables and the geometric distribution are removed from the course.
-- Topic 2.9 covers expected value / standard deviation only; topic 2.10
-- covers the binomial distribution only. Neither removed topic appears here.
--
-- Companion draft docs:
--   docs/product/AP_CHEMISTRY_UNIT2_TOPIC_POINT_BRIEFS.md
--   docs/product/AP_STATISTICS_UNIT2_TOPIC_POINT_BRIEFS.md

with brief_seed (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path
) as (
  values
  ($$ap_chemistry$$,2,$$2.1$$,$$Types of Chemical Bonds$$,$$very-important$$,$$very-important$$,$$Bonding is a continuum set by how unequally two atoms pull on shared electrons. Electronegativity rises left-to-right across a period and falls down a group (shell model plus Coulomb's law). Similar electronegativities give nonpolar covalent bonds, unequal ones give polar covalent bonds with a bond dipole, and large differences give bonds we call ionic. Metals instead delocalize their valence electrons across the whole solid rather than assigning them to individual atoms.$$,$$Every later structure-and-property argument in the course starts here: bond polarity feeds molecular dipoles in 2.7, charge magnitude feeds Coulombic reasoning in 2.2 and 2.3, and delocalized electrons explain metallic behavior in 2.4. AP questions constantly ask you to explain a physical property by naming the bonding type and justifying it, so a shaky grip on electronegativity trends silently costs points across three units.$$,$$Points come from classifying a bond as nonpolar covalent, polar covalent, or ionic AND justifying the classification with a stated electronegativity comparison, then using observed properties (conductivity when molten or dissolved, melting point, solubility, brittleness versus malleability) as the confirming evidence. Comparison items award credit for ranking bond polarity by relative electronegativity difference and for identifying which atom carries the partial negative charge.$$,$$State the electronegativity comparison explicitly before naming the bond type ('O is more electronegative than H, so the shared electrons are pulled toward O -- polar covalent, with delta-negative on O'), and when the item gives you experimental properties, let those properties decide the classification rather than the metal/nonmetal shortcut.$$,$$Treating ionic and covalent as two separate boxes, instead of a continuum where every polar bond already has some ionic character.$$,$$/learn/ap-chemistry/unit-2/types-of-chemical-bonds$$),
  ($$ap_chemistry$$,2,$$2.2$$,$$Intramolecular Force and Potential Energy$$,$$very-important$$,$$very-important$$,$$A graph of potential energy versus internuclear distance describes a bond quantitatively: the lowest point on the curve is the equilibrium bond length, and the depth of that well is the bond energy needed to pull the atoms apart. Higher bond order (single to double to triple) pulls the minimum to a shorter distance and deepens the well. For ions, Coulomb's law says larger charges and smaller ionic radii both strengthen the attraction.$$,$$This topic converts bonding from a label into a number you can compare and defend. It is the engine behind lattice-energy rankings, bond-length and bond-strength comparisons in 2.7, and every energy argument in later thermodynamics units, and it is one of the few Unit 2 skills that appears as a graph-reading task on the exam.$$,$$Points come from correctly reading equilibrium bond length and bond energy off a PE curve, from ranking bond length and bond energy by bond order in the same breath (shorter goes with stronger), and from applying Coulomb's law to ion pairs by citing BOTH factors -- the magnitude of the charges and the internuclear distance set by ionic radii -- to justify which interaction is stronger.$$,$$When you rank two ionic compounds, name charge and ionic size in the same sentence and say which one dominates (for example MgO over NaCl because 2+/2- charges outweigh any size difference); when reading a PE curve, quote the x-value at the minimum as bond length and the well depth as bond energy rather than describing the curve's shape.$$,$$Comparing only ion charges and ignoring ionic radius, or claiming a longer bond is somehow stronger.$$,$$/learn/ap-chemistry/unit-2/bond-energy-and-length$$),
  ($$ap_chemistry$$,2,$$2.3$$,$$Structure of Ionic Solids$$,$$somewhat-important$$,$$somewhat-important$$,$$In an ionic solid, cations and anions occupy a systematic, repeating three-dimensional array. That arrangement is not arbitrary: it is the packing that puts oppositely charged ions as close as possible while keeping like-charged ions apart, maximizing attraction and minimizing repulsion across the whole lattice.$$,$$It supplies the structural picture behind the properties you are asked to explain elsewhere -- why ionic solids are hard, brittle, high-melting, and conduct only when molten or dissolved. It carries narrower exam weight than the Lewis and VSEPR topics, but it is the bridge between Coulomb's law in 2.2 and bulk-property questions later.$$,$$Points come from describing the lattice as an extended periodic array of alternating cations and anions and explaining a macroscopic property by that arrangement -- for instance, that many strong Coulombic attractions throughout the lattice require large energy to disrupt (high melting point), or that shifting a layer aligns like charges and causes the crystal to fracture (brittleness).$$,$$Explain ionic properties by the alternating-array arrangement and the many attractions it creates, not by memorizing lattice names -- the AP Exam explicitly does not assess knowledge of specific crystal structures, so naming a structure type earns nothing and is not expected of you.$$,$$Describing an ionic solid as separate molecules or discrete ion pairs, rather than one extended lattice of alternating charges.$$,$$/learn/ap-chemistry/unit-2/ionic-solids$$),
  ($$ap_chemistry$$,2,$$2.4$$,$$Structure of Metals and Alloys$$,$$somewhat-important$$,$$somewhat-important$$,$$A metal is an array of positive metal ions immersed in a sea of delocalized valence electrons that belong to the solid as a whole. Alloys come in two structural flavors: interstitial alloys, where much smaller atoms (carbon in iron, giving steel) sit in the gaps of the host lattice, and substitutional alloys, where atoms of comparable radius (as in some brass) replace host atoms in lattice positions.$$,$$This is where delocalization from 2.1 becomes an explanation for real behavior -- conductivity, malleability, luster -- and where atomic radius from Unit 1 does concrete structural work. Its exam weight is narrower than the Lewis/VSEPR core, but the interstitial-versus-substitutional distinction is a clean, frequently testable size argument.$$,$$Points come from invoking mobile delocalized electrons to explain conductivity and from invoking layers of ions sliding past one another (with the electron sea still holding them together) to explain malleability, and from classifying an alloy as interstitial or substitutional by explicitly comparing the atomic radii of the two elements involved.$$,$$Classify an alloy by comparing atomic radii out loud -- significantly different radii means the small atoms fill interstices (interstitial), comparable radii means one atom replaces another in lattice sites (substitutional) -- and cite the radius comparison as your reason, not the identity of the metals.$$,$$Saying metals conduct because they 'have free electrons' without stating those delocalized electrons are mobile throughout the whole solid.$$,$$/learn/ap-chemistry/unit-2/metals-and-alloys$$),
  ($$ap_chemistry$$,2,$$2.5$$,$$Lewis Diagrams$$,$$very-important$$,$$very-important$$,$$A Lewis diagram is a bookkeeping drawing of where every valence electron in a molecule or ion sits. You build it by a fixed procedure: total the valence electrons (adjusting for overall charge), choose a central atom and arrange the others around it, connect them with single bonds, then distribute the remaining electrons as lone pairs to satisfy octets, converting lone pairs into multiple bonds when a central atom comes up short.$$,$$The Lewis diagram is the input to almost everything downstream -- resonance and formal-charge selection in 2.6, geometry, bond angles, hybridization, and molecular dipole in 2.7, and intermolecular-force reasoning in Unit 3. A drawing with the wrong electron count poisons every conclusion built on it, which is why free-response items so often ask you to draw one first.$$,$$Points come from producing a complete, correct diagram: the total valence-electron count matches the formula (including added electrons for anions and removed electrons for cations), every bonding pair and lone pair is shown, octets are satisfied where the procedure requires, and an ion's diagram is enclosed in brackets with the overall charge written outside.$$,$$Write the valence-electron total as a number before you draw anything, then count the electrons in your finished picture and confirm the two match -- and for a polyatomic ion, adjust that total for the charge and put brackets with the charge around the final structure.$$,$$Drawing only the bonds and forgetting lone pairs, or ignoring an ion's charge when totaling valence electrons.$$,$$/learn/ap-chemistry/unit-2/lewis-diagrams$$),
  ($$ap_chemistry$$,2,$$2.6$$,$$Resonance and Formal Charge$$,$$very-important$$,$$very-important$$,$$Two refinements sit on top of a finished Lewis diagram. When several EQUIVALENT diagrams are possible, resonance says the real molecule is a single averaged structure -- bonds intermediate in length and strength -- not a molecule flipping between forms. When candidate diagrams are NONEQUIVALENT, the octet rule plus formal charge picks the best one: minimize formal charges overall and place any negative formal charge on the more electronegative atom. The Lewis model has real limits, especially for odd-electron species.$$,$$This is the judgment layer between drawing a structure and using it. It explains why all the bonds in a nitrate or carbonate ion are identical rather than one short and two long, and it is the tool that tells you which of several legal drawings is the one the exam expects you to reason from.$$,$$Points come from drawing all equivalent resonance forms and stating that the actual structure is an average of them (with bond order and bond length between the extremes), and separately from computing formal charge -- valence electrons minus lone-pair electrons minus half the bonding electrons -- for the competing atoms and justifying your chosen structure by minimized formal charges and by negative formal charge sitting on the more electronegative atom.$$,$$Decide first whether your candidate structures are equivalent or nonequivalent: equivalent ones call for drawing the resonance set and describing an averaged structure, while nonequivalent ones call for showing the actual formal-charge arithmetic on the contested atoms and naming which structure wins and why.$$,$$Saying the molecule rapidly switches between resonance forms; it is one averaged structure, and the bonds are identical.$$,$$/learn/ap-chemistry/unit-2/resonance-and-formal-charge$$),
  ($$ap_chemistry$$,2,$$2.7$$,$$VSEPR and Hybridization$$,$$very-important$$,$$very-important$$,$$VSEPR takes a finished Lewis diagram and predicts three-dimensional shape by assuming regions of electron density around a central atom repel one another and spread as far apart as possible. From that arrangement you get the molecular geometry (linear, trigonal planar, tetrahedral, trigonal pyramidal, bent, trigonal bipyramidal, seesaw, T-shaped, octahedral, square pyramidal, square planar), approximate bond angles, relative bond lengths and energies, whether the molecule has a net dipole, and the hybridization label sp (180 degrees), sp2 (120 degrees), or sp3 (109.5 degrees). Sigma bonds form by head-on overlap and are stronger; pi bonds, present in multiple bonds, are weaker and block rotation, producing geometric isomers.$$,$$Geometry is the payoff of the whole unit and the entry point to Unit 3: whether a molecule is polar -- and therefore how it interacts with other molecules, dissolves, and boils -- depends on shape plus bond dipoles. This topic is among the most heavily assessed in the unit and shows up in both multiple-choice and free-response settings.$$,$$Points come from counting regions of electron density around the central atom (each lone pair counts as one, and a double or triple bond counts as ONE region), then naming the molecular geometry based on atom positions only, giving the associated bond angle, and -- when asked -- assigning the hybridization label. Polarity points require combining bond dipoles with the geometry to argue whether they cancel.$$,$$Count regions of electron density first and count each multiple bond as a single region, then answer exactly what was asked -- a geometry name if the question says geometry, an sp/sp2/sp3 label if it says hybridization. Note the scope limit: hybridization labels stop at sp3, so for a central atom with more than four electron pairs give only the shape, and never reach for d-orbital hybridization or molecular orbital theory, which the exam does not assess.$$,$$Counting a C=O double bond as two regions and answering sp3; a double bond is one region, so that carbon is sp2.$$,$$/learn/ap-chemistry/unit-2/vsepr-and-hybridization$$),
  ($$ap_statistics$$,2,$$2.1$$,$$Tabular and Graphical Representations for the Distributions of Two Categorical Variables$$,$$very-important$$,$$somewhat-important$$,$$A two-way (contingency) table cross-classifies every individual by two categorical variables at once, with the cell counts in the body, the row and column totals in the margins, and the grand total in the corner. The same data can be displayed as a segmented (stacked) bar chart or a side-by-side bar chart.$$,$$This is the first time in the course that two variables are examined together rather than one distribution at a time, and the cells of a two-way table are literally the events whose joint, marginal, and conditional probabilities you compute in 2.2 and again in 2.4 through 2.7.$$,$$You earn credit for correctly locating a requested count in the table (cell versus row total versus column total versus grand total), for building or completing a two-way table from a described scenario, and for reading a segmented or side-by-side bar chart back into the counts or percentages it represents.$$,$$Before extracting any number from a two-way table, write down in words what the row variable is, what the column variable is, and what a single cell counts -- this labeling step is what keeps you from grabbing a margin when a cell was asked for.$$,$$Treating a segmented bar chart's percentages as counts, so groups of very different sizes look equally large.$$,$$/learn/ap-statistics/unit-2/two-way-tables-and-graphs$$),
  ($$ap_statistics$$,2,$$2.2$$,$$Summary Statistics for Two Categorical Variables$$,$$very-important$$,$$very-important$$,$$Three different relative frequencies computed from the same two-way table: a joint relative frequency is one cell divided by the table total; a marginal relative frequency is a whole row or column total divided by the table total; a conditional relative frequency is a cell divided by its own row or column total. Same numerator, three different denominators.$$,$$Which total you divide by is the entire skill here, and it is the same distinction that reappears as joint, marginal, and conditional probability in 2.6. Comparing conditional relative frequencies across groups is also how you argue two categorical variables are or are not associated.$$,$$You earn credit for computing the requested relative frequency with the correct denominator, for stating which group the percentage describes, and for comparing conditional distributions across groups and drawing the association conclusion those comparisons support rather than just restating the numbers.$$,$$For every percentage you report from a two-way table, write it as a sentence in the form 'of the [group in the denominator], ___% are [category in the numerator]' -- if you cannot name the denominator group, you divided by the wrong total.$$,$$Dividing a cell by the grand total when the question asked 'of the seniors,' which requires dividing by that row's own total.$$,$$/learn/ap-statistics/unit-2/joint-marginal-conditional-relative-frequency$$),
  ($$ap_statistics$$,2,$$2.3$$,$$Estimating Probabilities Using Simulation$$,$$very-important$$,$$somewhat-important$$,$$A simulation models a chance process by running many artificial trials -- with a random digit table, a spinner, cards, or technology -- and estimates a probability as the proportion of trials in which the outcome of interest happened. The Law of Large Numbers is the justification: as trials grow, that long-run relative frequency approaches the true probability.$$,$$Simulation is the course's escape hatch for probabilities that are awkward to compute with a formula, and the same design-and-count logic returns later for randomization distributions and simulation-based inference. It is also where 'long-run relative frequency' gets its meaning.$$,$$You earn credit for describing a complete simulation design: what device generates the randomness, how digits map to real-world outcomes, what counts as one trial and when a trial stops, what you record each trial, and dividing successful trials by total trials to state an estimated probability.$$,$$When you describe a simulation, explicitly state where one trial ends and what you write down at that moment; a design that assigns digits but never defines the stopping point and the recorded quantity is incomplete even if your estimate is right.$$,$$Reporting a simulation estimate as the exact probability, instead of an estimate that gets closer to the truth as trials increase.$$,$$/learn/ap-statistics/unit-2/simulation-and-long-run-relative-frequency$$),
  ($$ap_statistics$$,2,$$2.4$$,$$Introduction to Probability$$,$$very-important$$,$$somewhat-important$$,$$Probability measures how often an outcome happens in the long run. When every outcome in the sample space is equally likely, the probability of an event is the number of outcomes in it divided by the total number of outcomes. Every probability lies between 0 and 1, and the complement rule says the probability an event does not happen is 1 minus the probability it does.$$,$$This topic sets ground rules the rest of the unit assumes without restating: the counting formula only works under equal likelihood, and the complement rule is the shortcut that makes 'at least one' problems tractable in 2.7 and in binomial problems in 2.10.$$,$$You earn credit for listing or counting the sample space correctly, for applying the equally-likely formula only when the setup justifies it, for using the complement rule to convert an 'at least one' or 'none' question into its easier opposite, and for reporting a value between 0 and 1.$$,$$When a question asks for 'at least one,' compute the probability of none and subtract from 1 rather than adding up cases -- but check first that 'none' is genuinely the only complementary outcome, since the shortcut only works when the two events partition the sample space.$$,$$Using outcomes-divided-by-total when the outcomes are not equally likely, such as unequal spinner sectors or weighted categories.$$,$$/learn/ap-statistics/unit-2/probability-basics-and-complements$$),
  ($$ap_statistics$$,2,$$2.5$$,$$Mutually Exclusive Events$$,$$somewhat-important$$,$$somewhat-important$$,$$Two events are mutually exclusive (disjoint) exactly when they cannot both happen on the same trial -- formally, the probability of both occurring together is zero. There is no overlap between them in the sample space; a single card cannot be both a heart and a spade.$$,$$Mutual exclusivity is the condition that makes the addition rule collapse to a simple sum, and it is the most confused idea in the unit because students hear 'cannot happen together' and think 'unrelated,' which is independence. Anchoring it here protects 2.6 and 2.7 from collapsing into each other.$$,$$You earn credit for deciding whether two described events can occur on the same trial, for supporting that decision with a zero overlap or with a nonzero overlap you can point to in a table or Venn diagram, and for recognizing when disjointness lets you add probabilities directly.$$,$$Test mutual exclusivity by asking one question -- could a single individual or a single trial land in both events at once? -- and answer it about the overlap only; do not compare the plain and conditional probabilities, which is the independence test in 2.7, not this one.$$,$$Assuming mutually exclusive means independent; disjoint events with nonzero probability are actually dependent, since one occurring rules the other out.$$,$$/learn/ap-statistics/unit-2/mutually-exclusive-events$$),
  ($$ap_statistics$$,2,$$2.6$$,$$Conditional Probability$$,$$very-important$$,$$very-important$$,$$The conditional probability of A given B equals the probability of both divided by the probability of B. Conditioning shrinks the sample space down to B alone, so B becomes the new denominator. Rearranged, this is the general multiplication rule for the probability that both events occur.$$,$$Conditional probability is the engine of the rest of the unit and of the course. It is the definition that makes the independence test in 2.7 meaningful, it is what a conditional relative frequency in 2.2 computes, and 'given' language is exactly how p-values are phrased in Units 3 and 4.$$,$$You earn credit for identifying which event is the condition and using it as the denominator, for computing the conditional probability correctly from a table or tree diagram, for applying the multiplication rule to chained events, and for interpreting the result in context as a probability restricted to the given group.$$,$$Translate the word after 'given that,' or the group named after 'of the,' into your denominator before you compute anything -- and note that the two directions of conditioning are different questions, so reversing them changes the answer even with identical data.$$,$$Reversing the condition -- answering 'probability of the disease given a positive test' with the probability of a positive test given the disease.$$,$$/learn/ap-statistics/unit-2/conditional-probability$$),
  ($$ap_statistics$$,2,$$2.7$$,$$Independent Events and Unions of Events$$,$$very-important$$,$$very-important$$,$$Two events are independent when knowing one occurred does not change the probability of the other, so the probability of both equals the product of the two probabilities. Separately, the union (addition) rule finds the probability that A or B (or both) occurs by adding the two and subtracting the overlap so it is not counted twice. The addition rule is on the formula sheet.$$,$$Independence is the assumption that licenses multiplying probabilities, and it is a stated condition for the binomial setting in 2.10 and for essentially every inference procedure later in the course. The union rule is where 'or' problems live, and its subtraction term is the overlap that mutual exclusivity in 2.5 sets to zero.$$,$$You earn credit for testing independence with actual numbers rather than asserting it, for stating the conclusion in context, and for applying the union rule with the overlap subtracted -- including recognizing when that overlap is zero.$$,$$Before multiplying probabilities across repeated selections, check whether the scenario actually removes items without replacement; if it does not, keep the probability constant on every trial. For an 'or' question, add the two probabilities and subtract the overlap so it is not counted twice.$$,$$Shrinking the numerator and denominator each draw, as if sampling without replacement, when the trials are independent and the probability stays constant.$$,$$/learn/ap-statistics/unit-2/independence-and-unions$$),
  ($$ap_statistics$$,2,$$2.8$$,$$Introduction to Random Variables and Probability Distributions$$,$$very-important$$,$$somewhat-important$$,$$A random variable assigns a number to each outcome of a chance process. A discrete probability distribution lists every possible value together with its probability, and those probabilities must sum to exactly 1. It can be given as a table, a graph, or a function. A cumulative distribution instead reports the accumulated probability up to and including a value.$$,$$This topic is about what a probability distribution is, before you compute anything from it. Everything downstream depends on that object being defined correctly: 2.9 computes its mean and standard deviation, 2.10 studies one specific named distribution, and 2.12 treats a statistic as a random variable with a distribution of its own.$$,$$You earn credit for defining the random variable in words as a numeric quantity, for verifying or completing a distribution so the probabilities sum to 1, for finding a missing probability by subtraction, and for reading probabilities off either the distribution or its cumulative version, including at-most versus strictly-less-than boundaries.$$,$$Whenever a distribution is presented as a table, sum the probabilities and confirm they total 1 before answering -- if a value is missing, that sum-to-1 requirement is how you recover it, and if they do not total 1 the given distribution is not valid.$$,$$Confusing a cumulative value with an individual probability, and using the accumulated total as one value's probability.$$,$$/learn/ap-statistics/unit-2/random-variables-and-distributions$$),
  ($$ap_statistics$$,2,$$2.9$$,$$Parameters of Random Variables$$,$$very-important$$,$$very-important$$,$$The parameters that summarize a discrete random variable's distribution. The expected value (mean) is the sum of each value multiplied by its own probability -- every possible value weighted by how likely it is. The standard deviation is the square root of the probability-weighted sum of squared deviations from that mean, and the variance is its square. All three appear on the official formula sheet.$$,$$Expected value is what 'the long-run average outcome' means numerically, and it is the tool behind fair-game, insurance, and expected-payoff questions. Because the mean is a weighted average, it is also the conceptual bridge to the mean of a sampling distribution in 2.12.$$,$$You earn credit for multiplying each value by its own probability and summing, for interpreting the result in context as a long-run average per trial rather than a value you expect on any single trial, for computing the standard deviation with squared deviations weighted by their probabilities, and for handling compound-event boundaries correctly.$$,$$When you compute an expected value, keep the probability factor attached to every term -- the mean of a random variable is a probability-weighted sum, never the plain average of the listed values, unless those values happen to be equally likely.$$,$$Averaging the possible values as if equally likely, or reading 'fewer than 3' as 3 or fewer when it means 2 or fewer.$$,$$/learn/ap-statistics/unit-2/expected-value-and-standard-deviation$$),
  ($$ap_statistics$$,2,$$2.10$$,$$The Binomial Distribution$$,$$very-important$$,$$very-important$$,$$The binomial random variable counts the number of successes in a fixed number of trials, with mean equal to n times p and standard deviation equal to the square root of n times p times one minus p -- all on the formula sheet. A binomial setting requires all four conditions: a fixed number of trials, independent trials, exactly two outcomes per trial, and a constant success probability on every trial.$$,$$This is the course's first named probability model, and the one students are most often asked to recognize from a word problem rather than being told to use. Establishing that a count is binomial is also what licenses the proportion-based inference procedures in the later units.$$,$$You earn credit for defining the random variable precisely as a count over a stated interval or set of trials, for naming the distribution as binomial and stating its n and p, for checking the four conditions against the scenario, and for computing the probability, mean, or standard deviation with the parameters identified in words.$$,$$Write the distribution statement in full -- X = the number of successes in n trials, and X is binomial with stated n and p -- and label n and p in words even when you compute with a calculator command, since an unlabeled command string forfeits the parameter-identification credit.$$,$$Writing only a calculator command as your answer, with no words naming the distribution as binomial or stating what n and p are.$$,$$/learn/ap-statistics/unit-2/binomial-distribution$$),
  ($$ap_statistics$$,2,$$2.11$$,$$The Normal Distribution$$,$$very-important$$,$$very-important$$,$$A continuous, symmetric, bell-shaped model for a quantitative variable, described entirely by its mean and standard deviation. The empirical rule says roughly 68%, 95%, and 99.7% of values fall within 1, 2, and 3 standard deviations of the mean. The standard normal distribution is the special case with mean 0 and standard deviation 1.$$,$$The normal distribution is the reference model for individual values in a population, and the machinery behind proportion and percentile questions. It is also the shape the Central Limit Theorem promises for a sample mean in 2.12 -- but there it describes a statistic, not an individual, and keeping those two uses separate is the central distinction of this unit.$$,$$You earn credit for applying the empirical rule to landmark boundaries, for standardizing a value and finding the area on the correct side or between two boundaries, for working backward from a given percentile to a raw value, and for stating the answer as a proportion or percentage of individuals in the population described.$$,$$Sketch the curve and shade the region before computing, then label whether your answer is a proportion or a percent and convert deliberately, so you do not introduce a factor-of-100 error.$$,$$Reporting a normal-curve area without labeling it as a proportion or a percent, then carrying a factor-of-100 error into the answer.$$,$$/learn/ap-statistics/unit-2/normal-distribution$$),
  ($$ap_statistics$$,2,$$2.12$$,$$Sampling Distributions and the Central Limit Theorem$$,$$very-important$$,$$very-important$$,$$A sampling distribution is the distribution of a statistic across all possible samples of a given size drawn from a population -- a distribution whose individual dots are whole samples' summary values, not individual subjects. It is distinct from the population distribution and from one particular sample's data. A randomization distribution is simulation-based and answers a different question than a sampling distribution. The Central Limit Theorem says the sampling distribution of a sample mean is approximately normal, improving as sample size grows.$$,$$This is the conceptual hinge of the whole course. Units 3 and 4 restate this same idea once per statistic and attach conditions and standard errors to it, so every confidence interval and significance test later is a specialization of what happens here.$$,$$You earn credit for identifying which of the three distributions a graph or description shows -- population, single sample, or sampling distribution of a statistic -- for stating that the Central Limit Theorem makes the sampling distribution of a sample mean approximately normal for a large enough sample, and for explaining that increasing sample size tightens the spread of the statistic.$$,$$Before describing any distribution here, name what one dot on it represents: one individual (population or single sample) or one whole sample's statistic (sampling distribution) -- and note the Central Limit Theorem's normality promise attaches to the sampling distribution, not to the population.$$,$$Claiming the Central Limit Theorem makes the population normal; it describes the distribution of the sample mean, while the population can stay skewed.$$,$$/learn/ap-statistics/unit-2/sampling-distributions-and-clt$$)
)
insert into app.topic_point_briefs (
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path, practice_subject_key, practice_unit_number,
  practice_topic_code, status, published_at
)
select
  subject_key, unit_number, topic_code, title, class_importance, exam_importance,
  what_it_is, why_it_matters, how_points_are_earned, answer_move,
  common_point_loss, learn_more_path, subject_key, unit_number, topic_code,
  'published', now()
from brief_seed
on conflict (subject_key, topic_code) do update
set
  unit_number = excluded.unit_number,
  title = excluded.title,
  class_importance = excluded.class_importance,
  exam_importance = excluded.exam_importance,
  what_it_is = excluded.what_it_is,
  why_it_matters = excluded.why_it_matters,
  how_points_are_earned = excluded.how_points_are_earned,
  answer_move = excluded.answer_move,
  common_point_loss = excluded.common_point_loss,
  learn_more_path = excluded.learn_more_path,
  practice_subject_key = excluded.practice_subject_key,
  practice_unit_number = excluded.practice_unit_number,
  practice_topic_code = excluded.practice_topic_code,
  status = excluded.status,
  published_at = excluded.published_at,
  updated_at = now();

commit;
