"""Phase B step 3: build the Development load SQL from accepted candidates. No hand edits: rows are
written exactly as extracted. Entries insert as 'published' (Development only; Production is a Hard
Gate). Hooks insert only when their entry is accepted and every checker accepted the hook; at most
--max-hooks hooks in topic order. Output: out/load_<subject>_u<unit>.sql plus a selection report."""
import json, pathlib, argparse, sys
HERE = pathlib.Path(__file__).resolve().parent


def q(s):
    return "NULL" if s is None else "'" + str(s).replace("'", "''") + "'"


def j(v):
    return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--subject-key", required=True); ap.add_argument("--unit", type=int, required=True)
    ap.add_argument("--max-hooks", type=int, default=8)
    ap.add_argument("--batch", required=True)   # e.g. task0067-reference-pilot-2026-10-09
    ap.add_argument("--po-accept", default=None)  # JSON: {"entries": [candidate_id], "hooks": [[candidate_id, hook_text]], "note": "..."}
    a = ap.parse_args()
    out = HERE / "out"
    cands, verdicts = {}, []
    for cp in sorted(out.glob(f"candidates_{a.subject_key}_u{a.unit}*.json")):
        for c in json.loads(cp.read_text()): cands[c["candidate_id"]] = c
    for vp in sorted(out.glob(f"verdicts_{a.subject_key}_u{a.unit}*.json")):
        if "_pre_recompute" in vp.name or "_void" in vp.name: continue
        verdicts += json.loads(vp.read_text())
    po = json.loads(pathlib.Path(a.po_accept).read_text()) if a.po_accept else {"entries": [], "hooks": [], "note": ""}
    for v in verdicts:
        if v["candidate_id"] in po.get("entries", []):
            v["accepted"] = True; v["po_override"] = po.get("note")
        for cid, ht in po.get("hooks", []):
            if v["candidate_id"] == cid:
                v["accepted"] = True; v["hooks_accepted"][ht] = True; v["po_override"] = po.get("note")
    accepted = [v for v in verdicts if v["accepted"] and not v["control"] and v["candidate_id"] in cands]
    rejected = [v for v in verdicts if not v["accepted"] and not v["control"]]
    def tkey(c):
        m, n = c["owner_topic_code"].split("."); return (int(m), int(n), c["title"])
    accepted.sort(key=lambda v: tkey(cands[v["candidate_id"]]))
    lines = ["-- generated by load.py; do not hand-edit. Batch: " + a.batch,
             f"-- subject {a.subject_key} unit {a.unit}: {len(accepted)} entries accepted, {len(rejected)} rejected",
             "begin;"]
    hooks_written = 0
    for v in accepted:
        c = cands[v["candidate_id"]]
        src = f"generated-checked; extractor={c.get('extractor')}; batch={a.batch}; candidate={c['candidate_id']}; ced={c.get('ced_evidence','')[:200]}" + (f"; po-override={v['po_override']}" if v.get("po_override") else "")
        lines.append(
            "insert into app.unit_reference_entries (subject_key, unit_number, owner_topic_code, topic_codes, kind, title, body, items, visual_asset_ref, caution, status, source_note)\n"
            f"values ({q(c['subject_key'])}, {c['unit_number']}, {q(c['owner_topic_code'])}, array[{', '.join(q(t) for t in c['topic_codes'])}]::text[], {q(c['kind'])}, {q(c['title'])}, {q(c['body'])}, {j(c.get('items') or [])}, NULL, {q(c.get('caution'))}, 'published', {q(src)})\n"
            "on conflict (subject_key, owner_topic_code, kind, title) do nothing;")
        for h in c.get("hooks") or []:
            if v["hooks_accepted"].get(h["hook_text"]) and hooks_written < a.max_hooks:
                hooks_written += 1
                lines.append(
                    "insert into app.topic_memory_hooks (reference_entry_id, kind, hook_text, expands_to, when_to_use, caution, status, source_note)\n"
                    f"select reference_entry_id, {q(h['kind'])}, {q(h['hook_text'])}, {j(h.get('expands_to') or [])}, {q(h['when_to_use'])}, {q(h.get('caution'))}, 'published', {q(h.get('source_note') or 'generated-checked')}\n"
                    f"from app.unit_reference_entries where subject_key = {q(c['subject_key'])} and owner_topic_code = {q(c['owner_topic_code'])} and kind = {q(c['kind'])} and title = {q(c['title'])}\n"
                    "on conflict (reference_entry_id, hook_text) do nothing;")
    lines.append("commit;")
    path = out / f"load_{a.subject_key}_u{a.unit}.sql"
    path.write_text("\n".join(lines) + "\n")
    rep = {"accepted": [v["candidate_id"] for v in accepted], "rejected": {v["candidate_id"]: {
        m: v["checkers"][m]["samples"][-1].get("entry", {}).get("reasons", "")[:300] for m in v["checkers"]} | ({"veto": (v["veto"] or {}).get("samples", [{}])[-1].get("entry", {}).get("reasons", "")[:300]} if v.get("veto") else {}) for v in rejected},
           "hooks_written": hooks_written}
    (out / f"selection_{a.subject_key}_u{a.unit}.json").write_text(json.dumps(rep, indent=2))
    print(f"{path.name}: {len(accepted)} entries, {hooks_written} hooks; rejected {len(rejected)}")


if __name__ == "__main__":
    main()
